BattleFrontier_Lounge8_MapScripts::
	.byte 0

BattleFrontier_Lounge8_EventScript_Man::
	msgbox BattleFrontier_Lounge8_Text_WhatATrainerNeeds, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_Woman::
	msgbox BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_NinjaBoy::
	msgbox BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling, MSGBOX_NPC
	end

BattleFrontier_Lounge8_Text_WhatATrainerNeeds:
	.string "El que un ENTRENADOR necessita…\p"
	.string "Coneixement…\n"
	.string "Estratègia…\l"
	.string "Sort…\l"
	.string "Coratge…\l"
	.string "Esperit…\l"
	.string "Valentia…\l"
	.string "I habilitat…\p"
	.string "Bé, jo tinc de tot!\n"
	.string "Seré imparable a cada edifici!\p"
	.string "Eh? POKéMON?\n"
	.string "Què és això?$"

BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains:
	.string "Coneixes els CERVELLS\n"
	.string "DE LA FRONTERA?\p"
	.string "Així és com en SCOTT anomena els set\n"
	.string "ENTRENADORS especials que dirigeixen\l"
	.string "les set instal·lacions de la FRONTERA.$"

BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling:
	.string "A la TORRE COMBAT, una noia gran\n"
	.string "em va dir que tinc molt talent\l"
	.string "per combatre!\p"
	.string "M'agraden més els CONCURSOS POKéMON!\p"
	.string "Però no se'm donen bé els CONCURSOS!\p"
	.string "Suposo que tenir talent i que t'agradi\n"
	.string "alguna cosa no és el mateix.$"

