SootopolisCity_House5_MapScripts::
	.byte 0

SootopolisCity_House5_EventScript_Maniac::
	msgbox SootopolisCity_House5_Text_SootopolisMtPyreConnection, MSGBOX_NPC
	end

SootopolisCity_House5_EventScript_Girl::
	msgbox SootopolisCity_House5_Text_BrotherUsedToStudySea, MSGBOX_NPC
	end

SootopolisCity_House5_Text_SootopolisMtPyreConnection:
	.string "Sembla que hi ha alguna connexió\n"
	.string "entre ALGÈPOLIS i el MONT PIRA.\p"
	.string "Els meus amics i jo vam investigar-ho\n"
	.string "al laboratori on jo treballava.$"

SootopolisCity_House5_Text_BrotherUsedToStudySea:
	.string "El meu germà gran estudiava el mar.$"

