RustboroCity_House2_MapScripts::
	.byte 0

RustboroCity_House2_EventScript_PokefanF::
	msgbox RustboroCity_House2_Text_TrainerSchoolExcellent, MSGBOX_NPC
	end

RustboroCity_House2_EventScript_LittleGirl::
	msgbox RustboroCity_House2_Text_RoxanneKnowsALot, MSGBOX_NPC
	end

RustboroCity_House2_Text_TrainerSchoolExcellent:
	.string "L'ESCOLA D'ENTRENADORS és excel·lent.\p"
	.string "Si hi estudies, fins i tot podries\n"
	.string "arribar a ser LÍDER DE GIMNÀS.$"

RustboroCity_House2_Text_RoxanneKnowsALot:
	.string "La PETRA, la LÍDER DE GIMNÀS, sap\n"
	.string "molt sobre POKéMON.\p"
	.string "També és molt forta!$"

