PacifidlogTown_House1_MapScripts::
	.byte 0

PacifidlogTown_House1_EventScript_Man::
	msgbox PacifidlogTown_House1_Text_RegiStory, MSGBOX_NPC
	end

PacifidlogTown_House1_EventScript_Woman::
	msgbox PacifidlogTown_House1_Text_SixDotsOpenThreeDoors, MSGBOX_NPC
	end

PacifidlogTown_House1_Text_RegiStory:
	.string "A la regió de HOENN, hi ha tres\n"
	.string "POKéMON que representen el poder\l"
	.string "de la roca, el gel i l'acer.\p"
	.string "Es diu que cadascun d'ells s'amaga\n"
	.string "al fons de coves.\p"
	.string "Aquesta és la història que vaig sentir\n"
	.string "quan era molt petit.$"

PacifidlogTown_House1_Text_SixDotsOpenThreeDoors:
	.string "“Sis punts obren tres portes.”\p"
	.string "L'avi solia dir això, però no sé\n"
	.string "què volia dir.$"

