gText_ApprenticeChallenge0::
	.string "Ehm, sóc l'aprenent núm. {STR_VAR_2} de {STR_VAR_1}.\n"
	.string "Snif… Aquesta tensió m'està afectant…$"

gText_ApprenticeChallenge1::
	.string "Sóc l'aprenent núm. {STR_VAR_2} de {STR_VAR_1}!\n"
	.string "Aquí anem!$"

gText_ApprenticeChallenge2::
	.string "Sóc l'aprenent núm. {STR_VAR_2} de {STR_VAR_1}!\n"
	.string "Accepta el meu desafiament!$"

gText_ApprenticeChallenge3::
	.string "Ehm… Sóc l'aprenent núm. {STR_VAR_2} de {STR_VAR_1}…\n"
	.string "Creus que algú com jo pot guanyar?$"

gText_ApprenticeChallenge4::
	.string "Sóc l'aprenent núm. {STR_VAR_2} de {STR_VAR_1}!\n"
	.string "Deixaré que em desafiïs!$"

gText_ApprenticeChallenge5::
	.string "Estic terriblement ocupat, però també\n"
	.string "sóc l'aprenent núm. {STR_VAR_2} de {STR_VAR_1}.$"

gText_ApprenticeChallenge6::
	.string "Sóc l'aprenent núm. {STR_VAR_2} de {STR_VAR_1}.\n"
	.string "Encantat de conèixer-te!$"

gText_ApprenticeChallenge7::
	.string "Serveixo com l'aprenent núm. {STR_VAR_2} de {STR_VAR_1}.\n"
	.string "Puc començar?$"

gText_ApprenticeChallenge8::
	.string "Eek! Sóc l'aprenent núm. {STR_VAR_2} de {STR_VAR_1}!\n"
	.string "Ho faré el millor que pugui!$"

gText_ApprenticeChallenge9::
	.string "Yiiihaa! Sóc l'aprenent núm. {STR_VAR_2} de {STR_VAR_1}!\n"
	.string "Posa't en guàrdia!$"

gText_ApprenticeChallenge10::
	.string "Sóc l'aprenent 1.000 de {STR_VAR_1}!\n"
	.string "De fet, sóc el núm. {STR_VAR_2}! Som-hi!$"

gText_ApprenticeChallenge11::
	.string "Sí, sóc l'aprenent núm. {STR_VAR_2} de {STR_VAR_1}!\n"
	.string "Comencem a moure'ns!$"

gText_ApprenticeChallenge12::
	.string "Yipii-iahuu! Sóc el que podries dir\n"
	.string "l'aprenent núm. {STR_VAR_2} de {STR_VAR_1}!$"

gText_ApprenticeChallenge13::
	.string "Cof! Sóc l'aprenent núm. {STR_VAR_2} de {STR_VAR_1}.\n"
	.string "Encantat de conèixer-te! Cof!$"

gText_ApprenticeChallenge14::
	.string "Això em posa nerviós…\n"
	.string "Sóc l'aprenent núm. {STR_VAR_2} de {STR_VAR_1}.$"

gText_ApprenticeChallenge15::
	.string "Sóc l'aprenent núm. {STR_VAR_2} de {STR_VAR_1},\n"
	.string "i no és cap mentida.$"

gText_ApprenticePleaseTeach0::
	.string "Ets… {PLAYER}?\n"
	.string "Oh! Snif…plor…\p"
	.string "Oh! P-perdona…\n"
	.string "Estic tan nerviós que no puc evitar plorar…\p"
	.string "Sóc {STR_VAR_1}, i realment et miro\n"
	.string "amb admiració, {PLAYER}.\p"
	.string "Jo… Tenia el somni d'un dia conèixer-te\n"
	.string "i preguntar-te sobre POKéMON.\p"
	.string "Si us plau, si us plau, {PLAYER}!\n"
	.string "Si us plau ensenya'm sobre POKéMON!$"

gText_ApprenticeRejectTeaching0::
	.string "Oh… P-però…\n"
	.string "Snif… Buaaaaa!\p"
	.string "Si us plau!\n"
	.string "T'ho suplico, si us plau!$"

gText_ApprenticeWhichLevelMode0::
	.string "Oh, de veritat? Ho faràs?\n"
	.string "Genial! Increïble! Auuuh!\p"
	.string "Oh… Ho sento…\n"
	.string "Estic tan content que estic plorant…\p"
	.string "Ehm… Llavors si us plau diga'm!\n"
	.string "És sobre la TORRE COMBAT.\p"
	.string "Què seria millor per a mi: Nivell 50\n"
	.string "o Nivell Obert?$"

gText_ApprenticeLevelModeThanks0::
	.string "{STR_VAR_1}?\n"
	.string "Buaaaaa!\p"
	.string "Oh! Ho sento molt!\n"
	.string "M'has fet feliç triant\n"
	.string "el nivell per a mi, i m'ha fet plorar…\p"
	.string "Snif…\n"
	.string "Moltes gràcies!\l"
	.string "Si us plau parla amb mi una altra vegada!$"

gText_ApprenticePleaseTeach1::
	.string "Uau! Ets {PLAYER}, oi?\n"
	.string "Ets increïblement fort, oi?\p"
	.string "Sóc {STR_VAR_1}!\n"
	.string "Acabo de convertir-me en ENTRENADOR!\p"
	.string "Si us plau, {PLAYER}!\n"
	.string "Pots ser el meu mestre i explicar-me\n"
	.string "moltes coses sobre ser ENTRENADOR?$"

gText_ApprenticeRejectTeaching1::
	.string "Ohhh, per què?\n"
	.string "Oh, si us plau? Si us plauuu?\l"
	.string "Si us plau sigues el meu mestre, si us plau!$"

gText_ApprenticeWhichLevelMode1::
	.string "Bé! Genial!\p"
	.string "La primera cosa que et volia preguntar és\n"
	.string "sobre la TORRE COMBAT!\p"
	.string "Les Sales de Nivell 50 i Nivell Obert…\n"
	.string "Quina seria perfecta per a mi?$"

gText_ApprenticeLevelModeThanks1::
	.string "{STR_VAR_1}, eh? És veritat!\n"
	.string "Ho faré el millor que pugui allà!\p"
	.string "Si ens tornem a trobar aquí, si us plau\n"
	.string "ensenya'm alguna cosa més, mestre!$"

gText_ApprenticePleaseTeach2::
	.string "Ehm… Ets {PLAYER}?\n"
	.string "El meu nom és {STR_VAR_1}.\p"
	.string "Vull convertir-me en ENTRENADOR POKéMON,\n"
	.string "però no sé què fer…\p"
	.string "Així que vaig pensar que potser podria demanar-te\n"
	.string "consell perquè ets tan famós.\p"
	.string "{PLAYER}, podries donar-me consell?$"

gText_ApprenticeRejectTeaching2::
	.string "Oh, però…\p"
	.string "Vull sincerament convertir-me en un ENTRENADOR\n"
	.string "POKéMON!\p"
	.string "Si us plau, pots respondre les meves preguntes?$"

gText_ApprenticeWhichLevelMode2::
	.string "Gràcies!\n"
	.string "Aquí va la meva primera pregunta de seguida!\p"
	.string "La TORRE COMBAT té dos nivells,\n"
	.string "Nivell 50 i Nivell Obert, oi?\p"
	.string "Quin nivell creus que és més\n"
	.string "adequat per a mi?$"

gText_ApprenticeLevelModeThanks2::
	.string "Oh, el desafiament de {STR_VAR_1}?\n"
	.string "Entès!\p"
	.string "Si tinc una altra pregunta, tornaré\n"
	.string "aquí pel teu consell!$"

gText_ApprenticePleaseTeach3::
	.string "Oh? Eh? Tu ets…\n"
	.string "No, això no pot ser veritat.\p"
	.string "No hi ha manera que algú\n"
	.string "com jo pogués conèixer {PLAYER}.\p"
	.string "…Realment ets {PLAYER}?\n"
	.string "No em puc creure que estigui parlant amb tu!\p"
	.string "Quan passa alguna cosa tan bona,\n"
	.string "només coses terribles em passaran\n"
	.string "ara, ho sé segur…\p"
	.string "…Ho sento…\n"
	.string "Sóc… {STR_VAR_1}…\p"
	.string "No hi ha res especial sobre\n"
	.string "mi de què pugui estar orgullós…\p"
	.string "Ni tan sols hauria de dir res sobre\n"
	.string "mi mateix perquè ho oblidaràs…\p"
	.string "Tenia el somni que si mai et trobés,\n"
	.string "{PLAYER}, potser podria demanar-te\n"
	.string "consell com a ENTRENADOR.\p"
	.string "Però no crec que accediries\n"
	.string "a això.\p"
	.string "…O seràs tan amable de donar-me\n"
	.string "consell?$"

gText_ApprenticeRejectTeaching3::
	.string "Ho sabia…\p"
	.string "Havia de passar perquè sóc un\n"
	.string "nigú tan avorrit…\p"
	.string "Però pensava que potser…\n"
	.string "No ho reconsideraràs, oi?\p"
	.string "Però no puc rendir-me així.\n"
	.string "T'ho demanaré mentre encara tinc sort!\p"
	.string "Si us plau, seràs tan amable de donar-me\n"
	.string "consell?$"

gText_ApprenticeWhichLevelMode3::
	.string "De veritat? No m'ho puc creure!\n"
	.string "No em puc creure que em donis consell!\l"
	.string "Jo… Sóc tan feliç…\p"
	.string "El que vull preguntar-te és realment\n"
	.string "trivial, però no puc decidir…\p"
	.string "A la TORRE COMBAT, et deixen\n"
	.string "triar Nivell 50 o Nivell Obert.\p"
	.string "A quin curs creus que fins i tot jo podria\n"
	.string "tenir una oportunitat?$"

gText_ApprenticeLevelModeThanks3::
	.string "{STR_VAR_1}? D'acord!\n"
	.string "Però realment creus que algú com\n"
	.string "jo tindria una oportunitat?\p"
	.string "Ho faré el millor que pugui, encara que no\n"
	.string "crec que funcioni.\p"
	.string "Moltes gràcies per dedicar\n"
	.string "temps a algú com jo.$"

gText_ApprenticePleaseTeach4::
	.string "Oh! Ets {PLAYER}{KUN}, oi?\p"
	.string "He sentit que ets fort en POKéMON!\p"
	.string "Sóc {STR_VAR_1}!\n"
	.string "Seré el teu amic!\p"
	.string "Ho sabies?\p"
	.string "No pots guanyar a la FRONTERA COMBAT\n"
	.string "si només saps el que ensenyen a\l"
	.string "l'ESCOLA D'ENTRENADORS.\p"
	.string "Estic disposat a escoltar el teu consell.\n"
	.string "Accediràs, és clar?$"

gText_ApprenticeRejectTeaching4::
	.string "Eh? Per què em rebutges?\n"
	.string "Sóc jo qui t'ho demana!\l"
	.string "Has de reconsiderar-ho!$"

gText_ApprenticeWhichLevelMode4::
	.string "D'acord, hi ha una cosa.\n"
	.string "Vull que ho decideixis per mi.\p"
	.string "Saps que la TORRE COMBAT té\n"
	.string "Sales de Nivell 50 i Nivell Obert?\p"
	.string "Quina creus que seria bona\n"
	.string "per a mi, {PLAYER}{KUN}?$"

gText_ApprenticeLevelModeThanks4::
	.string "D'acord, {STR_VAR_1} és adequat per a mi?\n"
	.string "Gràcies!\p"
	.string "Sabent que tu has pres la decisió,\n"
	.string "{PLAYER}{KUN}, no em disgustaré tant si\l"
	.string "perdo.\p"
	.string "D'acord, buscaré el teu consell una altra vegada.\n"
	.string "Adéu!$"

gText_ApprenticePleaseTeach5::
	.string "Oh, hola! {PLAYER}{KUN}!\n"
	.string "Et conec perquè ets famós!\l"
	.string "Diga'm {STR_VAR_1}! Encantat de conèixer-te!\p"
	.string "Sóc un TRIATLETA, així que em mantinc\n"
	.string "en forma fins i tot mentre crio POKéMON.\p"
	.string "També estic involucrat amb altres coses\n"
	.string "com la feina, fer migdiades, ball de saló…\p"
	.string "Estant tan ocupat, no és tan fàcil per\n"
	.string "a mi convertir-me en un ENTRENADOR decent.\p"
	.string "Així que tinc una proposta!\n"
	.string "Hi ha d'haver una raó per la qual ens hem trobat.\n"
	.string "Així que, {PLAYER}{KUN}, què tal si comparteixes la teva\l"
	.string "saviesa amb mi de tant en tant?$"

gText_ApprenticeRejectTeaching5::
	.string "Oh, però, si us plau?\n"
	.string "Un noi com jo necessita algú com\n"
	.string "tu, {PLAYER}{KUN}!\p"
	.string "Honestament, necessito el teu consell!$"

gText_ApprenticeWhichLevelMode5::
	.string "Gràcies! Això està millor!\n"
	.string "Així que, comencem amb una fàcil!\p"
	.string "Saps sobre els dos cursos de la TORRE COMBAT,\n"
	.string "oi?\l"
	.string "Saps, Nivell 50 i Nivell Obert.\p"
	.string "Jo sent un noi ocupat, per a quin hauria\n"
	.string "de preparar-me?$"

gText_ApprenticeLevelModeThanks5::
	.string "{STR_VAR_1}, eh? D'acord, entès.\n"
	.string "Trobaré temps d'alguna manera i ho provaré!\p"
	.string "…Upa, he d'anar a treballar!\n"
	.string "Gràcies! Ens veiem!$"

gText_ApprenticePleaseTeach6::
	.string "De cap manera! No-no!\n"
	.string "Ets potser el veritable {PLAYER}?\p"
	.string "A-ha! Genial! Sóc {STR_VAR_1},\n"
	.string "molt encantat de conèixer-te!\p"
	.string "{PLAYER}, ets molt fort,\n"
	.string "oi?\p"
	.string "Tothom parla de tu!\p"
	.string "Oh! Acabo de tenir una idea genial!\n"
	.string "Rebré consell teu, {PLAYER}!\l"
	.string "Segur que em farà més fort!\p"
	.string "No és una gran idea?\n"
	.string "Si us plau, vull el teu consell!$"

gText_ApprenticeRejectTeaching6::
	.string "Ahahaha, pots fer veure que ets dolent,\n"
	.string "però no em pots enganyar!\l"
	.string "Realment vols dir que sí, oi?$"

gText_ApprenticeWhichLevelMode6::
	.string "Bé! Sabia que tindries un gran cor,\n"
	.string "{PLAYER}!\p"
	.string "Què hauria de preguntar-te primer?\n"
	.string "…Oh, he pensat alguna cosa!\p"
	.string "Redoble de tambor, si us plau!\n"
	.string "La pregunta que tinc és…\p"
	.string "Si hagués d'acceptar un desafiament a la TORRE COMBAT\n"
	.string ", quin camí hauria de prendre?\p"
	.string "Nivell 50 o Nivell Obert?\n"
	.string "Quin em va més?$"

gText_ApprenticeLevelModeThanks6::
	.string "Oh-oh-oh!\n"
	.string "{STR_VAR_1}, dius!\l"
	.string "Gràcies per una resposta totalment genial!\p"
	.string "Suposo que això és tot el que volia\n"
	.string "preguntar-te avui.\p"
	.string "Trobem-nos aquí una altra vegada, d'acord?\n"
	.string "Gràcies!$"

gText_ApprenticePleaseTeach7::
	.string "Perdoni, però…\n"
	.string "Ets {PLAYER}?\p"
	.string "Sóc {STR_VAR_1}, i estic encantat de\n"
	.string "fer el teu coneixement.\p"
	.string "Fa temps que sóc un admirador\n"
	.string "teu…\p"
	.string "… … … … … …\p"
	.string "Ehm… Espero que no trobis aquesta\n"
	.string "petició massa feixuga, però…\p"
	.string "Puc convertir-me en el teu aprenent,\n"
	.string "{PLAYER}?$"

gText_ApprenticeRejectTeaching7::
	.string "Oh…!\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "…Crec que m'he desmaiat de l'impacte.\n"
	.string "Ho sento, crec que t'he entès malament.\p"
	.string "Si us plau! Si us plau digues que\n"
	.string "m'acceptaràs com a aprenent!$"

gText_ApprenticeWhichLevelMode7::
	.string "Oh… Estic encantat!\p"
	.string "No vull fer-te perdre el temps,\n"
	.string "així que si us plau aconsella'm sobre això.\p"
	.string "Tinc previst acceptar un desafiament a la TORRE COMBAT\n"
	.string "aviat.\p"
	.string "No obstant, hi ha dos nivells…\p"
	.string "Quin seria més adequat per a mi?\n"
	.string "Nivell 50 o Nivell Obert?$"

gText_ApprenticeLevelModeThanks7::
	.string "{STR_VAR_1} és la teva elecció!\n"
	.string "Ja veig. Ho faré el millor que pugui!\p"
	.string "Gràcies, {PLAYER}.\n"
	.string "Espero que pugui comptar amb tu una altra vegada.\l"
	.string "Cuida't!$"

gText_ApprenticePleaseTeach8::
	.string "Eek! Eek! {PLAYER}!\n"
	.string "M'has parlat!\l"
	.string "Jo… Estic bojament content!\p"
	.string "Jo! El meu nom és {STR_VAR_1}!\n"
	.string "Acabo de convertir-me en ENTRENADOR!\p"
	.string "Estic encantat d'haver-te conegut, {PLAYER},\n"
	.string "el gran nom dels cercles POKéMON!\p"
	.string "Oh-oh-oh, ja sé!\n"
	.string "Puc demanar-te un gran favor, {PLAYER}?\p"
	.string "Si us plau accepta'm com a aprenent!\n"
	.string "Vull aprendre de tu!$"

gText_ApprenticeRejectTeaching8::
	.string "Buaaaa!\n"
	.string "{PLAYER} m'ha rebutjat…\l"
	.string "És… És una experiència inestimable!\p"
	.string "{PLAYER}, si us plau! Vull sentir\n"
	.string "una resposta afirmativa aquest cop!\p"
	.string "Et demano la teva orientació!$"

gText_ApprenticeWhichLevelMode8::
	.string "Hieeeeh! {PLAYER} ha dit que sí!\n"
	.string "{PLAYER} ha dit que sí!\p"
	.string "No podré dormir aquesta nit…\n"
	.string "Moltíssimes gràcies!\p"
	.string "Llavors, aquí va la meva pregunta!\p"
	.string "A la TORRE COMBAT, què és adequat\n"
	.string "per a mi, Nivell 50 o Nivell Obert?$"

gText_ApprenticeLevelModeThanks8::
	.string "{STR_VAR_1}! Perfectament entès!\n"
	.string "Ho entenc perfectament!\l"
	.string "Estic boig de content!\p"
	.string "Espero que estiguis disposat a ensenyar-me\n"
	.string "més coses un altre cop.$"

gText_ApprenticePleaseTeach9::
	.string "Uau! Podries ser…\n"
	.string "Podries ser… {PLAYER}{KUN}?!\l"
	.string "Aquell ENTRENADOR tan fort i famós?\l"
	.string "Doncs, hola, no sóc el més afortunat!\p"
	.string "Hola, el meu nom és {STR_VAR_1}!\p"
	.string "He estat buscant\n"
	.string "un professor de POKéMON.\p"
	.string "I amb un temps impecable,\n"
	.string "has aparegut tu, {PLAYER}{KUN}!\p"
	.string "Així que, aquí ho tens, {PLAYER}{KUN}!\n"
	.string "Deixa'm ser el teu aprenent!$"

gText_ApprenticeRejectTeaching9::
	.string "Gwaaaah!\n"
	.string "Ets bastant genial i dur…\p"
	.string "No siguis així, si us plau.\n"
	.string "T'ho estic demanant!$"

gText_ApprenticeWhichLevelMode9::
	.string "Oh, sí! Aquesta és una resposta sòlida!\n"
	.string "Excel·lent, podria afegir!\p"
	.string "Així que què tal un primer consell\n"
	.string "sobre la TORRE COMBAT?\p"
	.string "Si hi anés, què seria millor?\n"
	.string "Nivell 50 o Nivell Obert?$"

gText_ApprenticeLevelModeThanks9::
	.string "Uh-huh, {STR_VAR_1} és!\n"
	.string "D'acord, A-D'acord!\l"
	.string "Iré a demostrar la meva vàlua, com, ja!\p"
	.string "D'acord, et miraré com el meu mentor!\n"
	.string "Adéu!$"

gText_ApprenticePleaseTeach10::
	.string "Oh, ei, {PLAYER}{KUN}, oi?\n"
	.string "La policia t'estava buscant!\p"
	.string "… … …\n"
	.string "És clar que estic mentint!\p"
	.string "Jo, sóc {STR_VAR_1}. Malgrat com\n"
	.string "semblo, sóc el CAMPIÓ POKéMON!\l"
	.string "…Això també és mentida!\p"
	.string "Això no és mentida, però.\n"
	.string "No sóc molt bo combatent.\p"
	.string "Així que, què tal si et converteixes en el meu mestre\n"
	.string "en tot el que és POKéMON?$"

gText_ApprenticeRejectTeaching10::
	.string "Si vas a actuar fred així,\n"
	.string "et mostraré què faré!\p"
	.string "Buaaa! Buaaa! Buaaa!\n"
	.string "Singlot!\p"
	.string "Hahaha, eren les meves LLÀGRIMES FALSES!\p"
	.string "Vinga, si us plau seràs\n"
	.string "el meu mestre POKéMON?$"

gText_ApprenticeWhichLevelMode10::
	.string "Yipii!\n"
	.string "Et compraré un vaixell per això!\p"
	.string "És clar que estic mentint una altra vegada!\n"
	.string "Però… Gràcies, mestre!\p"
	.string "Saps com hi ha Nivell 50 i\n"
	.string "Nivell Obert a la TORRE COMBAT?\p"
	.string "Tinc problemes per decidir quin\n"
	.string "nivell hauria de desafiar…\p"
	.string "Pots decidir per mi, mestre?$"

gText_ApprenticeLevelModeThanks10::
	.string "D'acord, així que {STR_VAR_1} és millor!\n"
	.string "Iré a l'altre nivell, llavors!\p"
	.string "És broma!\n"
	.string "Obeïré el teu ensenyament, mestre!\p"
	.string "Gràcies, mestre!\n"
	.string "Espero que em continuïs ensenyant!$"

gText_ApprenticePleaseTeach11::
	.string "H-O-L-A!\n"
	.string "I això s'escriu hola, i vol dir hola!\p"
	.string "Sóc {STR_VAR_1}, el MARINER\n"
	.string "que rapeja sóc jo!\p"
	.string "Ara et toca a tu, explica'm una mica sobre\n"
	.string "tu mateix, prova-ho!\p"
	.string "Uh-huh, uh-huh!\n"
	.string "{PLAYER}{KUN} és el teu nom,\l"
	.string "i POKéMON és el teu joc!\p"
	.string "I estàs a una edat delicada\n"
	.string "quan tot el món és el teu escenari!\p"
	.string "De totes maneres, només vull dir,\n"
	.string "que ets el desè ENTRENADOR\l"
	.string "que he parlat avui.\p"
	.string "Fem-ho una celebració!\n"
	.string "Converteix-te en el meu mentor per commemoració!$"

gText_ApprenticeRejectTeaching11::
	.string "Però!\n"
	.string "Has de treballar amb mi!\p"
	.string "No siguis tan provocador!\n"
	.string "Converteix-te en el meu mentor, si us plau!$"

gText_ApprenticeWhichLevelMode11::
	.string "Això és!\n"
	.string "{PLAYER}, tens l'esperit!\p"
	.string "Així que aquí va la meva primera pregunta\n"
	.string "que demana el teu suggeriment!\p"
	.string "És sobre la TORRE COMBAT,\n"
	.string "i depèn del meu poder!\p"
	.string "Nivell 50 i Nivell Obert hi ha,\n"
	.string "quin és el que és bo per a mi?$"

gText_ApprenticeLevelModeThanks11::
	.string "D'acord, {STR_VAR_1} és, dius!\n"
	.string "Iré i l'acceptaré pel meu camí!\p"
	.string "Si mai necessito consell,\n"
	.string "{PLAYER}, la teva paraula sempre seguiré!$"

gText_ApprenticePleaseTeach12::
	.string "Ei, hola, no ets tu {PLAYER}?\n"
	.string "Què hauria de fer? Parlar amb tu?\l"
	.string "Per què no? Ja estic parlant amb tu!\p"
	.string "{PLAYER}, et sorprèn veure'm?\n"
	.string "Més val que et digui qui sóc!\p"
	.string "{STR_VAR_1} és el que em pots dir.\n"
	.string "L'estrella més brillant del guitarrisme,\l"
	.string "sóc jo!\p"
	.string "M'estàs rebent?\n"
	.string "M'estàs rebent!\p"
	.string "La meva sort és de les millors,\n"
	.string "et faré una petició!\p"
	.string "{PLAYER}, deixa'm ser el teu subordinat!\n"
	.string "Vull que m'ho ensenyis tot!$"

gText_ApprenticeRejectTeaching12::
	.string "Em rebutges, llavors?\n"
	.string "Hauré de tornar-t'ho a demanar!\p"
	.string "{PLAYER}, et demano ser el teu subordinat!\n"
	.string "Necessito que m'ho ensenyis tot!$"

gText_ApprenticeWhichLevelMode12::
	.string "Sort, sí, uuuhu!\n"
	.string "Hauria de fer-te una pregunta?\p"
	.string "Com que som a prop de la TORRE COMBAT,\n"
	.string "què tal una pregunta sobre el seu poder?\p"
	.string "De les opcions que veus,\n"
	.string "quina és la correcta per a mi?$"

gText_ApprenticeLevelModeThanks12::
	.string "Si {STR_VAR_1} és el que suggereixes,\n"
	.string "ha de ser el millor!\p"
	.string "Bé, {PLAYER}, he de vagar lliure,\n"
	.string "però no t'oblidis de mi.\p"
	.string "Ens veiem una altra vegada, amic intel·ligent!$"

gText_ApprenticePleaseTeach13::
	.string "Oh, hola! Tu d'aquí!\n"
	.string "Pots fer-me un massatge a l'espatlla?\p"
	.string "…Sí, allà! Això és!\n"
	.string "Ai, ai! Oooh, què bé que fa!\p"
	.string "El meu nom és {STR_VAR_1}.\n"
	.string "Faig entrenament de karate, però el meu cos\n"
	.string "no està fet per aguantar l'abús…\p"
	.string "Vaig decidir que lluitaré amb POKéMON i\n"
	.string "em faré més fort.\p"
	.string "Ets {PLAYER}{KUN}, oi?\n"
	.string "El CAMPIÓ de la LLIGA POKéMON?\p"
	.string "Escolta, pots donar-me\n"
	.string "consell?$"

gText_ApprenticeRejectTeaching13::
	.string "Oh, per què?\p"
	.string "No seré una gran molèstia, ho prometo!\n"
	.string "Si us plau?$"

gText_ApprenticeWhichLevelMode13::
	.string "Gràcies. Molt amable de la teva part!\n"
	.string "…Cof! Cof!\p"
	.string "Uff, he de fer-me fort ràpid…\p"
	.string "Me n'aniré a la TORRE COMBAT\n"
	.string "ara mateix, però què seria millor\l"
	.string "per a mi? Nivell 50 o Nivell Obert?$"

gText_ApprenticeLevelModeThanks13::
	.string "Hm, d'acord. Això és {STR_VAR_1}.\n"
	.string "Iré allà ara mateix.\p"
	.string "Espero que pugui continuar demanant-te\n"
	.string "ajuda--després de tot, ets el meu mentor!$"

gText_ApprenticePleaseTeach14::
	.string "Er… Ehm…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Si us plau, no em miris així.\n"
	.string "Em fas sentir molt cohibit.\p"
	.string "Jo… Sóc {STR_VAR_1}.\p"
	.string "Em fa molta vergonya dir això,\n"
	.string "però exploro ruïnes antigues i coses així.\p"
	.string "Encara em fa més vergonya admetre\n"
	.string "que estic interessat en la FRONTERA COMBAT.\p"
	.string "{PLAYER}{KUN}, tens reputació de\n"
	.string "ser un ENTRENADOR dur…\p"
	.string "És difícil per a mi dir això,\n"
	.string "però vull demanar-te alguna cosa.\p"
	.string "Podries convertir-te en el meu mestre i\n"
	.string "donar-me consell?$"

gText_ApprenticeRejectTeaching14::
	.string "Si us plau no em facis fora així!\n"
	.string "No puc viure amb la humiliació.\p"
	.string "Si us plau converteix-te en el meu mestre!\n"
	.string "Necessito el teu consell!$"

gText_ApprenticeWhichLevelMode14::
	.string "G-gràcies…\p"
	.string "Però si us plau no em miris així.\n"
	.string "Em fa sentir tot confós.\p"
	.string "Si us plau, respon-me sense mirar\n"
	.string "els meus ulls.\p"
	.string "A la TORRE COMBAT…\n"
	.string "Quin nivell hauria d'intentar?$"

gText_ApprenticeLevelModeThanks14::
	.string "Oh… D'acord!\n"
	.string "Ho provaré.\p"
	.string "Espero que pugui fer un desafiament valent\n"
	.string "sense posar-me tot confós…\p"
	.string "Gràcies, {PLAYER}{KUN}.\n"
	.string "Si ens tornem a trobar, espero que siguis\n"
	.string "tan útil.$"

gText_ApprenticePleaseTeach15::
	.string "Hm? Sembles ser {PLAYER}{KUN}…\n"
	.string "Però ets realment real?\p"
	.string "Pots dir-me {STR_VAR_1}.\p"
	.string "He estat jugant amb la idea de\n"
	.string "ser aprenent d'un ENTRENADOR fort.\p"
	.string "Així que, he de dir que tinc sort que hagis vingut!\n"
	.string "…Realment ets {PLAYER}{KUN}, sí?\p"
	.string "No, no, si ets real, està bé.\n"
	.string "Només vull que em reconeguis\n"
	.string "com el teu aprenent.$"

gText_ApprenticeRejectTeaching15::
	.string "Oh?\n"
	.string "Però què et faria refusar?\p"
	.string "Demano disculpes per ser escèptic sobre\n"
	.string "la teva identitat.\p"
	.string "Si us plau accepta la meva disculpa i\n"
	.string "accepta'm com el teu aprenent.$"

gText_ApprenticeWhichLevelMode15::
	.string "Realment m'acceptes?\n"
	.string "No vull celebrar prematurament.\p"
	.string "Si és veritat, demano disculpes.\n"
	.string "Però ara, necessito el teu consell.\p"
	.string "Si entrés a la TORRE COMBAT,\n"
	.string "què seria digne de mi?\l"
	.string "Nivell 50 o Nivell Obert?$"

gText_ApprenticeLevelModeThanks15::
	.string "{STR_VAR_1}?\n"
	.string "Estàs segur?\p"
	.string "Ja veig. Si és el cas, està bé.\n"
	.string "T'agraeixo el teu temps.\p"
	.string "Sé que puc molestar, però em fa content\n"
	.string "que m'hagis acceptat.\p"
	.string "Trobem-nos una altra vegada!$"

gText_ApprenticeWhatHeldItem0::
	.string "Sospir… Plor…\n"
	.string "Oh, {PLAYER}!\p"
	.string "Estic tot embolicat en un dilema\n"
	.string "que no puc decidir.\p"
	.string "No puc decidir què hauria de fer\n"
	.string "que el meu {STR_VAR_1} aguanti.\p"
	.string "Si us plau diga'm, {PLAYER}.\n"
	.string "Quin objecte hauria de fer-li aguantar?$"

gText_ApprenticeHoldNothing0::
	.string "Oh, de veritat? No hauria de fer\n"
	.string "que el meu {STR_VAR_1} aguanti res?$"

gText_ApprenticeThanksNoHeldItem0::
	.string "Oh, d'acord! Estic content que s'hagi resolt!\n"
	.string "Genial! Increïble! Auuuh!\p"
	.string "Moltes gràcies!$"

gText_ApprenticeThanksHeldItem0::
	.string "Oh, estic tan content…\n"
	.string "Crec que també tinc aquest {STR_VAR_1}.\p"
	.string "Estic content que s'hagi resolt!\n"
	.string "Genial! Increïble! Auuuh!\p"
	.string "Moltes gràcies!$"

gText_ApprenticeItemAlreadyRecommended0::
	.string "Buaaaa! Si us plau no siguis dolent!\p"
	.string "Aquell objecte {STR_VAR_1} ja me'l van\n"
	.string "recomanar abans, plor…\p"
	.string "O vols dir que no hauria de fer\n"
	.string "que el meu {STR_VAR_2} aguanti res?$"

gText_ApprenticeWhatHeldItem1::
	.string "Bé! És {PLAYER}!\n"
	.string "Genial! Et volia preguntar alguna cosa!\p"
	.string "Fas que els teus POKéMON aguantin objectes?\n"
	.string "Vull fer que els meus aguantin objectes, però…\p"
	.string "Quin objecte seria bo que\n"
	.string "{STR_VAR_1} aguantés?\p"
	.string "Què en penses?$"

gText_ApprenticeHoldNothing1::
	.string "Eh? Vols dir que el meu {STR_VAR_1} no\n"
	.string "ha d'aguantar res?$"

gText_ApprenticeThanksNoHeldItem1::
	.string "Oh, ho entenc! Ho faré!\n"
	.string "Gràcies per ensenyar-me!$"

gText_ApprenticeThanksHeldItem1::
	.string "Oh, uau! Un {STR_VAR_1}, eh?\n"
	.string "D'acord, ho faré!\p"
	.string "Gràcies per ensenyar-me!$"

gText_ApprenticeItemAlreadyRecommended1::
	.string "Oh, eh, no, no és això el que volia dir.\n"
	.string "Vull saber sobre un objecte diferent\n"
	.string "dels que ja conec.\p"
	.string "O vols dir que el meu POKéMON no\n"
	.string "ha d'aguantar res aquest cop?$"

gText_ApprenticeWhatHeldItem2::
	.string "{PLAYER}, hola!\n"
	.string "És sobre el meu {STR_VAR_1}…\p"
	.string "Vull fer-li aguantar un bon objecte.\n"
	.string "Què seria bo per a ell?$"

gText_ApprenticeHoldNothing2::
	.string "Oh, llavors el meu {STR_VAR_1} no ha\n"
	.string "d'aguantar res?$"

gText_ApprenticeThanksNoHeldItem2::
	.string "D'acord, ho entenc!\n"
	.string "Ens veiem!$"

gText_ApprenticeThanksHeldItem2::
	.string "Oh, l'objecte {STR_VAR_1}?\n"
	.string "Entès!\p"
	.string "Faré tot el possible per trobar-ne un!\n"
	.string "Ens veiem!$"

gText_ApprenticeItemAlreadyRecommended2::
	.string "Algú ja em va ensenyar sobre\n"
	.string "el {STR_VAR_1}.\p"
	.string "Vull que el meu POKéMON aguanti un altre\n"
	.string "tipus d'objecte.\p"
	.string "O creus que {STR_VAR_2} no\n"
	.string "ha d'aguantar res?$"

gText_ApprenticeWhatHeldItem3::
	.string "Hola, {PLAYER}…\n"
	.string "Em sap greu molestar-te, però tinc\n"
	.string "alguna altra cosa que et volia preguntar.\p"
	.string "No crec que sigui prou bo per guanyar\n"
	.string "combats pel meu compte, així que estic pensant\n"
	.string "de fer que el meu {STR_VAR_1} aguanti un objecte.\p"
	.string "Però no sé què seria bo.\p"
	.string "{PLAYER}, si us plau, podries decidir\n"
	.string "per mi?$"

gText_ApprenticeHoldNothing3::
	.string "Un POKéMON que pertany a algú com jo\n"
	.string "estaria millor sense cap objecte?$"

gText_ApprenticeThanksNoHeldItem3::
	.string "Ho entenc…\n"
	.string "Estàs dient que no hauria de dependre dels objectes.\l"
	.string "Ho faré el millor que pugui per no fer-ho!\p"
	.string "Moltes gràcies!$"

gText_ApprenticeThanksHeldItem3::
	.string "L'objecte {STR_VAR_1}, d'acord.\n"
	.string "No estic segur si puc aconseguir-ne un…\l"
	.string "No! Faré tot el possible per aconseguir-lo.\p"
	.string "Moltes gràcies!$"

gText_ApprenticeItemAlreadyRecommended3::
	.string "Oh, però…\n"
	.string "Crec que ja he sentit parlar d'això abans…\p"
	.string "És potser perquè no he manipulat\n"
	.string "l'objecte {STR_VAR_1} gaire bé?\p"
	.string "O vols dir que no hauria de fer\n"
	.string "que el meu {STR_VAR_2} aguanti res?$"

gText_ApprenticeWhatHeldItem4::
	.string "Oh, {PLAYER}{KUN}.\n"
	.string "Hi ha alguna cosa que et volia preguntar.\p"
	.string "Saps com vas decidir quins\n"
	.string "POKéMON hauria de tenir per a mi?\p"
	.string "Però mai et vaig preguntar quin objecte\n"
	.string "hauria d'aguantar.\p"
	.string "Com que ja m'has donat consell,\n"
	.string "què tal veure-ho fins al final?\p"
	.string "Què seria bo? Vull fer\n"
	.string "que el meu {STR_VAR_1} aguanti alguna cosa.$"

gText_ApprenticeHoldNothing4::
	.string "Oh! Així que el meu {STR_VAR_1} hauria de fer\n"
	.string "el millor que pugui amb les mans buides?$"

gText_ApprenticeThanksNoHeldItem4::
	.string "Si creus que és el millor, ho faré.\p"
	.string "Sabent que tu has pres la decisió,\n"
	.string "{PLAYER}{KUN}, no em disgustaré tant si\l"
	.string "perdo.\p"
	.string "D'acord, buscaré el teu consell una altra vegada.\n"
	.string "Adéu!$"

gText_ApprenticeThanksHeldItem4::
	.string "L'objecte {STR_VAR_1}, eh?\n"
	.string "No està malament. L'utilitzaré!\p"
	.string "Sabent que tu has pres la decisió,\n"
	.string "{PLAYER}{KUN}, no em disgustaré tant si\l"
	.string "perdo.\p"
	.string "D'acord, buscaré el teu consell una altra vegada.\n"
	.string "Adéu!$"

gText_ApprenticeItemAlreadyRecommended4::
	.string "Eh? Què dius?\n"
	.string "Ja em vas parlar del {STR_VAR_1}\l"
	.string "abans.\p"
	.string "O vols dir que el meu {STR_VAR_2} hauria\n"
	.string "de fer el millor que pugui amb les mans buides?$"

gText_ApprenticeWhatHeldItem5::
	.string "Ei, {PLAYER}{KUN}!\p"
	.string "Tots dos estem ocupats, però sembla que ens\n"
	.string "trobem sovint de totes maneres!\p"
	.string "Avui he de caminar,\n"
	.string "fer neteja, i raspallar.\p"
	.string "Ni tan sols he tingut temps de comprar\n"
	.string "al meu estimat {STR_VAR_1} res.\p"
	.string "No tinc temps, així que què tal\n"
	.string "donar-me consell sobre què hauria de fer\n"
	.string "que el meu {STR_VAR_1} aguanti?$"

gText_ApprenticeHoldNothing5::
	.string "Oh, així que jo sent un noi ocupat, dius\n"
	.string "que el meu {STR_VAR_1} no necessita res?$"

gText_ApprenticeThanksNoHeldItem5::
	.string "D'acord, entès.\n"
	.string "No necessitaré temps per això.\p"
	.string "Gràcies avui!\n"
	.string "Ens veiem!$"

gText_ApprenticeThanksHeldItem5::
	.string "{STR_VAR_1}?\n"
	.string "D'acord, ho entenc!\p"
	.string "Ara he de córrer, però buscaré temps\n"
	.string "per aconseguir-ne un!\p"
	.string "Gràcies! Ens veiem!$"

gText_ApprenticeItemAlreadyRecommended5::
	.string "Ja em vas ensenyar sobre\n"
	.string "l'{STR_VAR_1}.\p"
	.string "No tinc temps, així que no\n"
	.string "em facis anar en cercles, vinga.\p"
	.string "O el meu {STR_VAR_2} no ha\n"
	.string "d'aguantar res?$"

gText_ApprenticeWhatHeldItem6::
	.string "Heeey! {PLAYER}!\p"
	.string "Saps què? Tinc una pregunta!\n"
	.string "Preparat? Aquí va!\p"
	.string "Quin objecte creus que hauria\n"
	.string "d'aguantar el meu {STR_VAR_1}?$"

gText_ApprenticeHoldNothing6::
	.string "Oh-oh-oh? No cal que el meu {STR_VAR_1}\n"
	.string "aguanti res?$"

gText_ApprenticeThanksNoHeldItem6::
	.string "Ah-ha!\n"
	.string "D'acord, entesos!\p"
	.string "Gràcies!$"

gText_ApprenticeThanksHeldItem6::
	.string "Oh! {STR_VAR_1}, dius?\n"
	.string "Gràcies, és un consell genial!\p"
	.string "Ens veiem una altra vegada, d'acord?\n"
	.string "Gràcies!$"

gText_ApprenticeItemAlreadyRecommended6::
	.string "Ah-ha?\n"
	.string "Però ja m'has recomanat el\n"
	.string "{STR_VAR_1} abans, oi?\p"
	.string "Ets molt oblidadís,\n"
	.string "{PLAYER}!\p"
	.string "O vols dir que el meu {STR_VAR_2}\n"
	.string "no necessita aguantar res?$"

gText_ApprenticeWhatHeldItem7::
	.string "{PLAYER}, lamento molestar-te.\p"
	.string "Tinc alguna cosa que desitjo preguntar-te.\n"
	.string "Espero que et sigui convenient.\p"
	.string "Quin objecte hauria de fer\n"
	.string "que el meu {STR_VAR_1} aguanti?$"

gText_ApprenticeHoldNothing7::
	.string "Ah, així que dius que és innecessari\n"
	.string "fer que el meu {STR_VAR_1} aguanti res?$"

gText_ApprenticeThanksNoHeldItem7::
	.string "Ja veig. Ho faré.\n"
	.string "Gràcies, {PLAYER}.\p"
	.string "Espero que pugui comptar amb tu una altra vegada.\l"
	.string "Cuida't!$"

gText_ApprenticeThanksHeldItem7::
	.string "{STR_VAR_1}… Ja veig.\n"
	.string "Ho faré.\p"
	.string "Gràcies, {PLAYER}.\n"
	.string "Espero que pugui comptar amb tu una altra vegada.\l"
	.string "Cuida't!$"

gText_ApprenticeItemAlreadyRecommended7::
	.string "Oh…?\n"
	.string "Però recordo que em vas parlar\n"
	.string "del {STR_VAR_1} abans…\p"
	.string "O dius que el meu {STR_VAR_2}\n"
	.string "no necessita aguantar res?$"

gText_ApprenticeWhatHeldItem8::
	.string "Aaah! {PLAYER}!\n"
	.string "Què bé! Et volia demanar alguna cosa!\p"
	.string "L'objecte que el meu POKéMON hauria d'aguantar--\n"
	.string "no tinc ni idea!\p"
	.string "Si us plau diga'm!\n"
	.string "Quin hauria d'aguantar el meu {STR_VAR_1}?$"

gText_ApprenticeHoldNothing8::
	.string "Oh, llavors el meu {STR_VAR_1}\n"
	.string "no hauria d'aguantar res?$"

gText_ApprenticeThanksNoHeldItem8::
	.string "Ho entenc perfectament!\n"
	.string "Estic boig de content!\p"
	.string "Espero que estiguis disposat a ensenyar-me\n"
	.string "més coses un altre cop.$"

gText_ApprenticeThanksHeldItem8::
	.string "{STR_VAR_1}!\n"
	.string "Perfectament entès!\l"
	.string "Estic boig de content!\p"
	.string "Espero que estiguis disposat a ensenyar-me\n"
	.string "més coses un altre cop.$"

gText_ApprenticeItemAlreadyRecommended8::
	.string "O-oh!\n"
	.string "{PLAYER}, pensava que ja m'havies\n"
	.string "recomanat el {STR_VAR_1}…\p"
	.string "Deus haver-t'ho oblidat, oi?\n"
	.string "No passa res, et perdono!\p"
	.string "O vols dir que el meu {STR_VAR_2}\n"
	.string "no hauria d'aguantar res?$"

gText_ApprenticeWhatHeldItem9::
	.string "Oh, {PLAYER}{KUN}!\n"
	.string "Escolta, tinc una petició.\p"
	.string "L'objecte que hauria de fer\n"
	.string "que el meu {STR_VAR_1} aguanti--\l"
	.string "no tinc cap idea bona.\p"
	.string "Què en penses, {PLAYER}{KUN}?$"

gText_ApprenticeHoldNothing9::
	.string "Uh-huh, {STR_VAR_1} no ha d'aguantar\n"
	.string "res?$"

gText_ApprenticeThanksNoHeldItem9::
	.string "Entès! Ho tinc!\p"
	.string "D'acord, et miraré com el meu mentor!\n"
	.string "Adéu!$"

gText_ApprenticeThanksHeldItem9::
	.string "Uh-huh, {STR_VAR_1}!\n"
	.string "OK, A-D'acord! M'encarregaré de l'objecte!\p"
	.string "D'acord, et miraré com el meu mentor!\n"
	.string "Adéu!$"

gText_ApprenticeItemAlreadyRecommended9::
	.string "Eh? Eh?\n"
	.string "No és l'{STR_VAR_1} el mateix objecte\n"
	.string "que em vas dir abans?\p"
	.string "O {STR_VAR_2} no ha d'aguantar\n"
	.string "res?$"

gText_ApprenticeWhatHeldItem10::
	.string "Oh, mestre!\n"
	.string "He estat esperant veure't!\p"
	.string "Vull fer que el meu {STR_VAR_1} aguanti\n"
	.string "alguna cosa, però no sé què.\p"
	.string "Mestre, digues! Quin objecte hauria\n"
	.string "d'aguantar el meu {STR_VAR_1}?$"

gText_ApprenticeHoldNothing10::
	.string "Oh, el meu {STR_VAR_1} no hauria\n"
	.string "d'aguantar res?$"

gText_ApprenticeThanksNoHeldItem10::
	.string "Ho entenc, mestre!\n"
	.string "Gràcies, mestre!\p"
	.string "Espero que em continuïs ensenyant!$"

gText_ApprenticeThanksHeldItem10::
	.string "D'acord, {STR_VAR_1}?\n"
	.string "Ho entenc, mestre!\p"
	.string "Gràcies, mestre!\n"
	.string "Espero que em continuïs ensenyant!$"

gText_ApprenticeItemAlreadyRecommended10::
	.string "Mestre, ja m'havies parlat del\n"
	.string "{STR_VAR_1} abans, oi?\p"
	.string "O el meu {STR_VAR_2} no hauria\n"
	.string "d'aguantar res?$"

gText_ApprenticeWhatHeldItem11::
	.string "Ei, ei! Si et plau, escolta,\n"
	.string "vull preguntar-te!\p"
	.string "Un objecte per al meu {STR_VAR_1},\n"
	.string "vull que en triïs un si vols!\p"
	.string "Quin hauria d'aguantar?\n"
	.string "Diga'm perquè ho sàpiga!$"

gText_ApprenticeHoldNothing11::
	.string "Oh, vols dir que no,\n"
	.string "el meu {STR_VAR_1} res hauria d'aguantar?$"

gText_ApprenticeThanksNoHeldItem11::
	.string "D'acord, ja ho sé!\n"
	.string "D'acord, em piro!\p"
	.string "Si mai necessito consell,\n"
	.string "{PLAYER}, la teva paraula sempre seguiré!$"

gText_ApprenticeThanksHeldItem11::
	.string "{STR_VAR_1}, dius!\n"
	.string "Ja ho sé, em piro!\p"
	.string "Si mai necessito consell,\n"
	.string "{PLAYER}, la teva paraula sempre seguiré!$"

gText_ApprenticeItemAlreadyRecommended11::
	.string "Ei, ei, no em facis ganyotes!\n"
	.string "Aquest objecte {STR_VAR_1} ja m'ho has dit!\p"
	.string "O vols dir que no, el meu {STR_VAR_2}\n"
	.string "res hauria d'aguantar?$"

gText_ApprenticeWhatHeldItem12::
	.string "Ei, ei, ei, {PLAYER}!\p"
	.string "L'objecte {STR_VAR_1},\n"
	.string "vull que el meu POKéMON l'aguanti i tot!\p"
	.string "Quin objecte creus que hauria\n"
	.string "d'aguantar el meu POKéMON?$"

gText_ApprenticeHoldNothing12::
	.string "Ding, ding!\n"
	.string "No vols dir que el meu {STR_VAR_1}\n"
	.string "no hauria d'aguantar res?$"

gText_ApprenticeThanksNoHeldItem12::
	.string "Perfecte!\n"
	.string "Si tu ho dius, ha de ser veritat!\p"
	.string "Bé, {PLAYER}, he de vagar lliure,\n"
	.string "però no t'oblidis de mi.\p"
	.string "Ens veiem una altra vegada, amic intel·ligent!$"

gText_ApprenticeThanksHeldItem12::
	.string "Oh, una elecció genial!\n"
	.string "Trobar un {STR_VAR_1} fa molt!\p"
	.string "Bé, {PLAYER}, he de vagar lliure,\n"
	.string "però no t'oblidis de mi.\p"
	.string "Ens veiem una altra vegada, amic intel·ligent!$"

gText_ApprenticeItemAlreadyRecommended12::
	.string "Ara, ara, ara!\n"
	.string "Ja em vas dir sobre el\n"
	.string "{STR_VAR_1} abans!\p"
	.string "Per què no m'escoltes?\n"
	.string "No és perquè et parli tant!\p"
	.string "O el meu {STR_VAR_2}\n"
	.string "no hauria d'aguantar res?$"

gText_ApprenticeWhatHeldItem13::
	.string "Ho-hola, {PLAYER}{KUN}.\n"
	.string "Hi ha alguna cosa que et vull preguntar.\p"
	.string "Em pregunto si em pots recomanar\n"
	.string "un objecte per al meu {STR_VAR_1}…\l"
	.string "Cof!$"

gText_ApprenticeHoldNothing13::
	.string "Um? El meu {STR_VAR_1} no ha\n"
	.string "d'aguantar res?$"

gText_ApprenticeThanksNoHeldItem13::
	.string "Ho entenc.\n"
	.string "Gràcies!\p"
	.string "Espero que pugui continuar demanant-te\n"
	.string "ajuda--després de tot, ets el meu mentor!$"

gText_ApprenticeThanksHeldItem13::
	.string "D'acord, {STR_VAR_1}.\n"
	.string "Gràcies!\p"
	.string "Espero que pugui continuar demanant-te\n"
	.string "ajuda--després de tot, ets el meu mentor!$"

gText_ApprenticeItemAlreadyRecommended13::
	.string "Ja em vas ensenyar sobre el\n"
	.string "{STR_VAR_1} abans, oi?\p"
	.string "Necessito saber sobre altres objectes…\n"
	.string "Cof! Cof!\p"
	.string "O el meu {STR_VAR_2} no hauria\n"
	.string "d'aguantar res?$"

gText_ApprenticeWhatHeldItem14::
	.string "Uh… Er…\n"
	.string "Hola, {PLAYER}{KUN}.\p"
	.string "Hi ha alguna cosa que et vull preguntar.\p"
	.string "Quin objecte hauria de fer\n"
	.string "que el meu {STR_VAR_1} aguanti?$"

gText_ApprenticeHoldNothing14::
	.string "Oh…\n"
	.string "El meu {STR_VAR_1} no ha d'aguantar res?$"

gText_ApprenticeThanksNoHeldItem14::
	.string "D'acord… Ho entenc.\p"
	.string "Gràcies, {PLAYER}{KUN}.\n"
	.string "Si ens tornem a trobar, espero que siguis\n"
	.string "tan útil.$"

gText_ApprenticeThanksHeldItem14::
	.string "D'acord… {STR_VAR_1}…\p"
	.string "Gràcies, {PLAYER}{KUN}.\n"
	.string "Si ens tornem a trobar, espero que siguis\n"
	.string "tan útil.$"

gText_ApprenticeItemAlreadyRecommended14::
	.string "Oh, però…\n"
	.string "Ja em vas dir sobre el {STR_VAR_1}…\p"
	.string "O el meu {STR_VAR_2} no hauria d'aguantar\n"
	.string "res?$"

gText_ApprenticeWhatHeldItem15::
	.string "Oh, {PLAYER}{KUN}! Hola.\n"
	.string "Volia fer-te una consulta.\p"
	.string "Tinc un dubte sobre quin objecte\n"
	.string "hauria de fer que el meu {STR_VAR_1} aguanti.\p"
	.string "Què en penses?$"

gText_ApprenticeHoldNothing15::
	.string "Ah.\n"
	.string "Així que el meu {STR_VAR_1} no hauria\n"
	.string "d'aguantar res?$"

gText_ApprenticeThanksNoHeldItem15::
	.string "Ja veig. Gràcies.\p"
	.string "Sé que puc molestar, però em fa content\n"
	.string "que m'hagis acceptat.\p"
	.string "Trobem-nos una altra vegada!$"

gText_ApprenticeThanksHeldItem15::
	.string "Ja veig. {STR_VAR_1}. Gràcies.\p"
	.string "Sé que puc molestar, però em fa content\n"
	.string "que m'hagis acceptat.\p"
	.string "Trobem-nos una altra vegada!$"

gText_ApprenticeItemAlreadyRecommended15::
	.string "Oh? Però estic segur que ja em vas\n"
	.string "recomanar el {STR_VAR_1} abans…\p"
	.string "O el meu {STR_VAR_2} no hauria\n"
	.string "d'aguantar res?$"

gText_ApprenticeWhichMonFirst0::
	.string "Buaaa, {PLAYER}!\n"
	.string "Tinc un dilema, plor…\p"
	.string "Vull començar a combatre amb altres persones,\n"
	.string "però no sé què fer.\p"
	.string "Com hauria de col·locar els meus POKéMON\n"
	.string "perquè siguin els més forts?\p"
	.string "Si us plau diga'm, {PLAYER}.\n"
	.string "Si fossis jo, quin d'aquests POKéMON\l"
	.string "enviries primer?$"

gText_ApprenticeMonFirstThanks0::
	.string "El meu {STR_VAR_1} hauria d'anar primer?\n"
	.string "Buaaaaa!\p"
	.string "Oh! Ho sento molt!\n"
	.string "M'has fet feliç triant\n"
	.string "el meu primer POKéMON, i m'ha fet plorar…\p"
	.string "Moltes gràcies!$"

gText_ApprenticeWhichMonFirst1::
	.string "Bé! És {PLAYER}!\n"
	.string "Genial! Et volia preguntar alguna cosa!\p"
	.string "Ehm, dels meus POKéMON, quin creus\n"
	.string "que hauria de sortir primer?$"

gText_ApprenticeMonFirstThanks1::
	.string "El meu {STR_VAR_1}? Això és veritat.\n"
	.string "D'acord, ho faré!\p"
	.string "Gràcies per ensenyar-me!$"

gText_ApprenticeWhichMonFirst2::
	.string "{PLAYER}, hola!\p"
	.string "Crec que, en un combat, és molt important\n"
	.string "quin POKéMON surt primer.\p"
	.string "Dels POKéMON que tinc,\n"
	.string "quin seria bo enviar primer?$"

gText_ApprenticeMonFirstThanks2::
	.string "El meu {STR_VAR_1} va primer?\n"
	.string "D'acord, ho entenc!\p"
	.string "Ens veiem!$"

gText_ApprenticeWhichMonFirst3::
	.string "Hola, {PLAYER}…\n"
	.string "Em sap greu molestar-te una altra vegada amb\n"
	.string "una altra pregunta.\p"
	.string "Tinc tan poca confiança, no sé\n"
	.string "què faria sense tu, {PLAYER}.\p"
	.string "Potser és una pèrdua de temps per a mi\n"
	.string "fins i tot preocupar-me per això, però simplement no puc\l"
	.string "decidir alguna cosa…\p"
	.string "Quin dels meus POKéMON hauria d'enviar\n"
	.string "primer en un combat?$"

gText_ApprenticeMonFirstThanks3::
	.string "El meu {STR_VAR_1}?\n"
	.string "Entès!\p"
	.string "No em puc creure que et molestis\n"
	.string "a respondre les meves preguntes tan sovint!\p"
	.string "Estic tan agraït que fins i tot parlis\n"
	.string "amb mi… Gràcies!$"

gText_ApprenticeWhichMonFirst4::
	.string "Oh, {PLAYER}{KUN}! Sóc jo!\n"
	.string "Estic tan content de veure't perquè tinc\n"
	.string "aquest petit problema.\p"
	.string "No puc decidir com hauria d'ordenar\n"
	.string "els meus POKéMON. Pots decidir per mi?\p"
	.string "Oh, no necessites decidir tot l'equip\n"
	.string "ara mateix.\p"
	.string "Què tal decidir només el primer\n"
	.string "POKéMON per a mi?$"

gText_ApprenticeMonFirstThanks4::
	.string "El meu {STR_VAR_1}? Genial!\p"
	.string "Sabent que tu has pres la decisió,\n"
	.string "{PLAYER}{KUN}, no em disgustaré tant si\l"
	.string "perdo.\p"
	.string "D'acord, buscaré el teu consell una altra vegada.\n"
	.string "Adéu!$"

gText_ApprenticeWhichMonFirst5::
	.string "Hola, el meu mestre {PLAYER}{KUN}!\n"
	.string "Estic ocupat una altra vegada avui!\p"
	.string "He de fer ciclisme, compres,\n"
	.string "i taral·lar.\p"
	.string "Ni tan sols he tingut temps de decidir\n"
	.string "com ordenar el meu equip POKéMON.\p"
	.string "Així que, què tal revisar el meu equip?\n"
	.string "Quin hauria d'anar primer?$"

gText_ApprenticeMonFirstThanks5::
	.string "D'acord, entès.\n"
	.string "Tinc prou temps almenys per posar\n"
	.string "el meu {STR_VAR_1} al capdavant de la fila!\p"
	.string "Ups, la meva xicota m'espera!\n"
	.string "Gràcies! Ens veiem!$"

gText_ApprenticeWhichMonFirst6::
	.string "Iuhuu! Hola, {PLAYER}!\n"
	.string "Sempre camines semblant dur!\p"
	.string "Escolta, necessito alguna cosa de tu\n"
	.string "un altre cop! És el de sempre!\p"
	.string "Redoble de tambor, si us plau!\n"
	.string "La pregunta que tinc és sobre el meu equip.\p"
	.string "Quin POKéMON meu hauria de ser el primer\n"
	.string "en sortir en un combat?$"

gText_ApprenticeMonFirstThanks6::
	.string "Hmhm!\n"
	.string "El meu {STR_VAR_1}, dius!\l"
	.string "Gràcies per una resposta molt genial!\p"
	.string "Suposo que això és tot el que volia\n"
	.string "preguntar-te avui.\p"
	.string "Trobem-nos aquí una altra vegada, d'acord?\n"
	.string "Gràcies!$"

gText_ApprenticeWhichMonFirst7::
	.string "Moltes gràcies per aturar-te a\n"
	.string "xerrar amb mi, {PLAYER}.\p"
	.string "Sé que m'aprofito de la teva\n"
	.string "amabilitat, però puc demanar-te consell?\p"
	.string "M'agradaria que decidissis l'ordre\n"
	.string "del meu equip POKéMON.\p"
	.string "Em faria content si poguessis decidir\n"
	.string "quin POKéMON hauria d'anar primer.$"

gText_ApprenticeMonFirstThanks7::
	.string "El meu {STR_VAR_1}!\n"
	.string "El posaré primer ara mateix!\p"
	.string "Gràcies, {PLAYER}.\n"
	.string "Espero que pugui comptar amb tu una altra vegada.\l"
	.string "Cuida't!$"

gText_ApprenticeWhichMonFirst8::
	.string "Eek! {PLAYER}!\n"
	.string "Jo… Estic boig de content de tornar-te a veure!\p"
	.string "Els meus POKéMON s'han tornat molt\n"
	.string "més forts!\p"
	.string "Però no sempre guanyo. Sembla que\n"
	.string "depèn de quin POKéMON va primer.\p"
	.string "{PLAYER}, si us plau, necessito la teva ajuda!\p"
	.string "Si us plau decideix quin dels meus POKéMON\n"
	.string "hauria de sortir primer!$"

gText_ApprenticeMonFirstThanks8::
	.string "Sospir… Estic aclaparat de felicitat…\p"
	.string "És com un somni que tu decideixis\n"
	.string "per mi, {PLAYER}.\p"
	.string "Però perfectament entès!\n"
	.string "Iré amb el meu {STR_VAR_1} primer!\p"
	.string "Espero que estiguis disposat a ensenyar-me\n"
	.string "més coses un altre cop.$"

gText_ApprenticeWhichMonFirst9::
	.string "Hola, hola!\n"
	.string "El meu mentor, {PLAYER}{KUN}!\l"
	.string "Colpeja'm amb el teu savi consell avui!\p"
	.string "Ja veus, he reunit un equip de\n"
	.string "tres POKéMON. Fins aquí tot bé.\p"
	.string "Però l'ordre de combat de l'equip encara no\n"
	.string "està decidit.\p"
	.string "Aquí és on entres tu, {PLAYER}{KUN}!\n"
	.string "Tu decideix quin POKéMON lidera!\p"
	.string "No siguis tímid ara.\n"
	.string "Digues-ho!$"

gText_ApprenticeMonFirstThanks9::
	.string "Uh-huh, el meu {STR_VAR_1} lidera!\n"
	.string "D'acord, A-D'acord!\l"
	.string "Reordenaré l'alineació, com, zas!\p"
	.string "D'acord, gràcies, com sempre!\n"
	.string "Adéu!$"

gText_ApprenticeWhichMonFirst10::
	.string "{PLAYER}{KUN}, escolta!\n"
	.string "És una crisi!\p"
	.string "Els meus POKéMON, tots tres, entren\n"
	.string "al combat alhora!\p"
	.string "És clar que això és impossible!\n"
	.string "Wahahaha!\p"
	.string "Això no és mentida, però.\n"
	.string "No sóc molt bo pensant en\n"
	.string "com hauria d'ordenar els meus POKéMON.\p"
	.string "Així que, què tal decidir per mi quin\n"
	.string "POKéMON hauria d'anar primer, mestre?$"

gText_ApprenticeMonFirstThanks10::
	.string "D'acord, així que és el meu {STR_VAR_1} que has triat?\n"
	.string "Deixaré que qualsevol altre vagi primer!\p"
	.string "És broma!\n"
	.string "Obeïré el teu ensenyament, mestre!\p"
	.string "Gràcies, mestre!\n"
	.string "Espero que em continuïs ensenyant!$"

gText_ApprenticeWhichMonFirst11::
	.string "H-O-L-A!\n"
	.string "I això s'escriu hola!\p"
	.string "El MARINER que rapeja sóc jo!\n"
	.string "Et presento una pregunta\n"
	.string "que és bastant bona!\p"
	.string "És una pregunta d'alineació d'equip\n"
	.string "que demana el teu suggeriment!\p"
	.string "D'aquest grup, quin hauria d'anar primer\n"
	.string "com el primer al lloc?$"

gText_ApprenticeMonFirstThanks11::
	.string "D'acord, et sento, clar que sí!\n"
	.string "Els canviaré, això faré!\p"
	.string "Si mai necessito consell,\n"
	.string "{PLAYER}, la teva paraula sempre seguiré!$"

gText_ApprenticeWhichMonFirst12::
	.string "Iahuu, {PLAYER}!\n"
	.string "Com estàs?\p"
	.string "Què hauria de fer? Seguir endavant i preguntar?\n"
	.string "Uh-huh, tinc alguna cosa a preguntar!\l"
	.string "M'estàs rebent?\l"
	.string "M'estàs rebent!\p"
	.string "Has de decidir, quin dels meus\n"
	.string "POKéMON és el primer a entrar!\l"
	.string "Al combat, vull dir.$"

gText_ApprenticeMonFirstThanks12::
	.string "Si el {STR_VAR_1} és el que suggereixes,\n"
	.string "ha de ser el millor!\p"
	.string "Bé, {PLAYER}, he de vagar lliure,\n"
	.string "però no t'oblidis de mi.\p"
	.string "Ens veiem una altra vegada, amic intel·ligent!$"

gText_ApprenticeWhichMonFirst13::
	.string "Hola, {PLAYER}{KUN}. Tinc una\n"
	.string "pregunta per a tu.\p"
	.string "Estic preocupat per l'ordre del meu equip.\n"
	.string "Què en penses, {PLAYER}{KUN}?\p"
	.string "Quin POKéMON hauria d'anar primer en un combat?$"

gText_ApprenticeMonFirstThanks13::
	.string "Hm, d'acord.\n"
	.string "Així que el meu {STR_VAR_1} va primer.\p"
	.string "Espero que pugui continuar demanant-te\n"
	.string "ajuda--després de tot, ets el meu mentor!$"

gText_ApprenticeWhichMonFirst14::
	.string "Er… Ehm…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Si us plau, no em miris així.\n"
	.string "Em fas sentir molt cohibit.\p"
	.string "Jo… Em fa vergonya dir això,\n"
	.string "però no tinc confiança.\p"
	.string "No sé l'ordre correcte en què\n"
	.string "els meus POKéMON haurien de combatre.\p"
	.string "Quin dels meus POKéMON hauria d'anar\n"
	.string "primer en un combat?$"

gText_ApprenticeMonFirstThanks14::
	.string "Oh… D'acord!\n"
	.string "Els posaré en l'ordre correcte.\p"
	.string "És una mica neguitós, però.\n"
	.string "No seria massa genial?\p"
	.string "Gràcies, {PLAYER}{KUN}.\n"
	.string "Si ens tornem a trobar, espero que siguis\n"
	.string "tan útil.$"

gText_ApprenticeWhichMonFirst15::
	.string "Hm? Sembles ser {PLAYER}{KUN}…\n"
	.string "Però ets realment real?\l"
	.string "Potser ets un bessó?\p"
	.string "Oh, no, no, no, no et preocupis!\n"
	.string "Si realment ets {PLAYER}, si us plau\l"
	.string "oblida la meva falta d'educació.\p"
	.string "El que m'agradaria és més\n"
	.string "del teu bon consell.\p"
	.string "Quin dels meus POKéMON hauria d'anar\n"
	.string "primer en un combat?$"

gText_ApprenticeMonFirstThanks15::
	.string "El meu {STR_VAR_1} va primer?\n"
	.string "Estàs segur?\p"
	.string "Ja veig. Si és el cas, està bé.\n"
	.string "T'agraeixo el teu temps.\p"
	.string "Trobem-nos una altra vegada!$"

gText_ApprenticeWhichMon0::
	.string "Snif…\n"
	.string "Oh, {PLAYER}!\p"
	.string "Quina sincronització perfecta!\n"
	.string "Hi ha alguna cosa que no puc decidir…\p"
	.string "No puc decidir quin POKéMON hauria\n"
	.string "d'utilitzar.\p"
	.string "No puc decidir entre els POKéMON\n"
	.string "{STR_VAR_1} i {STR_VAR_2}…\p"
	.string "{PLAYER}, quin creus que em donarà\n"
	.string "fins i tot a mi una oportunitat de guanyar?$"

gText_ApprenticeMonThanks0::
	.string "Snif… Jo… Ho entenc!\n"
	.string "Oh! Ho sento molt!\l"
	.string "M'has fet tan feliç que estic plorant…\p"
	.string "Faré tot el possible per atrapar un\n"
	.string "{STR_VAR_1}!\p"
	.string "Moltes gràcies!$"

gText_ApprenticeWhichMon1::
	.string "Bé! És {PLAYER}!\n"
	.string "Bé, has vingut en bon moment també!\l"
	.string "Necessito el teu consell una altra vegada!\p"
	.string "Ehm, estic tot barrejat--hauria d'utilitzar\n"
	.string "el meu {STR_VAR_1} o {STR_VAR_2}…\p"
	.string "Quin creus que hauria de criar,\n"
	.string "{PLAYER}?$"

gText_ApprenticeMonThanks1::
	.string "Oh, així que el meu {STR_VAR_1} és millor!\n"
	.string "D'acord, ho faré!\p"
	.string "Gràcies per ensenyar-me!$"

gText_ApprenticeWhichMon2::
	.string "{PLAYER}, hola!\n"
	.string "Tinc una pregunta que volia fer.\p"
	.string "Estic en un dilema sobre si hauria de\n"
	.string "criar un {STR_VAR_1} o {STR_VAR_2}.\p"
	.string "Quin POKéMON creus que serà\n"
	.string "més fort?$"

gText_ApprenticeMonThanks2::
	.string "{STR_VAR_1} és la teva elecció?\n"
	.string "D'acord, ho entenc!\p"
	.string "Iré a atrapar un {STR_VAR_1} fort\n"
	.string "ara mateix!\p"
	.string "Ens veiem!$"

gText_ApprenticeWhichMon3::
	.string "Hola, {PLAYER}…\p"
	.string "Ehm, probablement ja t'has oblidat\n"
	.string "d'algú com jo…\p"
	.string "…Però no importa si\n"
	.string "em pots donar consell…\p"
	.string "No puc decidir sobre el tipus de\n"
	.string "POKéMON que hauria de criar…\p"
	.string "He reduït les opcions als POKéMON\n"
	.string "{STR_VAR_1} i {STR_VAR_2}, però és\n"
	.string "on m'he quedat encallat…\p"
	.string "{PLAYER}, probablement no vols\n"
	.string "molestar-te, però si us plau decideix per mi.$"

gText_ApprenticeMonThanks3::
	.string "Però un {STR_VAR_1} salvatge fins i tot em farà\n"
	.string "cas?\p"
	.string "Ho intentaré!\p"
	.string "Però podré atrapar-ne un…\n"
	.string "No! Ho faré el millor que pugui!\p"
	.string "Gràcies!$"

gText_ApprenticeWhichMon4::
	.string "Oh, {PLAYER}{KUN}! Estic tan content de veure't!\n"
	.string "Et volia anar a buscar!\p"
	.string "Pots decidir quin tipus de POKéMON\n"
	.string "hauria d'utilitzar?\p"
	.string "Per exemple…\n"
	.string "Què tal els POKéMON {STR_VAR_1}\l"
	.string "i {STR_VAR_2}?\p"
	.string "Quin creus que seria\n"
	.string "millor?$"

gText_ApprenticeMonThanks4::
	.string "{STR_VAR_1}? Genial!\p"
	.string "Sabent que tu has pres la decisió,\n"
	.string "{PLAYER}{KUN}, no em disgustaré tant si\l"
	.string "perdo.\p"
	.string "D'acord, buscaré el teu consell una altra vegada.\n"
	.string "Adéu!$"

gText_ApprenticeWhichMon5::
	.string "Si no és {PLAYER}{KUN}! Com va?\n"
	.string "Estic ocupat una altra vegada com sempre!\p"
	.string "Vull fer-ho bé amb POKéMON també,\n"
	.string "però no he pogut decidir\n"
	.string "quin POKéMON hauria d'utilitzar.\p"
	.string "Saps com {STR_VAR_1} sembla fort?\n"
	.string "Però {STR_VAR_2} és difícil d'ignorar.\p"
	.string "{PLAYER}{KUN}, dóna'm una mica del teu bon\n"
	.string "consell! Quin seria bo per a mi?$"

gText_ApprenticeMonThanks5::
	.string "D'acord, entès.\n"
	.string "Trobaré temps d'alguna manera i atraparé\n"
	.string "aquest {STR_VAR_1} que has recomanat.\p"
	.string "Estic content d'haver trobat un bon mentor en tu.\n"
	.string "Gràcies! Ens veiem!$"

gText_ApprenticeWhichMon6::
	.string "Oh!\n"
	.string "Bé, és {PLAYER}!\p"
	.string "No he perdut el temps presumint\n"
	.string "als meus amics sobre haver-te conegut!\p"
	.string "Necessito fer servir el teu cervell una altra vegada avui.\n"
	.string "És una fàcil per a tu!\p"
	.string "Redoble de tambor, si us plau!\n"
	.string "La pregunta que tinc és…\p"
	.string "Si hagués de criar un POKéMON,\n"
	.string "i les opcions fossin un {STR_VAR_1}\l"
	.string "o {STR_VAR_2}, quin hauria de ser?$"

gText_ApprenticeMonThanks6::
	.string "Ahhh!\n"
	.string "{STR_VAR_1}, dius!\l"
	.string "Gràcies per una resposta molt genial!\p"
	.string "Suposo que això és tot el que volia\n"
	.string "preguntar-te avui.\p"
	.string "Trobem-nos aquí una altra vegada, d'acord?\n"
	.string "Gràcies!$"

gText_ApprenticeWhichMon7::
	.string "Oh, ets tu, {PLAYER}?\n"
	.string "Estic encantat de tornar-te a veure!\p"
	.string "Des que em vaig convertir en el teu aprenent,\n"
	.string "la meva confiança ha estat florint.\p"
	.string "Crec que estic llest per criar un POKéMON\n"
	.string "meu propi!\p"
	.string "{PLAYER}, puc imposar-te que triïs\n"
	.string "quin POKéMON hauria de criar?\p"
	.string "Les opcions són els POKéMON\n"
	.string "{STR_VAR_1} o {STR_VAR_2}…\l"
	.string "Quin POKéMON és adequat per a mi?$"

gText_ApprenticeMonThanks7::
	.string "Un {STR_VAR_1}!\n"
	.string "En trobaré un ara mateix!\p"
	.string "Gràcies, {PLAYER}.\n"
	.string "Espero que pugui comptar amb tu una altra vegada.\l"
	.string "Cuida't!$"

gText_ApprenticeWhichMon8::
	.string "Eek! {PLAYER}! T'he tornat a trobar!\n"
	.string "Jo… Estic boig de content!\p"
	.string "Oh-oh-oh, ja sé!\n"
	.string "No hauria de perdre aquesta oportunitat!\p"
	.string "Puc demanar-te un gran favor, {PLAYER}?\n"
	.string "Si us plau tria un POKéMON per a mi!\p"
	.string "Si us plau decideix quin seria millor,\n"
	.string "{STR_VAR_1} o {STR_VAR_2}!$"

gText_ApprenticeMonThanks8::
	.string "Uau! Has decidit per mi!\n"
	.string "Un {STR_VAR_1} és el que criaré\n"
	.string "el millor que pugui.\p"
	.string "Espero que estiguis disposat a ensenyar-me\n"
	.string "més coses un altre cop.$"

gText_ApprenticeWhichMon9::
	.string "Ei, ei!\n"
	.string "El meu mentor, {PLAYER}{KUN}!\p"
	.string "Hola, t'he estat buscant\n"
	.string "per més del teu savi consell!\p"
	.string "Quin tipus de POKéMON seria adequat\n"
	.string "per a mi, un {STR_VAR_1} o {STR_VAR_2}?\p"
	.string "No siguis tímid ara.\n"
	.string "Digues-ho!$"

gText_ApprenticeMonThanks9::
	.string "Uh-huh, un {STR_VAR_1}!\n"
	.string "D'acord, A-D'acord!\l"
	.string "En posaré un a una BALL, com, zas!\p"
	.string "D'acord, gràcies, com sempre!\n"
	.string "Adéu!$"

gText_ApprenticeWhichMon10::
	.string "{PLAYER}{KUN}, escolta! Grans notícies!\n"
	.string "He atrapat un POKéMON miratge!\p"
	.string "És clar que estic mentint!\n"
	.string "Wahahaha!\p"
	.string "Això no és mentida, però.\n"
	.string "No sóc molt bo atrapant\n"
	.string "POKéMON.\p"
	.string "Així que, què tal decidir per mi quin\n"
	.string "tipus de POKéMON hauria d'atrapar,\l"
	.string "mestre?\p"
	.string "Quin seria millor?\n"
	.string "{STR_VAR_1} o {STR_VAR_2}?$"

gText_ApprenticeMonThanks10::
	.string "D'acord, així que és {STR_VAR_1} que has triat?\n"
	.string "Agafaré l'altre tipus, llavors!\p"
	.string "És broma!\n"
	.string "Obeïré el teu ensenyament, mestre!\p"
	.string "Gràcies, mestre!\n"
	.string "Espero que em continuïs ensenyant!$"

gText_ApprenticeWhichMon11::
	.string "H-O-L-A!\n"
	.string "I això s'escriu hola!\p"
	.string "El MARINER que rapeja sóc jo!\n"
	.string "Segur que recordes qui sóc jo?\p"
	.string "Avui, tinc una pregunta POKéMON\n"
	.string "que demana el teu suggeriment!\p"
	.string "Tinc l'elecció entre aquest\n"
	.string "{STR_VAR_1} i {STR_VAR_2}, veus.\l"
	.string "Quin és el que he d'atrapar per a mi?$"

gText_ApprenticeMonThanks11::
	.string "{STR_VAR_1}, dius, ei, ei!\n"
	.string "Iré a buscar-ne un ara mateix!\p"
	.string "Si mai necessito consell,\n"
	.string "{PLAYER}, la teva paraula sempre seguiré!$"

gText_ApprenticeWhichMon12::
	.string "Oh, uau, si no és {PLAYER}!\p"
	.string "Què hauria de fer? Demanar el teu consell?\n"
	.string "Per què no? Ja estic parlant amb tu!\p"
	.string "Fa temps. Deixa'm trencar el gel.\n"
	.string "També busco consell!\l"
	.string "M'estàs rebent?\l"
	.string "M'estàs rebent!\p"
	.string "El meu POKéMON--quin hauria d'utilitzar?\n"
	.string "És o {STR_VAR_1} o {STR_VAR_2}.\l"
	.string "Quin tries?$"

gText_ApprenticeMonThanks12::
	.string "Si aquest {STR_VAR_1} és el millor,\n"
	.string "faré el que suggereixes!\p"
	.string "Bé, {PLAYER}, he de vagar lliure,\n"
	.string "però no t'oblidis de mi.\p"
	.string "Ens veiem una altra vegada, amic intel·ligent!$"

gText_ApprenticeWhichMon13::
	.string "Oh, hola, {PLAYER}{KUN}…\n"
	.string "Tinc un mal de cap terrible…\p"
	.string "Dec haver-me preocupat massa sobre\n"
	.string "el tipus de POKéMON que hauria de criar.\p"
	.string "Així que, estant les coses així,\n"
	.string "necessito que decideixis per mi.\p"
	.string "{PLAYER}{KUN}, si hagués de triar entre\n"
	.string "els POKéMON {STR_VAR_1} i\l"
	.string "{STR_VAR_2}, quin hauria de ser?$"

gText_ApprenticeMonThanks13::
	.string "Hm, un {STR_VAR_1}, d'acord.\n"
	.string "Iré a buscar-ne un quan em posi millor.\p"
	.string "Espero que pugui continuar demanant-te\n"
	.string "ajuda així.$"

gText_ApprenticeWhichMon14::
	.string "Er… Ehm…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Si us plau, no em miris així.\n"
	.string "Em poso tot confós…\l"
	.string "Jo… Necessito el teu consell.\p"
	.string "Jo… Em fa vergonya, però no puc\n"
	.string "decidir quin POKéMON utilitzar.\p"
	.string "Si les opcions fossin {STR_VAR_1} o\n"
	.string "{STR_VAR_2}, quin seria millor?$"

gText_ApprenticeMonThanks14::
	.string "Oh… D'acord!\n"
	.string "Ho faré el millor que pugui amb un {STR_VAR_1}.\p"
	.string "Espero que pugui fer-ho sense\n"
	.string "posar-me tot confós.\p"
	.string "Gràcies, {PLAYER}{KUN}.\n"
	.string "Si ens tornem a trobar, espero que siguis\n"
	.string "tan útil.$"

gText_ApprenticeWhichMon15::
	.string "Hm? Sembles ser {PLAYER}{KUN}…\n"
	.string "Però ets realment real?\p"
	.string "No, no, si ets real, està bé.\n"
	.string "De passada, m'agradaria obtenir\n"
	.string "el teu consell.\p"
	.string "És sobre el POKéMON que he d'utilitzar.\p"
	.string "Si les opcions són els POKéMON\n"
	.string "{STR_VAR_1} i {STR_VAR_2}, quin és\n"
	.string "més digne de mi?$"

gText_ApprenticeMonThanks15::
	.string "{STR_VAR_1}?\n"
	.string "Estàs segur?\p"
	.string "Ja veig. Si és el cas, està bé.\n"
	.string "T'agraeixo el teu temps.\p"
	.string "Espero que sigui alguna cosa que fins i tot jo pugui\n"
	.string "manejar amb aplom.\p"
	.string "Trobem-nos una altra vegada!$"

gText_ApprenticeWhichMove0::
	.string "Buaaa! Oh, {PLAYER}!\n"
	.string "Snif… Singlot…\p"
	.string "Tinc un dilema!\n"
	.string "No puc decidir un moviment per al\n"
	.string "meu {STR_VAR_1}…\p"
	.string "Si us plau, si us plau, {PLAYER}.\n"
	.string "Pots decidir per mi?\p"
	.string "Per al meu {STR_VAR_1}, quin moviment seria\n"
	.string "la millor elecció: {STR_VAR_2}\l"
	.string "o {STR_VAR_3}?$"

gText_ApprenticeMoveThanks0::
	.string "{STR_VAR_1}?\n"
	.string "Buaaaaa!\p"
	.string "Oh! Ho sento molt, {PLAYER}!\n"
	.string "M'has fet tan feliç decidint\n"
	.string "el moviment que estic plorant…\p"
	.string "Snif…\n"
	.string "Moltes gràcies!$"

gText_ApprenticeWhichMove1::
	.string "Bé! Hola, {PLAYER}!\n"
	.string "Necessito el teu consell una altra vegada!\p"
	.string "Vull ensenyar al meu {STR_VAR_1}\n"
	.string "un moviment genial.\p"
	.string "M'agrada qualsevol dels moviments\n"
	.string "{STR_VAR_2} o {STR_VAR_3}.\l"
	.string "Quina és la teva recomanació?$"

gText_ApprenticeMoveThanks1::
	.string "{STR_VAR_1} és millor? Suposo que sí!\n"
	.string "D'acord, aniré amb aquest!\p"
	.string "Si ens tornem a trobar aquí, si us plau\n"
	.string "ensenya'm alguna cosa més, mestre!$"

gText_ApprenticeWhichMove2::
	.string "{PLAYER}, hola!\n"
	.string "És sobre el meu {STR_VAR_1}, però estic\l"
	.string "preocupat pels seus moviments.\p"
	.string "Ja veus, són els moviments {STR_VAR_2}\n"
	.string "i {STR_VAR_3}.\p"
	.string "Quin és més fort i millor per al\n"
	.string "meu {STR_VAR_1}?$"

gText_ApprenticeMoveThanks2::
	.string "{STR_VAR_1} és la teva elecció?\n"
	.string "D'acord, ho entenc!\p"
	.string "Iré a ensenyar {STR_VAR_1} al\n"
	.string "meu POKéMON ara mateix!\p"
	.string "Ens veiem!$"

gText_ApprenticeWhichMove3::
	.string "Ohhh, {PLAYER}…\n"
	.string "No tinc remei, no, de veritat!\p"
	.string "He decidit criar un POKéMON,\n"
	.string "però ara ni tan sols puc decidir quin\n"
	.string "moviment hauria de deixar-li aprendre…\p"
	.string "Sé que no significa res\n"
	.string "per a tu, {PLAYER}.\p"
	.string "Però significa molt per a mi…\p"
	.string "Si us plau, {PLAYER}, podries triar\n"
	.string "un moviment per al meu {STR_VAR_1}?\p"
	.string "Si poguessis fins i tot triar entre\n"
	.string "{STR_VAR_2} i {STR_VAR_3}…$"

gText_ApprenticeMoveThanks3::
	.string "Ho entenc!\p"
	.string "Però fins i tot estarà disposat a aprendre\n"
	.string "{STR_VAR_1} per a mi…\l"
	.string "No! Ho faré el millor que pugui!\p"
	.string "Gràcies!$"

gText_ApprenticeWhichMove4::
	.string "Oh, {PLAYER}{KUN}!\n"
	.string "Just t'esperava veure també!\p"
	.string "Em preguntava quin moviment seria\n"
	.string "adequat per al meu {STR_VAR_1}.\p"
	.string "No puc decidir, així que pots decidir\n"
	.string "per mi en canvi?\p"
	.string "Per exemple… Què tal els moviments\n"
	.string "{STR_VAR_2} i {STR_VAR_3}?\l"
	.string "Quin seria millor?$"

gText_ApprenticeMoveThanks4::
	.string "{STR_VAR_1}? Genial!\p"
	.string "Sabent que tu has pres la decisió,\n"
	.string "{PLAYER}{KUN}, no em disgustaré tant si\l"
	.string "perdo.\p"
	.string "D'acord, buscaré el teu consell una altra vegada.\n"
	.string "Adéu!$"

gText_ApprenticeWhichMove5::
	.string "Com poden estar les coses tan ocupades?\n"
	.string "Ei, si no és {PLAYER}{KUN}!\l"
	.string "Com va?\p"
	.string "Des que m'he llevat aquest matí, he fet\n"
	.string "el meu jogging, natació, i cuina!\p"
	.string "No et creuries com n'estic d'ocupat!\p"
	.string "Ni tan sols puc decidir quin moviment\n"
	.string "hauria d'aprendre el meu {STR_VAR_1}!\p"
	.string "{STR_VAR_2} sembla bé, eh?\n"
	.string "Però {STR_VAR_3} també és decent.\p"
	.string "{PLAYER}{KUN}, dóna'm una mica del teu bon\n"
	.string "consell! Quin moviment seria bo per a mi?$"

gText_ApprenticeMoveThanks5::
	.string "D'acord, entès.\n"
	.string "Faré lloc a la meva agenda i\n"
	.string "ensenyaré aquest moviment.\p"
	.string "Estic content d'haver trobat un bon mentor en tu.\n"
	.string "Gràcies! Ens veiem!$"

gText_ApprenticeWhichMove6::
	.string "Oh! Sort!\n"
	.string "T'he tornat a trobar, {PLAYER}!\l"
	.string "Necessito fer servir el teu cervell una altra vegada avui.\p"
	.string "Redoble de tambor, si us plau!\n"
	.string "La pregunta que tinc és…\p"
	.string "Per al meu {STR_VAR_1}, quin és el moviment\n"
	.string "més adequat, {STR_VAR_2} o\l"
	.string "{STR_VAR_3}?$"

gText_ApprenticeMoveThanks6::
	.string "Ahhh!\n"
	.string "{STR_VAR_1}, dius!\l"
	.string "Gràcies per una resposta molt genial!\p"
	.string "Suposo que això és tot el que volia\n"
	.string "preguntar-te avui.\p"
	.string "Trobem-nos aquí una altra vegada, d'acord?\n"
	.string "Gràcies!$"

gText_ApprenticeWhichMove7::
	.string "Oh, hola, {PLAYER}.\n"
	.string "Espero que hagis estat bé?\p"
	.string "He de demanar-te consell una altra vegada.\n"
	.string "És sobre el meu estimat {STR_VAR_1}.\p"
	.string "Quin seria el moviment ideal per al\n"
	.string "meu adorable {STR_VAR_1}?\l"
	.string "{STR_VAR_2} o {STR_VAR_3}?$"

gText_ApprenticeMoveThanks7::
	.string "{STR_VAR_1}!\n"
	.string "L'ensenyaré ara mateix!\p"
	.string "Gràcies, {PLAYER}.\n"
	.string "Espero que pugui comptar amb tu una altra vegada.\l"
	.string "Cuida't!$"

gText_ApprenticeWhichMove8::
	.string "Eek! {PLAYER}! T'he tornat a trobar!\n"
	.string "Jo… Estic boig de content!\p"
	.string "Sempre que necessito alguna cosa, sempre\n"
	.string "hi ets per a mi, {PLAYER}!\p"
	.string "Avui, vull que em recomanis\n"
	.string "un moviment!\p"
	.string "Si us plau tria un moviment per al\n"
	.string "meu {STR_VAR_1}!\p"
	.string "Quin moviment seria millor,\n"
	.string "{STR_VAR_2} o {STR_VAR_3}?$"

gText_ApprenticeMoveThanks8::
	.string "Oh-oh-oh! Gràcies!\n"
	.string "{STR_VAR_1}!\l"
	.string "Perfectament entès!\p"
	.string "Espero que estiguis disposat a ensenyar-me\n"
	.string "més coses un altre cop.$"

gText_ApprenticeWhichMove9::
	.string "Hola, {PLAYER}{KUN}, bé!\n"
	.string "Espero més del\n"
	.string "teu savi consell avui!\p"
	.string "Quin seria el millor moviment per al\n"
	.string "meu {STR_VAR_1}?\p"
	.string "Hauria de ser alguna cosa que em\n"
	.string "deixi guanyar així!\p"
	.string "Seria {STR_VAR_2}?\n"
	.string "O {STR_VAR_3}?$"

gText_ApprenticeMoveThanks9::
	.string "Uh-huh, {STR_VAR_1}!\n"
	.string "Sí, bé!\l"
	.string "Faré que l'ensenyin, com, ka-blam!\p"
	.string "D'acord, gràcies, com sempre!\n"
	.string "Adéu!$"

gText_ApprenticeWhichMove10::
	.string "{PLAYER}{KUN}, és totalment salvatge!\p"
	.string "El meu POKéMON!\n"
	.string "Ha après sis moviments!\p"
	.string "És clar que estic mentint!\n"
	.string "Wahahaha!\p"
	.string "Això no és mentida, però.\n"
	.string "No sóc molt bo triant moviments\n"
	.string "per als meus POKéMON.\p"
	.string "Així que, què tal decidir per mi quin\n"
	.string "tipus de moviment hauria d'ensenyar?\p"
	.string "{STR_VAR_2} o {STR_VAR_3}--quin\n"
	.string "aniria millor amb el meu {STR_VAR_1}?$"

gText_ApprenticeMoveThanks10::
	.string "D'acord, així que és {STR_VAR_1} que has triat?\n"
	.string "Ensenyaré l'altre, llavors!\p"
	.string "És broma!\n"
	.string "Obeïré el teu ensenyament, mestre!\p"
	.string "Gràcies, mestre!\n"
	.string "Espero que em continuïs ensenyant!$"

gText_ApprenticeWhichMove11::
	.string "H-O-L-A!\n"
	.string "I això s'escriu hola!\p"
	.string "El MARINER que rapeja sóc jo!\n"
	.string "Segur que recordes qui sóc jo?\p"
	.string "Avui, tinc una pregunta de moviments\n"
	.string "que demana el teu suggeriment!\p"
	.string "Al meu {STR_VAR_1} li cal un moviment,\n"
	.string "{STR_VAR_2} o {STR_VAR_3}, veus.\l"
	.string "Quin és el que li he d'ensenyar?$"

gText_ApprenticeMoveThanks11::
	.string "{STR_VAR_1}, dius, ei, ei!\n"
	.string "Iré a ensenyar-lo ara mateix!\p"
	.string "Si mai necessito consell,\n"
	.string "{PLAYER}, la teva paraula sempre seguiré!$"

gText_ApprenticeWhichMove12::
	.string "Ei, ei, ei, {PLAYER}!\n"
	.string "Com estàs?\p"
	.string "Vull que em donis consell sobre\n"
	.string "un moviment!\l"
	.string "M'estàs rebent?\l"
	.string "M'estàs rebent!\p"
	.string "Quin moviment va millor amb\n"
	.string "el meu {STR_VAR_1}?\n"
	.string "{STR_VAR_2} o {STR_VAR_3}?$"

gText_ApprenticeMoveThanks12::
	.string "Si {STR_VAR_1} és el que suggereixes,\n"
	.string "ha de ser el millor!\p"
	.string "Bé, {PLAYER}, he de vagar lliure,\n"
	.string "però no t'oblidis de mi.\p"
	.string "Ens veiem una altra vegada, amic intel·ligent!$"

gText_ApprenticeWhichMove13::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Tinc una pregunta sobre moviments.\p"
	.string "Quin moviment hauria d'aprendre\n"
	.string "el meu {STR_VAR_1}?\p"
	.string "{STR_VAR_2} o {STR_VAR_3}?$"

gText_ApprenticeMoveThanks13::
	.string "Hm, {STR_VAR_1}, d'acord.\n"
	.string "L'ensenyaré quan tingui temps.\p"
	.string "Espero que pugui continuar demanant-te\n"
	.string "ajuda així.$"

gText_ApprenticeWhichMove14::
	.string "Er… Ehm…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Si us plau, no em miris així.\n"
	.string "Em poso tot confós…\p"
	.string "Jo… Necessito el teu consell.\p"
	.string "Em fa vergonya, però no puc\n"
	.string "decidir quin moviment ensenyar.\p"
	.string "Per al meu {STR_VAR_1},\n"
	.string "quin moviment seria millor,\l"
	.string "{STR_VAR_2} o {STR_VAR_3}?$"

gText_ApprenticeMoveThanks14::
	.string "Oh… D'acord!\n"
	.string "Ensenyaré {STR_VAR_1}.\p"
	.string "Espero que pugui fer-ho sense\n"
	.string "posar-me tot confós.\p"
	.string "Gràcies, {PLAYER}{KUN}.\n"
	.string "Si ens tornem a trobar, espero que siguis\n"
	.string "tan útil.$"

gText_ApprenticeWhichMove15::
	.string "Hm? Sembles ser {PLAYER}{KUN}…\n"
	.string "Però ets realment real?\p"
	.string "No, no, si ets real, està bé.\n"
	.string "De passada, m'agradaria obtenir\n"
	.string "el teu consell.\p"
	.string "És sobre un moviment per al meu {STR_VAR_1}.\p"
	.string "Si les opcions són els moviments\n"
	.string "{STR_VAR_2} i {STR_VAR_3}, quin és\n"
	.string "més digne de mi?$"

gText_ApprenticeMoveThanks15::
	.string "{STR_VAR_1}?\n"
	.string "Estàs segur?\p"
	.string "Ja veig. Si és el cas, està bé.\n"
	.string "T'agraeixo el teu temps.\p"
	.string "Espero que el meu POKéMON pugui\n"
	.string "fer-ne bon ús.\p"
	.string "Trobem-nos una altra vegada!$"

gText_ApprenticePickWinSpeech0::
	.string "Snif…\n"
	.string "Oh, {PLAYER}!\p"
	.string "Hi ha una última cosa\n"
	.string "que et vull preguntar, {PLAYER}.\p"
	.string "Quan guanyo un combat…\n"
	.string "Què hauria de dir?$"

gText_ApprenticeWinSpeechThanks0::
	.string "{STR_VAR_1}\p"
	.string "Ja veig… Està bé…\n"
	.string "Buaaaaa!\p"
	.string "Oh! Ho sento molt!\n"
	.string "Estic tan content que has decidit\n"
	.string "el que he de dir!\p"
	.string "Em temo que he après tot el que\n"
	.string "puc de tu, {PLAYER}…\p"
	.string "Però potser ens tornarem a veure\n"
	.string "en algun altre lloc.\p"
	.string "Gràcies… Snif… per tot!$"

gText_ApprenticePickWinSpeech1::
	.string "Bé! Hola, {PLAYER}!\n"
	.string "Necessito el teu consell una última vegada!\p"
	.string "Quan guanyo un combat,\n"
	.string "què hauria de dir?$"

gText_ApprenticeWinSpeechThanks1::
	.string "{STR_VAR_1}\p"
	.string "Oh, això és genial! D'acord!\n"
	.string "Ho diré!\p"
	.string "He après tot el que podia de tu.\p"
	.string "Gràcies per tot!$"

gText_ApprenticePickWinSpeech2::
	.string "{PLAYER}, hola!\n"
	.string "Tinc una última pregunta.\p"
	.string "Quan guanyo un combat,\n"
	.string "què hauria de dir?\p"
	.string "Vull que soni genial!$"

gText_ApprenticeWinSpeechThanks2::
	.string "{STR_VAR_1}\p"
	.string "D'acord, ho entenc!\n"
	.string "Gràcies!\p"
	.string "Ja no tinc res més a preguntar-te.\p"
	.string "Gràcies per tot, {PLAYER}.\n"
	.string "Adéu!$"

gText_ApprenticePickWinSpeech3::
	.string "Hola, {PLAYER}…\p"
	.string "Tinc una última pregunta…\p"
	.string "Si guanyo un combat…\n"
	.string "Què hauria de dir?$"

gText_ApprenticeWinSpeechThanks3::
	.string "{STR_VAR_1}\p"
	.string "Ja veig… Gràcies…\p"
	.string "Diré això quan guanyi…\p"
	.string "He après tot el que puc de tu, {PLAYER}.\p"
	.string "Moltes gràcies per tot.$"

gText_ApprenticePickWinSpeech4::
	.string "Oh, {PLAYER}{KUN}!\n"
	.string "Tinc una última pregunta.\p"
	.string "Quan guanyo un combat,\n"
	.string "què hauria de dir?\p"
	.string "Vull alguna cosa que soni genial!$"

gText_ApprenticeWinSpeechThanks4::
	.string "{STR_VAR_1}\p"
	.string "D'acord! Això és genial!\p"
	.string "Gràcies per tot, {PLAYER}{KUN}.\p"
	.string "Adéu!$"

gText_ApprenticePickWinSpeech5::
	.string "Ei, {PLAYER}{KUN}!\n"
	.string "Estic tan ocupat com sempre!\p"
	.string "No tinc temps per pensar\n"
	.string "en què dir quan guanyo.\p"
	.string "{PLAYER}{KUN}, dóna'm una mica del teu bon\n"
	.string "consell! Què hauria de dir quan guanyi?$"

gText_ApprenticeWinSpeechThanks5::
	.string "{STR_VAR_1}\p"
	.string "D'acord, entès.\n"
	.string "Diré això!\p"
	.string "Gràcies per tot!\n"
	.string "Ens veiem!$"

gText_ApprenticePickWinSpeech6::
	.string "Oh! Sort!\n"
	.string "T'he tornat a trobar, {PLAYER}!\p"
	.string "Tinc una última pregunta per a tu!\p"
	.string "Quan guanyo un combat,\n"
	.string "què hauria de dir?\p"
	.string "Vull alguna cosa genial!$"

gText_ApprenticeWinSpeechThanks6::
	.string "{STR_VAR_1}\p"
	.string "Ahhh!\n"
	.string "Això és genial!\p"
	.string "Gràcies per tot, {PLAYER}!\n"
	.string "Adéu!$"

gText_ApprenticePickWinSpeech7::
	.string "Oh, hola, {PLAYER}.\n"
	.string "Tinc una última pregunta.\p"
	.string "Quan guanyo un combat,\n"
	.string "què hauria de dir?$"

gText_ApprenticeWinSpeechThanks7::
	.string "{STR_VAR_1}\p"
	.string "Ja veig. És perfecte.\p"
	.string "Gràcies per tot, {PLAYER}.\n"
	.string "Cuida't!$"

gText_ApprenticePickWinSpeech8::
	.string "Eek! {PLAYER}!\n"
	.string "Tinc una última pregunta!\p"
	.string "Quan guanyo un combat,\n"
	.string "què hauria de dir?\p"
	.string "Vull alguna cosa genial!$"

gText_ApprenticeWinSpeechThanks8::
	.string "{STR_VAR_1}\p"
	.string "Oh-oh-oh! Gràcies!\n"
	.string "Perfectament entès!\p"
	.string "Gràcies per tot, {PLAYER}!$"

gText_ApprenticePickWinSpeech9::
	.string "Hola, {PLAYER}{KUN}!\n"
	.string "Tinc una última pregunta!\p"
	.string "Quan guanyo un combat,\n"
	.string "què hauria de dir?\p"
	.string "Vull alguna cosa que soni genial!$"

gText_ApprenticeWinSpeechThanks9::
	.string "{STR_VAR_1}\p"
	.string "Uh-huh, això és genial!\n"
	.string "Sí, bé!\l"
	.string "Intentaré dir això!\p"
	.string "I ara, és hora de dir adéu!\n"
	.string "Gràcies per tot!\p"
	.string "Dóna'm un combat algun dia, d'acord?\n"
	.string "Adéu!$"

gText_ApprenticePickWinSpeech10::
	.string "{PLAYER}{KUN}, hi ha grans problemes!\p"
	.string "Quan guanyo un combat, presumeixo d'això\n"
	.string "com a mínim una hora!\p"
	.string "És clar que estic mentint!\n"
	.string "Wahahaha!\p"
	.string "Això no és mentida, però.\n"
	.string "No sóc molt bo xerrant.\p"
	.string "Així que, què tal decidir per mi què\n"
	.string "hauria de dir després de guanyar un combat,\l"
	.string "mestre?$"

gText_ApprenticeWinSpeechThanks10::
	.string "{STR_VAR_1}\p"
	.string "Això és el que hauria de dir, eh?\n"
	.string "Llavors, m'allunyaré d'això!\p"
	.string "És broma!\n"
	.string "Obeïré el teu ensenyament, mestre!\p"
	.string "Gràcies per ensenyar-me tot aquest temps,\n"
	.string "mestre!\p"
	.string "Finalment estic entenent què vol dir ser\n"
	.string "un ENTRENADOR.\p"
	.string "Sortiré i guanyaré combats\n"
	.string "contra qualsevol ENTRENADOR.\p"
	.string "Potser seràs tu algun dia, mestre!\p"
	.string "Això és tot!\n"
	.string "Adéu, mestre meu!$"

gText_ApprenticePickWinSpeech11::
	.string "H-O-L-A!\n"
	.string "I això s'escriu hola!\p"
	.string "El MARINER que rapeja sóc jo!\n"
	.string "Aquesta serà la meva última pregunta,\l"
	.string "no ploris!\p"
	.string "És una pregunta de frases\n"
	.string "que demana el teu suggeriment!\p"
	.string "Si guanyo un combat, què puc dir\n"
	.string "d'una manera molt genial?$"

gText_ApprenticeWinSpeechThanks11::
	.string "{STR_VAR_1}\p"
	.string "Perfecte! Això és el que faré servir.\n"
	.string "Tenia raó de fer-te triar!\p"
	.string "I ara, crec que seria millor,\n"
	.string "si volés del niu!\p"
	.string "Gràcies per tot el que m'has ensenyat.\n"
	.string "Me'n vaig a una sèrie de combats!\p"
	.string "B-O-N-V-I-A-T-G-E!\n"
	.string "I això s'escriu bon viatge,\n"
	.string "a tu aquest és el meu homenatge!$"

gText_ApprenticePickWinSpeech12::
	.string "Oh, sí, {PLAYER}!\n"
	.string "T'he tornat a trobar avui!\p"
	.string "Què hauria de fer? Preguntar-te una altra vegada?\n"
	.string "Per què no? Ja t'estic preguntant!\p"
	.string "De totes maneres, {PLAYER}…\n"
	.string "M'estàs rebent?\l"
	.string "M'estàs rebent!\l"
	.string "Necessito més consell per a mi!\p"
	.string "És sobre el que hauria de cridar.\n"
	.string "Alguna cosa genial per cridar quan\n"
	.string "un combat acaba bé.\p"
	.string "Vinga, vull sentir-t'ho dir!$"

gText_ApprenticeWinSpeechThanks12::
	.string "{STR_VAR_1}\p"
	.string "D'acord, d'acord!\n"
	.string "Faré servir això perquè és tan genial!\p"
	.string "Ja no tinc res més a preguntar-te.\n"
	.string "Dir adéu és tot el que queda.\p"
	.string "Però potser algun dia ens trobem, amb un\n"
	.string "destinat a caure derrotat.\p"
	.string "Però, realment és hora de dir adéu.\p"
	.string "Bé, {PLAYER}, he de vagar lliure,\n"
	.string "però no t'oblidis de mi!\p"
	.string "Cuida't, {PLAYER}!\n"
	.string "T'estimo!$"

gText_ApprenticePickWinSpeech13::
	.string "{PLAYER}{KUN}, estic acabat…\n"
	.string "El meu nas no para de gotejar…\p"
	.string "Estava intentant pensar alguna cosa\n"
	.string "genial per dir quan guanyo un combat.\p"
	.string "Em va inspirar tant, que em va fer plorar,\n"
	.string "i ara el meu nas no para de rajar…\p"
	.string "Així que, estant les coses així,\n"
	.string "necessito que decideixis per mi, {PLAYER}{KUN}.\p"
	.string "Quan guanyo un combat,\n"
	.string "què hauria de dir?$"

gText_ApprenticeWinSpeechThanks13::
	.string "{STR_VAR_1}\p"
	.string "… … …Això és bo.\n"
	.string "No, és inspirador!\l"
	.string "Em porta llàgrimes fresques als ulls!\p"
	.string "Però malgrat les meves llàgrimes i nas\n"
	.string "rajant, faré servir aquesta frase!\p"
	.string "Ja no tinc res més a preguntar-te,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "A partir d'ara, som rivals!\n"
	.string "Gràcies per tot!$"

gText_ApprenticePickWinSpeech14::
	.string "Er… Ehm…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Si us plau, no em miris així.\n"
	.string "Em poses tot nerviós.\p"
	.string "Jo… Necessito el teu consell una altra vegada.\n"
	.string "Serà l'últim, però…\p"
	.string "És molt vergonyós preguntar,\n"
	.string "però i si guanyo un combat?\l"
	.string "Què hauria de dir?$"

gText_ApprenticeWinSpeechThanks14::
	.string "{STR_VAR_1}\p"
	.string "Oh… D'acord!\n"
	.string "Intentaré dir això!\l"
	.string "Potser estigui massa nerviós per dir-ho…\p"
	.string "Gràcies, {PLAYER}{KUN}.\n"
	.string "He de dir adéu ara.\p"
	.string "Obeïré tot el que m'has ensenyat,\n"
	.string "{PLAYER}{KUN}, i ho faré el millor que pugui.$"

gText_ApprenticePickWinSpeech15::
	.string "Hm? Sembles ser {PLAYER}{KUN}…\n"
	.string "Però ets realment real?\l"
	.string "Potser una NINA {PLAYER} intel·ligent?\p"
	.string "Oh, no, no, no, no et preocupis!\n"
	.string "Si realment ets real, si us plau\l"
	.string "oblida la meva falta d'educació.\p"
	.string "No cal que estiguis tan enfadat. Tot el que vull\n"
	.string "és més del teu bon consell.\p"
	.string "És sobre una frase.\p"
	.string "Més precisament, què hauria de dir\n"
	.string "si guanyo un combat?$"

gText_ApprenticeWinSpeechThanks15::
	.string "{STR_VAR_1}\p"
	.string "… … … … … …\n"
	.string "Quan guanyi un combat…\p"
	.string "{STR_VAR_1}\p"
	.string "…Parles seriosament?\p"
	.string "Ja veig. Si parles seriosament, està bé.\n"
	.string "T'agraeixo el teu temps.\p"
	.string "Espero que fins i tot jo pugui fer\n"
	.string "bon ús d'aquesta frase.\p"
	.string "Sembla que m'he quedat sec de quin consell\n"
	.string "necessito.\p"
	.string "Crec que és hora de dir-te\n"
	.string "adéu i sortir pel meu compte.\p"
	.string "Gràcies, mentor meu!\n"
	.string "Demano disculpes pel meu escepticisme!$"
