FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Et dono la benvinguda a la TENDA COMBAT\n"
	.string "SEU CASCALL!\p"
	.string "Sóc el teu guia per al Torneig KO Fix!$"

FallarborTown_BattleTentLobby_Text_TakeChallenge:
	.string "Ara, desitges acceptar el desafiament\n"
	.string "d'un Torneig KO Fix?$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge:
	.string "Esperem el teu desafiament en\n"
	.string "una altra ocasió!$"

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent:
	.string "A la TENDA COMBAT CASCALL,\n"
	.string "duem a terme el Torneig KO Fix.\p"
	.string "Tots els participants entren amb un equip de\n"
	.string "tres POKéMON.\p"
	.string "Els tres POKéMON s'han d'ordenar\n"
	.string "en l'ordre en què han d'aparèixer.\p"
	.string "Durant el combat, els POKéMON apareixeran\n"
	.string "un a un en l'ordre preestablert.\p"
	.string "Un cop un POKéMON entra en combat, ha de\n"
	.string "quedar-s'hi fins que es decideixi el resultat.\p"
	.string "Si un combat queda sense decidir en\n"
	.string "tres torns, es va a judici.\p"
	.string "Si vols interrompre el teu desafiament,\n"
	.string "si us plau desa el joc.\p"
	.string "Si no deses, no podràs\n"
	.string "continuar amb el teu desafiament.\p"
	.string "Si aconsegueixes la gesta de vèncer\n"
	.string "tres ENTRENADORS seguits,\l"
	.string "et presentarem un bon premi.$"

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Abans de mostrar-te la TENDA\n"
	.string "COMBAT, he de desar. Està bé?$"

@ Unused
FallarborTown_BattleTentLobby_Text_WhichLevelMode:
	.string "Oferim dos nivells de desafiament,\n"
	.string "Nivell 50 i Nivell Obert.\l"
	.string "Quina és la teva elecció?$"

FallarborTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Molt bé, ara selecciona els teus\n"
	.string "tres POKéMON, si us plau.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Estimat desafiador!\p"
	.string "No tens els tres POKéMON\n"
	.string "requerits per entrar.\p"
	.string "Tampoc han de portar el mateix\n"
	.string "tipus d'objectes.\p"
	.string "Els OUS{STR_VAR_1} no són elegibles.\p"
	.string "Quan hagis fet els teus preparatius,\n"
	.string "si us plau torna.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Estimat desafiador!\p"
	.string "No tens els tres POKéMON\n"
	.string "requerits per entrar.\p"
	.string "Per qualificar, has de portar tres\n"
	.string "tipus diferents de POKéMON.\p"
	.string "Tampoc han de portar el mateix\n"
	.string "tipus d'objectes.\p"
	.string "Els OUS{STR_VAR_1} no són elegibles.\p"
	.string "Quan hagis fet els teus preparatius,\n"
	.string "si us plau torna.$"

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent:
	.string "Ara et guiaré a\n"
	.string "la TENDA COMBAT.$"

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Estimat desafiador!\p"
	.string "No vas desar el joc abans\n"
	.string "d'apagar, oi?\p"
	.string "És lamentable, però això ha\n"
	.string "resultat en la teva desqualificació\l"
	.string "del teu desafiament.\p"
	.string "Pots, és clar, començar amb un\n"
	.string "desafiament nou.$"

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers:
	.string "Quin esplèndid! Has vençut\n"
	.string "tres ENTRENADORS seguits!$"

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame:
	.string "Si us plau espera mentre deso el joc.$"

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "En commemoració de la teva ratxa de 3 victòries,\n"
	.string "et presentem aquest premi.$"

FallarborTown_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} ha rebut el premi\n"
	.string "{STR_VAR_1}.$"

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize:
	.string "Oh?\n"
	.string "La teva BOSSA sembla estar plena.\p"
	.string "Et recomano que facis espai i\n"
	.string "tornis pel teu premi.$"

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving:
	.string "Moltes gràcies per participar!\p"
	.string "Si us plau espera mentre deso el joc.$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2:
	.string "Esperem el teu desafiament en\n"
	.string "una altra ocasió!$"

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival:
	.string "Hem estat esperant\n"
	.string "la teva arribada.\p"
	.string "Abans de mostrar-te la TENDA COMBAT,\n"
	.string "he de desar el joc. Si us plau espera.$"

VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Benvingut a la CARPA COMBAT\n"
	.string "VERDAZUL.\p"
	.string "$"

VerdanturfTown_BattleTentLobby_Text_TakeChallenge:
	.string "T'agradaria provar el desafiament?$"

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent:
	.string "En aquesta instal·lació de CARPA COMBAT,\n"
	.string "els ENTRENADORS competeixen per fer que\l"
	.string "els seus POKéMON creixin ràpidament.\p"
	.string "Podràs accedir al TORNEIG\n"
	.string "amb un equip de tres POKéMON.\p"
	.string "Durant cada combat, qualsevol POKéMON\n"
	.string "que guanyi pujarà de nivell.\p"
	.string "Quan superis tres entrenadors seguits,\n"
	.string "el teu repte haurà acabat.$"

VerdanturfTown_BattleTentLobby_Text_ReturnFortified:
	.string "Esperem veure't de nou quan\n"
	.string "vulguis enfortir els teus POKéMON.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_WhichLevelMode:
	.string "A quina modalitat t'agradaria\n"
	.string "competir?$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Em sap greu...\p"
	.string "No tens prou POKéMON que\n"
	.string "compleixen els requisits.\p"
	.string "Per participar en el Nivell 50,\n"
	.string "necessites tres POKéMON de\l"
	.string "nivell 50 o inferior.\p"
	.string "A més, no s'admeten POKéMON OUS\n"
	.string "ni POKéMON de la mateixa espècie.$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Em sap greu...\p"
	.string "No tens prou POKéMON que\n"
	.string "compleixen els requisits.\p"
	.string "Per participar en el Nivell Obert,\n"
	.string "necessites tres POKéMON.\p"
	.string "A més, no s'admeten POKéMON OUS\n"
	.string "ni POKéMON de la mateixa espècie.$"

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Molt bé, si us plau, selecciona\n"
	.string "els tres POKéMON que participaran.$"

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Abans de començar el repte,\n"
	.string "he de desar el teu progrés.\p"
	.string "És correcte?$"

VerdanturfTown_BattleTentLobby_Text_NowFollowMe:
	.string "Ara, si us plau, segueix-me.$"

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded:
	.string "Felicitats!\p"
	.string "Els teus resultats seran\n"
	.string "registrats.\p"
	.string "Si us plau, espera mentre\n"
	.string "desem les teves dades.$"

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak:
	.string "Felicitats!\p"
	.string "Has aconseguit una ratxa de\n"
	.string "tres victòries seguides!\p"
	.string "Els teus POKéMON han de sentir-se\n"
	.string "més forts que mai!$"

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded:
	.string "La teva gesta serà registrada.\p"
	.string "Si us plau, espera mentre\n"
	.string "desem les teves dades.$"

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "A més, per celebrar la teva\n"
	.string "victòria, et fem entrega\l"
	.string "d'aquest premi!$"

SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Benvingut a la CARPA COMBAT\n"
	.string "PORTUAL.\p"
	.string "$"

SlateportCity_BattleTentLobby_Text_TakeChallenge:
	.string "T'agradaria provar el desafiament?$"

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent:
	.string "En aquesta instal·lació de CARPA COMBAT,\n"
	.string "els ENTRENADORS combaten amb POKéMON\l"
	.string "de lloguer en lloc dels seus.\p"
	.string "Podràs accedir al TORNEIG\n"
	.string "amb un equip de tres POKéMON.\p"
	.string "No sabràs els moviments dels POKéMON\n"
	.string "de lloguer fins que comenci el combat.\p"
	.string "A més, podràs canviar POKéMON\n"
	.string "amb el teu oponent derrotat.\p"
	.string "Quan superis tres entrenadors seguits,\n"
	.string "el teu repte haurà acabat.$"

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit:
	.string "Esperem la teva propera visita.$"

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode:
	.string "A quina modalitat t'agradaria\n"
	.string "competir?$"

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Molt bé, abans de començar el repte,\n"
	.string "he de desar el teu progrés.\p"
	.string "És correcte?$"

@ Unused
SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping:
	.string "Durant el teu desafiament, guardarem\n"
	.string "els teus POKéMON en custòdia.\p"
	.string "Si us plau, tria els POKéMON\n"
	.string "que vols deixar-nos.$"

SlateportCity_BattleTentLobby_Text_StepThisWay:
	.string "Si us plau, vine per aquí.\p"
	.string "Aquí pots triar els teus tres\n"
	.string "POKéMON de lloguer.$"

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults:
	.string "Molt bé, retorna els POKéMON de\n"
	.string "lloguer, si us plau.\p"
	.string "Desem els teus resultats.\p"
	.string "Si us plau, espera mentre\n"
	.string "desem les teves dades.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals:
	.string "Em sap greu, però has de tornar\n"
	.string "els POKéMON de lloguer.\p"
	.string "Hi ha alguns POKéMON que no\n"
	.string "pots intercanviar.\p"
	.string "Si us plau, retorna'ls tots.$"

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons:
	.string "Felicitats!\p"
	.string "Has guanyat tres combats seguits!\p"
	.string "Ara, si us plau, retorna els\n"
	.string "POKéMON de lloguer.$"

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize:
	.string "La teva gesta serà registrada.\p"
	.string "Si us plau, espera mentre\n"
	.string "desem les teves dades.\p"
	.string "A més, et fem entrega d'aquest\n"
	.string "premi per la teva victòria!$"

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom:
	.string "Ei, la teva MOTXILLA és plena.\p"
	.string "Si us plau, fes espai per al\n"
	.string "premi.$"

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou:
	.string "T'estàvem esperant.\p"
	.string "Aquí tens els teus POKéMON\n"
	.string "que havíem guardat.$"

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Oh?\p"
	.string "Sembla que vas sortir sense\n"
	.string "desar l'última vegada.\p"
	.string "Em temo que no podem\n"
	.string "retornar-te els POKéMON\l"
	.string "que combatien amb tu.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons:
	.string "Aquí tens els teus POKéMON\n"
	.string "que havíem guardat.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} ha rebut el premi\n"
	.string "{STR_VAR_1}.$"

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed:
	.string "Les regles del Combat Intercanvi\n"
	.string "estan llistades.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading:
	.string "Quin apartat vols llegir?$"

SlateportCity_BattleTentLobby_Text_ExplainBasicRules:
	.string "En un esdeveniment de Combat Intercanvi,\n"
	.string "només pots fer servir tres POKéMON.\p"
	.string "Quan guanyes un combat, pots canviar\n"
	.string "un dels teus POKéMON per un del teu\l"
	.string "oponent derrotat.\p"
	.string "Si guanyes tres combats seguits,\n"
	.string "el teu repte ha acabat.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules:
	.string "Només pots intercanviar POKéMON\n"
	.string "amb l'ENTRENADOR que acabes de\l"
	.string "derrotar.\p"
	.string "No pots fer cap intercanvi si\n"
	.string "fuges o perds el combat.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules:
	.string "Després de cada combat que guanyis,\n"
	.string "pots intercanviar un dels teus\l"
	.string "POKéMON derrotats pels del teu\l"
	.string "oponent.\p"
	.string "Només pots intercanviar un\n"
	.string "POKéMON per combat.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes:
	.string "Hi ha dos punts clau a tenir en compte\n"
	.string "quan intercanviïs POKéMON.\p"
	.string "Primer, pots intercanviar només\n"
	.string "POKéMON que hagin caigut al combat.\p"
	.string "Segon, no pots intercanviar POKéMON\n"
	.string "que ja tinguis al teu equip.$"

SlateportCity_BattleTentLobby_Text_ExplainMonRules:
	.string "Els POKéMON de la CARPA COMBAT\n"
	.string "PORTUAL són tots de lloguer.\p"
	.string "No sabràs els seus moviments fins\n"
	.string "que comenci el combat.\p"
	.string "Pots triar el primer POKéMON\n"
	.string "en funció de la seva espècie.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2:
	.string "Les regles de la CARPA COMBAT\n"
	.string "VERDAZUL estan llistades.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading:
	.string "Quin apartat vols llegir?$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules:
	.string "Aquí a la CARPA COMBAT VERDAZUL,\n"
	.string "els POKéMON han de combatre sense\n"
	.string "rebre ordres del seu ENTRENADOR.\p"
	.string "Depenent de la natura del POKéMON,\n"
	.string "pot tenir preferències sobre\n"
	.string "quin tipus de moviments fa servir.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules:
	.string "Depenent de la seva natura, un POKéMON\n"
	.string "pot preferir atacar en lloc de fer\l"
	.string "servir moviments d'estat.\p"
	.string "La inversa també és certa.\p"
	.string "Pel tipus de natura, el POKéMON pot\n"
	.string "preferir moviments ofensius o moviments\l"
	.string "d'estat.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules:
	.string "Hi ha moviments ofensius que infligeixen\n"
	.string "dany directe a l'oponent.\p"
	.string "Hi ha moviments d'estat que causen\n"
	.string "efectes adversos al rival sense\l"
	.string "facturar-li danys.\p"
	.string "També hi ha moviments defensius que\n"
	.string "augmenten les estadístiques pròpies.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules:
	.string "Quan no està sota les ordres del seu\n"
	.string "ENTRENADOR, un POKéMON pot no poder\l"
	.string "funcionar al màxim potencial.\p"
	.string "Per exemple, pot no poder canviar el\n"
	.string "POKéMON actiu.\p"
	.string "O el POKéMON pot no ser capaç de\n"
	.string "fer servir objectes de batalla.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules:
	.string "Depenent de la seva natura, un POKéMON\n"
	.string "pot començar a fer servir moviments\l"
	.string "que normalment no utilitzaria si la\l"
	.string "seva vida està en perill.\p"
	.string "Quan estigui pròxim al KO,\n"
	.string "el POKéMON pot fer servir moviments\l"
	.string "estratègics o ofensius en el seu lloc.$"

BattleTentLobby_Text_ExplainLevelRules:
	.string "En aquesta CARPA COMBAT, els nivells\n"
	.string "dels teus oponents s'ajustaran segons\l"
	.string "la modalitat triada.\p"
	.string "Si tries el Nivell 50, els teus\n"
	.string "POKéMON que superin el nivell 50\l"
	.string "seran ajustats a Nv.50.\p"
	.string "No hi ha cap restricció en el Nivell\n"
	.string "Obert. Tots els POKéMON hi poden\l"
	.string "participar.$"

VerdanturfTown_BattleTentLobby_Text_RulesAreListed:
	.string "Les regles de la CARPA COMBAT\n"
	.string "VERDAZUL estan llistades.$"
