BattleDome_Text_Potential1::
	.string "El millor candidat a ser campió!$"

BattleDome_Text_Potential2::
	.string "Un equip segur finalista.$"

BattleDome_Text_Potential3::
	.string "Un probable finalista dels tres primers.$"

BattleDome_Text_Potential4::
	.string "Un candidat a acabar primer.$"

BattleDome_Text_Potential5::
	.string "Un equip amb potencial de primera classe.$"

BattleDome_Text_Potential6::
	.string "L'equip sorpresa d'aquest torneig.$"

BattleDome_Text_Potential7::
	.string "Un equip per sobre de la mitjana.$"

BattleDome_Text_Potential8::
	.string "L'equip mitjà d'aquest torneig.$"

BattleDome_Text_Potential9::
	.string "Un equip amb potencial mitjà.$"

BattleDome_Text_Potential10::
	.string "Un equip per sota de la mitjana.$"

BattleDome_Text_Potential11::
	.string "Un equip que busca la seva primera victòria.$"

BattleDome_Text_Potential12::
	.string "Una victòria farà orgullós aquest equip.$"

BattleDome_Text_Potential13::
	.string "En general, un equip feble.$"

BattleDome_Text_Potential14::
	.string "Un equip amb potencial molt baix.$"

BattleDome_Text_Potential15::
	.string "Un equip poc probable que guanyi el torneig.$"

BattleDome_Text_Potential16::
	.string "L'equip menys probable de guanyar.$"

BattleDome_Text_PotentialDomeAceTucker::
	.string "La superestrella perfecta i invencible!$"

BattleDome_Text_StyleRiskDisaster::
	.string "Disposat a arriscar el desastre total a vegades.$"

BattleDome_Text_StyleEndureLongBattles::
	.string "Hàbil a aguantar combats llargs.$"

BattleDome_Text_StyleVariesTactics::
	.string "Varia les tàctiques segons l'oponent.$"

BattleDome_Text_StyleToughWinningPattern::
	.string "Té un patró de victòria dur.$"

BattleDome_Text_StyleUsesVeryRareMove::
	.string "De vegades utilitza un moviment molt rar.$"

BattleDome_Text_StyleUsesStartlingMoves::
	.string "Utilitza moviments sorprenents i disruptius.$"

BattleDome_Text_StyleConstantlyWatchesHP::
	.string "Constantment vigila els PS en combat.$"

BattleDome_Text_StyleStoresAndLoosesPower::
	.string "Bo a acumular i després alliberar poder.$"

BattleDome_Text_StyleEnfeeblesFoes::
	.string "Hàbil a debilitar els enemics.$"

BattleDome_Text_StylePrefersLuckTactics::
	.string "Prefereix tàctiques que depenen de la sort.$"

BattleDome_Text_StyleRegalAtmosphere::
	.string "Ataca amb una atmosfera reial.$"

BattleDome_Text_StylePowerfulLowPPMoves::
	.string "Ataca amb moviments potents de baix PP.$"

BattleDome_Text_StyleEnfeebleThenAttack::
	.string "Hàbil a debilitar i després atacar.$"

BattleDome_Text_StyleBattlesWhileEnduring::
	.string "Combat mentre aguanta tots els atacs.$"

BattleDome_Text_StyleUpsetsFoesEmotionally::
	.string "Hàbil a alterar emocionalment els enemics.$"

BattleDome_Text_StyleStrongAndStraightforward::
	.string "Utilitza moviments forts i directes.$"

BattleDome_Text_StyleAggressivelyStrongMoves::
	.string "Utilitza agressivament moviments forts.$"

BattleDome_Text_StyleCleverlyDodgesAttacks::
	.string "Combat mentre esquiva hàbilment els atacs.$"

BattleDome_Text_StyleUsesUpsettingMoves::
	.string "Hàbil a utilitzar atacs alteradors.$"

BattleDome_Text_StyleUsesPopularMoves::
	.string "Utilitza molts moviments populars.$"

BattleDome_Text_StyleHasPowerfulComboMoves::
	.string "Té moviments per a combinacions potents.$"

BattleDome_Text_StyleUsesHighProbabilityMoves::
	.string "Utilitza atacs d'alta probabilitat.$"

BattleDome_Text_StyleAggressivelySpectacularMoves::
	.string "Utilitza agressivament moviments espectaculars.$"

BattleDome_Text_StyleEmphasizesOffenseOverDefense::
	.string "Emfatitza l'ofensa sobre la defensa.$"

BattleDome_Text_StyleEmphasizesDefenseOverOffense::
	.string "Emfatitza la defensa sobre l'ofensa.$"

BattleDome_Text_StyleAttacksQuicklyStrongMoves::
	.string "Ataca ràpidament amb moviments forts.$"

BattleDome_Text_StyleUsesAddedEffectMoves::
	.string "Sovint utilitza moviments amb efectes afegits.$"

BattleDome_Text_StyleUsesBalancedMixOfMoves::
	.string "Utilitza una barreja equilibrada de moviments.$"

BattleDome_Text_StyleSampleMessage1::
	.string "Aquest és el missatge de mostra 1.$"

BattleDome_Text_StyleSampleMessage2::
	.string "Aquest és el missatge de mostra 2.$"

BattleDome_Text_StyleSampleMessage3::
	.string "Aquest és el missatge de mostra 3.$"

BattleDome_Text_StyleSampleMessage4::
	.string "Aquest és el missatge de mostra 4.$"

BattleDome_Text_EmphasizesHPAndAtk::
	.string "Emfatitza PS i ATAC.$"

BattleDome_Text_EmphasizesHPAndDef::
	.string "Emfatitza PS i DEFENSA.$"

BattleDome_Text_EmphasizesHPAndSpeed::
	.string "Emfatitza PS i VELOCITAT.$"

BattleDome_Text_EmphasizesHPAndSpAtk::
	.string "Emfatitza PS i AT. ESP.$"

BattleDome_Text_EmphasizesHPAndSpDef::
	.string "Emfatitza PS i DEF. ESP.$"

BattleDome_Text_EmphasizesAtkAndDef::
	.string "Emfatitza ATAC i DEFENSA.$"

BattleDome_Text_EmphasizesAtkAndSpeed::
	.string "Emfatitza ATAC i VELOCITAT.$"

BattleDome_Text_EmphasizesAtkAndSpAtk::
	.string "Emfatitza ATAC i AT. ESP.$"

BattleDome_Text_EmphasizesAtkAndSpDef::
	.string "Emfatitza ATAC i DEF. ESP.$"

BattleDome_Text_EmphasizesDefAndSpeed::
	.string "Emfatitza DEFENSA i VELOCITAT.$"

BattleDome_Text_EmphasizesDefAndSpAtk::
	.string "Emfatitza DEFENSA i AT. ESP.$"

BattleDome_Text_EmphasizesDefAndSpDef::
	.string "Emfatitza DEFENSA i DEF. ESP.$"

BattleDome_Text_EmphasizesSpeedAndSpAtk::
	.string "Emfatitza VELOCITAT i AT. ESP.$"

BattleDome_Text_EmphasizesSpeedAndSpDef::
	.string "Emfatitza VELOCITAT i DEF. ESP.$"

BattleDome_Text_EmphasizesSpAtkAndSpDef::
	.string "Emfatitza AT. ESP. i DEF. ESP.$"

BattleDome_Text_EmphasizesHP::
	.string "Emfatitza PS.$"

BattleDome_Text_EmphasizesAtk::
	.string "Emfatitza ATAC.$"

BattleDome_Text_EmphasizesDef::
	.string "Emfatitza DEFENSA.$"

BattleDome_Text_EmphasizesSpeed::
	.string "Emfatitza VELOCITAT.$"

BattleDome_Text_EmphasizesSpAtk::
	.string "Emfatitza AT. ESP.$"

BattleDome_Text_EmphasizesSpDef::
	.string "Emfatitza DEF. ESP.$"

BattleDome_Text_NeglectsHPAndAtk::
	.string "Descuida PS i ATAC.$"

BattleDome_Text_NeglectsHPAndDef::
	.string "Descuida PS i DEFENSA.$"

BattleDome_Text_NeglectsHPAndSpeed::
	.string "Descuida PS i VELOCITAT.$"

BattleDome_Text_NeglectsHPAndSpAtk::
	.string "Descuida PS i AT. ESP.$"

BattleDome_Text_NeglectsHPAndSpDef::
	.string "Descuida PS i DEF. ESP.$"

BattleDome_Text_NeglectsAtkAndDef::
	.string "Descuida ATAC i DEFENSA.$"

BattleDome_Text_NeglectsAtkAndSpeed::
	.string "Descuida ATAC i VELOCITAT.$"

BattleDome_Text_NeglectsAtkAndSpAtk::
	.string "Descuida ATAC i AT. ESP.$"

BattleDome_Text_NeglectsAtkAndSpDef::
	.string "Descuida ATAC i DEF. ESP.$"

BattleDome_Text_NeglectsDefAndSpeed::
	.string "Descuida DEFENSA i VELOCITAT.$"

BattleDome_Text_NeglectsDefAndSpAtk::
	.string "Descuida DEFENSA i AT. ESP.$"

BattleDome_Text_NeglectsDefAndSpDef::
	.string "Descuida DEFENSA i DEF. ESP.$"

BattleDome_Text_NeglectsSpeedAndSpAtk::
	.string "Descuida VELOCITAT i AT. ESP.$"

BattleDome_Text_NeglectsSpeedAndSpDef::
	.string "Descuida VELOCITAT i DEF. ESP.$"

BattleDome_Text_NeglectsSpAtkAndSpDef::
	.string "Descuida AT. ESP. i DEF. ESP.$"

BattleDome_Text_NeglectsHP::
	.string "Descuida PS.$"

BattleDome_Text_NeglectsAtk::
	.string "Descuida ATAC.$"

BattleDome_Text_NeglectsDef::
	.string "Descuida DEFENSA.$"

BattleDome_Text_NeglectsSpeed::
	.string "Descuida VELOCITAT.$"

BattleDome_Text_NeglectsSpAtk::
	.string "Descuida AT. ESP.$"

BattleDome_Text_NeglectsSpDef::
	.string "Descuida DEF. ESP.$"

BattleDome_Text_RaisesMonsWellBalanced::
	.string "Cria POKéMON de manera equilibrada.$"

BattleDome_Text_LetTheBattleBegin::
	.string "Que comenci el combat!$"

BattleDome_Text_TrainerWonUsingMove::
	.string "{STR_VAR_1} ha guanyat usant {STR_VAR_2}!$"

BattleDome_Text_TrainerBecameChamp::
	.string "{STR_VAR_1} s'ha convertit en el campió!$"

BattleDome_Text_TrainerWonByDefault::
	.string "{STR_VAR_1} ha guanyat per defecte!$"

BattleDome_Text_TrainerWonOutrightByDefault::
	.string "{STR_VAR_1} ha guanyat directament per defecte!$"

BattleDome_Text_TrainerWonNoMoves::
	.string "{STR_VAR_1} ha guanyat sense usar moviments!$"

BattleDome_Text_TrainerWonOutrightNoMoves::
	.string "{STR_VAR_1} ha guanyat directament sense moviments!$"

BattleDome_Text_Round1Match1::
	.string "Ronda 1, Combat 1$"

BattleDome_Text_Round1Match2::
	.string "Ronda 1, Combat 2$"

BattleDome_Text_Round1Match3::
	.string "Ronda 1, Combat 3$"

BattleDome_Text_Round1Match4::
	.string "Ronda 1, Combat 4$"

BattleDome_Text_Round1Match5::
	.string "Ronda 1, Combat 5$"

BattleDome_Text_Round1Match6::
	.string "Ronda 1, Combat 6$"

BattleDome_Text_Round1Match7::
	.string "Ronda 1, Combat 7$"

BattleDome_Text_Round1Match8::
	.string "Ronda 1, Combat 8$"

BattleDome_Text_Round2Match1::
	.string "Ronda 2, Combat 1$"

BattleDome_Text_Round2Match2::
	.string "Ronda 2, Combat 2$"

BattleDome_Text_Round2Match3::
	.string "Ronda 2, Combat 3$"

BattleDome_Text_Round2Match4::
	.string "Ronda 2, Combat 4$"

BattleDome_Text_SemifinalMatch1::
	.string "Semifinal Combat 1$"

BattleDome_Text_SemifinalMatch2::
	.string "Semifinal Combat 2$"

BattleDome_Text_FinalMatch::
	.string "Final$"
