PetalburgCity_Gym_Text_GiveEnigmaBerry:
	.string "PARE: Hola, {PLAYER}!\p"
	.string "Acabo de rebre una BAIA molt rara.\n"
	.string "M'agradaria que te la quedessis.$"

Route104_Text_PlantBerriesInSoilTakeThis:
	.string "Si veus BAIES creixent en terra\n"
	.string "tova, agafa-les sense problema.\p"
	.string "Però assegura't de plantar una BAIA\n"
	.string "al mateix lloc. És de bon costum.\p"
	.string "Mira, et comparteixo això.$"

Route104_Text_TrainersOftenMakeMonHoldBerries:
	.string "Pel que sembla, deus ser\n"
	.string "ENTRENADOR, no?\p"
	.string "Els ENTRENADORS sovint fan que els\n"
	.string "POKéMON portin BAIES.\p"
	.string "Tu decides si cultivar les BAIES\n"
	.string "o utilitzar-les.$"

Route111_Text_WateredPlantsEveryDayTakeBerry:
	.string "Regava les plantes cada dia.\n"
	.string "Van créixer moltes flors.\p"
	.string "I també em van donar moltes BAIES.\p"
	.string "Aquí tens!\n"
	.string "Te la pots quedar!$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:
	.string "M'esforçaré molt i faré BAIES\n"
	.string "de diferents colors.\p"
	.string "Espero que tu també t'esforcis!$"

Route111_Text_WhatColorBerriesToLookForToday:
	.string "Em pregunto de quin color buscarem\n"
	.string "les BAIES avui?$"

Route114_Text_LoveUsingBerryCrushShareBerry:
	.string "M'encanta utilitzar la màquina\n"
	.string "TRITURA BAIES, així que en col·lecciono.\p"
	.string "Et comparteixo una, si vols.$"

Route114_Text_TryBerryCrushWithFriends:
	.string "Hauries de provar la màquina TRITURA\n"
	.string "BAIES amb els teus amics.$"

Route114_Text_FunToThinkAboutBerries:
	.string "Quina BAIA s'hauria de plantar?\n"
	.string "S'haurien d'utilitzar o acumular?\p"
	.string "És divertit pensar-hi.$"

Route120_Text_BerriesExpressionOfLoveIsntIt:
	.string "Les BAIES creixen absorbint llum solar.\p"
	.string "Ajudem les BAIES a créixer regant-les\n"
	.string "regularment.\p"
	.string "És una expressió d'amor, no trobes?$"

Route120_Text_YesYouUnderstand:
	.string "Sí, sí.\n"
	.string "Entens el que vull dir.\p"
	.string "Hauries d'agafar això.$"

Route120_Text_MakeYourOwnImpressions:
	.string "Oh… Però és important formar les\n"
	.string "teves pròpies impressions, suposo…\p"
	.string "Pots quedar-te això.$"

Route120_Text_BerryIsRareRaiseItWithCare:
	.string "Crec que aquesta BAIA és rara.\n"
	.string "Espero que la cuidis amb estima.$"

Route120_Text_IllGetMoreBerriesFromBerryMaster:
	.string "Aconseguiré més BAIES del\n"
	.string "MESTRE BAIER.$"

LilycoveCity_Text_BerrySuitsYou:
	.string "Al cap i a la fi…\p"
	.string "De la mateixa manera que els vestits\n"
	.string "m'escauen, una brisa fresca escau a la mar.\p"
	.string "I a tu, una BAIA t'escau perfectament…\p"
	.string "Per què deu ser?$"

LilycoveCity_Text_BecauseYoureTrainer:
	.string "Al cap i a la fi…\p"
	.string "És perquè ets ENTRENADOR!$"

LilycoveCity_Text_PokeblocksSuitPokemon:
	.string "Al cap i a la fi…\p"
	.string "De la manera que la simplicitat\n"
	.string "digna m'escau, els {POKEBLOCK} escauen\l"
	.string "als POKéMON.$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:
	.string "Em pots dir el MESTRE BAIER.\p"
	.string "Somio amb omplir el món de flors\n"
	.string "boniques, així que cultivo BAIES\l"
	.string "i les reparteixo a tothom.\p"
	.string "Te'n mereixes una!$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:
	.string "Per què ser garrepa?\n"
	.string "Agafa'n una altra!$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:
	.string "Assegura't de visitar la floristeria\n"
	.string "PÈTALS BONICS prop de CIUTAT FERRICA.\p"
	.string "Que les flors omplin el món!$"

Route123_BerryMastersHouse_Text_DoneForToday:
	.string "Per avui ja n'hi ha prou.\n"
	.string "Torna un altre dia.\p"
	.string "Que les flors omplin el món!$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:
	.string "La manera com el meu marit cultiva\n"
	.string "BAIES, oh, és el millor del món.\p"
	.string "Em fa sentir orgullosa, de debò.\p"
	.string "Per cert, nen, has sentit alguna\n"
	.string "bona dita últimament?$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis:
	.string "Ah! Quina dita tan extraordinària!\n"
	.string "Inspiradora, de veritat!\p"
	.string "Vull que tinguis això.$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:
	.string "Oh! Una bona dita és.\n"
	.string "Ets força extraordinari.\p"
	.string "Vull que tinguis això.$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:
	.string "Els nostres quatre néts haurien de\n"
	.string "superar el meu marit.\p"
	.string "L'alegria mai desapareix de la meva vida!$"

Route123_BerryMastersHouse_Text_Ah:
	.string "Ah…$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:
	.string "Hola!\p"
	.string "Aquesta és la floristeria PÈTALS BONICS.\n"
	.string "Escampant flors per tot el món!$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:
	.string "{PLAYER}{KUN}, t'agradaria aprendre sobre\n"
	.string "les BAIES?$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:
	.string "Com et dius?\p"
	.string "{PLAYER}{KUN}.\n"
	.string "És un nom bonic.\p"
	.string "{PLAYER}{KUN}, t'agradaria aprendre sobre\n"
	.string "les BAIES?$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:
	.string "Les BAIES creixen en arbres que només\n"
	.string "prosperen en terra tova i fèrtil.\p"
	.string "Si agafes BAIES, assegura't de\n"
	.string "plantar-ne una altra a la terra.\p"
	.string "Una BAIA plantada aviat brotarà,\n"
	.string "creixerà, florirà i tornarà a\l"
	.string "donar BAIES.\p"
	.string "Vull veure el món sencer ple de\n"
	.string "flors boniques.\l"
	.string "Aquest és el meu somni.\p"
	.string "Ajuda'm, {PLAYER}{KUN}. Planta BAIES\n"
	.string "i porta més flors al món.$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:
	.string "Les flors porten tanta felicitat a\n"
	.string "la gent, no trobes?$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:
	.string "Hola!\p"
	.string "Com més atenció donis a les flors,\n"
	.string "més boniques floreixen.\p"
	.string "T'agradarà cuidar flors. N'estic\n"
	.string "segura. Pots quedar-te això.$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:
	.string "Mentre les plantes de BAIES creixen,\n"
	.string "rega-les amb la REGADORA WAILMER.\p"
	.string "Oh, una altra cosa.\p"
	.string "Si no reculls les BAIES durant un temps,\n"
	.string "cauran a terra.\l"
	.string "Però tornaran a brotar.\p"
	.string "No és increïble?\n"
	.string "És com si tinguessin voluntat de viure.$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:
	.string "Intento ser com les meves germanes\n"
	.string "grans. Jo també cultivo flors!\p"
	.string "Aquí tens!\n"
	.string "És per a tu!$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:
	.string "Pots plantar una BAIA i fer-la créixer,\n"
	.string "o pots fer que un POKéMON la porti.\p"
	.string "Però ara tenen una màquina que barreja\n"
	.string "diferents BAIES i fa dolços\l"
	.string "per a POKéMON.\p"
	.string "Jo també vull dolços.$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese:
	.string "Hola, com et dius?\p"
	.string "… … …  … … …  … … …\n"
	.string "D'acord. Què bonic!\p"
	.string "Jo em dic KIRI.\p"
	.string "El meu papa i la meva mama em van\n"
	.string "posar aquest nom perquè creixés sana\l"
	.string "i de bon cor. Era el seu desig.\p"
	.string "Pots quedar-te una d'aquestes.$"

SootopolisCity_Text_GiveYouThisBerryToo:
	.string "KIRI també et donarà aquesta BAIA!\n"
	.string "M'agrada molt!$"

SootopolisCity_Text_WhatKindOfWishInYourName:
	.string "Em pregunto quin tipus de desig\n"
	.string "conté el teu nom.$"

SootopolisCity_Text_LikeSeasonBornIn:
	.string "Primavera, estiu, tardor i hivern.\p"
	.string "Si neixes a la primavera, t'agrada\n"
	.string "la primavera, i si neixes a l'estiu,\l"
	.string "t'agrada l'estiu?$"

SootopolisCity_Text_ThenILoveAutumn:
	.string "Doncs KIRI va néixer a la tardor,\n"
	.string "així que m'encanta la tardor!\p"
	.string "Quina estació t'agrada a tu?$"

SootopolisCity_Text_OhDoesntMatter:
	.string "Oh…\n"
	.string "No importa…\p"
	.string "Hi ha tantes coses que vull saber…$"
