gText_Birch_Welcome::
	.string "Hola! Perdona per fer-te esperar!\p"
	.string "Benvingut al món dels POKéMON!\p"
	.string "Em dic BEDOLL.\p"
	.string "Però tothom em diu el PROFESSOR\n"
	.string "POKéMON.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Això és el que anomenem un POKéMON.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Aquest món està àmpliament habitat per\n"
	.string "criatures conegudes com POKéMON.\p"
	.string "Els humans vivim al costat dels POKéMON,\n"
	.string "a vegades com a companys de joc, i\l"
	.string "a vegades com a companys de feina.\p"
	.string "I de vegades, ens unim\n"
	.string "i lluitem contra altres com nosaltres.\p"
	.string "Però malgrat la nostra proximitat, no ho\n"
	.string "sabem tot sobre els POKéMON.\p"
	.string "De fet, hi ha molts, molts\n"
	.string "misteris al voltant dels POKéMON.\p"
	.string "Per desvelar els misteris POKéMON,\n"
	.string "he estat fent recerca.\l"
	.string "Això és el que faig.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "I tu qui ets?$"

gText_Birch_BoyOrGirl::
	.string "Ets un noi?\n"
	.string "O ets una noia?$"

gText_Birch_WhatsYourName::
	.string "D'acord.\n"
	.string "Com et dius?$"

gText_Birch_SoItsPlayer::
	.string "Així que ets {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, d'acord!\p"
	.string "Tu ets {PLAYER}{KUN} que et mudes al meu\n"
	.string "poblet natal de LLAURAVET.\l"
	.string "Ara ho entenc!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Bé, estàs preparat?\p"
	.string "La teva pròpia aventura està a punt\n"
	.string "de començar.\p"
	.string "Tingues coratge, i llança't al\n"
	.string "món dels POKéMON on somnis,\l"
	.string "aventures i amistats t'esperen!\p"
	.string "Bé, t'espero més tard.\n"
	.string "Vine a veure'm al meu LABORATORI POKéMON.\p"
	.string "$"
