BerryBlender_Text_BlendWithTheBlendMaster:
	.string "MESTRE MESCLADOR: En efecte!\n"
	.string "El MESTRE MESCLADOR sóc jo!\p"
	.string "Barreja amb mi, i veuràs\n"
	.string "la mestressa que aporto a les barreges!$"

BerryBlender_Text_SeeMyMasteryInAction:
	.string "MESTRE MESCLADOR: Hmmm! Així que\n"
	.string "vols veure el meu mestratge en acció?$"

BerryBlender_Text_TooBusyNowIsee:
	.string "Hmmm!\p"
	.string "Així que estàs massa ocupat ara, ja veig!\p"
	.string "Però no pateixis!\n"
	.string "Seré aquí tot el dia!\l"
	.string "Torna ràpid dels teus afers!$"

BerryBlender_Text_BlendMasterNoBerries:
	.string "Hmmm!\p"
	.string "No tens ni una sola BAIA!\p"
	.string "Seré aquí tot el dia!\n"
	.string "Torna ràpid amb unes BAIES!$"

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks:
	.string "És clar!\n"
	.string "És clar!\p"
	.string "Per cert…\n"
	.string "Ja saps com barrejar {POKEBLOCK}S\l"
	.string "de les BAIES?$"

BerryBlender_Text_BlendMasterExplainBerryBlending:
	.string "Hmmm!\p"
	.string "Ah, però és un procés simple!\p"
	.string "Quan la fletxa del MESCLADOR arribi\n"
	.string "a la teva marca, prem el botó A.\p"
	.string "Això és tot el que has de fer.\p"
	.string "Quan vegis com de precisament premo\n"
	.string "el botó A, ho entendràs.$"

BerryBlender_Text_BlendMasterLetsBerryBlender:
	.string "Bé!\p"
	.string "Comencem, doncs!\p"
	.string "Tots junts amb el MESTRE MESCLADOR,\n"
	.string "a BARREJAR BAIES!$"

BerryBlender_Text_BlendMasterNoPokeblockCase:
	.string "Hmmm!\p"
	.string "Sembla que no tens\n"
	.string "l'ESTOIG de {POKEBLOCK}!\p"
	.string "Seré aquí tot el dia!\n"
	.string "Aconsegueix l'ESTOIG de {POKEBLOCK} i torna!$"

BerryBlender_Text_BlendMasterPokeblockCaseFull:
	.string "Hmmm!\p"
	.string "Sembla que el teu ESTOIG de {POKEBLOCK}\n"
	.string "està ple!\p"
	.string "Seré aquí tot el dia!\n"
	.string "Fes servir uns {POKEBLOCK}S i torna!$"

BerryBlender_Text_WhoaAwesome:
	.string "Uau!\n"
	.string "Increïble!$"

BerryBlender_Text_WickedlyFast:
	.string "Increïblement ràpid!$"

BerryBlender_Text_WhatAnExpert:
	.string "Quin expert!$"

BerryBlender_Text_MadeAmazingPokeblocksWithMaster:
	.string "Quan vaig barrejar amb el MESTRE,\n"
	.string "vam fer {POKEBLOCK}S increïbles!$"

BerryBlender_Text_QualitiesOfBlendMaster:
	.string "Ulls que segueixen la fletxa\n"
	.string "amb intensitat mecànica…\p"
	.string "Una mà que prem el botó A\n"
	.string "amb precisió de rellotgeria…\p"
	.string "Posseir aquestes qualitats fa\n"
	.string "que el MESTRE MESCLADOR sigui genial.$"

BerryBlender_Text_MasterWorksOnSkillsInMountains:
	.string "Es diu que el MESTRE MESCLADOR treballa\n"
	.string "les seves habilitats a les muntanyes.\p"
	.string "De vegades, ve a LLIRINESA\n"
	.string "a barrejar BAIES tot el dia.$"
