Text_PictureBookShelf:
	.string "Hi ha una col·lecció de contes\n"
	.string "il·lustrats de POKéMON.$"

Text_BookShelf:
	.string "Està plena de tot tipus de llibres.$"

Text_PokemonCenterBookShelf:
	.string "Revistes de POKéMON!\n"
	.string "AMIC POKéMON…\p"
	.string "MANUAL POKéMON…\n"
	.string "POKéMON ADORABLES…$"

Text_Vase:
	.string "Aquest gerro sembla car…\n"
	.string "Hi has mirat dins…\p"
	.string "Però estava buit.$"

Text_EmptyTrashCan:
	.string "Està buit.$"

Text_ShopShelf:
	.string "Els prestatges estan plens de\n"
	.string "tot tipus de productes POKéMON.$"

Text_Blueprint:
	.string "Una mena de plànol?\n"
	.string "És massa complicat!$"
