gContestHallPaintingCaption::
	.string "{STR_VAR_1}\n"
	.string "{STR_VAR_3} de {STR_VAR_2}$"

@ Unused
gContestPaintingContest::
	.string "CONCURS$"

gContestRankNormal::
	.string "RANG NORMAL$"

gContestRankSuper::
	.string "RANG SÚPER$"

gContestRankHyper::
	.string "RANG HÍPER$"

gContestRankMaster::
	.string "RANG MESTRE$"

gContestLink::
	.string "ENLLAÇ$"

gContestCoolness::
	.string "DURESA$"

gContestBeauty::
	.string "BELLESA$"

gContestCuteness::
	.string "SIMPATIA$"

gContestSmartness::
	.string "ENGINY$"

gContestToughness::
	.string "FORÇA$"

gContestPaintingCool1::
	.string "Súper dur sense parar--\n"
	.string "l'inestimable {STR_VAR_1}$"

gContestPaintingCool2::
	.string "Ei, hola!\n"
	.string "El POKéMON ben plantat {STR_VAR_1}$"

gContestPaintingCool3::
	.string "El meravellós, fantàstic i\n"
	.string "molt genial {STR_VAR_1}$"

gContestPaintingBeauty1::
	.string "L'última Venus del segle--\n"
	.string "el bell {STR_VAR_1}$"

gContestPaintingBeauty2::
	.string "El somriure brillant i\n"
	.string "resplendent de {STR_VAR_1}$"

gContestPaintingBeauty3::
	.string "El súper ídol del CENTRE POKéMON--\n"
	.string "l'incomparable {STR_VAR_1}$"

gContestPaintingCute1::
	.string "L'encantador i dolç {STR_VAR_1}$"

gContestPaintingCute2::
	.string "El retrat guanyador\n"
	.string "del bonic {STR_VAR_1}$"

gContestPaintingCute3::
	.string "Fes-nos una pampalluga!\n"
	.string "El POKéMON bufó {STR_VAR_1}$"

gContestPaintingSmart1::
	.string "El mestre de l'enginy--\n"
	.string "el savi POKéMON {STR_VAR_1}$"

gContestPaintingSmart2::
	.string "{STR_VAR_1}--l'escollit\n"
	.string "entre tots els POKéMON$"

gContestPaintingSmart3::
	.string "El moment d'elegància\n"
	.string "de l'excel·lent {STR_VAR_1}$"

gContestPaintingTough1::
	.string "El velocista poderosament\n"
	.string "musculós {STR_VAR_1}$"

gContestPaintingTough2::
	.string "El fort, més fort i\n"
	.string "el més fort {STR_VAR_1}$"

gContestPaintingTough3::
	.string "El dur poderós\n"
	.string "híper POKéMON {STR_VAR_1}$"
