@ With the exception of Link standby, none of the below texts are used

gTest_MissedTurn::
	.string "Torn perdut$"

gText_LinkStandby4::
	.string "Enllaç en espera!$"

gText_WinnerIsPlayersMonCongrats::
	.string "El guanyador és {STR_VAR_2} de\n"
	.string "{STR_VAR_1}! Felicitats!$"

gText_WinnerIsPlayersMon::
	.string "El guanyador és {STR_VAR_2} de {STR_VAR_1}!{PAUSE_UNTIL_PRESS}$"

gText_PrimaryJudgingNumX::
	.string "Avaluació primària: Núm. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SecondaryJudgingNumX::
	.string "Avaluació secundària: Núm. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX::
	.string "Esdeveniment establert: Núm. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MoveUsedMostOften::
	.string "El moviment més utilitzat:\n"
	.string "{STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MostImpressiveMon::
	.string "El POKéMON més impressionant:\n"
	.string "{STR_VAR_2} de {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX2::
	.string "Esdeveniment establert: Núm. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_LinkTVProgramWillNotBeMadeTrainerLost::
	.string "No es farà un programa de TV d'enllaç\n"
	.string "perquè l'ENTRENADOR ha perdut.{PAUSE_UNTIL_PRESS}$"
