EventTicket_Text_ShowOldSeaMap:
	.string "El ferri a PORTLAVANDA és…\p"
	.string "Perdona?\n"
	.string "Podem navegar a aquest lloc del mapa?\p"
	.string "Conec algú que t'ajudarà millor.\n"
	.string "Si us plau, espera.$"

EventTicket_Text_ThatPass:
	.string "El ferri a PORTLAVANDA és…\p"
	.string "Oh?\n"
	.string "Aquest PASSI…$"

EventTicket_Text_ShowEonTicket:
	.string "Sí, company, ets tu qui ha portat\n"
	.string "aquest PASSI tan estrany?\p"
	.string "T'ho diré, intentes arribar a una\n"
	.string "petita illeta molt al sud.\p"
	.string "No se sap què trobarem un cop\n"
	.string "hi arribem, sí.\l"
	.string "Em fa tremolar els ossos!\p"
	.string "Tothom a bord!$"

EventTicket_Text_SouthernIslandSailBack:
	.string "Sí, company, no hi ha res a veure\n"
	.string "ni fer en aquesta illa oblidada.\p"
	.string "Què et sembla si tornem a LLIRINESA?$"

EventTicket_Text_SailHome:
	.string "D'acord, doncs!\n"
	.string "Tornem a casa navegant!$"

EventTicket_Text_AsYouLike:
	.string "D'acord, com vulguis.$"

SouthernIsland_Interior_Text_Sign:
	.string "“Tots els somnis són una altra\n"
	.string "realitat. No ho oblidis mai…”$"

SouthernIsland_Exterior_Text_Sign:
	.string "“Aquells amb records esvaidits\n"
	.string "busquen gravar-los al cor…”$"
