EventTicket_Text_OldSeaMapTooFar:
	.string "Què passa, jovenet?\p"
	.string "Què, ets tu qui suposadament té\n"
	.string "un vell mapa estripat?\p"
	.string "A veure.\n"
	.string "… … … … … …\p"
	.string "Noi, això és bastant lluny.\n"
	.string "Em temo que no puc ajudar-te…$"

EventTicket_Text_BrineyHoldOnASecond:
	.string "BRINEY: Espera un moment!\p"
	.string "Què és això de rebutjar algú\n"
	.string "a qui dec tant?$"

EventTicket_Text_BrineyLetsSail:
	.string "{PLAYER}{KUN}, ho sento moltíssim.\p"
	.string "Has vingut a buscar la meva ajuda,\n"
	.string "i gairebé t'hem fet fora.\p"
	.string "Bé, deixa'm arreglar-ho.\p"
	.string "Navegarem ara mateix, és clar!\p"
	.string "Trobem aquesta illa al\n"
	.string "VELL MAPA MARÍ!$"

EventTicket_Text_OddTicketGetOnBoard:
	.string "Ets tu qui ha portat aquest\n"
	.string "bitllet estrany?\p"
	.string "On vols anar és una illa\n"
	.string "que és molt, molt lluny.\p"
	.string "Ningú sap què hi espera…\p"
	.string "Només de pensar-ho, se m'encén\n"
	.string "la sang de mariner!\p"
	.string "Puja a bord, jovenet!$"

FarawayIsland_Entrance_Text_SailorReturn:
	.string "El CAPITÀ BRINEY pot ser tan\n"
	.string "exasperadament capritxós…\p"
	.string "Vols tornar a LLIRINESA?$"

BirthIsland_Harbor_Text_SailorReturn:
	.string "Quina illa de forma estranya, eh?\n"
	.string "Vols tornar a LLIRINESA?$"

EventTicket_Text_OddTicketsWhereTo:
	.string "Ets tu qui ha portat aquests\n"
	.string "bitllets estranys?\p"
	.string "… … …Hm.\p"
	.string "Aquests bitllets et portaran a illes\n"
	.string "que són molt, molt lluny.\p"
	.string "Ningú sap què hi espera,\n"
	.string "ni què hi pot passar.\p"
	.string "Només de pensar-ho, se m'encén\n"
	.string "la sang de mariner!\p"
	.string "Puja a bord, jovenet!\n"
	.string "On navegarem primer?$"

NavelRock_Harbor_Text_SailorReturn:
	.string "Has… Has sentit això?\n"
	.string "Aquell grunyit greu de dins.\p"
	.string "Estàs segur que és segur?\n"
	.string "Creus que hauríem de marxar?$"

FarawayIsland_Entrance_Text_Sign:
	.string "L'escriptura s'esvaeix com si\n"
	.string "s'hagués escrit fa molt temps…\p"
	.string "“…bre, dia 6\n"
	.string "Si cap humà…posa el peu aquí…\l"
	.string "altra vegada…que sigui una pers…\l"
	.string "de bon cor…amb aquesta esperança, parteixo…”$"

FarawayIsland_Interior_Text_Mew:
	.string "Myuu…$"
