@ Battle Tower
gText_AnabelWonSilver::
	.string "L'AS DE LA TORRE, ANABEL, ha vençut\n"
	.string "el repte de l'aspirant {STR_VAR_1}!$"

gText_AnabelDefeatSilver::
	.string "L'AS DE LA TORRE, ANABEL, ha estat\n"
	.string "derrotada per l'aspirant {STR_VAR_1}!$"

gText_AnabelWonGold::
	.string "L'AS DE LA TORRE, ANABEL, ha destruït\n"
	.string "el somni del desafiant {STR_VAR_1}!$"

gText_AnabelDefeatGold::
	.string "El desafiant {STR_VAR_1} ha enderrocat\n"
	.string "l'AS DE LA TORRE, ANABEL!$"

@ Battle Dome
gText_TuckerWonSilver::
	.string "L'AS DE LA CÚPULA, TUCK, ha vençut\n"
	.string "el repte de l'aspirant {STR_VAR_1}!$"

gText_TuckerDefeatSilver::
	.string "L'AS DE LA CÚPULA, TUCK, ha estat\n"
	.string "derrotat per l'aspirant {STR_VAR_1}!$"

gText_TuckerWonGold::
	.string "L'AS DE LA CÚPULA, TUCK, ha destruït\n"
	.string "el somni del desafiant {STR_VAR_1}!$"

gText_TuckerDefeatGold::
	.string "El desafiant {STR_VAR_1} ha enderrocat\n"
	.string "l'AS DE LA CÚPULA, TUCK!$"

@ Battle Factory
gText_NolandWonSilver::
	.string "El CAP DE FÀBRICA, NOLAND, ha vençut\n"
	.string "el repte de l'aspirant {STR_VAR_1}!$"

gText_NolandDefeatSilver::
	.string "El CAP DE FÀBRICA, NOLAND, ha estat\n"
	.string "derrotat per l'aspirant {STR_VAR_1}!$"

gText_NolandWonGold::
	.string "El CAP DE FÀBRICA, NOLAND, ha destruït\n"
	.string "el somni del desafiant {STR_VAR_1}!$"

gText_NolandDefeatGold::
	.string "El desafiant {STR_VAR_1} ha enderrocat\n"
	.string "el CAP DE FÀBRICA, NOLAND!$"

@ Battle Pike
gText_LucyWonSilver::
	.string "La REINA DEL PIC, LUCY, ha vençut\n"
	.string "el repte de l'aspirant {STR_VAR_1}!$"

gText_LucyDefeatSilver::
	.string "La REINA DEL PIC, LUCY, ha estat\n"
	.string "derrotada per l'aspirant {STR_VAR_1}!$"

gText_LucyWonGold::
	.string "La REINA DEL PIC, LUCY, ha destruït\n"
	.string "el somni del desafiant {STR_VAR_1}!$"

gText_LucyDefeatGold::
	.string "El desafiant {STR_VAR_1} ha enderrocat\n"
	.string "la REINA DEL PIC, LUCY!$"

@ Battle Arena
gText_GretaWonSilver::
	.string "El MAGNAT DE L'ARENA, GRETA, ha vençut\n"
	.string "el repte de l'aspirant {STR_VAR_1}!$"

gText_GretaDefeatSilver::
	.string "El MAGNAT DE L'ARENA, GRETA, ha estat\n"
	.string "derrotada per l'aspirant {STR_VAR_1}!$"

gText_GretaWonGold::
	.string "El MAGNAT DE L'ARENA, GRETA, ha\n"
	.string "destruït el somni del desafiant\l"
	.string "{STR_VAR_1}!$"

gText_GretaDefeatGold::
	.string "El desafiant {STR_VAR_1} ha enderrocat\n"
	.string "el MAGNAT DE L'ARENA, GRETA!$"

@ Battle Palace
gText_SpenserWonSilver::
	.string "El SENYOR DEL PALAU, SPENSER, ha vençut\n"
	.string "el repte de l'aspirant {STR_VAR_1}!$"

gText_SpenserDefeatSilver::
	.string "El SENYOR DEL PALAU, SPENSER, ha estat\n"
	.string "derrotat per l'aspirant {STR_VAR_1}!$"

gText_SpenserWonGold::
	.string "El SENYOR DEL PALAU, SPENSER, ha\n"
	.string "destruït el somni del desafiant\l"
	.string "{STR_VAR_1}!$"

gText_SpenserDefeatGold::
	.string "El desafiant {STR_VAR_1} ha enderrocat\n"
	.string "el SENYOR DEL PALAU, SPENSER!$"

@ Battle Pyramid
gText_BrandonWonSilver::
	.string "El REI DE LA PIRÀMIDE, BRANDON, ha\n"
	.string "vençut el repte de l'aspirant\l"
	.string "{STR_VAR_1}!$"

gText_BrandonDefeatSilver::
	.string "El REI DE LA PIRÀMIDE, BRANDON, ha\n"
	.string "estat derrotat per l'aspirant\l"
	.string "{STR_VAR_1}!$"

gText_BrandonWonGold::
	.string "El REI DE LA PIRÀMIDE, BRANDON, ha\n"
	.string "destruït el somni del desafiant\l"
	.string "{STR_VAR_1}!$"

gText_BrandonDefeatGold::
	.string "El desafiant {STR_VAR_1} ha enderrocat\n"
	.string "el REI DE LA PIRÀMIDE, BRANDON!$"
