LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket:
	.string "Benvingut al RACÓ DE LA LOTERIA!\p"
	.string "T'agradaria treure un bitllet\n"
	.string "de la loteria avui?$"

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow:
	.string "Em sap greu.\p"
	.string "Sembla que ja has tret un bitllet.\p"
	.string "Si us plau, torna demà.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain:
	.string "Si us plau, torna a visitar-nos!$"

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket:
	.string "Si us plau, treu un bitllet.$"

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait:
	.string "El número del teu bitllet és\n"
	.string "{STR_VAR_1}.\p"
	.string "Si us plau, espera un moment.\p"
	.string "Comprovarem els números d'ID\n"
	.string "dels POKéMON que portes i que\l"
	.string "tens emmagatzemats.$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon:
	.string "Coincideix amb el número d'ID de\n"
	.string "{STR_VAR_2}, que tens al teu equip!$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon:
	.string "Coincideix amb el número d'ID de\n"
	.string "{STR_VAR_2}, que tens al PC!$"

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched:
	.string "Ho sento, però el teu número\n"
	.string "no coincideix amb cap.\p"
	.string "Si us plau, torna demà!$"

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched:
	.string "Felicitats!\p"
	.string "Els dos últims dígits del teu número\n"
	.string "coincideixen!\p"
	.string "Guanyes el tercer premi, un\n"
	.string "{STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched:
	.string "Felicitats!\p"
	.string "Els tres últims dígits del teu número\n"
	.string "coincideixen!\p"
	.string "Guanyes el segon premi, un\n"
	.string "{STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched:
	.string "Ei! Felicitats!\p"
	.string "Els quatre últims dígits del teu\n"
	.string "número coincideixen!\p"
	.string "Guanyes el primer premi, un\n"
	.string "{STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched:
	.string "Uau! Felicitats!\p"
	.string "Els cinc dígits del teu número\n"
	.string "coincideixen perfectament!\p"
	.string "Guanyes el gran premi, un\n"
	.string "{STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis:
	.string "Oh?\p"
	.string "No tens espai a la MOTXILLA\n"
	.string "per a això.\p"
	.string "Si us plau, torna després de fer\n"
	.string "espai.$"

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding:
	.string "Aquí tens el premi que\n"
	.string "guardàvem per a tu!$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2:
	.string "Si us plau, torna a visitar-nos!$"
