@ Only contains the text for the Mauville Man named Giddy. The rest is in scripts/mauville_man.inc
GiddyText_SoPretty::
	.string " tan bonic!$"

GiddyText_SoDarling::
	.string " tan encantador!$"

GiddyText_SoRelaxed::
	.string " tan relaxat!$"

GiddyText_SoSunny::
	.string " tan assolellat!$"

GiddyText_SoDesirable::
	.string " tan desitjable!$"

GiddyText_SoExciting::
	.string " tan emocionant!$"

GiddyText_SoAmusing::
	.string " tan divertit!$"

GiddyText_SoMagical::
	.string " tan màgic!$"

GiddyText_Is::
	.string " és$"

GiddyText_DontYouAgree::
	.string "\n"
	.string "No hi estàs d'acord?$"

GiddyText_ISoWantToGoOnAVacation::
	.string "Tinc tantes ganes d'anar de vacances.\n"
	.string "Coneixes algun lloc bonic?$"

GiddyText_IBoughtCrayonsWith120Colors::
	.string "He comprat ceres de 120 colors!\n"
	.string "No trobes que és genial?$"

GiddyText_WouldntItBeNiceIfWeCouldFloat::
	.string "No seria bonic si poguéssim flotar\n"
	.string "en un núvol de bombolles?$"

GiddyText_WhenYouWriteOnASandyBeach::
	.string "Quan escrius a la sorra de la platja,\n"
	.string "les onades ho esborren. Em fa tristesa.$"

GiddyText_WhatsTheBottomOfTheSeaLike::
	.string "Com deu ser el fons del mar?\n"
	.string "M'encantaria anar-hi almenys un cop!$"

GiddyText_WhenYouSeeTheSettingSunDoesIt::
	.string "Quan veus el sol ponent, no et\n"
	.string "fan ganes de tornar a casa?$"

GiddyText_LyingBackInTheGreenGrass::
	.string "Estirar-se a l'herba verda…\n"
	.string "Oh, és tan, tan bonic!$"

GiddyText_SecretBasesAreSoWonderful::
	.string "Les BASES SECRETES són meravelloses!\n"
	.string "No notes l'emoció?$"
