MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "Aquest moviment només\n"
	.string "es pot aprendre un cop.$"

MoveTutor_Text_SwaggerTeach:
	.string "Vols que ensenyi\n"
	.string "FANFARRONEJAR?$"

MoveTutor_Text_SwaggerDeclined:
	.string "D'acord, torna quan\n"
	.string "vulguis!$"

MoveTutor_Text_SwaggerWhichMon:
	.string "A quin POKéMON vols\n"
	.string "ensenyar FANFARRONEJAR?$"

MoveTutor_Text_SwaggerTaught:
	.string "Li he ensenyat\n"
	.string "FANFARRONEJAR!$"

MoveTutor_Text_RolloutTeach:
	.string "Vols que ensenyi\n"
	.string "RODAVOLTA?$"

MoveTutor_Text_RolloutDeclined:
	.string "D'acord, torna quan\n"
	.string "vulguis!$"

MoveTutor_Text_RolloutWhichMon:
	.string "A quin POKéMON vols\n"
	.string "ensenyar RODAVOLTA?$"

MoveTutor_Text_RolloutTaught:
	.string "Li he ensenyat\n"
	.string "RODAVOLTA!$"

MoveTutor_Text_FuryCutterTeach:
	.string "Vols que ensenyi\n"
	.string "TALL FURIÓS?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "D'acord, torna quan\n"
	.string "vulguis!$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "A quin POKéMON vols\n"
	.string "ensenyar TALL FURIÓS?$"

MoveTutor_Text_FuryCutterTaught:
	.string "Li he ensenyat\n"
	.string "TALL FURIÓS!$"

MoveTutor_MimicTeach:
	.string "Vols que ensenyi\n"
	.string "MIMÈTIC?$"

MoveTutor_MimicDeclined:
	.string "D'acord, torna quan\n"
	.string "vulguis!$"

MoveTutor_Text_MimicWhichMon:
	.string "A quin POKéMON vols\n"
	.string "ensenyar MIMÈTIC?$"

MoveTutor_Text_MimicTaught:
	.string "Li he ensenyat\n"
	.string "MIMÈTIC!$"

MoveTutor_Text_MetronomeTeach:
	.string "Vols que ensenyi\n"
	.string "METRÒNOM?$"

MoveTutor_Text_MetronomeDeclined:
	.string "D'acord, torna quan\n"
	.string "vulguis!$"

MoveTutor_Text_MetronomeWhichMon:
	.string "A quin POKéMON vols\n"
	.string "ensenyar METRÒNOM?$"

MoveTutor_Text_MetronomeTaught:
	.string "Li he ensenyat\n"
	.string "METRÒNOM!$"

MoveTutor_Text_SleepTalkTeach:
	.string "Vols que ensenyi\n"
	.string "PARLAR DORMINT?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "D'acord, torna quan\n"
	.string "vulguis!$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "A quin POKéMON vols\n"
	.string "ensenyar PARLAR DORMINT?$"

MoveTutor_Text_SleepTalkTaught:
	.string "Li he ensenyat\n"
	.string "PARLAR DORMINT!$"

MoveTutor_Text_SubstituteTeach:
	.string "Vols que ensenyi\n"
	.string "SUBSTITUT?$"

MoveTutor_Text_SubstituteDeclined:
	.string "D'acord, torna quan\n"
	.string "vulguis!$"

MoveTutor_Text_SubstituteWhichMon:
	.string "A quin POKéMON vols\n"
	.string "ensenyar SUBSTITUT?$"

MoveTutor_Text_SubstituteTaught:
	.string "Li he ensenyat\n"
	.string "SUBSTITUT!$"

MoveTutor_Text_DynamicPunchTeach:
	.string "Vols que ensenyi\n"
	.string "PUNY DINÀMIC?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "D'acord, torna quan\n"
	.string "vulguis!$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "A quin POKéMON vols\n"
	.string "ensenyar PUNY DINÀMIC?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "Li he ensenyat\n"
	.string "PUNY DINÀMIC!$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "Vols que ensenyi\n"
	.string "DOBLE FIL?$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "D'acord, torna quan\n"
	.string "vulguis!$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "A quin POKéMON vols\n"
	.string "ensenyar DOBLE FIL?$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "Li he ensenyat\n"
	.string "DOBLE FIL!$"

MoveTutor_Text_ExplosionTeach:
	.string "Vols que ensenyi\n"
	.string "EXPLOSIÓ?$"

MoveTutor_Text_ExplosionDeclined:
	.string "D'acord, torna quan\n"
	.string "vulguis!$"

MoveTutor_Text_ExplosionWhichMon:
	.string "A quin POKéMON vols\n"
	.string "ensenyar EXPLOSIÓ?$"

MoveTutor_Text_ExplosionTaught:
	.string "Li he ensenyat\n"
	.string "EXPLOSIÓ!$"
