gText_ObtainedTheItem::
	.string "Has obtingut\n"
	.string "{STR_VAR_1}!$"

gText_TheBagIsFull::
	.string "La MOTXILLA està plena.$"

gText_PutItemInPocket::
	.string "Has desat {STR_VAR_1}\n"
	.string "a la bossa {STR_VAR_2}.$"

gText_PlayerFoundOneItem::
	.string "{PLAYER} ha trobat un/a\n"
	.string "{STR_VAR_1}!$"

gText_TooBadBagIsFull::
	.string "Llàstima!\n"
	.string "La MOTXILLA està plena.$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} ha desat {STR_VAR_1}\n"
	.string "a la MOTXILLA.$"

gText_ObtainedTheDecor::
	.string "Has obtingut {STR_VAR_1}!$"

gText_NoRoomLeftForAnother::
	.string "No queda espai per a\n"
	.string "més decoració.$"

gText_TheDecorWasTransferredToThePC::
	.string "La decoració s'ha\n"
	.string "transferit al PC.$"
