Text_BootUpPC:
	.string "{PLAYER} ha encès el PC.$"

gText_WhichPCShouldBeAccessed::
	.string "A quin PC vols accedir?$"

gText_AccessedSomeonesPC::
	.string "Has accedit al PC\n"
	.string "d'algú.$"

gText_StorageSystemOpened::
	.string "S'ha obert el sistema\n"
	.string "d'emmagatzematge.$"

gText_AccessedPlayersPC::
	.string "Has accedit al PC de\n"
	.string "{PLAYER}.$"

gText_AccessedLanettesPC::
	.string "Has accedit al PC de\n"
	.string "la LANETTE.$"
