gText_PkmnTransferredSomeonesPC::
	.string "{STR_VAR_2} ha estat transferit al\n"
	.string "PC D'ALGÚ.\p"
	.string "S'ha col·locat a la\n"
	.string "CAIXA “{STR_VAR_1}”.$"

gText_PkmnTransferredLanettesPC::
	.string "{STR_VAR_2} ha estat transferit al\n"
	.string "PC DE LANETTE.\p"
	.string "S'ha col·locat a la\n"
	.string "CAIXA “{STR_VAR_1}”.$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "La CAIXA “{STR_VAR_3}” del\n"
	.string "PC D'ALGÚ estava plena.\p"
	.string "{STR_VAR_2} ha estat transferit a\n"
	.string "la CAIXA “{STR_VAR_1}”.$"

gText_PkmnTransferredLanettesPCBoxFull::
	.string "La CAIXA “{STR_VAR_3}” del\n"
	.string "PC DE LANETTE estava plena.\p"
	.string "{STR_VAR_2} ha estat transferit a\n"
	.string "la CAIXA “{STR_VAR_1}”.$"

gText_NoMoreRoomForPokemon::
	.string "No hi ha més espai per a POKéMON!\p"
	.string "Les CAIXES de POKéMON estan plenes\n"
	.string "i no en poden acceptar més!$"

gText_NicknameThisPokemon::
	.string "Vols posar un malnom a\n"
	.string "aquest {STR_VAR_1}?$"
