gText_WouldYouLikeToRestYourPkmn::
	.string "Vols que curem els\n"
	.string "teus POKéMON?$"

gText_IllTakeYourPkmn::
	.string "D'acord, deixa'm els\n"
	.string "teus POKéMON.$"

gText_RestoredPkmnToFullHealth::
	.string "Els teus POKéMON estan\n"
	.string "completament curats!$"

gText_WeHopeToSeeYouAgain::
	.string "Esperem tornar a veure't!$"

gText_WelcomeCutShort::
	.string "Benvingut al CENTRE\n"
	.string "POKéMON.$"

gText_NoticesGoldCard::
	.string "Oh? Aquesta targeta és…$"

gText_YouWantTheUsual::
	.string "Vols el de sempre?\n"
	.string "Tractament complet per\n"
	.string "als teus POKéMON?$"

gText_IllTakeYourPkmn2::
	.string "D'acord, deixa'm els\n"
	.string "teus POKéMON.$"

gText_ThankYouForWaiting::
	.string "Gràcies per esperar!$"

gText_WeHopeToSeeYouAgain2::
	.string "Esperem tornar a veure't!$"
