Questionnaire_Text_FillOut::
	.string "Hi ha un qüestionari.\n"
	.string "Vols omplir-lo?$"

Questionnaire_Text_ThankYou::
	.string "Gràcies per dedicar temps a\n"
	.string "omplir el nostre qüestionari.\p"
	.string "Els teus comentaris s'usaran\n"
	.string "com a referència futura.$"

Questionnaire_Text_YouKnowThoseWordsGift::
	.string "Oh, hola!\n"
	.string "Coneixes aquestes paraules?\p"
	.string "Això vol dir que deus saber sobre\n"
	.string "el REGAL MISTERI.\p"
	.string "A partir d'ara, hauries de\n"
	.string "rebre REGALS MISTERI!$"

Questionnaire_Text_YouCanAccessMysteryGift::
	.string "Un cop desis la partida, pots\n"
	.string "accedir al REGAL MISTERI.$"

Questionnaire_Text_YouKnowThoseWordsEvent::
	.string "Oh, hola!\n"
	.string "Coneixes aquestes paraules?\p"
	.string "Això vol dir que deus saber sobre\n"
	.string "l'ESDEVENIMENT MISTERI.$"

Questionnaire_Text_YouCanAccessMysteryEvent::
	.string "Un cop desis la partida, pots\n"
	.string "accedir a l'ESDEVENIMENT MISTERI.$"

MysteryGift_Text_TheresATicketForYou::
	.string "Gràcies per usar el Sistema\n"
	.string "d'ESDEVENIMENT MISTERI.\p"
	.string "Tu deus ser {PLAYER}.\n"
	.string "Hi ha un tiquet aquí per a tu.$"

MysteryGift_Text_TryUsingItAtLilycovePort::
	.string "Sembla que és per usar al\n"
	.string "port de CALAGUA.\p"
	.string "Per què no ho proves i veus\n"
	.string "de què es tracta?$"
