	.align 2
gText_ConfirmSave::
	.string "Vols desar la partida?$"

gText_AlreadySavedFile::
	.string "Ja hi ha una partida\n"
	.string "desada. D'acord\l"
	.string "sobreescriure-la?$"

gText_SavingDontTurnOff::
	.string "Desant…\n"
	.string "No apaguis la consola.$"

gText_PlayerSavedGame::
	.string "{PLAYER} ha desat\n"
	.string "la partida.$"

gText_DifferentSaveFile::
	.string "La partida desada és\n"
	.string "diferent. D'acord\l"
	.string "sobreescriure-la?$"

gText_SaveError::
	.string "Error en desar.\n"
	.string "Si us plau, apaga i\l"
	.string "encén la consola.$"

gText_SavingDontTurnOffPower::
	.string "Desant…\n"
	.string "No apaguis la consola.$"
