ShoalCave_LowTideEntranceRoom_Text_AreYouPlanningOnGoingInThere:
	.string "Tens pensat entrar-hi?\n"
	.string "Hi ha SAL MARESMA i\l"
	.string "CLOSQUES MARESMA a dins.$"

ShoalCave_LowTideEntranceRoom_Text_BringMe4ShoalSaltAndShells:
	.string "Si em portes 4 SALS MARESMA\n"
	.string "i 4 CLOSQUES MARESMA, et\l"
	.string "faré quelcom especial!$"

ShoalCave_LowTideEntranceRoom_Text_WouldYouLikeShellBell:
	.string "Oh! Tens 4 de cada!\n"
	.string "Vols que et faci una\l"
	.string "CAMPANA CLOSCA?$"

ShoalCave_LowTideEntranceRoom_Text_MakeShellBellRightAway:
	.string "D'acord! La faré ara\n"
	.string "mateix!$"

ShoalCave_LowTideEntranceRoom_Text_ExplainShellBell:
	.string "La CAMPANA CLOSCA cura\n"
	.string "una mica el POKéMON que\l"
	.string "la porta quan ataca.$"

ShoalCave_LowTideEntranceRoom_Text_WantedToMakeShellBell:
	.string "Volia fer-te una CAMPANA\n"
	.string "CLOSCA...\l"
	.string "Torna quan tinguis 4 de cada!$"

ShoalCave_LowTideEntranceRoom_Text_NoSpaceInYourBag:
	.string "No tens espai a la\n"
	.string "MOTXILLA!$"

ShoalCave_Text_WasShoalSaltNowNothing:
	.string "Abans hi havia SAL MARESMA\n"
	.string "aquí, però ara no hi ha res.$"

ShoalCave_Text_WasShoallShellNowNothing:
	.string "Abans hi havia una CLOSCA\n"
	.string "MARESMA aquí, però ara\n"
	.string "no hi ha res.$"
