Route102_Text_CalvinIntro:
	.string "Si tens POKéMON amb tu, ets un\n"
	.string "ENTRENADOR POKéMON oficial!\l"
	.string "No pots dir que no al meu desafiament!$"

Route102_Text_CalvinDefeated:
	.string "Argh, he perdut…\n"
	.string "Hauria d'haver entrenat més els meus…$"

Route102_Text_CalvinPostBattle:
	.string "Escolta. Si ets fort, m'ho hauries\n"
	.string "d'haver dit abans!$"

Route102_Text_CalvinRegister:
	.string "He estat treballant dur des que\n"
	.string "et vaig veure.\p"
	.string "M'agradaria tornar a lluitar, pots\n"
	.string "registrar-me al teu POKéNAV?$"

Route102_Text_CalvinRegisterShort:
	.string "M'agradaria tornar a lluitar, pots\n"
	.string "registrar-me al teu POKéNAV?$"

Route102_Text_CalvinRematchIntro:
	.string "Des que vaig perdre contra tu, he\n"
	.string "entrenat desesperadament els meus POKéMON.\l"
	.string "No pots dir que no al meu desafiament!$"

Route102_Text_CalvinRematchDefeated:
	.string "Argh, he perdut…\n"
	.string "El meu mètode d'entrenament no és correcte?$"

Route102_Text_CalvinRematchPostBattle:
	.string "Si et fas més fort,\n"
	.string "jo també em faré més fort.$"

Route102_Text_AllenIntro:
	.string "Acabes de fer-te ENTRENADOR?\n"
	.string "Som tots dos principiants!$"

Route102_Text_AllenDefeated:
	.string "T'he cridat perquè pensava\n"
	.string "que et podia guanyar…$"

Route102_Text_AllenPostBattle:
	.string "Encara no he guanyat ni un cop…\n"
	.string "M'agradaria guanyar aviat…$"

Route102_Text_RickIntro:
	.string "Haha! Les mirades s'han creuat!\n"
	.string "Lluitaré amb els meus POKéMON BICHO!$"

Route102_Text_RickDefeated:
	.string "Au! Fora de combat!$"

Route102_Text_RickPostBattle:
	.string "Si creues la mirada amb un ENTRENADOR,\n"
	.string "l'has de desafiar! És una regla!$"

Route102_Text_TianaIntro:
	.string "Seguiré guanyant i aspiraré a ser\n"
	.string "el millor ENTRENADOR.\p"
	.string "Ajuda'm a avançar la meva carrera!$"

Route102_Text_TianaDefeated:
	.string "He acabat avançant la teva carrera…$"

Route102_Text_TianaPostBattle:
	.string "Per seguir guanyant, veig que\n"
	.string "he d'atrapar més POKéMON.$"

Route103_Text_DaisyIntro:
	.string "Has sentit l'atracció de la nostra\n"
	.string "fragància que calma l'ànima?$"

Route103_Text_DaisyDefeated:
	.string "No t'has deixat portar pel nostre aroma…$"

Route103_Text_DaisyPostBattle:
	.string "L'aromateràpia és una forma de curació\n"
	.string "mental que funciona amb fragàncies.$"

Route103_Text_AmyIntro:
	.string "AMY: Sóc l'AMY.\n"
	.string "I aquesta és la meva germaneta LIV.\l"
	.string "Lluitem juntes!$"

Route103_Text_AmyDefeated:
	.string "AMY: Oh no, hem perdut.$"

Route103_Text_AmyPostBattle:
	.string "AMY: Has de pensar en moltes coses\n"
	.string "quan lluites contra dos ENTRENADORS.$"

Route103_Text_AmyNotEnoughPokemon:
	.string "AMY: Oh no, només tens un POKéMON\n"
	.string "amb tu.\l"
	.string "No pots lluitar contra nosaltres així.$"

Route103_Text_LivIntro:
	.string "LIV: Lluitem juntes com un\n"
	.string "equip.$"

Route103_Text_LivDefeated:
	.string "LIV: Oh, hem perdut, germaneta…$"

Route103_Text_LivPostBattle:
	.string "LIV: Treballem perfectament juntes,\n"
	.string "jo i la meva germana gran…\p"
	.string "Però hem perdut igualment…$"

Route103_Text_AmyLivRegister:
	.string "LIV: De veritat, som molt millors…\n"
	.string "És veritat! T'ho demostrarem el pròxim cop!$"

Route103_Text_LivNotEnoughPokemon:
	.string "LIV: Si vols lluitar contra nosaltres,\n"
	.string "has de tenir dos POKéMON!\l"
	.string "No és just si no en tens!$"

Route103_Text_AmyRematchIntro:
	.string "AMY: Sóc l'AMY.\n"
	.string "I aquesta és la meva germaneta LIV.\l"
	.string "Lluitem juntes!$"

Route103_Text_AmyRematchDefeated:
	.string "AMY: Oh, no!\n"
	.string "No hem pogut guanyar altra vegada…$"

Route103_Text_AmyRematchPostBattle:
	.string "AMY: Has de pensar en moltes coses\n"
	.string "quan lluites contra dos ENTRENADORS.$"

Route103_Text_AmyRematchNotEnoughPokemon:
	.string "AMY: Oh no, només tens un POKéMON\n"
	.string "amb tu.\l"
	.string "No pots lluitar contra nosaltres així.$"

Route103_Text_LivRematchIntro:
	.string "LIV: Lluitem juntes com un\n"
	.string "equip.$"

Route103_Text_LivRematchDefeated:
	.string "LIV: Ohh, hem perdut altra vegada…\n"
	.string "Germaneta…$"

Route103_Text_LivRematchPostBattle:
	.string "LIV: Treballem perfectament juntes,\n"
	.string "jo i la meva germana gran…\p"
	.string "Però per què hem perdut altra vegada?$"

Route103_Text_LivRematchNotEnoughPokemon:
	.string "LIV: Si vols lluitar contra nosaltres,\n"
	.string "has de tenir dos POKéMON!\l"
	.string "No és just si no en tens!$"

Route103_Text_AndrewIntro:
	.string "Gah! El meu fil de pesca s'ha embolicat!\n"
	.string "M'estic frustrant i enfadant!\l"
	.string "Ja n'hi ha prou! Lluita contra mi!$"

Route103_Text_AndrewDefeated:
	.string "Gah! He perdut!\n"
	.string "Ara estic encara més molest!$"

Route103_Text_AndrewPostBattle:
	.string "Gah, encara estic furiós…\n"
	.string "Grrrrr…$"

Route103_Text_MiguelIntro:
	.string "El meu POKéMON és deliciosament adorable!\n"
	.string "No siguis tímid, t'ho mostraré!$"

Route103_Text_MiguelDefeated:
	.string "Oh, Déu meu!\n"
	.string "El meu estimat POKéMON!$"

Route103_Text_MiguelPostBattle:
	.string "El meu POKéMON és adorable\n"
	.string "fins i tot quan està esvaït!$"

Route103_Text_MiguelRegister:
	.string "Et faré venir a veure el meu\n"
	.string "deliciós POKéMON una altra vegada!$"

Route103_Text_MiguelRematchIntro:
	.string "Ei, tu! El meu adorable POKéMON\n"
	.string "s'ha tornat encara més bonic!$"

Route103_Text_MiguelRematchDefeated:
	.string "Oh!\n"
	.string "El meu estimat POKéMON!$"

Route103_Text_MiguelRematchPostBattle:
	.string "Com més temps passo amb ell,\n"
	.string "més adorable es torna el meu POKéMON.$"

Route103_Text_PeteIntro:
	.string "Aquesta distància…\n"
	.string "Hauries de nedar-la!$"

Route103_Text_PeteDefeated:
	.string "Oh, molt ben fet!$"

Route103_Text_PetePostBattle:
	.string "Oh, ara entenc el que vols dir.\p"
	.string "Si tingués un POKéMON tan de confiança,\n"
	.string "també voldria fer SURF amb ell!$"

Route103_Text_IsabelleIntro:
	.string "Mira per on vas!\n"
	.string "Xocarem!$"

Route103_Text_IsabelleDefeated:
	.string "Ai…$"

Route103_Text_IsabellePostBattle:
	.string "Sóc mala nedadora i estava practicant…\n"
	.string "Perdona per gairebé xocar amb tu.$"

Route103_Text_RhettIntro:
	.string "Uau!\n"
	.string "Com has entrat en un espai tan petit?$"

Route103_Text_RhettDefeated:
	.string "Uau!\n"
	.string "El nen sap lluitar!$"

Route103_Text_RhettPostBattle:
	.string "T'agraden els espais estrets\n"
	.string "com aquest?$"

Route103_Text_MarcosIntro:
	.string "T'ha atret el so planyívol de la\n"
	.string "meva guitarra?$"

Route103_Text_MarcosDefeated:
	.string "El meu espectacle en solitari\n"
	.string "està arruïnat…$"

Route103_Text_MarcosPostBattle:
	.string "Estava tocant la guitarra on hi havia\n"
	.string "poca gent, però s'han reunit molts fans.\p"
	.string "Heh, potser m'hauria de fer professional.$"

Route104_Text_GinaIntro:
	.string "GINA: D'acord, lluitem amb els nostres\n"
	.string "POKéMON!$"

Route104_Text_GinaDefeat:
	.string "GINA: Perdre em molesta!$"

Route104_Text_GinaPostBattle:
	.string "GINA: Ets fort!\n"
	.string "Hem d'entrenar molt més!$"

Route104_Text_GinaNotEnoughMons:
	.string "GINA: Oh? Només un POKéMON?\n"
	.string "Doncs no lluitem amb tu.\p"
	.string "Si només hi ha un POKéMON, estarà\n"
	.string "sol. Això no és bonic.$"

Route104_Text_MiaIntro:
	.string "MIA: Som bessones, així que lluitem\n"
	.string "amb POKéMON juntes.$"

Route104_Text_MiaDefeat:
	.string "MIA: Hem lluitat juntes, però hem\n"
	.string "perdut les dues…$"

Route104_Text_MiaPostBattle:
	.string "MIA: Entrenarem més els nostres POKéMON\n"
	.string "i serem fortes com tu.$"

Route104_Text_MiaNotEnoughMons:
	.string "MIA: Vols lluitar amb nosaltres?\p"
	.string "No pot ser si no tens dos POKéMON\n"
	.string "amb tu.\l"
	.string "Som massa fortes per a tu!$"

Route104_Text_IvanIntro:
	.string "Per què mantenir-ho en secret?\n"
	.string "Sóc l'expert en POKéMON d'AIGUA!\p"
	.string "Eh?\n"
	.string "No em coneixes?$"

Route104_Text_IvanDefeat:
	.string "Pensava que no era tan dolent, si puc\n"
	.string "dir-ho, però sembla que no… Bleah…$"

Route104_Text_IvanPostBattle:
	.string "M'he concentrat massa en la pesca.\n"
	.string "He oblidat que havia d'entrenar els meus POKéMON…$"

Route104_Text_BillyIntro:
	.string "Deixar petjades a la sorra és\n"
	.string "tan divertit!$"

Route104_Text_BillyDefeat:
	.string "Waah! M'ha entrat sorra a les sabatilles!\n"
	.string "Estàn plenes de granets!$"

Route104_Text_BillyPostBattle:
	.string "Vull deixar les meves petjades a la\n"
	.string "sorra arreu, però desapareixen\n"
	.string "ràpidament…$"

Route104_Text_HaleyIntro:
	.string "Hauria de…\n"
	.string "O no?\p"
	.string "D'acord, sí, lluitaré!$"

Route104_Text_HaleyDefeat:
	.string "No hauria d'haver lluitat…$"

Route104_Text_HaleyPostBattle:
	.string "Si t'enfrontes a una decisió i deixes\n"
	.string "que algú altre triï per tu, te'n\n"
	.string "penediràs, passi el que passi.$"

Route104_Text_HaleyRegister1:
	.string "Ets fort, però t'hauria de registrar\n"
	.string "al meu POKéNAV?\l"
	.string "Potser no hauria…\p"
	.string "D'acord, sí, et registraré!$"

Route104_Text_HaleyRegister2:
	.string "Ets fort, però t'hauria de registrar\n"
	.string "al meu POKéNAV?\l"
	.string "Potser no hauria…\p"
	.string "D'acord, sí, et registraré!$"

Route104_Text_HaleyRematchIntro:
	.string "Vinga, lluita amb mi!$"

Route104_Text_HaleyRematchDefeat:
	.string "Ohh…\n"
	.string "Pensava que podria guanyar…$"

Route104_Text_HaleyPostRematch:
	.string "Vaig decidir lluitar, així que puc\n"
	.string "acceptar aquesta derrota amb gràcia.\p"
	.string "Tot i així em molesta haver perdut!$"

Route104_Text_WinstonIntro:
	.string "Oh, és clar, acceptaré el teu desafiament.\n"
	.string "Tinc molts diners.$"

Route104_Text_WinstonDefeat:
	.string "Per què no he pogut guanyar?$"

Route104_Text_WinstonPostBattle:
	.string "Hi ha coses que els diners no poden comprar.\n"
	.string "Això és POKéMON…$"

Route104_Text_WinstonRegister1:
	.string "Hm?\n"
	.string "Ah, has obtingut un POKéNAV.\p"
	.string "Et registraré amb gust.\n"
	.string "Després de tot, tinc molts diners.$"

Route104_Text_WinstonRegister2:
	.string "Hm?\n"
	.string "Ah, has obtingut un POKéNAV.\p"
	.string "Et registraré amb gust.\n"
	.string "Després de tot, tinc molts diners.$"

Route104_Text_WinstonRematchIntro:
	.string "Després de perdre contra tu, he après\n"
	.string "moltes coses sobre POKéMON.$"

Route104_Text_WinstonRematchDefeat:
	.string "He perdut altra vegada?\n"
	.string "Per què no he pogut guanyar?$"

Route104_Text_WinstonPostRematch:
	.string "Sóc fabulosament ric, però no puc\n"
	.string "guanyar a POKéMON…\p"
	.string "És tan profund, el món dels POKéMON…$"

Route104_Text_CindyIntro:
	.string "Devíem estar destinats a trobar-nos.\n"
	.string "Puc demanar-te un combat?$"

Route104_Text_CindyDefeat:
	.string "Oh, mare meva!$"

Route104_Text_CindyPostBattle:
	.string "“Hola” és el principi de “adéu”.\n"
	.string "Espero que ens tornem a veure.$"

Route104_Text_CindyRegister1:
	.string "Hola, ens tornem a trobar.\p"
	.string "Sembla que ens atreiem. Registrem-nos\n"
	.string "mútuament als nostres POKéNAVS.$"

Route104_Text_CindyRegister2:
	.string "Hauríem de commemorar com semblem\n"
	.string "atreire'ns mútuament.\p"
	.string "Registrem-nos als nostres POKéNAVS.$"

Route104_Text_CindyRematchIntro:
	.string "Hola, ens tornem a trobar.\n"
	.string "Puc demanar-te un combat?$"

Route104_Text_CindyRematchDefeat:
	.string "Oh, mare meva…\n"
	.string "He fet el millor que he pogut…$"

Route104_Text_CindyPostRematch:
	.string "“Hola” és el principi de “adéu”.\n"
	.string "Espero que ens tornem a veure.$"

Route104_Text_DarianIntro:
	.string "He pescat un POKéMON d'aspecte dur!\p"
	.string "Té una qualitat màgica!\n"
	.string "Segur que sembla dur, sí senyor!$"

Route104_Text_DarianDefeat:
	.string "Però què…$"

Route104_Text_DarianPostBattle:
	.string "Ei, MAGIKARP, segur que no fas honor\n"
	.string "al teu nom, oi?$"

Route105_Text_FosterIntro:
	.string "Se suposa que hi ha una roca mística\n"
	.string "per aquí.\l"
	.string "En saps alguna cosa?$"

Route105_Text_FosterDefeated:
	.string "Pensava massa en aquella roca, mentre\n"
	.string "els meus POKéMON seguien febles…$"

Route105_Text_FosterPostBattle:
	.string "Puc passar hores i hores mirant\n"
	.string "una bona roca sense avorrir-me.$"

Route105_Text_LuisIntro:
	.string "Uf! M'he preocupat que un nen s'estava\n"
	.string "ofegant quan t'he vist.\p"
	.string "Sembla que estàs bé, què et sembla\n"
	.string "un combat?$"

Route105_Text_LuisDefeated:
	.string "Glub… Glub…$"

Route105_Text_LuisPostBattle:
	.string "Si t'estàs ofegant, la senyal és\n"
	.string "agitar un braç cap a la platja.$"

Route105_Text_DominikIntro:
	.string "Nedar al mar blau profund…\n"
	.string "És la millor sensació!$"

Route105_Text_DominikDefeated:
	.string "He perdut…\n"
	.string "Ara em sento trist…$"

Route105_Text_DominikPostBattle:
	.string "Per què el mar és blau?\p"
	.string "Ho vaig aprendre al MUSEU de\n"
	.string "SLATEPORT, però ho he oblidat.$"

Route105_Text_BeverlyIntro:
	.string "El meu cos se sent més lleuger a l'aigua.\n"
	.string "És com si hagués aprimat!$"

Route105_Text_BeverlyDefeated:
	.string "Estic flotant…$"

Route105_Text_PostBattle:
	.string "El pes del cos es redueix a només\n"
	.string "una desena part a l'aigua.\p"
	.string "Això em faria pesar…\n"
	.string "Ui! No et diré el meu pes!$"

Route105_Text_ImaniIntro:
	.string "El cel blau, blau…\n"
	.string "El mar immens…\l"
	.string "És tan tranquil…$"

Route105_Text_ImaniDefeated:
	.string "He perdut mentre m'estava relaxant!$"

Route105_Text_ImaniPostBattle:
	.string "Vull que em diguin que sóc relaxant\n"
	.string "per estar a prop. Riure.$"

Route105_Text_AndresIntro:
	.string "Estic convençut que el mar ens amaga\n"
	.string "secrets.$"

Route105_Text_AndresDefeated:
	.string "Sí…\n"
	.string "No sóc bo lluitant…$"

Route105_Text_AndresPostBattle:
	.string "Estic segur que hi ha molts secrets\n"
	.string "per descobrir als mars del món.\p"
	.string "Penso trobar-los tots!$"

Route105_Text_AndresRegister:
	.string "Eh? Sóc tan feble, però vols\n"
	.string "registrar-me al teu POKéNAV?$"

Route105_Text_AndresRematchIntro:
	.string "T'he dit que sóc feble…\n"
	.string "Estàs segur que vols fer això?$"

Route105_Text_AndresRematchDefeated:
	.string "Sí…\n"
	.string "No pensava que pogués guanyar.$"

Route105_Text_AndresRematchPostBattle:
	.string "Potser sóc feble lluitant, però el meu\n"
	.string "afany d'explorar és imbatible.\p"
	.string "Viatjaré pels mars de tot el món!$"

Route105_Text_JosueIntro:
	.string "Estic esgotat de nedar.\n"
	.string "No hi estic acostumat.\p"
	.string "Necessito un combat per canviar de ritme!$"

Route105_Text_JosueDefeated:
	.string "He perdut perquè he lluitat al mar.$"

Route105_Text_JosuePostBattle:
	.string "Sí, per a mi el cel va molt millor\n"
	.string "que el mar.$"

Route106_Text_ElliotIntro:
	.string "Què prefereixes, pescar al mar\n"
	.string "o a un rierol?$"

Route106_Text_ElliotDefeated:
	.string "Com a la pesca d'altura, he perdut\n"
	.string "espectacularment!$"

Route106_Text_ElliotPostBattle:
	.string "La pesca és genial tant si és al mar\n"
	.string "com a un rierol.\l"
	.string "Hi estàs d'acord, oi?$"

Route106_Text_ElliotRegister:
	.string "La pesca és genial, però lluitar també.\n"
	.string "Si no et fa res, podem tornar-nos a veure?$"

Route106_Text_ElliotRematchIntro:
	.string "He atrapat molts POKéMON pescant.\n"
	.string "Et mostraré un combat impressionant!$"

Route106_Text_ElliotRematchDefeated:
	.string "He perdut espectacularment altra vegada!$"

Route106_Text_ElliotRematchPostBattle:
	.string "Guanyar o perdre, els POKéMON són genials!\n"
	.string "Hi estàs d'acord, oi?$"

Route106_Text_NedIntro:
	.string "Què fa la gent si necessita anar\n"
	.string "al lavabo?\p"
	.string "I si la CANYA pica un de gros mentre\n"
	.string "sóc al lavabo? No puc anar-hi…$"

Route106_Text_NedDefeated:
	.string "He perdut perquè intento no anar\n"
	.string "al lavabo…$"

Route106_Text_NedPostBattle:
	.string "Oh, no! Tinc la sensació que pescaré\n"
	.string "un de gros!$"

Route106_Text_DouglasIntro:
	.string "Hahaha! Sóc un corredor dolent, però\n"
	.string "a l'aigua no em pots atrapar!$"

Route106_Text_DouglasDefeated:
	.string "Em rendeixo!$"

Route106_Text_DouglasPostBattle:
	.string "No perdria en una cursa de natació…$"

Route106_Text_KylaIntro:
	.string "El mar és el meu pati. No m'ho posaré\n"
	.string "fàcil perquè siguis un nen!$"

Route106_Text_KylaDefeated:
	.string "Per casualitat t'ho has posat fàcil\n"
	.string "amb mi?$"

Route106_Text_KylaPostBattle:
	.string "Deixar-se portar per les ones…\n"
	.string "M'encanta! Per què no ho proves?$"

Route107_Text_DarrinIntro:
	.string "Badall…\p"
	.string "Dec haver-me adormit mentre em deixava\n"
	.string "portar per les ones.$"

Route107_Text_DarrinDefeated:
	.string "Ahaha, he perdut…\n"
	.string "Crec que faré una becaina…$"

Route107_Text_DarrinPostBattle:
	.string "Flotar i deixar-se bressolar per les\n"
	.string "ones: és com dormir en un llit\n"
	.string "esponjós i còmode.$"

Route107_Text_TonyIntro:
	.string "El mar és com el meu pati.\n"
	.string "Lluitem!$"

Route107_Text_TonyDefeated:
	.string "He perdut al meu territori…\n"
	.string "Estic en xoc!$"

Route107_Text_TonyPostBattle:
	.string "Nedo pels mars amb el cor ple de\n"
	.string "somnis…\p"
	.string "És una cançó!\n"
	.string "De totes maneres, seguiré nedant.$"

Route107_Text_TonyRegister:
	.string "M'has deixat de pedra!\n"
	.string "Bé, perquè no m'oblidis…$"

Route107_Text_TonyRematchIntro:
	.string "Nedant pel mar gran i ample,\n"
	.string "el meu POKéMON s'ha fet més fort!$"

Route107_Text_TonyRematchDefeated:
	.string "Quin xoc!\p"
	.string "El meu POKéMON s'ha fet més fort, però\n"
	.string "jo segueixo sent feble com a ENTRENADOR!$"

Route107_Text_TonyRematchPostBattle:
	.string "El que aprens en combat et fa un\n"
	.string "ENTRENADOR més fort.\l"
	.string "Les ones m'ho han ensenyat.$"

Route107_Text_DeniseIntro:
	.string "Coneixes un poblet que es diu\n"
	.string "DEWFORD?$"

Route107_Text_DeniseDefeated:
	.string "Odio això!$"

Route107_Text_DenisePostBattle:
	.string "Una dita estranya s'està posant de moda\n"
	.string "al SALÓ DEWFORD.$"

Route107_Text_BethIntro:
	.string "Volies lluitar amb mi?\n"
	.string "És clar, endavant!$"

Route107_Text_BethDefeated:
	.string "No he estat prou bo per a tu.$"

Route107_Text_BethPostBattle:
	.string "Crec que seguiràs millorant.\n"
	.string "Jo també ho intentaré!$"

Route107_Text_LisaIntro:
	.string "LISA: Et desafiem com a germana\n"
	.string "i germà!$"

Route107_Text_LisaDefeated:
	.string "LISA: Increïble.\n"
	.string "Ets d'una altra classe de fort.$"

Route107_Text_LisaPostBattle:
	.string "LISA: Tens amics que vindrien a la\n"
	.string "platja amb tu?$"

Route107_Text_LisaNotEnoughPokemon:
	.string "LISA: Si vols lluitar amb nosaltres,\n"
	.string "porta més POKéMON.$"

Route107_Text_RayIntro:
	.string "RAY: Sempre lluitem amb POKéMON, jo\n"
	.string "i la meva germana.\p"
	.string "Sempre perdo, però et podem guanyar\n"
	.string "2 contra 2!$"

Route107_Text_RayDefeated:
	.string "RAY: Uau, estàs a un nivell més alt\n"
	.string "que nosaltres!$"

Route107_Text_RayPostBattle:
	.string "RAY: La meva germana em va donar el\n"
	.string "meu POKéMON. El vaig criar i ara és\n"
	.string "el meu company important!$"

Route107_Text_RayNotEnoughPokemon:
	.string "RAY: Si vols lluitar amb nosaltres,\n"
	.string "vés a buscar més POKéMON!$"

Route107_Text_CamronIntro:
	.string "Estic enmig d'un triatló,\n"
	.string "però no estic gens cansat!$"

Route107_Text_CamronDefeated:
	.string "Això m'ha esgotat…$"

Route107_Text_CamronPostBattle:
	.string "Encara em queda nedar i córrer després\n"
	.string "d'això.\p"
	.string "Estaré bé?$"

Route108_Text_JeromeIntro:
	.string "El meu somni és nedar pels set mars\n"
	.string "del món!$"

Route108_Text_JeromeDefeated:
	.string "No podré nedar pels set mars\n"
	.string "així…$"

Route108_Text_JeromePostBattle:
	.string "Jugar amb POKéMON marins és un dels\n"
	.string "plaers de nedar!$"

Route108_Text_MatthewIntro:
	.string "Ei, hola! Tu també vas cap al\n"
	.string "VAIXELL ABANDONAT?$"

Route108_Text_MatthewDefeated:
	.string "M'estic enfonsant!\n"
	.string "Glub… Glub…$"

Route108_Text_MatthewPostBattle:
	.string "Hi ha gent que fins i tot entra dins\n"
	.string "d'aquell VAIXELL ABANDONAT.$"

Route108_Text_TaraIntro:
	.string "El meu xicot mentider em va dir que\n"
	.string "estava genial en biquini…$"

Route108_Text_TaraDefeated:
	.string "Oh, quina llàstima!$"

Route108_Text_TaraPostBattle:
	.string "Encara que sigui mentida, m'encanta\n"
	.string "que em diguin que estic genial…\l"
	.string "Les noies som tan complexes…$"

Route108_Text_MissyIntro:
	.string "M'encanta el mar!\n"
	.string "Obido totes les preocupacions quan nedo!$"

Route108_Text_MissyDefeated:
	.string "Quan perdo un combat, em poso\n"
	.string "molt estressada!$"

Route108_Text_MissyPostBattle:
	.string "Elimina l'estrès nedant!\n"
	.string "És molt saludable!$"

Route108_Text_CoryIntro:
	.string "M'encanten els POKéMON tipus AIGUA.\n"
	.string "També m'encanten els altres POKéMON!$"

Route108_Text_CoryDefeated:
	.string "Buaaa! He perdut!\n"
	.string "Buaaa! Buaaa!$"

Route108_Text_CoryPostBattle:
	.string "Cridar em va bé!\n"
	.string "M'anima!$"

Route108_Text_CoryRegister:
	.string "També m'encanten els ENTRENADORS forts!\n"
	.string "Registra'm al teu POKéNAV!$"

Route108_Text_CoryRematchIntro:
	.string "Guanyi o perdi, m'encanta lluitar al mar!$"

Route108_Text_CoryRematchDefeated:
	.string "Buaaa! He perdut altra vegada!\n"
	.string "Buaaa! Buaaa!$"

Route108_Text_CoryRematchPostBattle:
	.string "Si t'enfrontes a un repte,\n"
	.string "prova de cridar al mar!$"

Route108_Text_CarolinaIntro:
	.string "Estic molt orgullosa dels meus POKéMON.\n"
	.string "Et mostrarem un combat ràpid!$"

Route108_Text_CarolinaDefeated:
	.string "Això no ha estat gens bonic.$"

Route108_Text_CarolinaPostBattle:
	.string "Ja que estic al mar així, no em faria\n"
	.string "res posar-me un banyador rosa amb volants…$"

Route109_Text_DavidIntro:
	.string "Hiyah! Mira els meus abdominals esculpits!\n"
	.string "Això és el que en diuen “definit”!$"

Route109_Text_DavidDefeated:
	.string "Aiyah!\n"
	.string "He fallat!$"

Route109_Text_DavidPostBattle:
	.string "Hiyah!\p"
	.string "Els meus abdominals esculpits no tenen\n"
	.string "res a veure amb les batalles POKéMON!$"

Route109_Text_AliceIntro:
	.string "Estàs ben protegit contra el sol?$"

Route109_Text_AliceDefeated:
	.string "Au, au, au!$"

Route109_Text_AlicePostBattle:
	.string "Les galtes són les que més es cremen!$"

Route109_Text_HueyIntro:
	.string "He ancorat en ports de tot el món,\n"
	.string "però SLATEPORT és el millor.$"

Route109_Text_HueyDefeated:
	.string "Ets el millor!$"

Route109_Text_HueyPostBattle:
	.string "Al millor port hi havia el millor\n"
	.string "ENTRENADOR…$"

Route109_Text_EdmondIntro:
	.string "Urrrrppp…\n"
	.string "Lluitar? Amb mi?$"

Route109_Text_EdmondDefeated:
	.string "Urp… Ooooooohhhhhh…\n"
	.string "Urrrrpppp…$"

Route109_Text_EdmondPostBattle:
	.string "Normalment sóc més fort que això!\n"
	.string "Només tinc mareig!\p"
	.string "Sóc MARINER, però…$"

Route109_Text_RickyIntro:
	.string "Tinc set… M'aniria bé un REFRESC\n"
	.string "a la CASA DE LA PLATJA…$"

Route109_Text_RickyDefeated:
	.string "Ai…$"

Route109_Text_RickyPostBattle:
	.string "Estic mort de gana… El meu flotador\n"
	.string "sembla un donut gegant…$"

Route109_Text_RickyRegister:
	.string "Voldràs tenir un altre combat amb mi\n"
	.string "quan no tingui tanta set?$"

Route109_Text_RickyRematchIntro:
	.string "Tinc gana, però tinc prou energia\n"
	.string "per a un combat!$"

Route109_Text_RickyRematchDefeated:
	.string "He perdut…\n"
	.string "És perquè tinc gana…$"

Route109_Text_RickyRematchPostBattle:
	.string "Quan menges a la platja, tot sembla\n"
	.string "tenir un gust una mica millor.$"

Route109_Text_LolaIntro:
	.string "Una para-sol de platja no sembla\n"
	.string "una flor gegant?$"

Route109_Text_LolaDefeated:
	.string "Mare!$"

Route109_Text_LolaPostBattle:
	.string "Si mires la platja des del cel,\n"
	.string "sembla un gran jardí de flors!$"

Route109_Text_LolaRegister:
	.string "Jo?\n"
	.string "Sóc aquí cada dia!$"

Route109_Text_LolaRematchIntro:
	.string "No tornaré a perdre contra tu!\n"
	.string "Per això tinc el meu flotador!$"

Route109_Text_LolaRematchDefeated:
	.string "Mare!$"

Route109_Text_LolaRematchPostBattle:
	.string "Si tinc un flotador, la meva simpatia\n"
	.string "i la del meu POKéMON augmenten molt!$"

Route109_Text_AustinaIntro:
	.string "No puc nedar sense el meu flotador,\n"
	.string "però no perdré a POKéMON!$"

Route109_Text_AustinaDefeated:
	.string "He perdut perquè tinc un flotador?$"

Route109_Text_AustinaPostBattle:
	.string "El meu flotador és un accessori de moda.\n"
	.string "No em poden veure sense ell.$"

Route109_Text_GwenIntro:
	.string "Hola, gran ENTRENADOR.\n"
	.string "Vols lluitar amb mi?$"

Route109_Text_GwenDefeated:
	.string "Oh, ets fort.$"

Route109_Text_GwenPostBattle:
	.string "Com has arribat a ser tan fort?$"

Route109_Text_CarterIntro:
	.string "Wahahah! Aquest tio pescarà\n"
	.string "un de gros!$"

Route109_Text_CarterDefeated:
	.string "Aquest tio acaba de perdre'n un…$"

Route109_Text_CarterPostBattle:
	.string "Aquest tio pensa que ets dels grossos.\n"
	.string "No, seràs dels grossos!$"

Route109_Text_PaulIntro:
	.string "PAUL: Bé, això trenca el rotllo.\p"
	.string "M'agradaria que no molestessis el\n"
	.string "nostre temps preciós junts.$"

Route109_Text_PaulDefeated:
	.string "PAUL: Bé, em rendeixo.$"

Route109_Text_PaulPostBattle:
	.string "PAUL: Bé, no diguis a ningú que som\n"
	.string "aquí.\l"
	.string "Aquest és només el nostre món privat de dos!$"

Route109_Text_PaulNotEnoughPokemon:
	.string "PAUL: Estem totalment i profundament\n"
	.string "enamorats. Per això fem lluitar els\n"
	.string "nostres POKéMON junts.$"

Route109_Text_MelIntro:
	.string "MEL: Estem, com, totalment enamorats.\n"
	.string "El nostre romanç escalfa tot HOENN!$"

Route109_Text_MelDefeated:
	.string "MEL: Hem perdut, i és culpa meva!\n"
	.string "PAUL m'odiarà!$"

Route109_Text_MelPostBattle:
	.string "MEL: Um, PAUL, estàs enfadat amb mi?\n"
	.string "Sis plau no t'enfadis.$"

Route109_Text_MelNotEnoughPokemon:
	.string "MEL: Estem, com, profunda i veritablement\n"
	.string "enamorats. Per això fem lluitar els\n"
	.string "nostres POKéMON junts.$"

Route109_Text_ChandlerIntro:
	.string "Tadaaa! Veus?\n"
	.string "El meu flotador és rodó!$"

Route109_Text_ChandlerDefeated:
	.string "Oh, oh!\n"
	.string "Quina llàstima!$"

Route109_Text_ChandlerPostBattle:
	.string "Després de mostrar-te el meu flotador\n"
	.string "rodó, també…$"

Route109_Text_HaileyIntro:
	.string "No sé nedar, així que faig veure\n"
	.string "que nedo.$"

Route109_Text_HaileyDefeated:
	.string "M'ho pensava!\n"
	.string "No creia que poguéssim guanyar.$"

Route109_Text_HaileyPostBattle:
	.string "Quan aprengui a nedar, crec que\n"
	.string "el meu POKéMON es tornarà més fort.$"

Route109_Text_ElijahIntro:
	.string "Per a un tio tan mascle com jo, aquest\n"
	.string "tipus de POKéMON és el company perfecte!$"

Route109_Text_ElijahDefeated:
	.string "Sóc guai fins i tot en la derrota, eh?$"

Route109_Text_ElijahPostBattle:
	.string "Per a un tio tan mascle com jo, un port\n"
	.string "és l'escenari perfecte!\p"
	.string "Suposo que aniré cap a SLATEPORT.$"

Route110_Text_JacobIntro:
	.string "Ep! Compte!\n"
	.string "Suposo que no estàs acostumat a la\n"
	.string "carrera de BICI.$"

Route110_Text_JacobDefeated:
	.string "Ep!\n"
	.string "Els frens m'han fallat!$"

Route110_Text_JacobPostBattle:
	.string "Les rodes punxades i els problemes de\n"
	.string "frens poden causar lesions greus!\l"
	.string "Inspecciona la teva BICI per problemes!$"

Route110_Text_AnthonyIntro:
	.string "Ei, tu!\n"
	.string "Pots seguir el meu ritme?$"

Route110_Text_AnthonyDefeated:
	.string "M'he estavellat!$"

Route110_Text_AnthonyPostBattle:
	.string "La velocitat sola no em farà guanyar a POKéMON.\n"
	.string "He de reconsiderar això…$"

Route110_Text_BenjaminIntro:
	.string "No t'espantis si la teva BICI va ràpida!$"

Route110_Text_BenjaminDefeated:
	.string "No m'hauria d'espantar durant les\n"
	.string "batalles POKéMON…$"

Route110_Text_BenjaminPostBattle:
	.string "No cal espantar-se ni estressar-se.\n"
	.string "Calma. Hi ha temps de sobra.$"

Route110_Text_BenjaminRegister:
	.string "Seguiré sense estressar-me.\n"
	.string "Truca'm si t'animes.$"

Route110_Text_BenjaminRematchIntro:
	.string "No vas una mica massa ràpid?\n"
	.string "Calma't i lluitem.$"

Route110_Text_BenjaminRematchDefeated:
	.string "No m'he espantat, però he perdut igualment…$"

Route110_Text_BenjaminRematchPostBattle:
	.string "No cal espantar-se ni estressar-se.\n"
	.string "Calma. Hi ha temps de sobra.$"

Route110_Text_AbigailIntro:
	.string "El triatló és extremadament dur.\p"
	.string "Has de completar les tres proves de\n"
	.string "natació, ciclisme i córrer.$"

Route110_Text_AbigailDefeated:
	.string "Les batalles POKéMON també són dures!$"

Route110_Text_AbigailPostBattle:
	.string "Estic esgotada, necessito una pausa.\n"
	.string "És important descansar adequadament.$"

Route110_Text_AbigailRegister:
	.string "Saps què, m'agrades!\n"
	.string "Tinguem una revenja a la RUTA CICLISTA.$"

Route110_Text_AbigailRematchIntro:
	.string "No és genial fer un combat mentre\n"
	.string "vas amb bici?$"

Route110_Text_AbigailRematchDefeated:
	.string "Uau…\n"
	.string "Com pots ser tan fort?$"

Route110_Text_AbigailRematchPostBattle:
	.string "Anaves a batre un rècord?\p"
	.string "Ho sento si t'he entretingut!$"

Route110_Text_JasmineIntro:
	.string "He estat pedalant sense parar.\n"
	.string "Tinc les cuixes com roques!$"

Route110_Text_JasmineDefeated:
	.string "Em preocupen les rampes musculars…$"

Route110_Text_JasminePostBattle:
	.string "Oh, tens algunes INSÍGNIES DE GIMNÀS?\n"
	.string "No és estrany que siguis tan fort!$"

Route110_Text_EdwardIntro:
	.string "He previst les teves intencions!\n"
	.string "És impossible que perdi!$"

Route110_Text_EdwardDefeated:
	.string "No vaig profetitzar la meva pròpia derrota!$"

Route110_Text_EdwardPostBattle:
	.string "Veig el teu futur…\p"
	.string "Hmm…\n"
	.string "Veig una llum brillant…$"

Route110_Text_JaclynIntro:
	.string "Ahahahaha!\n"
	.string "T'enlluarnaré amb les meves meravelles!$"

Route110_Text_JaclynDefeated:
	.string "He perdut meravellosament!$"

Route110_Text_JaclynPostBattle:
	.string "Has guanyat només perquè ha estat una\n"
	.string "meravella! Sí, una meravella!\l"
	.string "No creguis que pots guanyar sempre!$"

Route110_Text_EdwinIntro:
	.string "Podria veure els teus POKéMON?\n"
	.string "Només una ullada, si us plau?$"

Route110_Text_EdwinDefeated:
	.string "Volia completar\n"
	.string "la meva col·lecció…$"

Route110_Text_EdwinPostBattle:
	.string "Quan veig un POKéMON que no conec,\n"
	.string "la meva passió de col·leccionista s'encén!$"

Route110_Text_EdwinRegister:
	.string "També m'agrada col·leccionar registres\n"
	.string "de TRUCA'M…$"

Route110_Text_EdwinRematchIntro:
	.string "Hola, has atrapat nous POKéMON?\p"
	.string "Podria veure els teus POKéMON?\n"
	.string "Només una ullada, si us plau?$"

Route110_Text_EdwinRematchDefeated:
	.string "Els teus POKéMON…\n"
	.string "Et tinc enveja.$"

Route110_Text_EdwinRematchPostBattle:
	.string "Oh, anhelo fer meus tots els POKéMON\n"
	.string "rars!$"

Route110_Text_DaleIntro:
	.string "Ei!\n"
	.string "No t'acostis d'amagat per darrere així!$"

Route110_Text_DaleDefeated:
	.string "He perdut!\n"
	.string "Renoi!$"

Route110_Text_DalePostBattle:
	.string "La pesca és qüestió de concentració.\n"
	.string "T'has de fixar en el flotador.$"

Route110_Text_IsabelIntro:
	.string "Ahahaha! Aniria a qualsevol lloc per\n"
	.string "mostrar el meu adorable POKéMON.$"

Route110_Text_IsabelDefeated:
	.string "Oh, mare meva, això no pot ser.$"

Route110_Text_IsabelPostBattle:
	.string "En lloc de lluitar, potser hauria de\n"
	.string "mostrar el meu POKéMON al CLUB DE FANS.$"

Route110_Text_IsabelRegister:
	.string "Això no ha estat ni de bon tros el que\n"
	.string "puc fer per mostrar el meu POKéMON.\p"
	.string "Et tindré com a públic captiu tan\n"
	.string "sovint com pugui!$"

Route110_Text_IsabelRematchIntro:
	.string "Ahahahaha! Estaria encantada de mostrar\n"
	.string "el meu POKéMON tan sovint com vulguis!$"

Route110_Text_IsabelRematchDefeated:
	.string "Oh, mare meva, això no pot ser.$"

Route110_Text_IsabelRematchPostBattle:
	.string "No crec que mai pogués deixar de mostrar\n"
	.string "el meu POKéMON.\p"
	.string "Però també m'agrada lluitar!$"

Route110_Text_TimmyIntro:
	.string "He trobat uns POKéMON genials a l'herba\n"
	.string "d'aquí al voltant!$"

Route110_Text_TimmyDefeated:
	.string "Ser guai no és suficient per guanyar…$"

Route110_Text_TimmyPostBattle:
	.string "És difícil lluitar amb POKéMON que\n"
	.string "acabes d'atrapar.$"

Route110_Text_AlyssaIntro:
	.string "He caigut de la RUTA CICLISTA…\p"
	.string "Superaré la vergonya lluitant amb tu!$"

Route110_Text_AlyssaDefeated:
	.string "Ai!\n"
	.string "He acabat perdent!$"

Route110_Text_AlyssaPostBattle:
	.string "Caure… Perdre…\n"
	.string "Això és tan humiliant per a mi!$"

Route110_Text_JosephIntro:
	.string "D'acord! És hora d'anar a tope! Si no\n"
	.string "pots seguir el ritme, et quedaràs enrere!$"

Route110_Text_JosephDefeated:
	.string "Has agafat bé el ritme…$"

Route110_Text_JosephPostBattle:
	.string "Això no m'ensorrarà!\n"
	.string "Perdre m'ha fet millor persona!$"

Route110_Text_KalebIntro:
	.string "Quan els POKéMON bonics s'ajuden…\n"
	.string "No veuràs una escena més adorable!$"

Route110_Text_KalebDefeated:
	.string "No tens compassió ni pietat?$"

Route110_Text_KalebPostBattle:
	.string "D'acord, d'acord, heu fet el millor que\n"
	.string "heu pogut, bonic meus.$"

Route111_Text_DrewIntro:
	.string "Oh, ei! Aquestes ULLERES t'escauen.\n"
	.string "Però crec que a mi em queden millor.\p"
	.string "Decidem a qui li queden millor amb\n"
	.string "un combat!$"

Route111_Text_DrewDefeat:
	.string "No podia veure què passava als meus\n"
	.string "costats per culpa de les ULLERES.$"

Route111_Text_DrewPostBattle:
	.string "Les ULLERES fan possible travessar\n"
	.string "les tempestes de sorra.\l"
	.string "Això em fa feliç!$"

Route111_Text_HeidiIntro:
	.string "Estic fent un pícnic al desert.\p"
	.string "Sempre pots trobar un ENTRENADOR,\n"
	.string "aíxí que també puc gaudir d'un combat aquí!$"

Route111_Text_HeidiDefeat:
	.string "Ohhh! Ets dolent!$"

Route111_Text_HeidiPostBattle:
	.string "Quan lluites en una tempesta de sorra,\n"
	.string "vigila els PS dels teus POKéMON.\p"
	.string "Poden esvanir-se si no els vigiles!$"

Route111_Text_BeauIntro:
	.string "Portar aquestes ULLERES em fa sentir\n"
	.string "com un superheroi.\l"
	.string "Ara mateix, ningú em pot guanyar!$"

Route111_Text_BeauDefeat:
	.string "No puc guanyar només amb esperit…$"

Route111_Text_BeauPostBattle:
	.string "Seré un heroi de veritat algun dia.\n"
	.string "Treballaré més dur per fer-me més\n"
	.string "fort a mi i als meus POKéMON.$"

Route111_Text_BeckyIntro:
	.string "He sentit que hi ha fòssils per trobar\n"
	.string "al desert. On poden ser?$"

Route111_Text_BeckyDefeat:
	.string "M'he quedat curt…$"

Route111_Text_BeckyPostBattle:
	.string "Si poden trobar fòssils al desert,\n"
	.string "deu haver estat un mar abans.$"

Route111_Text_DustyIntro:
	.string "Durant trenta anys he buscat ruïnes\n"
	.string "antigues!\l"
	.string "M'han de desafiar?$"

Route111_Text_DustyDefeat:
	.string "Mentre he buscat ruïnes, no he buscat\n"
	.string "POKéMON forts.$"

Route111_Text_DustyPostBattle:
	.string "Durant trenta anys he buscat ruïnes\n"
	.string "antigues!\p"
	.string "No, espera, eren quaranta anys?\n"
	.string "Quants eren ara?$"

Route111_Text_DustyRegister:
	.string "No he estat buscant cap POKéMON fort.\p"
	.string "Però, per alguna raó, m'agraden molt\n"
	.string "els POKéNAVS.$"

Route111_Text_DustyRematchIntro:
	.string "Durant trenta anys he buscat ruïnes\n"
	.string "antigues!\p"
	.string "No, espera, eren quaranta anys?\n"
	.string "De totes maneres, m'han de desafiar?$"

Route111_Text_DustyRematchDefeat:
	.string "No he trobat ruïnes, ni tampoc he\n"
	.string "trobat cap POKéMON fort…$"

Route111_Text_DustyPostRematch:
	.string "Durant trenta anys he buscat ruïnes\n"
	.string "antigues!\p"
	.string "No, espera, eren quaranta anys que\n"
	.string "he buscat?\p"
	.string "Hmm… Podrien ser cinquanta…\n"
	.string "Quant de temps fa que estic en això?$"

Route111_Text_TravisIntro:
	.string "Estic ple d'energia!\n"
	.string "I el meu POKéMON també està animat!$"

Route111_Text_TravisDefeat:
	.string "El meu POKéMON ha perdut l'energia…$"

Route111_Text_TravisPostBattle:
	.string "Quan veig un ENTRENADOR amb molta energia,\n"
	.string "no puc evitar mirar.$"

Route111_Text_IreneIntro:
	.string "No sé on vas, però voldries lluitar?$"

Route111_Text_IreneDefeat:
	.string "Oh, ets repugnantment bo!$"

Route111_Text_IrenePostBattle:
	.string "Estic pensant que hauria d'anar a\n"
	.string "MT. XEMENEIA, però la vista d'aquí\n"
	.string "al voltant també és molt bonica.$"

Route111_Text_DaisukeIntro:
	.string "Per entrenar-me, desafio a tots\n"
	.string "els que trobo!$"

Route111_Text_DaisukeDefeat:
	.string "Em rendeixo!$"

Route111_Text_DaisukePostBattle:
	.string "Tot el que puc fer és seguir entrenant\n"
	.string "fins que pugui derrotar ENTRENADORS\n"
	.string "forts com tu.$"

Route111_Text_WiltonIntro:
	.string "Mostra'm com has endurit els teus\n"
	.string "POKéMON.$"

Route111_Text_WiltonDefeat:
	.string "Ja veig, els has endurit\n"
	.string "considerablement.$"

Route111_Text_WiltonPostBattle:
	.string "Els POKéMON i ENTRENADORS aprenen molt\n"
	.string "lluitant.\p"
	.string "El que és important és no rendir-se\n"
	.string "mai encara que perdis.$"

Route111_Text_WiltonRegister:
	.string "Hi ha molt a aprendre del teu estil\n"
	.string "d'entrenament.\p"
	.string "Demano una revenja si et ve de gust.$"

Route111_Text_WiltonRematchIntro:
	.string "Estem entrenant aquí per elevar el\n"
	.string "nostre joc al següent nivell.\l"
	.string "Queda't i entrena amb nosaltres!$"

Route111_Text_WiltonRematchDefeat:
	.string "Ooh, ets decent!$"

Route111_Text_WiltonPostRematch:
	.string "Ja que ets tan fort, hauries d'aspirar\n"
	.string "a la LLIGA POKéMON.$"

Route111_Text_BrookeIntro:
	.string "Oh, els teus POKéMON semblen actors\n"
	.string "seriosos.\n"
	.string "He de demanar-te un combat.$"

Route111_Text_BrookeDefeat:
	.string "No només semblen forts,\n"
	.string "són forts!$"

Route111_Text_BrookePostBattle:
	.string "Pensava que estava criant els meus POKéMON\n"
	.string "diligentment, però, oh no, encara queda\n"
	.string "molt per fer.$"

Route111_Text_BrookeRegister:
	.string "M'agradaria poder fer-me amic de més\n"
	.string "gent forta com tu!$"

Route111_Text_BrookeRematchIntro:
	.string "Pots fer els POKéMON més forts o més\n"
	.string "febles segons els moviments que els\n"
	.string "ensenyes.\p"
	.string "Quins moviments saben els teus POKéMON?$"

Route111_Text_BrookeRematchDefeat:
	.string "Els has ensenyat bons moviments!$"

Route111_Text_BrookePostRematch:
	.string "Potser hauria d'haver aturat l'evolució\n"
	.string "dels meus POKéMON fins que aprenguessin\n"
	.string "millors moviments…$"

Route111_Text_CeliaIntro:
	.string "No hauria d'haver vingut a un lloc com\n"
	.string "aquest per fer un pícnic!$"

Route111_Text_CeliaDefeat:
	.string "Ai!\n"
	.string "Realment no hauria d'haver vingut!$"

Route111_Text_CeliaPostBattle:
	.string "En una tempesta de sorra com aquesta,\n"
	.string "no puc preparar el pícnic ni amb les\n"
	.string "meves ULLERES posades…$"

Route111_Text_BryanIntro:
	.string "Com de fort ets?\n"
	.string "Exposarem aquest secret!$"

Route111_Text_BryanDefeat:
	.string "Oh! La teva força!\n"
	.string "Està envoltada de misteri!$"

Route111_Text_BryanPostBattle:
	.string "Aquest desert amaga misteris a les\n"
	.string "seves sorres canviants!$"

Route111_Text_BrandenIntro:
	.string "Et donaré una mica del meu entrepà\n"
	.string "si perds.$"

Route111_Text_BrandenDefeat:
	.string "Tsc! Pensava que un entrepà seria\n"
	.string "prou suborn…$"

Route111_Text_BrandenPostBattle:
	.string "Al meu SANDSHREW li encanta menjar\n"
	.string "els meus entrepans.$"

Route111_Text_TyronIntro:
	.string "Aquest és el meu tipus de POKéMON favorit!$"

Route111_Text_TyronDefeat:
	.string "Espera!\n"
	.string "Has pogut veure bé el meu POKéMON?$"

Route111_Text_TyronPostBattle:
	.string "Quan tinc un combat, gaudeixo mostrant\n"
	.string "el meu POKéMON.\p"
	.string "Aposto que tothom se sent així quan\n"
	.string "entra en un combat!$"

Route111_Text_CelinaIntro:
	.string "Mostra'm com posar una mica d'emoció\n"
	.string "a la meva vida.$"

Route111_Text_CelinaDefeat:
	.string "Oh… Mare meva…\n"
	.string "Això ha estat massa emoció.$"

Route111_Text_CelinaPostBattle:
	.string "El meu pols encara va a tota.\n"
	.string "Ets un ENTRENADOR fabulós.$"

Route111_Text_HaydenIntro:
	.string "Quan estàs tan mort de gana com jo,\n"
	.string "no hi ha lloc per a la pietat!$"

Route111_Text_HaydenDefeat:
	.string "Ai…$"

Route111_Text_HaydenPostBattle:
	.string "L'estómac em gruny!\n"
	.string "Potser puc rostir unes BAIES…$"

Route111_Text_BiancaIntro:
	.string "Véns de MAUVILLE?\n"
	.string "Doncs hauries d'estar ple d'energia!$"

Route111_Text_BiancaDefeat:
	.string "Ooh lala!\n"
	.string "Això és molt per digerir!$"

Route111_Text_BiancaPostBattle:
	.string "Aquest camí d'aquí…\n"
	.string "Tens un bon tros per viatjar.$"

Route112_Text_BriceIntro:
	.string "Hahahaha!\n"
	.string "Què tal si tenim un combat?\l"
	.string "Tu i jo!\l"
	.string "Hahahaha!$"

Route112_Text_BriceDefeat:
	.string "He perdut!\n"
	.string "Hahahaha!$"

Route112_Text_BricePostBattle:
	.string "Hahahahaha! Alguna cosa m'ha entrat pel nas!\n"
	.string "Hahahaha-atxím!$"

Route112_Text_TrentIntro:
	.string "Les meves cames són sòlides de pujar\n"
	.string "i baixar muntanyes.\p"
	.string "No cediran fàcilment, amic!$"

Route112_Text_TrentDefeat:
	.string "Au! Se m'han encalamat les cames!$"

Route112_Text_TrentPostBattle:
	.string "Prova de fer senderisme, i vull dir\n"
	.string "de debò, per aquests camins de\n"
	.string "muntanya amb una motxilla pesant.\p"
	.string "Això, amic meu, et posarà el cos\n"
	.string "en forma de debò.$"

Route112_Text_TrentRegister:
	.string "Au, se m'han encalamat les cames.\n"
	.string "Pots agafar-me unes benes de la\n"
	.string "motxilla?\p"
	.string "No, això és el meu POKéNAV!\n"
	.string "Oh, bé, et registraré.$"

Route112_Text_TrentRematchIntro:
	.string "He estat mantenint-me en forma fent\n"
	.string "senderisme. Força, en tinc de sobra!$"

Route112_Text_TrentRematchDefeat:
	.string "M'han superat en força?$"

Route112_Text_TrentRematchPostBattle:
	.string "He sentit que hi ha ENTRENADORS molt\n"
	.string "forts al cim de MT. XEMENEIA.\p"
	.string "Penso pujar-hi i desafiar-los!$"

Route112_Text_LarryIntro:
	.string "Sóc fort.\n"
	.string "No ploraré si perdo.$"

Route112_Text_LarryDefeat:
	.string "Buaaa!$"

Route112_Text_LarryPostBattle:
	.string "No ploro perquè trobo a faltar la mama!\n"
	.string "Snif…$"

Route112_Text_CarolIntro:
	.string "Quan ets de pícnic, doncs,\n"
	.string "simplement has de cantar!\l"
	.string "Vinga, canta amb mi!$"

Route112_Text_CarolDefeat:
	.string "Oh, ets tan fort!$"

Route112_Text_CarolPostBattle:
	.string "No importa si ets bo o dolent\n"
	.string "cantant o als POKéMON.\p"
	.string "Si et diverteixes més, guanyes!$"

Route112_Text_BryantIntro:
	.string "He atrapat POKéMON calents al CAMÍ FOGÓS!\n"
	.string "Mira!$"

Route112_Text_BryantDefeat:
	.string "Quin viatge tan mogut ha estat!$"

Route112_Text_BryantPostBattle:
	.string "M'agrada la manera com lluites.\n"
	.string "Té un cert estil.$"

Route112_Text_ShaylaIntro:
	.string "Oh, no ets un ENTRENADOR adorable!\n"
	.string "Sis plau, necessito un combat romàntic!\l"
	.string "Sóc bastant decent!$"

Route112_Text_ShaylaDefeat:
	.string "Oh, que fort ets!\n"
	.string "M'has donat un bon ensurt!$"

Route112_Text_ShaylaPostBattle:
	.string "Estàs ocupat ara?\n"
	.string "Pensava que potser podríem tenir\n"
	.string "una revenja ara mateix…\l"
	.string "Però no passa res si estàs ocupat.$"

Route113_Text_JaylenIntro:
	.string "Pots endevinar per què fa tan fresc\n"
	.string "per aquí?$"

Route113_Text_JaylenDefeat:
	.string "Puf!\n"
	.string "Quina pudor!$"

Route113_Text_JaylenPostBattle:
	.string "La cendra volcànica bloqueja el sol,\n"
	.string "aíxí que no fa gaire calor.\p"
	.string "Això em va bé: no suporto la calor!$"

Route113_Text_DillonIntro:
	.string "L'erupció del volcà és prova que la\n"
	.string "terra és viva.$"

Route113_Text_DillonDefeat:
	.string "Ets una mena de fort!$"

Route113_Text_DillonPostBattle:
	.string "Au! Aiii! No hi veig!\n"
	.string "M'ha entrat cendra a les pestanyes!\p"
	.string "Ho entens? Cendra i pestanyes?\p"
	.string "D'acord, ha estat dolent, perdona…$"

Route113_Text_MadelineIntro:
	.string "Faig servir aquest para-sol per protegir\n"
	.string "de la cendra volcànica bruta i fastigosa\n"
	.string "al meu estimat NUMEL.$"

Route113_Text_MadelineDefeat:
	.string "Buf, buf…\n"
	.string "Estic esgotada…$"

Route113_Text_MadelinePostBattle:
	.string "Ets molt bo en això.\n"
	.string "He de dir que estic impressionada!$"

Route113_Text_MadelineRegister:
	.string "Aquí, posa't sota el meu para-sol.\n"
	.string "Deixa'm registrar-te al meu POKéNAV.$"

Route113_Text_MadelineRematchIntro:
	.string "Oh, hola, no fa temps que no ens veiem?\n"
	.string "Puc convidar-te a un combat?$"

Route113_Text_MadelineRematchDefeat:
	.string "Oh, que genial!$"

Route113_Text_MadelinePostRematch:
	.string "Continues sent molt bo en això.\n"
	.string "He de dir que estic impressionada!$"

Route113_Text_LaoIntro:
	.string "Salto de les cendres! Hiyah!\n"
	.string "Et desafio!$"

Route113_Text_LaoDefeat:
	.string "Amb honor admeto la derrota!$"

Route113_Text_LaoPostBattle:
	.string "He de refinar l'art de l'ocultació.\n"
	.string "T'acomiado.$"

Route113_Text_LaoRegister:
	.string "Yiiyaah! Presencia l'antiga tècnica\n"
	.string "ninja del registre de POKéNAV!$"

Route113_Text_LaoRematchIntro:
	.string "Salto de les cendres! Hiyah!\n"
	.string "Et desafio!$"

Route113_Text_LaoRematchDefeat:
	.string "Amb honor admeto la derrota!$"

Route113_Text_LaoPostRematch:
	.string "La meva ocultació impecable ha estat\n"
	.string "traïda per les meves habilitats de\n"
	.string "combat immadures…\p"
	.string "T'acomiado.$"

Route113_Text_LungIntro:
	.string "Gràcies per trobar-me!\n"
	.string "Però encara hem de lluitar!$"

Route113_Text_LungDefeat:
	.string "Usaré el meu ninjutsu contra tu…\n"
	.string "“CAPA REMOLÍ DE CENDRA VOLCÀNICA”!\p"
	.string "…Què?\n"
	.string "Ja s'ha acabat?$"

Route113_Text_LungPostBattle:
	.string "Saps què és fastigós d'amagar-se?\n"
	.string "És solitari si no ve ningú.$"

Route113_Text_ToriIntro:
	.string "TORI: Tots dos recollim cendres.\n"
	.string "També lluitem amb POKéMON.$"

Route113_Text_ToriDefeat:
	.string "TORI: Hem perdut… És avorrit, així que\n"
	.string "aniré a buscar més cendres.$"

Route113_Text_ToriPostBattle:
	.string "TORI: Quanta cendra tenim?\n"
	.string "Prou per a una FLAUTA BLANCA, espero.$"

Route113_Text_ToriNotEnoughMons:
	.string "TORI: Volem lluitar 2 contra 2.\n"
	.string "Si no, perdríem!$"

Route113_Text_TiaIntro:
	.string "TIA: Tots dos recollim cendres.\n"
	.string "També lluitem amb POKéMON.$"

Route113_Text_TiaDefeat:
	.string "TIA: No hem pogut guanyar… És avorrit,\n"
	.string "aíxí que aniré a buscar més cendres.$"

Route113_Text_TiaPostBattle:
	.string "TIA: Tenim molta cendra!\n"
	.string "Crec que prou per a una FLAUTA BLANCA!$"

Route113_Text_TiaNotEnoughMons:
	.string "TIA: Volem lluitar 2 contra 2.\n"
	.string "Si no, no guanyarem!$"

Route113_Text_CobyIntro:
	.string "Pfft, amb aquestes ales et puc\n"
	.string "fer fora d'un cop!$"

Route113_Text_CobyDefeat:
	.string "Què… Què?$"

Route113_Text_CobyPostBattle:
	.string "No sé què dir quan em guanyen\n"
	.string "tan fàcilment…$"

Route113_Text_SophieIntro:
	.string "La calidesa d'aquí em fa son.\n"
	.string "Lluita amb mi per mantenir-me despert.$"

Route113_Text_SophieDefeat:
	.string "Això és un somni.\n"
	.string "N'estic segur…$"

Route113_Text_SophiePostBattle:
	.string "Perdre em crema…\n"
	.string "Dormiré aquí mateix!\l"
	.string "Zzz!$"

Route113_Text_LawrenceIntro:
	.string "Potser estaves enmig de\n"
	.string "recollir cendres volcàniques?$"

Route113_Text_LawrenceDefeat:
	.string "Ehehe.\n"
	.string "Ens han guanyat netament.$"

Route113_Text_LawrencePostBattle:
	.string "Jo també m'hauria d'amagar sota les cendres.$"

Route113_Text_WyattIntro:
	.string "V-vols lluitar amb mi?\n"
	.string "Tot i que acabo d'atrapar el meu POKéMON?$"

Route113_Text_WyattDefeat:
	.string "E-estàs tan content de guanyar?\n"
	.string "Tot i que només sóc jo?$"

Route113_Text_WyattPostBattle:
	.string "Oh, ara vols dir alguna cosa\n"
	.string "al perdedor?\p"
	.string "No ets el més guai?\n"
	.string "Humph!$"

Route114_Text_LennyIntro:
	.string "Iodeleihihuuu!\p"
	.string "… …\p"
	.string "S'hauria de cridar\n"
	.string "“iodeleihihuuu” ja que aquí\l"
	.string "no fa eco!$"

Route114_Text_LennyDefeat:
	.string "Iodeleihihuuu!$"

Route114_Text_LennyPostBattle:
	.string "Quan era petit, creia que hi havia\n"
	.string "algú copiant-me i cridant\l"
	.string "de tornada, “Iodeleihihuuu”.$"

Route114_Text_LucasIntro:
	.string "Si no estàs preparat, no hauries\n"
	.string "d'estar a les muntanyes!$"

Route114_Text_LucasDefeat:
	.string "Les muntanyes no perdonen…$"

Route114_Text_LucasPostBattle:
	.string "A l'hivern, les muntanyes es tornen\n"
	.string "mortals amb ventisques i allaus.$"

Route114_Text_ShaneIntro:
	.string "Acampar és divertit! Pots pescar, rostir\n"
	.string "núvols de sucre i explicar històries de por!\p"
	.string "Però el millor de tot són les batalles\n"
	.string "POKéMON!$"

Route114_Text_ShaneDefeat:
	.string "Massa fort!$"

Route114_Text_ShanePostBattle:
	.string "Crec que és genial poder anar\n"
	.string "d'acampada amb els meus POKéMON.$"

Route114_Text_NancyIntro:
	.string "Necessito fer exercici després de menjar.\n"
	.string "Tinguem un combat!$"

Route114_Text_NancyDefeat:
	.string "Oh, no!$"

Route114_Text_NancyPostBattle:
	.string "Acabo de fer un àpat deliciós.\n"
	.string "Em ve son…$"

Route114_Text_SteveIntro:
	.string "Ufufufufufu…\n"
	.string "Vols lluitar contra el meu POKéMON?$"

Route114_Text_SteveDefeat:
	.string "E-El meu POKéMON…$"

Route114_Text_StevePostBattle:
	.string "Un cos gran ple de bonys i dur,\n"
	.string "banyes enormes i ullals ferotges…\p"
	.string "Ufufufufu…\n"
	.string "M'agradaria tenir un POKéMON així…$"

Route114_Text_SteveRegister:
	.string "No oblidis el que m'has fet!\n"
	.string "Faré que no ho puguis oblidar!$"

Route114_Text_SteveRematchIntro:
	.string "Ufufufufufu…\n"
	.string "Vinga, lluita contra el meu POKéMON…$"

Route114_Text_SteveRematchDefeat:
	.string "Em sento tan afortunat de poder veure\n"
	.string "els teus POKéMON…$"

Route114_Text_StevePostRematch:
	.string "Ufufufufufu…\p"
	.string "Quan veig POKéMON lluitant, em poso\n"
	.string "tot tremolós…$"

Route114_Text_BernieIntro:
	.string "Si encens una foguera, assegura't\n"
	.string "de tenir aigua a mà.$"

Route114_Text_BernieDefeat:
	.string "Gràcies per apagar el meu foc!$"

Route114_Text_BerniePostBattle:
	.string "Realment has de tenir cura amb\n"
	.string "qualsevol tipus de foc al bosc.\p"
	.string "Mai subestimis el poder del foc.$"

Route114_Text_BernieRegister:
	.string "Has encès el meu esperit.\n"
	.string "Registrem-nos mútuament!$"

Route114_Text_BernieRematchIntro:
	.string "Has après a tenir aigua a mà\n"
	.string "per a les fogueres?$"

Route114_Text_BernieRematchDefeat:
	.string "M'han ruixat abans de poder\n"
	.string "encendre'm, suposo.$"

Route114_Text_BerniePostRematch:
	.string "Realment has de tenir cura amb\n"
	.string "qualsevol tipus de foc al bosc.\p"
	.string "Mai subestimis el poder del foc.$"

Route114_Text_ClaudeIntro:
	.string "Si estiguéssim pescant, no tindries\n"
	.string "cap oportunitat contra mi.\l"
	.string "Així que, porta els teus POKéMON!$"

Route114_Text_ClaudeDefeat:
	.string "Si estiguéssim pescant, hauria guanyat…$"

Route114_Text_ClaudePostBattle:
	.string "Crec que provaré sort pescant un\n"
	.string "de gros a les CASCADES METEOR.\p"
	.string "Hi ha d'haver alguna cosa allà dins.\n"
	.string "Ho sé segur.$"

Route114_Text_NolanIntro:
	.string "M'agrada pescar. Però també m'agrada\n"
	.string "lluitar!\p"
	.string "Si algú em desafia, hi sóc,\n"
	.string "fins i tot si estic pescant.$"

Route114_Text_NolanDefeat:
	.string "M'agrada lluitar, però això no vol dir\n"
	.string "que sigui bo…$"

Route114_Text_NolanPostBattle:
	.string "Aquesta vegada ho aconseguiré!\p"
	.string "Sempre penso això, així que no puc\n"
	.string "deixar la pesca ni els POKéMON.$"

Route114_Text_TyraIntro:
	.string "TYRA: Bé, és clar.\n"
	.string "Estic d'humor per això.\l"
	.string "T'ensenyaré una mica sobre POKéMON.$"

Route114_Text_TyraDefeat:
	.string "TYRA: Quin estil de combat tan increïble!$"

Route114_Text_TyraPostBattle:
	.string "TYRA: Estava ensenyant a la meva alumna\n"
	.string "IVY sobre POKéMON.$"

Route114_Text_TyraNotEnoughMons:
	.string "TYRA: Riure…\n"
	.string "Si vols lluitar amb nosaltres, només un\n"
	.string "POKéMON no és suficient!$"

Route114_Text_IvyIntro:
	.string "IVY: Qui et va ensenyar sobre POKéMON?$"

Route114_Text_IvyDefeat:
	.string "IVY: Quin estil de combat tan increïble!$"

Route114_Text_IvyPostBattle:
	.string "IVY: Vaig començar a entrenar POKéMON\n"
	.string "perquè TYRA, la meva mentora,\n"
	.string "m'ho va ensenyar!$"

Route114_Text_IvyNotEnoughMons:
	.string "IVY: Només tens un POKéMON?\n"
	.string "Crec que es deu sentir sol.$"

Route114_Text_KaiIntro:
	.string "N'he pescat un de gros!\n"
	.string "Un d'enorme, t'ho dic!$"

Route114_Text_KaiDefeat:
	.string "De què anava això?\n"
	.string "El meu ha perdut en mida?$"

Route114_Text_KaiPostBattle:
	.string "D'acord!\n"
	.string "Pescaré un de més gros!$"

Route114_Text_CharlotteIntro:
	.string "Jo!\n"
	.string "No sóc només una cara bonica!$"

Route114_Text_CharlotteDefeat:
	.string "Això no ha estat gens bonic!$"

Route114_Text_CharlottePostBattle:
	.string "No vull un POKéMON que només\n"
	.string "sigui bonic.\p"
	.string "Adoro els bonics que tenen alguna\n"
	.string "peculiaritat!$"

Route114_Text_AngelinaIntro:
	.string "Has fet evolucionar molt els teus\n"
	.string "POKéMON?$"

Route114_Text_AngelinaDefeat:
	.string "Oh, ja veig.\n"
	.string "És bo saber-ho.$"

Route114_Text_AngelinaPostBattle:
	.string "Alguns POKéMON canvien tant quan\n"
	.string "evolucionen que espanta!$"

Route115_Text_TimothyIntro:
	.string "Hm…\n"
	.string "Sembles bastant capaç…\l"
	.string "Deixa'm fer-te companyia!$"

Route115_Text_TimothyDefeat:
	.string "Ets molt més fort del que\n"
	.string "m'imaginava!$"

Route115_Text_TimothyPostBattle:
	.string "No existeix el geni de naixement.\n"
	.string "Tot depèn de l'esforç!\l"
	.string "Això és el que crec…$"

Route115_Text_TimothyRegister:
	.string "Hmm… Una derrota tan completa feia\n"
	.string "temps que no en tenia.\p"
	.string "Si ho permets, desitjaria una altra\n"
	.string "oportunitat per lluitar.$"

Route115_Text_TimothyRematchIntro:
	.string "Hm… Com sempre, la teva agilitat parla\n"
	.string "per si sola.\l"
	.string "Vinga, fes-me companyia!$"

Route115_Text_TimothyRematchDefeat:
	.string "Tan fort com sempre!$"

Route115_Text_TimothyPostRematch:
	.string "Tot és qüestió d'esforç!\p"
	.string "He perdut perquè no m'he esforçat\n"
	.string "prou!$"

Route115_Text_KoichiIntro:
	.string "Tu!\p"
	.string "El meu MACHOP!\p"
	.string "Exigeix un combat!$"

Route115_Text_KoichiDefeat:
	.string "Au, au, au!$"

Route115_Text_KoichiPostBattle:
	.string "El meu equip de MACHOP!\p"
	.string "Mentre busquin poder, em faré fort\n"
	.string "amb ells!$"

Route115_Text_NobIntro:
	.string "La meva habilitat més forta és trencar\n"
	.string "maons amb el front!$"

Route115_Text_NobDefeat:
	.string "Ugwaaaah!\n"
	.string "Tinc el cap trencat!$"

Route115_Text_NobPostBattle:
	.string "He estat ensenyant karate als meus POKéMON.\p"
	.string "Sembla que seran molt millors que jo.\n"
	.string "Això m'emociona.$"

Route115_Text_NobRegister:
	.string "M'impressiones! Dóna'm una revenja\n"
	.string "després que refaci el meu entrenament!$"

Route115_Text_NobRematchIntro:
	.string "Després que em guanyessis, hem entrenat\n"
	.string "dur per millorar les habilitats.\l"
	.string "Vinga, dóna'ns una revenja!$"

Route115_Text_NobRematchDefeat:
	.string "Ugwaaah!\n"
	.string "Hem perdut altra vegada!$"

Route115_Text_NobPostRematch:
	.string "Els meus POKéMON es faran més forts!\n"
	.string "Redoblaré l'entrenament!$"

Route115_Text_CyndyIntro:
	.string "Aquesta platja és el meu lloc secret\n"
	.string "d'entrenament! No vinguis a molestar!$"

Route115_Text_CyndyDefeat:
	.string "No he entrenat prou!$"

Route115_Text_CyndyPostBattle:
	.string "La sorra actua com a coixí per reduir\n"
	.string "l'impacte i prevenir lesions.\l"
	.string "Aquest és el lloc perfecte per entrenar.$"

Route115_Text_CyndyRegister:
	.string "D'acord, bé, ets lliure de venir aquí.\n"
	.string "A canvi, m'agradaria tornar a lluitar amb tu.$"

Route115_Text_CyndyRematchIntro:
	.string "D'acord, comencem aquest combat!$"

Route115_Text_CyndyRematchDefeat:
	.string "Jo puc lluitar però el meu POKéMON…$"

Route115_Text_CyndyPostRematch:
	.string "Fins i tot quan perdo, gaudeixo una mica.\n"
	.string "Deu ser que m'encanten els POKéMON.$"

Route115_Text_HectorIntro:
	.string "Tinc un POKéMON rar!\n"
	.string "Vols que te'l mostri?$"

Route115_Text_HectorDefeat:
	.string "Tu…\n"
	.string "Vols el meu POKéMON, oi?$"

Route115_Text_HectorPostBattle:
	.string "Tinc aquest POKéMON rar.\n"
	.string "N'hi ha prou per mantenir-me satisfet.$"

Route115_Text_KyraIntro:
	.string "Lluitaré mentre corro!\n"
	.string "Intenta seguir-me el ritme!$"

Route115_Text_KyraDefeat:
	.string "Buf, buf…$"

Route115_Text_KyraPostBattle:
	.string "He comès l'error d'intentar lluitar\n"
	.string "mentre corria!\n"
	.string "Hauria de córrer per calmar-me…$"

Route115_Text_JaidenIntro:
	.string "Pren això!\n"
	.string "Atac ninja ultra POKéMON!$"

Route115_Text_JaidenDefeat:
	.string "Waaah!\n"
	.string "La nostra estratègia ha fallat!$"

Route115_Text_JaidenPostBattle:
	.string "Però els meus POKéMON eren ultra,\n"
	.string "oi?$"

Route115_Text_HeleneIntro:
	.string "Els meus POKéMON tenen força de nivell\n"
	.string "cinturó negre!$"

Route115_Text_HeleneDefeat:
	.string "Això és massa humiliant!$"

Route115_Text_HelenePostBattle:
	.string "Rarament trobo algú millor que jo…\p"
	.string "Ja ho entenc!\n"
	.string "Ets un LÍDER DE GIMNÀS, oi?$"

Route115_Text_AlixIntro:
	.string "Les mirades s'han creuat!\n"
	.string "Ara no hi ha escapatòria!$"

Route115_Text_AlixDefeat:
	.string "Gah!\n"
	.string "No està malament!$"

Route115_Text_AlixPostBattle:
	.string "Oh, bé.\n"
	.string "Crec que em TELETRANSPORTARÉ a casa.$"

Route115_Text_MarleneIntro:
	.string "Has pertorbat la meva meditació…\n"
	.string "Seràs castigat per això.$"

Route115_Text_MarleneDefeat:
	.string "Has trencat la meva concentració!$"

Route115_Text_MarlenePostBattle:
	.string "Estava meditant amb el meu POKéMON.\n"
	.string "Però aquest lloc no és gaire pacífic…$"

Route116_Text_ClarkIntro:
	.string "Si el túnel no travessa, simplement\n"
	.string "pujaré per dalt.$"

Route116_Text_ClarkDefeat:
	.string "Buf… Buf…\n"
	.string "Perdre m'ha cansat…$"

Route116_Text_ClarkPostBattle:
	.string "No és cap problema si no hi ha túnel.\n"
	.string "Per a un MUNTANYENC, les muntanyes són camins!$"

Route116_Text_JoeyIntro:
	.string "Els meus POKéMON manen!\n"
	.string "Mira'ls!$"

Route116_Text_JoeyDefeat:
	.string "Au! Una rascada!\n"
	.string "M'he de posar una tireta!$"

Route116_Text_JoeyPostBattle:
	.string "Les tiretes són senyals de duresa!\n"
	.string "En tinc una altra!$"

Route116_Text_JoseIntro:
	.string "Els meus POKéMON BICHO són durs!\n"
	.string "Lluitem!$"

Route116_Text_JoseDefeat:
	.string "He perdut!\n"
	.string "Pensava que et tenia!$"

Route116_Text_JosePostBattle:
	.string "Els POKéMON BICHO evolucionen ràpid.\n"
	.string "Així que també es fan forts ràpid.$"

Route116_Text_JaniceIntro:
	.string "Deixa'm ensenyar-te com de fort és\n"
	.string "el meu adorable POKéMON!$"

Route116_Text_JaniceDefeat:
	.string "Estàs un graó per sobre meu…$"

Route116_Text_JanicePostBattle:
	.string "POKéMON que tenen simpatia i poder,\n"
	.string "crec que és l'ideal.$"

Route116_Text_JerryIntro:
	.string "Aprenem tot tipus de coses a l'ESCOLA\n"
	.string "D'ENTRENADORS.\n"
	.string "Vull provar les coses de debò!$"

Route116_Text_JerryDefeat:
	.string "He anat de tranquil a l'escola…\n"
	.string "Per això he perdut.$"

Route116_Text_JerryPostBattle:
	.string "Hauré de repetir alguns cursos a\n"
	.string "l'ESCOLA D'ENTRENADORS.\l"
	.string "Si no, ROXANNE s'enfadarà.$"

Route116_Text_JerryRegister1:
	.string "Vaig aprendre a l'ESCOLA D'ENTRENADORS\n"
	.string "que un POKéNAV pot registrar ENTRENADORS.\p"
	.string "No entenc gaire què significa,\n"
	.string "aíxí que puc provar-ho?$"

Route116_Text_JerryRegister2:
	.string "Vaig aprendre a l'ESCOLA D'ENTRENADORS\n"
	.string "que un POKéNAV pot registrar ENTRENADORS.\p"
	.string "No entenc gaire què significa,\n"
	.string "aíxí que puc provar-ho?$"

Route116_Text_JerryRematchIntro:
	.string "He estat estudiant seriosament a\n"
	.string "l'ESCOLA D'ENTRENADORS.\l"
	.string "No perdré com l'última vegada.$"

Route116_Text_JerryRematchDefeat:
	.string "Eh?\n"
	.string "He estudiat diligentment.$"

Route116_Text_JerryPostRematch:
	.string "Hauré de repetir alguns cursos a\n"
	.string "l'ESCOLA D'ENTRENADORS.\l"
	.string "Si no, ROXANNE s'enfadarà.$"

Route116_Text_KarenIntro:
	.string "Estudio a l'escola, i també estudio\n"
	.string "de camí a casa!$"

Route116_Text_KarenDefeat:
	.string "Estic en xoc: he perdut?$"

Route116_Text_KarenPostBattle:
	.string "Ai, mai no seré una ENTRENADORA elegant\n"
	.string "com ROXANNE d'aquesta manera!$"

Route116_Text_KarenRegister1:
	.string "Oh, uau! Això no és un POKéNAV?\n"
	.string "Jo també en tinc un! Sis plau registra'm!$"

Route116_Text_KarenRegister2:
	.string "Oh, uau! Això no és un POKéNAV?\n"
	.string "Jo també en tinc un! Sis plau registra'm!$"

Route116_Text_KarenRematchIntro:
	.string "He estudiat molt des que et vaig veure.\n"
	.string "Has de veure els meus progressos!$"

Route116_Text_KarenRematchDefeat:
	.string "Estic en xoc.\n"
	.string "He perdut altra vegada?$"

Route116_Text_KarenPostRematch:
	.string "Has guanyat ROXANNE?\n"
	.string "Doncs no et puc guanyar. Encara no.$"

Route116_Text_SarahIntro:
	.string "Perquè ho sàpigues, mai ningú m'ha\n"
	.string "guanyat en res.$"

Route116_Text_SarahDefeat:
	.string "Oh, mare meva.\n"
	.string "Aquesta és una experiència nova per a mi.$"

Route116_Text_SarahPostBattle:
	.string "La meva vida de luxe m'ofereix tot\n"
	.string "el que puc desitjar.\p"
	.string "Però quan es tracta de POKéMON,\n"
	.string "la meva riquesa no té significat.$"

Route116_Text_DawsonIntro:
	.string "Quan vegis el preciós pelatge del meu\n"
	.string "POKéMON, la seva bellesa et deixarà\n"
	.string "indefens!$"

Route116_Text_DawsonDefeat:
	.string "Oh, cari, digues que no és veritat!$"

Route116_Text_DawsonPostBattle:
	.string "Oh, no, no, no!\n"
	.string "Has despentinat el pelatge del meu POKéMON!\l"
	.string "També m'has arruïnat el pentinat!\l"
	.string "Ara hauré de trucar al meu estilista!$"

Route116_Text_DevanIntro:
	.string "Et donarem fort!$"

Route116_Text_DevanDefeat:
	.string "Aiyiyi!\n"
	.string "No hi ha hagut competència!$"

Route116_Text_DevanPostBattle:
	.string "Hauria de provar diferents tipus de\n"
	.string "POKéMON, això és el que hauria de fer.$"

Route116_Text_JohnsonIntro:
	.string "Aquí dalt és un carreró sense sortida.\n"
	.string "Estic avorrit, podem lluitar?$"

Route116_Text_JohnsonDefeat:
	.string "Ha estat divertit tot i que he perdut.$"

Route116_Text_JohnsonPostBattle:
	.string "Vols quedar-te aquí i fer-me\n"
	.string "companyia?$"

Route117_Text_IsaacIntro:
	.string "Escolta, podries lluitar contra\n"
	.string "els POKéMON que estic criant?$"

Route117_Text_IsaacDefeat:
	.string "Has criat els teus magníficament…$"

Route117_Text_IsaacPostBattle:
	.string "El POKéMON no va només de poder.\p"
	.string "Polir un aspecte únic del caràcter\n"
	.string "d'un és una altra manera de gaudir\l"
	.string "del POKéMON.$"

Route117_Text_IsaacRegister:
	.string "Redoblaré el meu entrenament.\n"
	.string "Vindràs a veure'ns?$"

Route117_Text_IsaacRematchIntro:
	.string "Els POKéMON que he estat criant\n"
	.string "es veuen bé, igual que abans.$"

Route117_Text_IsaacRematchDefeat:
	.string "Saps com criar-los bé.\n"
	.string "Potser tens habilitats de GUARDERIA…$"

Route117_Text_IsaacPostRematch:
	.string "Els teus POKéMON creixen bé!\n"
	.string "Hauries d'inscriure'ls en CONCURSOS.$"

Route117_Text_LydiaIntro:
	.string "Si us plau, deixa'm avaluar si has\n"
	.string "criat els teus POKéMON correctament.$"

Route117_Text_LydiaDefeat:
	.string "Sí, estan creixent correctament.$"

Route117_Text_LydiaPostBattle:
	.string "Prova de criar POKéMON amb més\n"
	.string "atenció als seus trets de caràcter.$"

Route117_Text_LydiaRegister:
	.string "M'alegro d'haver conegut una ENTRENADORA\n"
	.string "tan excel·lent. Espero veure't de nou.$"

Route117_Text_LydiaRematchIntro:
	.string "Deixa'm revaluar si has criat\n"
	.string "els teus POKéMON correctament.$"

Route117_Text_LydiaRematchDefeat:
	.string "Estan creixent admirablement.$"

Route117_Text_LydiaPostRematch:
	.string "Sembla que els POKéMON els agraden\n"
	.string "diferents {POKEBLOCK}S, segons la natura.$"

Route117_Text_DylanIntro:
	.string "Estic enmig d'un triatló, però,\n"
	.string "tant se val, lluitem!$"

Route117_Text_DylanDefeat:
	.string "M'he quedat sense energia!$"

Route117_Text_DylanPostBattle:
	.string "Potser l'he espifiada…\p"
	.string "Podria haver caigut a l'últim lloc\n"
	.string "durant aquell combat…$"

Route117_Text_DylanRegister:
	.string "Els POKéMON també han de ser forts?\n"
	.string "M'agradaria que m'entrenissis!$"

Route117_Text_DylanRematchIntro:
	.string "Estic just enmig d'un triatló,\n"
	.string "però vaig còmodament al davant.\l"
	.string "Fem un combat ràpid!$"

Route117_Text_DylanRematchDefeat:
	.string "M'he tornat a quedar sense energia!$"

Route117_Text_DylanPostRematch:
	.string "Era el millor en natació i ciclisme,\n"
	.string "però encara no tinc tanta confiança\l"
	.string "amb els POKéMON.$"

Route117_Text_MariaIntro:
	.string "Faig l'entrenament de triatló amb POKéMON,\n"
	.string "així que estic força segura de la meva velocitat.$"

Route117_Text_MariaDefeat:
	.string "Suposo que necessito\n"
	.string "practicar més.$"

Route117_Text_MariaPostBattle:
	.string "L'entrenament només té sentit si\n"
	.string "el mantens regularment.\p"
	.string "D'acord! Reprendré l'entrenament!\n"
	.string "Demà!$"

Route117_Text_MariaRegister:
	.string "Sembla que entrenes correctament…\n"
	.string "Si vols, lluitarem més tard!$"

Route117_Text_MariaRematchIntro:
	.string "Segueixes amb el teu entrenament?\n"
	.string "Jo sí!\l"
	.string "Deixa'm mostrar-te l'evidència!$"

Route117_Text_MariaRematchDefeat:
	.string "Suposo que necessito\n"
	.string "practicar més.$"

Route117_Text_MariaPostRematch:
	.string "Reprendré l'entrenament demà.\n"
	.string "Lluitem de nou algun dia!$"

Route117_Text_DerekIntro:
	.string "Abans un CAÇABITXOS!\n"
	.string "I ara un ENTOMÒLEG!\p"
	.string "Però el meu amor pels POKéMON\n"
	.string "roman inalterable!$"

Route117_Text_DerekDefeat:
	.string "La meva ineptitud també roman\n"
	.string "inalterable…$"

Route117_Text_DerekPostBattle:
	.string "Només vaig seguir el meu cor, i ara\n"
	.string "em diuen ENTOMÒLEG…\p"
	.string "Tot i això, sóc expert en POKéMON BICHO,\n"
	.string "així que és natural que em diguin\l"
	.string "ENTOMÒLEG.$"

Route117_Text_AnnaIntro:
	.string "ANNA: Estic amb la meva bonica companya\n"
	.string "estudiant júnior. He de fer-ho bé!$"

Route117_Text_AnnaDefeat:
	.string "ANNA: Estic amb la meva bonica companya\n"
	.string "estudiant júnior! Deixa'm guanyar!$"

Route117_Text_AnnaPostBattle:
	.string "ANNA: Els teus POKéMON tenen bones\n"
	.string "combinacions.\p"
	.string "Diria que només ets segona darrere nostre!$"

Route117_Text_AnnaAndMegRegister:
	.string "ANNA: No podem acceptar això!\n"
	.string "Tornaràs, oi?$"

Route117_Text_AnnaNotEnoughMons:
	.string "ANNA: Si vols lluitar contra nosaltres,\n"
	.string "porta dos POKéMON amb tu.$"

Route117_Text_MegIntro:
	.string "MEG: M'aliaré amb la meva súper companya\n"
	.string "estudiant sènior i et venceré!$"

Route117_Text_MegDefeat:
	.string "MEG: Oh, no!\n"
	.string "Ho sento, ANNA! T'he decebut…$"

Route117_Text_MegPostBattle:
	.string "MEG: He arrossegat l'ANNA cap avall…\n"
	.string "Si no, hauria guanyat!$"

Route117_Text_MegNotEnoughMons:
	.string "MEG: Només tens un POKéMON?\n"
	.string "Aleshores no podem lluitar amb tu.\p"
	.string "Volem un combat de 2 contra 2.$"

Route117_Text_AnnaRematchIntro:
	.string "ANNA: No puc seguir perdent davant\n"
	.string "la meva companya júnior, oi?$"

Route117_Text_AnnaRematchDefeat:
	.string "ANNA: No he pogut agafar el ritme.$"

Route117_Text_AnnaPostRematch:
	.string "ANNA: Els teus POKéMON tenen bones\n"
	.string "combinacions.\p"
	.string "Diria que només ets segona darrere nostre!$"

Route117_Text_AnnaRematchNotEnoughMons:
	.string "ANNA: Si vols lluitar contra nosaltres,\n"
	.string "porta dos POKéMON amb tu.$"

Route117_Text_MegRematchIntro:
	.string "MEG: M'aliaré amb la meva companya\n"
	.string "sènior i guanyaré aquest cop!$"

Route117_Text_MegRematchDefeat:
	.string "MEG: Massa fort!$"

Route117_Text_MegPostRematch:
	.string "MEG: He lluitat junt amb la meva\n"
	.string "companya sènior, però hem perdut…\p"
	.string "És tan descoratjador…$"

Route117_Text_MegRematchNotEnoughMons:
	.string "MEG: Només tens un POKéMON?\n"
	.string "Aleshores no podem lluitar amb tu.\p"
	.string "Volem un combat de 2 contra 2.$"

Route117_Text_MelinaIntro:
	.string "No és bonic? Lluitar mentre mires\n"
	.string "les flors boniques?$"

Route117_Text_MelinaDefeat:
	.string "Oh, això és força impressionant!$"

Route117_Text_MelinaPostBattle:
	.string "És meravellós fer fúting\n"
	.string "mentre mires les flors.$"

Route117_Text_BrandiIntro:
	.string "Deixa'm demostrar el poder\n"
	.string "amagat dins d'un POKéMON PSÍQUIC!$"

Route117_Text_BrandiDefeat:
	.string "Sorprenent!$"

Route117_Text_BrandiPostBattle:
	.string "Els POKéMON PSÍQUICS són complexos.\n"
	.string "Hauries de provar d'atrapar-ne.$"

Route117_Text_AishaIntro:
	.string "Concentra't a aconseguir la victòria.\n"
	.string "Així és com lluito!$"

Route117_Text_AishaDefeat:
	.string "No perdo temps enfadant-me per\n"
	.string "una derrota--prefereixo entrenar.$"

Route117_Text_AishaPostBattle:
	.string "Crec que si et preocupa perdre,\n"
	.string "és més probable que perdis.$"

Route118_Text_RoseIntro:
	.string "L'aroma de les flors té un poder\n"
	.string "màgic. Ens neteja cos i ànima.$"

Route118_Text_RoseDefeat:
	.string "Oh, vaja.\n"
	.string "Sembla que he perdut.$"

Route118_Text_RosePostBattle:
	.string "Flors, POKéMON…\n"
	.string "M'encanta tot el que fa bona olor.\p"
	.string "Coses pudents…\n"
	.string "Passo.$"

Route118_Text_RoseRegister:
	.string "Snif… Aquesta olor--és un POKéNAV!\n"
	.string "Hem de registrar-nos mútuament!$"

Route118_Text_RoseRematchIntro:
	.string "T'ha atret aquí la dolça\n"
	.string "aroma?$"

Route118_Text_RoseRematchDefeat:
	.string "El poder de l'aroma…\n"
	.string "No sembla haver fet gaire.$"

Route118_Text_RosePostRematch:
	.string "Si uses una aroma dolça correctament,\n"
	.string "els POKéMON se sentiran atrets.$"

Route118_Text_PerryIntro:
	.string "POKéMON OCELL que VOLEN elegant\n"
	.string "al cel… Són els millors!$"

Route118_Text_PerryDefeat:
	.string "Urgh…\n"
	.string "He xocat…$"

Route118_Text_PerryPostBattle:
	.string "Tens grans POKéMON.\n"
	.string "Hauré d'entrenar millor els meus.$"

Route118_Text_ChesterIntro:
	.string "Aixequeu el vol!\n"
	.string "Els meus POKéMON OCELL!$"

Route118_Text_ChesterDefeat:
	.string "Sí que han alçat el vol…$"

Route118_Text_ChesterPostBattle:
	.string "Si es fessin més forts, podrien\n"
	.string "volar més lliurement…$"

Route118_Text_BarnyIntro:
	.string "Sóc un PESCADOR, però també ENTRENADOR.\n"
	.string "Estic criant els POKéMON que he atrapat.$"

Route118_Text_BarnyDefeat:
	.string "Pensava que anava bé en el meu\n"
	.string "entrenament…$"

Route118_Text_BarnyPostBattle:
	.string "No he pogut guanyar entrenant POKéMON\n"
	.string "mentre pescava…\p"
	.string "Ho feia a mitges?$"

Route118_Text_WadeIntro:
	.string "Per als PESCADORS, l'equipament és clau.\p"
	.string "Però per als ENTRENADORS, els ingredients\n"
	.string "clau són POKéMON i cor, és clar!$"

Route118_Text_WadeDefeat:
	.string "M'han vençut en cor?$"

Route118_Text_WadePostBattle:
	.string "Pensant-ho bé, pescar és una batalla\n"
	.string "entre un PESCADOR i un POKéMON.$"

Route118_Text_DaltonIntro:
	.string "Deixa que la meva melodia sacsegi la teva ànima!$"

Route118_Text_DaltonDefeat:
	.string "La-lalala…$"

Route118_Text_DaltonPostBattle:
	.string "Una guitarra elèctrica no sempre\n"
	.string "ha de fer soroll…\p"
	.string "Es pot rasquejar per treure\n"
	.string "aquesta melodia commovadora…$"

Route118_Text_DaltonRegister:
	.string "Quan compongui millors melodies,\n"
	.string "has de venir a escoltar, d'acord?$"

Route118_Text_DaltonRematchIntro:
	.string "Una melodia dels meus POKéMON i jo…\n"
	.string "Deixa'ns lliurar-la a la teva ànima.$"

Route118_Text_DaltonRematchDefeat:
	.string "La-lalala…$"

Route118_Text_DaltonPostRematch:
	.string "Quan toco, les meves emocions haurien\n"
	.string "d'arribar-te a través de la guitarra…$"

Route118_Text_DeandreIntro:
	.string "Endavant, endavant, endavant!\n"
	.string "POKéMON 1, 2 i 3!$"

Route118_Text_DeandreDefeat:
	.string "Torneu, POKéMON! Esteu bé?\n"
	.string "POKéMON 1, 2 i 3?!$"

Route118_Text_DeandrePostBattle:
	.string "No és genial que tingui un equip\n"
	.string "de combat POKéMON?\p"
	.string "Pots copiar-me--no em fa res!$"

Route119_Text_BrentIntro:
	.string "Som el CERCLE MÍMIC!\n"
	.string "IMITEM el que fas!$"

Route119_Text_BrentDefeat:
	.string "Vaja!\n"
	.string "He perdut!$"

Route119_Text_BrentPostBattle:
	.string "Què té de bo la mímica?\p"
	.string "Fufufu…\n"
	.string "Mai ho entendràs…$"

Route119_Text_DonaldIntro:
	.string "Per fi ens trobem!\n"
	.string "Els meus POKéMON BICHO et faran companyia!$"

Route119_Text_DonaldDefeat:
	.string "M'agradaria no haver-nos trobat mai…$"

Route119_Text_DonaldPostBattle:
	.string "Vull IMITAR-te una mica més.\n"
	.string "Pots afanyar-te i moure't?$"

Route119_Text_TaylorIntro:
	.string "Si fas un pas endavant, nosaltres també.\p"
	.string "Si gires a la dreta, nosaltres també…$"

Route119_Text_TaylorDefeat:
	.string "Però si tu guanyes, jo perdo…$"

Route119_Text_TaylorPostBattle:
	.string "No puc IMITAR que guanyis el combat.\n"
	.string "Això és impossible…\l"
	.string "Em crema per dins…$"

Route119_Text_DougIntro:
	.string "Sí, finalment m'has atrapat!\n"
	.string "O intentaves evitar-me?$"

Route119_Text_DougDefeat:
	.string "Uau, ha estat un gran combat!$"

Route119_Text_DougPostBattle:
	.string "Som el CERCLE MÍMIC!\n"
	.string "Espero que hagis gaudit l'actuació.$"

Route119_Text_GregIntro:
	.string "No saps qui sóc, oi?\p"
	.string "Però jo tampoc et conec.\n"
	.string "Així que lluitem!$"

Route119_Text_GregDefeat:
	.string "Ets força fort!$"

Route119_Text_GregPostBattle:
	.string "Fins que marxis a algun lloc,\n"
	.string "seguirem imitant cada moviment teu.$"

Route119_Text_KentIntro:
	.string "El CERCLE MÍMIC el van formar gent\n"
	.string "a qui agrada IMITAR.\p"
	.string "Un combat comença a l'instant que ens trobem!$"

Route119_Text_KentDefeat:
	.string "Em rendeixo!$"

Route119_Text_KentPostBattle:
	.string "No t'uniries al nostre CERCLE MÍMIC?$"

Route119_Text_JacksonIntro:
	.string "Qui té el coneixement i\n"
	.string "la tècnica per sobreviure?\p"
	.string "Els RANGERS POKéMON, ells!$"

Route119_Text_JacksonDefeat:
	.string "No tenia prou coneixements\n"
	.string "de POKéMON…$"

Route119_Text_JacksonPostBattle:
	.string "Trencar amb la civilització i\n"
	.string "despertar l'esperit salvatge interior!\p"
	.string "Aquesta és la nostra visió.$"

Route119_Text_JacksonRegister:
	.string "Espero que em donis la revenja sense\n"
	.string "burlar-te de la meva manca de coneixement.$"

Route119_Text_JacksonRematchIntro:
	.string "Recuperaré el meu esperit salvatge\n"
	.string "estant amb els POKéMON.$"

Route119_Text_JacksonRematchDefeat:
	.string "Has seguit sent fort!$"

Route119_Text_JacksonPostRematch:
	.string "Creu en els teus POKéMON.\n"
	.string "Creu en tu mateix.\p"
	.string "El camí es revelarà davant teu.$"

Route119_Text_CatherineIntro:
	.string "Oh? Mira't.\p"
	.string "Per algú d'aventura,\n"
	.string "viatges molt lleuger.$"

Route119_Text_CatherineDefeat:
	.string "Els accidents passen quan no\n"
	.string "estàs preparat!$"

Route119_Text_CatherinePostBattle:
	.string "Viatges lleuger però tens\n"
	.string "tot el que necessites.\p"
	.string "Estàs preparat mentalment i\n"
	.string "físicament.$"

Route119_Text_CatherineRegister:
	.string "Tens un POKéNAV?\n"
	.string "És una eina imprescindible per a un ENTRENADOR.\p"
	.string "Oh, en tens un!\n"
	.string "Registrem-nos, doncs!$"

Route119_Text_CatherineRematchIntro:
	.string "Com va el teu viatge amb\n"
	.string "els POKéMON?$"

Route119_Text_CatherineRematchDefeat:
	.string "Encara em falta alguna cosa…$"

Route119_Text_CatherinePostRematch:
	.string "De la mateixa manera que tu, com a\n"
	.string "ENTRENADOR, confies en els teus POKéMON,\l"
	.string "ells confien en tu.$"

Route119_Text_HughIntro:
	.string "El vast cel amaga promeses infinites!\p"
	.string "Res es pot comparar a la pura\n"
	.string "exaltació del vol!$"

Route119_Text_HughDefeat:
	.string "A terra i fora!$"

Route119_Text_HughPostBattle:
	.string "Els meus POKéMON OCELL han fet realitat\n"
	.string "els meus somnis de volar!$"

Route119_Text_PhilIntro:
	.string "Et mostraré el veritable potencial meu\n"
	.string "i dels meus POKéMON OCELL!$"

Route119_Text_PhilDefeat:
	.string "Ens faltava potencial…$"

Route119_Text_PhilPostBattle:
	.string "Des de petit, sempre he\n"
	.string "admirat els POKéMON OCELL…$"

Route119_Text_YasuIntro:
	.string "Amagar-me a les ombres, i viure\n"
	.string "a la foscor… Això és el meu destí.\p"
	.string "Sorgeixo per desafiar-te!$"

Route119_Text_YasuDefeat:
	.string "Admeto la derrota!$"

Route119_Text_YasuPostBattle:
	.string "Els derrotats en combat es retiren\n"
	.string "en silenci a les ombres.\l"
	.string "Això, també, és el destí…$"

Route119_Text_TakashiIntro:
	.string "Si no estàs en guàrdia,\n"
	.string "et faràs mal!$"

Route119_Text_TakashiDefeat:
	.string "Ets sorprenentment bo!$"

Route119_Text_TakashiPostBattle:
	.string "El meu atac sorpresa ha acabat\n"
	.string "en fracàs…$"

Route119_Text_HideoIntro:
	.string "Per amagar un arbre, usa un bosc!$"

Route119_Text_HideoDefeat:
	.string "M'inclino davant la teva superioritat.$"

Route119_Text_HideoPostBattle:
	.string "Per amagar un arbre, usa un bosc!\n"
	.string "Per amagar un POKéMON, usa un POKéMON!\p"
	.string "No hi ha cap significat profund\n"
	.string "amagat en això.$"

Route119_Text_ChrisIntro:
	.string "M'has parlat…\n"
	.string "Així que vols desafiar-me!\p"
	.string "És clar! Provaré els POKéMON que he\n"
	.string "atrapat mentre feia SURF!$"

Route119_Text_ChrisDefeat:
	.string "No tinc ni idea del que es\n"
	.string "necessita per guanyar.$"

Route119_Text_ChrisPostBattle:
	.string "Fer SURF sobre el meu POKéMON…\p"
	.string "Després pescar des de la seva esquena…\p"
	.string "És un moment indescriptiblement luxós!$"

Route119_Text_FabianIntro:
	.string "Colpeja'm amb un acord de poder!\n"
	.string "La victòria és meva!\l"
	.string "És el nostre moment de brillar, uau, sí!$"

Route119_Text_FabianDefeat:
	.string "M'has ensenyat qui mana!\n"
	.string "Haurem d'acceptar la derrota, oh, no!$"

Route119_Text_FabianPostBattle:
	.string "Colpeja'm amb un altre acord de poder!\n"
	.string "Deixa'm en pau!\l"
	.string "La teva victòria hauràs d'expiar!$"

Route119_Text_DaytonIntro:
	.string "Hohoho!\n"
	.string "M'agraden els ENTRENADORS joves!\l"
	.string "Tinguem un bon combat!$"

Route119_Text_DaytonDefeat:
	.string "Ets força sorprenent!\n"
	.string "Hohoho!$"

Route119_Text_DaytonPostBattle:
	.string "Hohoho!\n"
	.string "Intentaré emular l'energia dels\l"
	.string "ENTRENADORS joves com tu!$"

Route119_Text_RachelIntro:
	.string "On i quan sigui,\n"
	.string "sempre porto el meu paraigua a la mà.$"

Route119_Text_RachelDefeat:
	.string "Oh, però…\n"
	.string "Això no és just.$"

Route119_Text_RachelPostBattle:
	.string "Em preguntes si el meu paraigua és pesat?\n"
	.string "La teva BOSSA està més plena de trastos\l"
	.string "dels que mai porto jo.$"

Route120_Text_ColinIntro:
	.string "Tens algun moviment que pugui\n"
	.string "colpejar un POKéMON volador?$"

Route120_Text_ColinDefeat:
	.string "M'has superat volant!$"

Route120_Text_ColinPostBattle:
	.string "El moviment VOL és convenient,\n"
	.string "no trobes?\p"
	.string "Mentre el POKéMON vola,\n"
	.string "gairebé cap moviment el pot colpejar.$"

Route120_Text_RobertIntro:
	.string "El meu POKéMON és fort!\n"
	.string "I el teu?$"

Route120_Text_RobertDefeat:
	.string "Els teus POKéMON eren més forts…$"

Route120_Text_RobertPostBattle:
	.string "Un POKéMON que creix constantment és\n"
	.string "un en qui pots confiar.$"

Route120_Text_RobertRegister:
	.string "Es pot comptar amb tu per millorar.\n"
	.string "M'agradaria registrar-te al meu POKéNAV!$"

Route120_Text_RobertRematchIntro:
	.string "Un POKéMON que creix constantment és\n"
	.string "un en qui pots confiar.$"

Route120_Text_RobertRematchDefeat:
	.string "Els teus POKéMON són seriosament forts.$"

Route120_Text_RobertPostRematch:
	.string "Els meus POKéMON es fan més forts.\n"
	.string "Jo també he de fer-me més fort.$"

Route120_Text_LorenzoIntro:
	.string "Comprovaré els teus POKéMON per veure si\n"
	.string "estan preparats per a l'aire lliure.$"

Route120_Text_LorenzoDefeat:
	.string "Amb POKéMON tan forts, no corres\n"
	.string "perill de necessitar rescat!$"

Route120_Text_LorenzoPostBattle:
	.string "Viatjar on el cor desitgi\n"
	.string "amb POKéMON…\l"
	.string "Aquesta és la joia de ser ENTRENADOR.$"

Route120_Text_JennaIntro:
	.string "Com és la teva forma física?\n"
	.string "Si no estàs en forma, podries tenir\l"
	.string "problemes en situacions crítiques.$"

Route120_Text_JennaDefeat:
	.string "Estic totalment en forma, però…$"

Route120_Text_JennaPostBattle:
	.string "L'entrenament físic és part de la meva rutina.\n"
	.string "Sempre corro amb els meus POKéMON.$"

Route120_Text_JeffreyIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Vols lluitar?$"

Route120_Text_JeffreyDefeat:
	.string "He perdut…$"

Route120_Text_JeffreyPostBattle:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "M'esforçaré més…$"

Route120_Text_JeffreyRegister:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Tens un POKéNAV…?$"

Route120_Text_JeffreyRematchIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Vols lluitar de nou?$"

Route120_Text_JeffreyRematchDefeat:
	.string "… … … … … …\n"
	.string "He perdut de nou…$"

Route120_Text_JeffreyPostRematch:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "M'esforçaré més…\l"
	.string "Pels meus preuats POKéMON BICHO…$"

Route120_Text_JenniferIntro:
	.string "Els POKéMON tenen moltes habilitats especials.\n"
	.string "Si vols ser un ENTRENADOR de primera,\l"
	.string "aprèn sobre elles.$"

Route120_Text_JenniferDefeat:
	.string "Evidentment estàs pensant.$"

Route120_Text_JenniferPostBattle:
	.string "Les habilitats especials dels POKéMON\n"
	.string "faran canviar els estils de combat.$"

Route120_Text_ChipIntro:
	.string "Qui ets?\p"
	.string "Potser busques les ruïnes antigues\n"
	.string "que segons rumors podrien existir\l"
	.string "segons la llegenda?$"

Route120_Text_ChipDefeat:
	.string "Quin contratemps vergonyós…$"

Route120_Text_ChipPostBattle:
	.string "Aquella roca gegant… M'agradaria\n"
	.string "creure que conté ruïnes antigues.\l"
	.string "Però no veig cap entrada.$"

Route120_Text_ClarissaIntro:
	.string "Per què porto aquest paraigua?\p"
	.string "T'ho diré si pots guanyar-me.$"

Route120_Text_ClarissaDefeat:
	.string "Un paraigua no pot defensar-se dels\n"
	.string "atacs POKéMON…$"

Route120_Text_ClarissaPostBattle:
	.string "No crec que la llum forta del sol sigui bona\n"
	.string "per als meus POKéMON.\l"
	.string "Així que els protegeixo amb el paraigua.$"

Route120_Text_AngelicaIntro:
	.string "Jo, POKéMON, i el meu paraigua…\p"
	.string "Si falta algun d'ells,\n"
	.string "la imatge de bellesa es farà malbé.$"

Route120_Text_AngelicaDefeat:
	.string "Has arruïnat completament la meva bellesa…$"

Route120_Text_AngelicaPostBattle:
	.string "Un paraigua no t'aniria gens bé.\p"
	.string "Vaja, una cosa així només\n"
	.string "et faria nosa.$"

Route120_Text_KeigoIntro:
	.string "Adoptaré els moviments dels POKéMON\n"
	.string "i crearé noves tècniques ninja.$"

Route120_Text_KeigoDefeat:
	.string "La creació de noves tècniques ninja\n"
	.string "és només un somni llunyà…$"

Route120_Text_KeigoPostBattle:
	.string "Potser hauria de ser aprenent\n"
	.string "d'un sensei ninja.$"

Route120_Text_RileyIntro:
	.string "Els ninjas ens ocultem sota les nostres\n"
	.string "capes de camuflatge.\l"
	.string "Aposto que no sabies on era!$"

Route120_Text_RileyDefeat:
	.string "He perdut!\n"
	.string "Hauria de camuflar la meva vergonya!$"

Route120_Text_RileyPostBattle:
	.string "Les nostres capes de camuflatge són\n"
	.string "totes fetes a mà.$"

Route120_Text_CallieIntro:
	.string "Si no pares atenció,\n"
	.string "et podries fer mal!$"

Route120_Text_CallieDefeat:
	.string "Ai!\n"
	.string "Jo he estat qui s'ha fet mal.$"

Route120_Text_CalliePostBattle:
	.string "Em pregunto… Hauria de fer evolucionar\n"
	.string "els meus POKéMON? Tot i que són monos com són.$"

Route120_Text_LeonelIntro:
	.string "Els teus POKéMON d'equip…\n"
	.string "Tens de diferents tipus?$"

Route120_Text_LeonelDefeat:
	.string "He vist la teva política en acció!$"

Route120_Text_LeonelPostBattle:
	.string "Crec que és impressionant que siguis tan fort\n"
	.string "lluitant amb els teus POKéMON favorits.$"

Route121_Text_VanessaIntro:
	.string "Vols jugar amb els meus POKéMON\n"
	.string "deliciosament bonics?$"

Route121_Text_VanessaDefeat:
	.string "No era això el que volia dir!$"

Route121_Text_VanessaPostBattle:
	.string "Vaig a un CONCURS a CALAGUA.\p"
	.string "Els meus POKéMON no haurien de tenir\n"
	.string "problemes per arrasar la CLASSE MESTRE.$"

Route121_Text_WalterIntro:
	.string "Amb els meus POKéMON, he viatjat\n"
	.string "als quatre racons del món.\p"
	.string "Podries dir que tinc certa confiança\n"
	.string "en les meves habilitats.$"

Route121_Text_WalterDefeat:
	.string "Ah, ben jugat.$"

Route121_Text_WalterPostBattle:
	.string "M'agradaria donar la volta al món\n"
	.string "un altre cop amb els meus POKéMON.$"

Route121_Text_WalterRegister:
	.string "La teva habilitat POKéMON és remarcable.\n"
	.string "Deixa'm registrar-te com a record.$"

Route121_Text_WalterRematchIntro:
	.string "Amb els meus POKéMON, he viatjat\n"
	.string "als quatre racons del món.\p"
	.string "Podries dir que tinc certa confiança\n"
	.string "en les meves habilitats.$"

Route121_Text_WalterRematchDefeat:
	.string "Ah, ben jugat.$"

Route121_Text_WalterPostRematch:
	.string "Els teus POKéMON i tu…\p"
	.string "La vostra habilitat conjunta serà\n"
	.string "considerada forta, fins i tot a l'estranger.$"

Route121_Text_TammyIntro:
	.string "Hi ha poders més enllà de la nostra\n"
	.string "comprensió al món…$"

Route121_Text_TammyDefeat:
	.string "He perdut…$"

Route121_Text_TammyPostBattle:
	.string "MT. PIRA…\n"
	.string "Hi ha un poder misteriós\l"
	.string "treballant allà…$"

Route121_Text_KateIntro:
	.string "KATE: Juntes, som invencibles!\n"
	.string "Demostrarem com de dures som!$"

Route121_Text_KateDefeat:
	.string "KATE: L'he espifiada davant de la meva\n"
	.string "companya estudiant júnior…$"

Route121_Text_KatePostBattle:
	.string "KATE: Quan algú depèn de mi,\n"
	.string "tinc la necessitat de semblar guai\l"
	.string "davant d'ells…$"

Route121_Text_KateNotEnoughMons:
	.string "KATE: Si només tens un POKéMON,\n"
	.string "no podem lluitar amb tu.\p"
	.string "Això seria assetjament.$"

Route121_Text_JoyIntro:
	.string "JOY: Juntes, som invencibles!\n"
	.string "Demostrarem com de dures som!$"

Route121_Text_JoyDefeat:
	.string "JOY: Si us plau, perdona'm, KATE!$"

Route121_Text_JoyPostBattle:
	.string "JOY: Ehehe, hauré d'entrenar amb KATE,\n"
	.string "la meva companya sènior, un altre cop.$"

Route121_Text_JoyNotEnoughMons:
	.string "JOY: Necessites almenys dos POKéMON\n"
	.string "si ens vols desafiar!$"

Route121_Text_JessicaIntro:
	.string "Para! Fes una bona ullada als meus\n"
	.string "preciosos POKéMON!$"

Route121_Text_JessicaDefeat:
	.string "Oh, com t'atreveixes!\n"
	.string "No t'ho prenguis tan seriosament!$"

Route121_Text_JessicaPostBattle:
	.string "Potser aniré a atrapar més POKéMON\n"
	.string "al SAFARI.$"

Route121_Text_JessicaRegister:
	.string "Aquesta vegada t'ho he posat fàcil!\n"
	.string "El proper cop no serà així!$"

Route121_Text_JessicaRematchIntro:
	.string "Els meus preciosos POKéMON han crescut!\n"
	.string "Fes una bona ullada!$"

Route121_Text_JessicaRematchDefeat:
	.string "Oh, com t'atreveixes!\n"
	.string "Encara no t'ho prendràs amb calma!$"

Route121_Text_JessicaPostRematch:
	.string "Potser aniré a atrapar més POKéMON\n"
	.string "al SAFARI.$"

Route121_Text_CristinIntro:
	.string "Tinc aquesta rutina.\n"
	.string "Derrota cinc ENTRENADORS al dia.\l"
	.string "Saps què? Ets el número cinc!$"

Route121_Text_CristinDefeat:
	.string "No!\n"
	.string "Ets horrible!$"

Route121_Text_CristinPostBattle:
	.string "No esperava perdre tan fàcilment…\n"
	.string "Guanyaré el proper cop!$"

Route121_Text_CristinRegister:
	.string "Això ha estat una humiliació total!\n"
	.string "No t'oblidaré…\l"
	.string "Dóna'm el teu POKéNAV!$"

Route121_Text_CristinRematchIntro:
	.string "Tinc una nova rutina.\n"
	.string "Derrota deu ENTRENADORS al dia.\l"
	.string "Saps què? Ets el número deu!$"

Route121_Text_CristinRematchDefeat:
	.string "Espera! Això és brut!\n"
	.string "Exigeixo la revenja!$"

Route121_Text_CristinPostRematch:
	.string "Un oponent que no puc vèncer…\n"
	.string "Ploramiques…\l"
	.string "No puc creure que estigui passant…$"

Route121_Text_CaleIntro:
	.string "No veus que porto tot això\n"
	.string "amb mi?\p"
	.string "Tot i això, insistes que\n"
	.string "lluitem?$"

Route121_Text_CaleDefeat:
	.string "És clar que he perdut!\n"
	.string "Porto coses a les dues mans!$"

Route121_Text_CalePostBattle:
	.string "He comprat massa coses a\n"
	.string "les GALERIES CALAGUA.\p"
	.string "És carretera amunt d'aquí.\n"
	.string "M'agradaria tenir una BOSSA com la teva.$"

Route121_Text_MylesIntro:
	.string "No hi ha res que m'agradi més que\n"
	.string "mirar els POKéMON d'altres!$"

Route121_Text_MylesDefeat:
	.string "Super impressionant!$"

Route121_Text_MylesPostBattle:
	.string "Són genials, els teus POKéMON!\n"
	.string "Com els cries?$"

Route121_Text_PatIntro:
	.string "Vull que tothom vegi els POKéMON\n"
	.string "que he criat!$"

Route121_Text_PatDefeat:
	.string "Uau!\n"
	.string "Espectacular!$"

Route121_Text_PatPostBattle:
	.string "Crio cada POKéMON amb el mateix amor\n"
	.string "i cura--no tinc favorits.$"

Route121_Text_MarcelIntro:
	.string "Els meus POKéMON mai han tastat la derrota!\n"
	.string "A la pròxima victòria, els inscriuré\n"
	.string "a CONCURSOS.$"

Route121_Text_MarcelDefeat:
	.string "Oh, què ha passat aquí?$"

Route121_Text_MarcelPostBattle:
	.string "Potser hauré d'entrenar la colla una mica més\n"
	.string "abans d'entrar a cap CONCURS.$"

Route123_Text_WendyIntro:
	.string "Vols determinar com de fort ets?\n"
	.string "Jo seré la prova!$"

Route123_Text_WendyDefeat:
	.string "Has aprovat amb nota!$"

Route123_Text_WendyPostBattle:
	.string "Vèncer fins i tot a mi…\n"
	.string "La teva força és meravellosa!$"

Route123_Text_BraxtonIntro:
	.string "Sembla que tens una gran col·lecció\n"
	.string "de MEDALLES DE GIMN.\p"
	.string "Deixa'm veure si realment mereixes\n"
	.string "aquestes MEDALLES!$"

Route123_Text_BraxtonDefeat:
	.string "Oh, les mereixes, sens dubte!$"

Route123_Text_BraxtonPostBattle:
	.string "Has deixat les teves MEDALLES orgulloses\n"
	.string "en aquest combat!$"

Route123_Text_VioletIntro:
	.string "Diuen que els bons moments estan\n"
	.string "plens de bones aromes.$"

Route123_Text_VioletDefeat:
	.string "Oh…\n"
	.string "Oloro l'amarg aroma de la desgràcia…$"

Route123_Text_VioletPostBattle:
	.string "El jardí del MESTRE BAIES està ple\n"
	.string "de fragàncies reconfortants.$"

Route123_Text_CameronIntro:
	.string "Ser psíquic és qüestió de voluntat.\p"
	.string "M'he convençut de no perdre contra\n"
	.string "ningú. Això em fa fort!$"

Route123_Text_CameronDefeat:
	.string "Em sento trist…$"

Route123_Text_CameronPostBattle:
	.string "Ser psíquic és qüestió de voluntat.\n"
	.string "Pensava que no perdria contra tu…$"

Route123_Text_CameronRegister:
	.string "Ho sento!\n"
	.string "Tu i jo lluitarem de nou!\l"
	.string "No puc dir si guanyaré, però…\p"
	.string "Deixa'm veure el teu POKéNAV.$"

Route123_Text_CameronRematchIntro:
	.string "M'he convençut que no perdré més.\n"
	.string "Això em fa fort!$"

Route123_Text_CameronRematchDefeat:
	.string "Em sento trist…$"

Route123_Text_CameronPostRematch:
	.string "Hauria d'entrenar al MT. PIRA…\n"
	.string "Mai et venceré així…$"

Route123_Text_JackiIntro:
	.string "No t'alegris massa si els teus POKéMON\n"
	.string "desenvolupan poders psíquics.\p"
	.string "Has de refinar aquests poders per\n"
	.string "fer-los realment útils.$"

Route123_Text_JackiDefeat:
	.string "Aclaparat!$"

Route123_Text_JackiPostBattle:
	.string "Tots tenim poders psíquics.\n"
	.string "Només hem oblidat com usar-los.$"

Route123_Text_JackiRegister:
	.string "M'agradaria enfrontar-te de nou.\n"
	.string "Et sembla bé?$"

Route123_Text_JackiRematchIntro:
	.string "Has despertat els poders psíquics\n"
	.string "dins teu?$"

Route123_Text_JackiRematchDefeat:
	.string "Impressionant!$"

Route123_Text_JackiPostRematch:
	.string "El teu poder amb els POKéMON…\n"
	.string "Això podria ser un poder psíquic també.$"

Route123_Text_MiuIntro:
	.string "MIU: Hola, ENTRENADOR. Espero que els teus\n"
	.string "POKéMON no plorin quan perdin.$"

Route123_Text_MiuDefeat:
	.string "MIU: Oh-oh, hem perdut.$"

Route123_Text_MiuPostBattle:
	.string "MIU: ENTRENADOR, els teus POKéMON són\n"
	.string "forts perquè sou amics.$"

Route123_Text_MiuNotEnoughMons:
	.string "MIU: No és divertit lluitar si no\n"
	.string "tens dos POKéMON.$"

Route123_Text_YukiIntro:
	.string "YUKI: D'acord!\n"
	.string "Vencerem els POKéMON de l'ENTRENADOR!$"

Route123_Text_YukiDefeat:
	.string "YUKI: Oh-oh, hem perdut.$"

Route123_Text_YukiPostBattle:
	.string "YUKI: Per què ets tan fort?\n"
	.string "Mai havíem perdut abans.$"

Route123_Text_YukiNotEnoughMons:
	.string "YUKI: No és divertit lluitar si no\n"
	.string "tens dos POKéMON.$"

Route123_Text_KindraIntro:
	.string "MT. PIRA…\n"
	.string "On els esperits dels POKéMON dormen…\l"
	.string "Els teus POKéMON dormiran?$"

Route123_Text_KindraDefeat:
	.string "Desbordant de vitalitat…$"

Route123_Text_KindraPostBattle:
	.string "MT. PIRA…\n"
	.string "On els esperits dels POKéMON dormen…\p"
	.string "Ha de desbordar amb un poder que\n"
	.string "calma els esperits…$"

Route123_Text_FernandoIntro:
	.string "T'apagaré els llums mentre\n"
	.string "arrenco amb aquesta cançó!$"

Route123_Text_FernandoDefeat:
	.string "Ei, para!\n"
	.string "Encara tocava la intro!$"

Route123_Text_FernandoPostBattle:
	.string "Ets rock sòlid.\n"
	.string "M'agradaria escriure una cançó sobre tu.$"

Route123_Text_FernandoRegister:
	.string "El proper cop, escolta\n"
	.string "la cançó sencera, vols?$"

Route123_Text_FernandoRematchIntro:
	.string "Avui és el dia que ho faré!\n"
	.string "T'apagaré els llums abans\n"
	.string "d'acabar de cantar la meva cançó!$"

Route123_Text_FernandoRematchDefeat:
	.string "Ei, para!\n"
	.string "Ni tan sols he arribat a la tornada!$"

Route123_Text_FernandoPostRematch:
	.string "Pensava que estaries tan captivat\n"
	.string "per la meva cançó que perdries.$"

Route123_Text_DavisIntro:
	.string "Aquest és el meu increïble POKéMON BICHO!\n"
	.string "El meu germà gran me'l va aconseguir.$"

Route123_Text_DavisDefeat:
	.string "Buaaah!\n"
	.string "Ets dolent!$"

Route123_Text_DavisPostBattle:
	.string "No li diguis al meu germà que he perdut.\n"
	.string "Ho has de mantenir en secret!$"

Route123_Text_JazmynIntro:
	.string "La meva confiança augmentarà\n"
	.string "vencent algú evidentment fort!$"

Route123_Text_JazmynDefeat:
	.string "Adéu a la meva confiança…$"

Route123_Text_JazmynPostBattle:
	.string "Diuen que no pots jutjar una persona\n"
	.string "per l'aparença.\p"
	.string "Però sovint, el seu aspecte no menteix…$"

Route123_Text_FrederickIntro:
	.string "Hola, nen!\n"
	.string "Tens una estona?$"

Route123_Text_FrederickDefeat:
	.string "Ah, un nen molt capaç!\n"
	.string "Deixa'm contribuir a la teva paga.$"

Route123_Text_FrederickPostBattle:
	.string "Contribuir a la teva paga?\n"
	.string "No era prou amb els diners del premi?$"

Route123_Text_AlbertoIntro:
	.string "T'he de dir que els POKéMON OCELL\n"
	.string "són la meva obsessió!\p"
	.string "Els ocells són genials!\n"
	.string "Són els millors!$"

Route123_Text_AlbertoDefeat:
	.string "Fins i tot en la derrota, els POKéMON OCELL són genials!$"

Route123_Text_AlbertoPostBattle:
	.string "Recullo plomes de POKéMON OCELL que\n"
	.string "es dispersen durant els combats.\p"
	.string "Faré un barret amb\n"
	.string "plomes de POKéMON OCELL.$"

Route123_Text_EdIntro:
	.string "Quan no hi ha ENTRENADORS a prop,\n"
	.string "deixo que els meus POKéMON lluitin entre ells.\l"
	.string "Els observo.$"

Route123_Text_EdDefeat:
	.string "M'agraden força els teus POKéMON.$"

Route123_Text_EdPostBattle:
	.string "Hehe, et robo les idees de combat!\n"
	.string "Crec que em faran millor.$"

Route123_Text_JonasIntro:
	.string "He parat una emboscada, i un ENTRENADOR\n"
	.string "ha caigut a la meva trampa!$"

Route123_Text_JonasDefeat:
	.string "Si no perds, com se suposa que\n"
	.string "em divertiré jugant a ninjas?$"

Route123_Text_JonasPostBattle:
	.string "Pararé una emboscada a un ENTRENADOR\n"
	.string "que sembli més feble el proper cop.$"

Route123_Text_KayleyIntro:
	.string "Acabo de comprar aquest paraigua.\n"
	.string "La meva monor hauria d'haver pujat un terç!$"

Route123_Text_KayleyDefeat:
	.string "Ets millor que jo unes\n"
	.string "cinc vegades!$"

Route123_Text_KayleyPostBattle:
	.string "Usar accessoris efectivament és\n"
	.string "el secret de l'atractiu de moda.$"

Route124_Text_SpencerIntro:
	.string "Ei, t'has perdut al mar?\p"
	.string "Si pots vèncer els meus POKéMON,\n"
	.string "et puc servir de pilot.$"

Route124_Text_SpencerDefeat:
	.string "He perdut el rumb en batalla!$"

Route124_Text_SpencerPostBattle:
	.string "Molta gent perd el rumb al mar.\p"
	.string "Si ets d'aquests, hauries de consultar\n"
	.string "el MAPA del POKéNAV.$"

Route124_Text_RolandIntro:
	.string "Hm! Vas muntant un POKéMON en lloc\n"
	.string "de nedar tu mateix…\p"
	.string "Tinc enveja!$"

Route124_Text_RolandDefeat:
	.string "Oh!\n"
	.string "No puc…$"

Route124_Text_RolandPostBattle:
	.string "Em refrredo…\n"
	.string "He estat massa temps a l'aigua…\p"
	.string "M'agradaria poder muntar un POKéMON com tu…$"

Route124_Text_JennyIntro:
	.string "Si només sures al mar\n"
	.string "així, els POKéMON vénen a jugar.$"

Route124_Text_JennyDefeat:
	.string "Oh, ximple.\n"
	.string "He anat i he perdut.$"

Route124_Text_JennyPostBattle:
	.string "Mentre nedava, he notat que alguns\n"
	.string "POKéMON ataquen, i altres només miren.\p"
	.string "Suposo que els POKéMON tenen les seves\n"
	.string "pròpies personalitats.$"

Route124_Text_JennyRegister:
	.string "És només un caprici, però potser et faré\n"
	.string "registrar-me al teu POKéNAV.$"

Route124_Text_JennyRematchIntro:
	.string "Si només sures al mar així,\n"
	.string "els ENTRENADORS et desafien!$"

Route124_Text_JennyRematchDefeat:
	.string "Què estrany…\n"
	.string "He perdut de nou…$"

Route124_Text_JennyPostRematch:
	.string "Això no té res a veure amb res,\n"
	.string "però potser visitaré la CASA TRUCS.$"

Route124_Text_GraceIntro:
	.string "M'estic avorrrint de nedar…\n"
	.string "Què tal un combat?$"

Route124_Text_GraceDefeat:
	.string "No tenia ni idea que fossis\n"
	.string "tan fort!$"

Route124_Text_GracePostBattle:
	.string "Tot l'esforç que has posat deu haver-te\n"
	.string "fet tan fort.$"

Route124_Text_ChadIntro:
	.string "Fufufufu… Busseig profund sota l'aigua\n"
	.string "per anar sota cobertura.\l"
	.string "Sondejar les profunditats és on excel·leixo!$"

Route124_Text_ChadDefeat:
	.string "Glub, glub, glub…\n"
	.string "M'enfonso…$"

Route124_Text_ChadPostBattle:
	.string "Tinc informació fiable que hi ha\n"
	.string "un punt de BUSSEIG per aquí.\p"
	.string "Em dóna ganes d'anar a les\n"
	.string "profunditats de nou…$"

Route124_Text_LilaIntro:
	.string "LILA: Ai…\p"
	.string "Aquí estic al mar, però qui m'acompanya?\n"
	.string "El meu germanet!\p"
	.string "Lluitem perquè no hagi de pensar\n"
	.string "en això!$"

Route124_Text_LilaDefeat:
	.string "LILA: ROY! És culpa teva que hem perdut!\n"
	.string "T'espera una bronca després!$"

Route124_Text_LilaPostBattle:
	.string "LILA: Ai…\p"
	.string "Si no fos el meu germanet\n"
	.string "al meu costat, sinó un xicot maco…$"

Route124_Text_LilaNotEnoughMons:
	.string "LILA: Penses lluitar contra nosaltres?\n"
	.string "No sense tenir dos POKéMON.$"

Route124_Text_RoyIntro:
	.string "ROY: La meva germana gran és dura amb POKéMON!\p"
	.string "No ploris quan perdis!$"

Route124_Text_RoyDefeat:
	.string "ROY: Oh-oh…\n"
	.string "La meva germana gran em renyarà…$"

Route124_Text_RoyPostBattle:
	.string "ROY: La meva germana gran fa molta por\n"
	.string "quan s'enfada.\p"
	.string "Per això no té xicot.$"

Route124_Text_LilaRoyRegister:
	.string "ROY: Lluitaràs amb nosaltres de nou?\n"
	.string "Però ves amb calma el proper cop, d'acord?$"

Route124_Text_RoyNotEnoughMons:
	.string "ROY: Volies lluitar contra nosaltres?\n"
	.string "Porta dos POKéMON, doncs.$"

Route124_Text_LilaRematchIntro:
	.string "LILA: Ai…\p"
	.string "Aquí estic al mar, però qui m'acompanya?\n"
	.string "El meu germanet!\p"
	.string "Oh, hola, fa temps. Lluitem perquè\n"
	.string "no hagi de pensar en coses!$"

Route124_Text_LilaRematchDefeat:
	.string "LILA: ROY!\n"
	.string "És culpa teva que hem perdut de nou!\p"
	.string "Tindrem una sessió d'entrenament després!$"

Route124_Text_LilaPostRematch:
	.string "LILA: Ai…\p"
	.string "Si tingués un xicot maco, venceríem\n"
	.string "a qualsevol amb combinacions precioses…$"

Route124_Text_LilaRematchNotEnoughMons:
	.string "LILA: Penses lluitar contra nosaltres?\n"
	.string "No sense tenir dos POKéMON.$"

Route124_Text_RoyRematchIntro:
	.string "ROY: Si perdem, me la carregaré.\n"
	.string "Hi aniré totalment a sac!$"

Route124_Text_RoyRematchDefeat:
	.string "ROY: Oh-oh…\n"
	.string "La meva germana gran em tornarà a renyar.$"

Route124_Text_RoyPostRematch:
	.string "ROY: La meva germana gran fa molta por\n"
	.string "quan s'enfada.\p"
	.string "Em farà entrenar molt\n"
	.string "dur amb POKéMON després…$"

Route124_Text_RoyRematchNotEnoughMons:
	.string "ROY: Volies lluitar contra nosaltres?\n"
	.string "Porta dos POKéMON, doncs.$"

Route124_Text_DeclanIntro:
	.string "Aquí estic nedant sol\n"
	.string "en aquest ampli i bonic mar.\p"
	.string "No hi ha altra paraula.\n"
	.string "Això és patètic!$"

Route124_Text_DeclanDefeat:
	.string "Em sento trist.\n"
	.string "Trist com el cel…$"

Route124_Text_DeclanPostBattle:
	.string "Hauria de parlar amb NEDADORES\n"
	.string "i convidar-les a una llarga nedada.$"

Route124_Text_IsabellaIntro:
	.string "No perdré contra cap\n"
	.string "ENTRENADOR surfista.$"

Route124_Text_IsabellaDefeat:
	.string "Només tinc suor als ulls!\n"
	.string "No estic plorant!$"

Route124_Text_IsabellaPostBattle:
	.string "Pots trobar fragments de colors\n"
	.string "bonics de coses per aquí.$"

Route125_Text_NolenIntro:
	.string "T'he sentit apropar-te, així que\n"
	.string "m'he quedat esperant-te!$"

Route125_Text_NolenDefeat:
	.string "Em rendeixo!$"

Route125_Text_NolenPostBattle:
	.string "El so viatja més ràpid a l'aigua\n"
	.string "que a través de l'aire.$"

Route125_Text_StanIntro:
	.string "Ei, tu!\n"
	.string "Mira els meus dolços POKéMON!$"

Route125_Text_StanDefeat:
	.string "He fracassat…$"

Route125_Text_StanPostBattle:
	.string "Em va fascinar l'encant de HORSEA,\n"
	.string "així que vaig començar a nedar també.$"

Route125_Text_TanyaIntro:
	.string "Estic cansat de nedar.\n"
	.string "Et ve de gust lluitar amb mi?$"

Route125_Text_TanyaDefeat:
	.string "Ets massa!$"

Route125_Text_TanyaPostBattle:
	.string "Uf…\n"
	.string "Cap on és ALGALIA?$"

Route125_Text_SharonIntro:
	.string "T'agradaria enfrontar-te als POKéMON\n"
	.string "tipus AIGUA que he criat?$"

Route125_Text_SharonDefeat:
	.string "He perdut…$"

Route125_Text_SharonPostBattle:
	.string "El teu poder… Ets l'autèntic.\n"
	.string "Estic impressionada!$"

Route125_Text_ErnestIntro:
	.string "Eip! Sóc un MARINER fort i dur!\n"
	.string "He travessat els mars del món!$"

Route125_Text_ErnestDefeat:
	.string "Gwrroooar!\n"
	.string "No he pogut guanyar!$"

Route125_Text_ErnestPostBattle:
	.string "La marea puja i baixa dins de la\n"
	.string "COVA ARENA.\p"
	.string "Per cert, són unes sis hores de\n"
	.string "marea alta a marea baixa. Ho sabies?$"

Route125_Text_ErnestRegister:
	.string "Registra'm al teu POKéNAV,\n"
	.string "i t'explicaré alguna cosa bona.$"

Route125_Text_ErnestRematchIntro:
	.string "Ja és hora de cobrar-me la revenja!\n"
	.string "Vinga, lluitem!$"

Route125_Text_ErnestRematchDefeat:
	.string "No he pogut guanyar!\n"
	.string "Definitivament no he pogut guanyar!$"

Route125_Text_ErnestRematchPostBattle:
	.string "La COVA ARENA…\p"
	.string "Hi ha llocs on pots i no pots\n"
	.string "arribar depenent de la pujada i baixada\l"
	.string "de la marea.\p"
	.string "Per cert, són unes sis hores de\n"
	.string "marea alta a marea baixa. No ho oblidis!$"

Route125_Text_KimIntro:
	.string "KIM: Un vell graciós viu a la\n"
	.string "COVA ARENA. Algú m'ho va dir.\l"
	.string "Tu també vas a veure'l?$"

Route125_Text_KimDefeat:
	.string "KIM: Pensava que guanyaríem.$"

Route125_Text_KimPostBattle:
	.string "KIM: Un vell graciós viu a la\n"
	.string "COVA ARENA, oi?\p"
	.string "Anem a veure'l, IRIS!$"

Route125_Text_KimNotEnoughMons:
	.string "KIM: No, no, no! Necessites dos POKéMON,\n"
	.string "o no val!$"

Route125_Text_IrisIntro:
	.string "IRIS: KIM, em pots dir què busquem\n"
	.string "aquí fora?$"

Route125_Text_IrisDefeat:
	.string "IRIS: Oh, hem estat a punt.$"

Route125_Text_IrisPostBattle:
	.string "IRIS: KIM, de veritat entrarem a\n"
	.string "la COVA ARENA?\l"
	.string "Ens mullarem molt.$"

Route125_Text_IrisNotEnoughMons:
	.string "IRIS: Oh, mai podríem fer\n"
	.string "res com un combat de 2 contra 1.$"

Route125_Text_PresleyIntro:
	.string "Per què un ORNITÒLEG com jo\n"
	.string "vindria al mar?$"

Route125_Text_PresleyDefeat:
	.string "D'acord.\n"
	.string "T'explicaré per què sóc aquí.$"

Route125_Text_PresleyPostBattle:
	.string "He posat un missatge en una ampolla i l'he\n"
	.string "llançat al mar.\p"
	.string "Segur que una NEDADORA\n"
	.string "el trobarà!$"

Route125_Text_AuronIntro:
	.string "Ei! Eres tu qui llançava escombraries\n"
	.string "al mar?$"

Route125_Text_AuronDefeat:
	.string "Oh, no llançaves escombraries\n"
	.string "al mar.$"

Route125_Text_AuronPostBattle:
	.string "He trobat una ampolla lletja surant\n"
	.string "a les onades abans.\p"
	.string "M'enfada que algú\n"
	.string "contamini el mar!$"

Route126_Text_BarryIntro:
	.string "Nedar és un entrenament de cos sencer!\n"
	.string "Et posaràs en forma!$"

Route126_Text_BarryDefeat:
	.string "Ho admeto!\n"
	.string "Tu guanyes!$"

Route126_Text_BarryPostBattle:
	.string "Gràcies a la meva rutina de natació diària…\n"
	.string "Mira! Delecta't amb aquest físic!$"

Route126_Text_DeanIntro:
	.string "Aquesta imponent muntanya blanca de roca\n"
	.string "és ARRECÍPOLIS.$"

Route126_Text_DeanDefeat:
	.string "M'han acabat?$"

Route126_Text_DeanPostBattle:
	.string "No puc trobar l'entrada a\n"
	.string "ARRECÍPOLIS. On deu ser?$"

Route126_Text_NikkiIntro:
	.string "Ufufufufu!\n"
	.string "Sóc una sirena!$"

Route126_Text_NikkiDefeat:
	.string "La meva fantasia ha esclatat com una bombolla!\n"
	.string "Blub, blub, blub…$"

Route126_Text_NikkiPostBattle:
	.string "M'has destrossat… Vull desaparèixer\n"
	.string "en una onada de desesperació…$"

Route126_Text_BrendaIntro:
	.string "Hola, nen!\n"
	.string "Vols un combat amb mi?$"

Route126_Text_BrendaDefeat:
	.string "Oh, nooooo!$"

Route126_Text_BrendaPostBattle:
	.string "M'encanta jugar amb POKéMON al mar\n"
	.string "d'aquesta manera!$"

Route126_Text_PabloIntro:
	.string "Mira aquest cos esculpit!\n"
	.string "Estic més definit que un CINTURÓ NEGRE!$"

Route126_Text_PabloDefeat:
	.string "Ups! Massa fort!\n"
	.string "No està malament! Gens malament!$"

Route126_Text_PabloPostBattle:
	.string "Perdre contra tu m'ha estimulat els sentits!\n"
	.string "M'entrenaré a mi i als meus POKéMON més dur!$"

Route126_Text_PabloRegister:
	.string "Sí, no estàs gens malament!\n"
	.string "M'agradaria conèixer-te més!$"

Route126_Text_PabloRematchIntro:
	.string "Mira aquest cos bonic!\n"
	.string "Tinc més bona forma que un NEDADOR!$"

Route126_Text_PabloRematchDefeat:
	.string "Ups! Realment massa fort!\n"
	.string "No està malament! Gens malament!$"

Route126_Text_PabloPostRematch:
	.string "M'entrenaré encara més dur!\n"
	.string "Ets un gran motivador!\l"
	.string "Has de tornar!$"

Route126_Text_LeonardoIntro:
	.string "L'any passat no sabia ni nedar,\n"
	.string "però ara sóc un NEDADOR decent.\p"
	.string "Crec que ara sóc capaç de tot.$"

Route126_Text_LeonardoDefeat:
	.string "Uf, ser cobdiciós no m'ha\n"
	.string "servit de res.$"

Route126_Text_LeonardoPostBattle:
	.string "Si practiques alguna cosa,\n"
	.string "milloraràs.\p"
	.string "Ets jove--no tinguis por de\n"
	.string "provar tot tipus de coses!$"

Route126_Text_IsobelIntro:
	.string "Si et puja aigua de mar pel nas,\n"
	.string "no és horrible?$"

Route126_Text_IsobelDefeat:
	.string "Ack! Tu…\n"
	.string "Glub!$"

Route126_Text_IsobelPostBattle:
	.string "Ooh, m'he ofegat amb una mica d'aigua!\n"
	.string "És amarga! És salada!!$"

Route126_Text_SiennaIntro:
	.string "Hi poso tot el cor\n"
	.string "en això!$"

Route126_Text_SiennaDefeat:
	.string "Tu tenies més cor!$"

Route126_Text_SiennaPostBattle:
	.string "Necessito refredar-me ara…\n"
	.string "Crec que faré busseig.$"

Route127_Text_CamdenIntro:
	.string "Ho veig a la teva cara.\n"
	.string "Em vols desafiar.$"

Route127_Text_CamdenDefeat:
	.string "Awawawawawa…$"

Route127_Text_CamdenPostBattle:
	.string "Un combat ben jugat em deixa\n"
	.string "fresc i serè.$"

Route127_Text_DonnyIntro:
	.string "Tens un rival contra qui\n"
	.string "odis perdre?$"

Route127_Text_DonnyDefeat:
	.string "Arrrgh!\n"
	.string "Odio perdre!$"

Route127_Text_DonnyPostBattle:
	.string "Si tens un rival, no tens la sensació\n"
	.string "que has de seguir millorant?$"

Route127_Text_JonahIntro:
	.string "A través de la pesca, he assolit\n"
	.string "un estat de serenitat calmada…\p"
	.string "Si us plau, deixa'm demostrar-ho…$"

Route127_Text_JonahDefeat:
	.string "Tot i que he perdut, el meu cor\n"
	.string "roman calmat…$"

Route127_Text_JonahPostBattle:
	.string "No importa que no atrapi res.\n"
	.string "El fil roman a l'aigua…$"

Route127_Text_HenryIntro:
	.string "Ups! No em diguis que he enganxat\n"
	.string "un POKéMON que fa SURF?$"

Route127_Text_HenryDefeat:
	.string "No puc seguir el ritme!$"

Route127_Text_HenryPostBattle:
	.string "Seria un problema si enganxés\n"
	.string "el teu POKéMON dur!$"

Route127_Text_RogerIntro:
	.string "Bé, ei! Aquest és un combat entre\n"
	.string "un fan POKéMON i un aficionat a la pesca!$"

Route127_Text_RogerDefeat:
	.string "No! El meu fil està tot embolicat!\n"
	.string "S'ha acabat la festa!$"

Route127_Text_RogerPostBattle:
	.string "El meu fil de pesca balla!\n"
	.string "El tango embolicat! Hahaha, grrr!$"

Route127_Text_AidanIntro:
	.string "Els POKéMON OCELL tenen excel·lent visió.\n"
	.string "Detecten preses des de grans altures.$"

Route127_Text_AidanDefeat:
	.string "Uf… Em rendeixo.$"

Route127_Text_AidanPostBattle:
	.string "Hi ha molts punts de busseig\n"
	.string "al mar d'aquí.\p"
	.string "Es poden detectar fàcilment des del cel\n"
	.string "pel seu color més fosc.$"

Route127_Text_KojiIntro:
	.string "Corre descalç.\n"
	.string "Això endurir-te les plantes dels peus!$"

Route127_Text_KojiDefeat:
	.string "Ai!\n"
	.string "M'ha entrat un còdol sota una ungla!$"

Route127_Text_KojiPostBattle:
	.string "Anar descalç és genial.\n"
	.string "Però les teves SABATES CORREDORES també molen.$"

Route127_Text_KojiRegister:
	.string "Això és el que faig a la gent que em venç!\n"
	.string "Espero que puguem repetir-ho.$"

Route127_Text_KojiRematchIntro:
	.string "Encara corro descalç cada dia.\n"
	.string "Les meves plantes són dures!$"

Route127_Text_KojiRematchDefeat:
	.string "Ai!\n"
	.string "Els còdols s'han clavat als meus arcs!$"

Route127_Text_KojiPostRematch:
	.string "Vols anar descalç una estona?\n"
	.string "Així puc provar les teves SABATES CORREDORES?$"

Route127_Text_AthenaIntro:
	.string "Hauríem de tenir un combat\n"
	.string "lent i metòdic.$"

Route127_Text_AthenaDefeat:
	.string "No m'has donat l'oportunitat\n"
	.string "de fer cap estratègia.$"

Route127_Text_AthenaPostBattle:
	.string "Quan estic envoltada del mar blau\n"
	.string "i el cel, sembla que el temps s'alenteix.$"

Route128_Text_IsaiahIntro:
	.string "COLOSALIA encara està molt\n"
	.string "llunyana…$"

Route128_Text_IsaiahDefeat:
	.string "La meva primera victòria sembla\n"
	.string "estar lluny, també…$"

Route128_Text_IsaiahPostBattle:
	.string "Tota la meva vida ha anat de perdre,\n"
	.string "però mai em rendiré!$"

Route128_Text_IsaiahRegister:
	.string "Sé que ara no sóc bo, però crec\n"
	.string "que eventualment puc guanyar.\p"
	.string "Si us plau, registra'm al teu POKéNAV.$"

Route128_Text_IsaiahRematchIntro:
	.string "Encara em sento bé. Seguiré\n"
	.string "nadant cap a COLOSALIA.$"

Route128_Text_IsaiahRematchDefeat:
	.string "Encara no he tastat la primera victòria…$"

Route128_Text_IsaiahPostRematch:
	.string "Eventualment arribaré a COLOSALIA\n"
	.string "on eventualment puc guanyar…$"

Route128_Text_KatelynIntro:
	.string "Has de nedar, anar en bici, i després córrer\n"
	.string "una marató en un triatló.\p"
	.string "És una cursa esgotadora que consisteix\n"
	.string "en tres proves.$"

Route128_Text_KatelynDefeat:
	.string "Un combat POKéMON també és esgotador…$"

Route128_Text_KatelynPostBattle:
	.string "Després he d'anar en BICI, però…\n"
	.string "Estic a punt de llençar la tovallola…$"

Route128_Text_KatelynRegister:
	.string "Bé, tant val treure el millor\n"
	.string "d'això. M'agradaria la revenja algun dia.$"

Route128_Text_KatelynRematchIntro:
	.string "Un triatló és llarg. Però suposo que\n"
	.string "el camí per ser CAMPIÓ POKéMON\n"
	.string "també és llarg i esgotador.$"

Route128_Text_KatelynRematchDefeat:
	.string "Un combat POKéMON realment és dur\n"
	.string "i implacable…$"

Route128_Text_KatelynPostRematch:
	.string "Hauries de pensar seriosament en\n"
	.string "els desafiaments del CAMÍ VICTÒRIA.$"

Route128_Text_AlexaIntro:
	.string "Hem treballat tan dur per muntar\n"
	.string "un desafiament a la LLIGA POKéMON…\p"
	.string "No ens podem permetre perdre ara!$"

Route128_Text_AlexaDefeat:
	.string "Oh!\n"
	.string "Com pot haver passat això?!$"

Route128_Text_AlexaPostBattle:
	.string "Després de tot el que he fet per arribar,\n"
	.string "no em rendiré per un contratemps.$"

Route128_Text_RubenIntro:
	.string "No hi ha ENTRENADOR més fort que jo!$"

Route128_Text_RubenDefeat:
	.string "No pot ser!$"

Route128_Text_RubenPostBattle:
	.string "Probablement no hi ha ENTRENADOR\n"
	.string "més fort que tu!$"

Route128_Text_WayneIntro:
	.string "Vull visitar COLOSALIA, així que\n"
	.string "m'he atrapat un POKéMON que sap\n"
	.string "el moviment CASCADA per pujar les cascades.$"

Route128_Text_WayneDefeat:
	.string "Estic abatut!$"

Route128_Text_WaynePostBattle:
	.string "Ai, ximple!\p"
	.string "El meu POKéMON sap CASCADA, però\n"
	.string "no tinc la MEDALLA DEL GIMNÀS ARRECÍPOLIS!$"

Route128_Text_HarrisonIntro:
	.string "Sembles força dur.\n"
	.string "Em pregunto si puc guanyar?$"

Route128_Text_HarrisonDefeat:
	.string "Ai!\n"
	.string "Suposo que era impossible guanyar.$"

Route128_Text_HarrisonPostBattle:
	.string "Hi ha ENTRENADORS durs a dojo\n"
	.string "al voltant de COLOSALIA.\p"
	.string "Creus que estic fora del meu nivell?$"

Route128_Text_CarleeIntro:
	.string "La llum del sol sembla més forta\n"
	.string "en aquesta zona.$"

Route128_Text_CarleeDefeat:
	.string "No hi veia gaire bé per culpa\n"
	.string "de l'enlluernament del sol.$"

Route128_Text_CarleePostBattle:
	.string "Hauria de tornar aviat.\n"
	.string "Necessito tornar-me a posar protector solar.$"

Route129_Text_ChaseIntro:
	.string "Aquest és el meu primer triatló.\n"
	.string "Estic tens i nerviós!$"

Route129_Text_ChaseDefeat:
	.string "Wroooaaar!\n"
	.string "No he aconseguit guanyar!$"

Route129_Text_ChasePostBattle:
	.string "Si estic tot tens, no podré\n"
	.string "donar-ho tot.$"

Route129_Text_AllisonIntro:
	.string "Estic enmig d'un triatló,\n"
	.string "però clar, per què no lluitem?$"

Route129_Text_AllisonDefeat:
	.string "Estava segura que guanyaria!$"

Route129_Text_AllisonPostBattle:
	.string "Saps quina és la cosa més gran\n"
	.string "dels triatlons?\p"
	.string "Provar els límits de la teva pròpia\n"
	.string "força i resistència contra\n"
	.string "la Mare Natura!$"

Route129_Text_ReedIntro:
	.string "Ei, ei!\n"
	.string "Posem-nos-hi!$"

Route129_Text_ReedDefeat:
	.string "Vençut, estic vençut.\n"
	.string "Això és tot, acabat!$"

Route129_Text_ReedPostBattle:
	.string "No hi ha res per a un perdedor.\n"
	.string "És hora de tornar a casa.$"

Route129_Text_TishaIntro:
	.string "Quina pressa?\n"
	.string "Fem-ho amb calma.$"

Route129_Text_TishaDefeat:
	.string "Oh, vaja.\n"
	.string "Volia relaxar-me una mica més…$"

Route129_Text_TishaPostBattle:
	.string "No odies cometre errors quan\n"
	.string "vas amb pressa?\p"
	.string "Per això intento fer les coses\n"
	.string "a poc a poc.$"

Route129_Text_ClarenceIntro:
	.string "Fer surf no és tan fàcil com sembla,\n"
	.string "oi?$"

Route129_Text_ClarenceDefeat:
	.string "Guanyar segur que no és fàcil.$"

Route129_Text_ClarencePostBattle:
	.string "Tens la mirada posada en la LLIGA\n"
	.string "POKéMON? Segueix així!$"

Route130_Text_RodneyIntro:
	.string "Quina sorpresa! No esperava veure\n"
	.string "un ENTRENADOR al mar.\p"
	.string "Crec que hauríem de lluitar!$"

Route130_Text_RodneyDefeat:
	.string "Aquest nen és molt dur…$"

Route130_Text_RodneyPostBattle:
	.string "Els teus ulls tenen la mirada d'algú\n"
	.string "que ha experimentat durs desafiaments\n"
	.string "i ha guanyat. Et queda bé!$"

Route130_Text_KatieIntro:
	.string "Al mar blau profund,\n"
	.string "el meu cor blau destrossat troba\n"
	.string "consol entre les onades.$"

Route130_Text_KatieDefeat:
	.string "Com el vast mar blau,\n"
	.string "el món dels POKéMON abasta\n"
	.string "profunditats increïbles.$"

Route130_Text_KatiePostBattle:
	.string "Els nens del món somien\n"
	.string "amb ser algun dia\n"
	.string "el CAMPIÓ POKéMON.$"

Route130_Text_SantiagoIntro:
	.string "Surant al mar obert així…\n"
	.string "És tranquil.$"

Route130_Text_SantiagoDefeat:
	.string "Necessitava ser una mica menys tranquil!$"

Route130_Text_SantiagoPostBattle:
	.string "Nedar i lluitar així…\n"
	.string "Sóc un noi feliç…$"

Route131_Text_RichardIntro:
	.string "El mar bull de POKéMON.\n"
	.string "Nedar no és fàcil, t'ho dic.$"

Route131_Text_RichardDefeat:
	.string "Els POKéMON criats per ENTRENADORS\n"
	.string "són seriosament durs…$"

Route131_Text_RichardPostBattle:
	.string "Buf… Buf…\n"
	.string "Estic esgotat…\p"
	.string "Anar és fàcil. Tornar\n"
	.string "és la part difícil.\p"
	.string "Tindré energia per fer\n"
	.string "el viatge de tornada?$"

Route131_Text_HermanIntro:
	.string "El mar… El mar… El mar…\n"
	.string "El mar fins on arriben aquests ulls!\l"
	.string "Estic fart del mar!$"

Route131_Text_HermanDefeat:
	.string "Bleah!$"

Route131_Text_HermanPostBattle:
	.string "Estic avorrit del mar, però he de nedar.\p"
	.string "Sóc un nedador nat!\n"
	.string "Això és el que sóc.$"

Route131_Text_SusieIntro:
	.string "Ei, cielet, espera!\n"
	.string "Hauríem de lluitar, tu i jo!$"

Route131_Text_SusieDefeat:
	.string "Ets dur malgrat el teu\n"
	.string "aspected!$"

Route131_Text_SusiePostBattle:
	.string "Has vist un noi allà que es queixa\n"
	.string "que està avorrit del mar?\p"
	.string "Tot són paraules.\n"
	.string "Està perdudament enamorat del mar!$"

Route131_Text_KaraIntro:
	.string "Per què els homes estimen tant els\n"
	.string "banyadors?\p"
	.string "Tots em miren embadalits!$"

Route131_Text_KaraDefeat:
	.string "Estic fora del meu nivell!$"

Route131_Text_KaraPostBattle:
	.string "Potser no és el meu banyador el que fa\n"
	.string "que els homes mirin. Deu ser la meva bellesa!$"

Route131_Text_ReliIntro:
	.string "RELI: Treballarem junts com a germans\n"
	.string "per enfrontar-te!$"

Route131_Text_ReliDefeat:
	.string "RELI: No hem pogut guanyar tot i que\n"
	.string "hem treballat junts…$"

Route131_Text_ReliPostBattle:
	.string "RELI: La gent de PASSANÚVOLS estan\n"
	.string "junts amb el mar i els POKéMON des de\n"
	.string "que neixen.$"

Route131_Text_ReliNotEnoughMons:
	.string "RELI: No tens dos POKéMON?\n"
	.string "Aleshores no podem gaudir d'un combat.$"

Route131_Text_IanIntro:
	.string "IAN: Faig el meu millor junt amb\n"
	.string "la meva germana!$"

Route131_Text_IanDefeat:
	.string "IAN: He fet el meu millor amb la meva germana,\n"
	.string "però encara no hem pogut guanyar…$"

Route131_Text_IanPostBattle:
	.string "IAN: Saps que PASSANÚVOLS és\n"
	.string "una ciutat flotant?\p"
	.string "Així que, on sigui el mar,\n"
	.string "és part de PASSANÚVOLS!$"

Route131_Text_IanNotEnoughMons:
	.string "IAN: Si tens dos POKéMON,\n"
	.string "et desafiarem!$"

Route131_Text_TaliaIntro:
	.string "Si em pots vèncer, et donaré\n"
	.string "informació genial!$"

Route131_Text_TaliaDefeat:
	.string "Oh?\n"
	.string "He perdut?$"

Route131_Text_TaliaPostBattle:
	.string "Hi ha un lloc estrany a prop.\n"
	.string "Hi ha una torre enorme allà.\l"
	.string "Per què no hi fas una ullada?$"

Route131_Text_KevinIntro:
	.string "La gent de PASSANÚVOLS són\n"
	.string "gent pacífica.\p"
	.string "Mai s'enfaden.\n"
	.string "Això també va per mi.$"

Route131_Text_KevinDefeat:
	.string "Ups!$"

Route131_Text_KevinPostBattle:
	.string "Tch! …Oh, espera.\n"
	.string "No estic enfadat. Honestament!\p"
	.string "Però, noi, ets fort!\n"
	.string "Hahaha!$"

Route132_Text_GilbertIntro:
	.string "De petit sempre m'encostipava,\n"
	.string "però em vaig posar en forma\n"
	.string "quan vaig començar a nedar.$"

Route132_Text_GilbertDefeat:
	.string "Anhelo més poder…$"

Route132_Text_GilbertPostBattle:
	.string "Els ENTRENADORS viatgen pels camps i\n"
	.string "muntanyes, així que també deuen estar en forma.$"

Route132_Text_DanaIntro:
	.string "Intento no nedar on els corrents\n"
	.string "són massa forts.$"

Route132_Text_DanaDefeat:
	.string "Oh, si us plau, no!$"

Route132_Text_DanaPostBattle:
	.string "Si m'emporta el corrent, perdré\n"
	.string "tota la noció del lloc…$"

Route132_Text_RonaldIntro:
	.string "Guanyar o perdre, mai ho sabràs\n"
	.string "fins que ho provis!$"

Route132_Text_RonaldDefeat:
	.string "Waah!\n"
	.string "M'he enfonsat en la derrota!$"

Route132_Text_RonaldPostBattle:
	.string "Mai lluito quan sé que guanyaré.\n"
	.string "M'agrada lluitar al límit entre\n"
	.string "la victòria i la derrota!$"

Route132_Text_KiyoIntro:
	.string "Contemplo POKéMON 24 hores al dia.\n"
	.string "Com pots vèncer-me?$"

Route132_Text_KiyoDefeat:
	.string "Perdo.\n"
	.string "Admetré la derrota.$"

Route132_Text_KiyoPostBattle:
	.string "Urggh…\n"
	.string "Ets un fanàtic POKéMON, oi?\p"
	.string "Deus contemplar POKéMON 24 hores\n"
	.string "al dia, no?$"

Route132_Text_MakaylaIntro:
	.string "Sempre estic amb el meu marit,\n"
	.string "però puc guanyar fins i tot sense ell.$"

Route132_Text_MakaylaDefeat:
	.string "Oh, suposo que no era prou bona.$"

Route132_Text_MakaylaPostBattle:
	.string "Aquell jove d'allà s'assembla\n"
	.string "al meu marit quan era jove.\p"
	.string "Em fa enrojolar!$"

Route132_Text_JonathanIntro:
	.string "Algú m'ha estat mirant fixament.\n"
	.string "Eres tu?$"

Route132_Text_JonathanDefeat:
	.string "Uau!\n"
	.string "Això és força fort, sí!$"

Route132_Text_JonathanPostBattle:
	.string "No puc treure'm la sensació que\n"
	.string "algú em mira.\p"
	.string "No em puc concentrar!$"

Route132_Text_PaxtonIntro:
	.string "On deu haver anat la meva dona?\n"
	.string "Sempre estic amb ella.\l"
	.string "Em pregunto si puc guanyar sol.$"

Route132_Text_PaxtonDefeat:
	.string "Ah, veig que no he pogut\n"
	.string "guanyar sol al cap i a la fi.$"

Route132_Text_PaxtonPostBattle:
	.string "La meva dona deu estar buscant-me.\n"
	.string "Més val que la trobi de seguida.$"

Route132_Text_DarcyIntro:
	.string "M'agradava entrenar aquí sol.\n"
	.string "És horrible que hagi vingut tota aquesta gent!$"

Route132_Text_DarcyDefeat:
	.string "D'acord! No em queixaré que\n"
	.string "altra gent sigui aquí.$"

Route132_Text_DarcyPostBattle:
	.string "Suposo que puc fer parella amb aquell\n"
	.string "vell i desafiar l'altre equip.$"

Route133_Text_FranklinIntro:
	.string "Els corrents t'han portat aquí també?\n"
	.string "Això devia estar destinat.\l"
	.string "Lluitem!$"

Route133_Text_FranklinDefeat:
	.string "Fort!\n"
	.string "Massa!$"

Route133_Text_FranklinPostBattle:
	.string "Quina sort la meva que un ENTRENADOR\n"
	.string "dur com tu arribés aquí…\l"
	.string "Dec estar maleït…$"

Route133_Text_DebraIntro:
	.string "He portat una vida de pena i misèria…\n"
	.string "M'han abandonat, i aquí és on\n"
	.string "he anat a parar…$"

Route133_Text_DebraDefeat:
	.string "Una altra derrota…$"

Route133_Text_DebraPostBattle:
	.string "Una vida a la deriva…\n"
	.string "Ja no la vull més!$"

Route133_Text_LindaIntro:
	.string "Benvingut!\n"
	.string "T'estava esperant!$"

Route133_Text_LindaDefeat:
	.string "No! Si us plau!$"

Route133_Text_LindaPostBattle:
	.string "Un nen ENTRENADOR fort…\n"
	.string "Què molest!$"

Route133_Text_WarrenIntro:
	.string "Vull guanyar com tothom, però no\n"
	.string "criaré POKéMON com tothom.$"

Route133_Text_WarrenDefeat:
	.string "Maleïda sia!\n"
	.string "El meu mètode encara és massa fluix!$"

Route133_Text_WarrenPostBattle:
	.string "És molt més divertit fer les coses\n"
	.string "com jo vull que ser com tothom.\l"
	.string "Vull dir, és obvi!$"

Route133_Text_BeckIntro:
	.string "He vingut fins aquí amb els meus\n"
	.string "POKéMON OCELL.$"

Route133_Text_BeckDefeat:
	.string "Tu…\n"
	.string "Ets increïblement genial!$"

Route133_Text_BeckPostBattle:
	.string "M'agradaria tornar a ARBORADA,\n"
	.string "però també m'ha agradat aquest lloc.$"

Route133_Text_MollieIntro:
	.string "Dec haver lluitat milers\n"
	.string "de vegades. He perdut el compte.$"

Route133_Text_MollieDefeat:
	.string "Potser he perdut milers de vegades,\n"
	.string "però una derrota encara fa mal.$"

Route133_Text_MolliePostBattle:
	.string "Segueix així, jove. Perquè puguis\n"
	.string "ser com el meu marit i jo.$"

Route133_Text_ConorIntro:
	.string "Els joves estan massa contents d'anar\n"
	.string "amb el corrent. Estan sense direcció.$"

Route133_Text_ConorDefeat:
	.string "Tens un ferm sentit del propòsit.$"

Route133_Text_ConorPostBattle:
	.string "No deixis que altres et desviïn.\n"
	.string "No perdis la direcció a mesura que creixes.$"

Route134_Text_JackIntro:
	.string "Fins i tot els POKéMON que saben nedar\n"
	.string "són arrossegats pels corrents ràpids.$"

Route134_Text_JackDefeat:
	.string "Aiyeeeeh!$"

Route134_Text_JackPostBattle:
	.string "Crec que els POKéMON gaudeixen dels\n"
	.string "corrents ràpids d'aquestes zones.$"

Route134_Text_LaurelIntro:
	.string "Els meus LUVDISC busquen un combat\n"
	.string "divertit. T'hi uneixes?$"

Route134_Text_LaurelDefeat:
	.string "Uix!$"

Route134_Text_LaurelPostBattle:
	.string "Hi ha un col·leccionista que va\n"
	.string "darrere les ESCAMES de LUVDISC.$"

Route134_Text_AlexIntro:
	.string "D'acord! Ja hem descansat prou, colla!\n"
	.string "És hora d'un combat!$"

Route134_Text_AlexDefeat:
	.string "Esgotats de nou…$"

Route134_Text_AlexPostBattle:
	.string "Els meus POKéMON OCELL es cansen ràpid\n"
	.string "després d'un vol llarg…$"

Route134_Text_HitoshiIntro:
	.string "Ets un ENTRENADOR POKéMON.\n"
	.string "No calen paraules. Lluitem ara.$"

Route134_Text_HitoshiDefeat:
	.string "… … … … … …\n"
	.string "… … … … … …$"

Route134_Text_HitoshiPostBattle:
	.string "He estat jo qui t'ha desafiat, i tot i\n"
	.string "aix he perdut. Estic profundament avergonyit…$"

Route134_Text_AaronIntro:
	.string "La marea salvatge d'aquesta zona serveix\n"
	.string "per fer-nos més forts que mai.$"

Route134_Text_AaronDefeat:
	.string "Admet la derrota de bon grat.$"

Route134_Text_AaronPostBattle:
	.string "Tornarem a entrenar a\n"
	.string "CASCADA METEORS.\p"
	.string "Si vols, hauries d'anar-hi tu també.\n"
	.string "Definitivament t'endurir!$"

Route134_Text_KelvinIntro:
	.string "La-la nostra barca!\n"
	.string "La marea se l'ha emportat!$"

Route134_Text_KelvinDefeat:
	.string "Awawawawah!\n"
	.string "Si us plau, para! Si us plau!$"

Route134_Text_KelvinPostBattle:
	.string "Si no podem fer SURF, com se suposa\n"
	.string "que tornarem a casa?\p"
	.string "De fet, sé que un POKéMON esvaït\n"
	.string "encara pot fer SURF, però em sap greu.$"

Route134_Text_MarleyIntro:
	.string "Poden els teus POKéMON esquivar\n"
	.string "els nostres atacs ultraràpids?$"

Route134_Text_MarleyDefeat:
	.string "No sabia que existís tal tècnica!\n"
	.string "Ens has derrotat completament.$"

Route134_Text_MarleyPostBattle:
	.string "No he perdut la passió per la velocitat.\n"
	.string "M'esforçaré més.$"

Route134_Text_ReynaIntro:
	.string "Els meus POKéMON no poden ser derrotats\n"
	.string "fàcilment!$"

Route134_Text_ReynaDefeat:
	.string "Estàs broma!\n"
	.string "Explica'm com he perdut!$"

Route134_Text_ReynaPostBattle:
	.string "Haha!\n"
	.string "Has guanyat, d'acord!\p"
	.string "Tornaré a pujar enfrontant-me a\n"
	.string "ENTRENADORS que em trobi!$"

Route134_Text_HudsonIntro:
	.string "Escolta, has vist un altre MARINER\n"
	.string "per aquí?$"

Route134_Text_HudsonDefeat:
	.string "Això sí que és!$"

Route134_Text_HudsonPostBattle:
	.string "La nostra barca ha anat a la deriva.\p"
	.string "El meu company és un noi tímid, així que\n"
	.string "estic preocupat per ell.$"
