gTrickHouse_Mechadoll_Oddish::
	.string "ODDISH$"

gTrickHouse_Mechadoll_Poochyena::
	.string "POOCHYENA$"

gTrickHouse_Mechadoll_Taillow::
	.string "TAILLOW$"

gTrickHouse_Mechadoll_Azurill::
	.string "AZURILL$"

gTrickHouse_Mechadoll_Lotad::
	.string "LOTAD$"

gTrickHouse_Mechadoll_Wingull::
	.string "WINGULL$"

gTrickHouse_Mechadoll_Dustox::
	.string "DUSTOX$"

gTrickHouse_Mechadoll_Zubat::
	.string "ZUBAT$"

gTrickHouse_Mechadoll_Nincada::
	.string "NINCADA$"

gTrickHouse_Mechadoll_Ralts::
	.string "RALTS$"

gTrickHouse_Mechadoll_Zigzagoon::
	.string "ZIGZAGOON$"

gTrickHouse_Mechadoll_Slakoth::
	.string "SLAKOTH$"

gTrickHouse_Mechadoll_Poochyena2::
	.string "POOCHYENA$"

gTrickHouse_Mechadoll_Shroomish::
	.string "SHROOMISH$"

gTrickHouse_Mechadoll_Zigzagoon2::
	.string "ZIGZAGOON$"

gTrickHouse_Mechadoll_Poochyena3::
	.string "POOCHYENA$"

gTrickHouse_Mechadoll_Zubat2::
	.string "ZUBAT$"

gTrickHouse_Mechadoll_Carvanha::
	.string "CARVANHA$"

gTrickHouse_Mechadoll_BurnHeal::
	.string "ANTICREMADA$"

gTrickHouse_Mechadoll_HarborMail::
	.string "CARTA PORT$"

gTrickHouse_Mechadoll_SamePrice::
	.string "El mateix preu$"

gTrickHouse_Mechadoll_60Yen::
	.string "60 iens$"

gTrickHouse_Mechadoll_55Yen::
	.string "55 iens$"

gTrickHouse_Mechadoll_Nothing::
	.string "Res$"

gTrickHouse_Mechadoll_CostMore::
	.string "Costa més$"

gTrickHouse_Mechadoll_CostLess::
	.string "Costa menys$"

gTrickHouse_Mechadoll_SamePrice2::
	.string "El mateix preu$"

gTrickHouse_Mechadoll_Male::
	.string "Mascle$"

gTrickHouse_Mechadoll_Female::
	.string "Femella$"

gTrickHouse_Mechadoll_Neither::
	.string "Cap dels dos$"

gTrickHouse_Mechadoll_ElderlyMen::
	.string "Avis$"

gTrickHouse_Mechadoll_ElderlyLadies::
	.string "Àvies$"

gTrickHouse_Mechadoll_SameNumber::
	.string "El mateix nombre$"

gTrickHouse_Mechadoll_None::
	.string "Cap$"

gTrickHouse_Mechadoll_One::
	.string "Un$"

gTrickHouse_Mechadoll_Two::
	.string "Dos$"

gTrickHouse_Mechadoll_Two2::
	.string "Dos$"

gTrickHouse_Mechadoll_Three::
	.string "Tres$"

gTrickHouse_Mechadoll_Four::
	.string "Quatre$"

gTrickHouse_Mechadoll_Six::
	.string "Sis$"

gTrickHouse_Mechadoll_Seven::
	.string "Set$"

gTrickHouse_Mechadoll_Eight::
	.string "Vuit$"

gTrickHouse_Mechadoll_Six2::
	.string "Sis$"

gTrickHouse_Mechadoll_Seven2::
	.string "Set$"

gTrickHouse_Mechadoll_Eight2::
	.string "Vuit$"
