LilycoveCity_ContestLobby_Text_InterviewRequest:
	.string "Oh, hola! Has estat en un CONCURS\n"
	.string "POKéMON, oi?\l"
	.string "És fàcil de dir pels teus POKéMON.\p"
	.string "Sóc reporter. Estic treballant en una\n"
	.string "història sobre CONCURSOS POKéMON.\p"
	.string "Si em permets, estaries disposat a\n"
	.string "respondre algunes preguntes?$"

LilycoveCity_ContestLobby_Text_DescribeContest:
	.string "Oh, ho faràs?\n"
	.string "Gràcies.\p"
	.string "Breument, com descriuries el\n"
	.string "CONCURS en què acabes d'entrar?$"

LilycoveCity_ContestLobby_Text_WhatImageWhenYouHearX:
	.string "Ah, ja veig.\n"
	.string "És un comentari molt edificant.\p"
	.string "Es nota bé com va ser\n"
	.string "el CONCURS.\p"
	.string "Tinc una última pregunta.\p"
	.string "Quan sents la paraula “{STR_VAR_2}”,\n"
	.string "quina imatge et ve al cap?$"

LilycoveCity_ContestLobby_Text_ThatsAllForInterview:
	.string "Ja veig!\p"
	.string "Així que és així com t'imagines el\n"
	.string "concepte de “{STR_VAR_2}”.\p"
	.string "Gràcies!\n"
	.string "M'has donat bones idees.\p"
	.string "Crec que ara puc escriure una bona\n"
	.string "història sobre CONCURSOS POKéMON.\p"
	.string "Potser, només potser, aquesta història\n"
	.string "arribarà a la televisió.\l"
	.string "Espero que hi estiguis atent!$"

LilycoveCity_ContestLobby_Text_PleaseDoShareStoryWithMe:
	.string "Oh, quina llàstima…\p"
	.string "Bé, si trobes una bona història,\n"
	.string "si us plau comparteix-la amb mi.$"

LilycoveCity_ContestLobby_Text_LookingForwardToNextContest:
	.string "Estaré esperant el teu pròxim\n"
	.string "CONCURS POKéMON.$"

gTVBravoTrainerText00::
	.string "Sí!\n"
	.string "És l'hora de BRAVO ENTRENADOR!\p"
	.string "Avui, farem un perfil d'un POKéMON\n"
	.string "que pertany a {STR_VAR_1}.\p"
	.string "Aquest POKéMON té un rang {STR_VAR_3}\n"
	.string "en la Categoria {STR_VAR_2}.$"

gTVBravoTrainerText01::
	.string "Presentem {STR_VAR_2} el\n"
	.string "{STR_VAR_1}!\p"
	.string "El malnom {STR_VAR_2}…\p"
	.string "Fins i tot el malnom exhala un aire que\n"
	.string "proclama “{STR_VAR_3}”!$"

gTVBravoTrainerText02::
	.string "De tota manera, quan l'ENTRENADOR {STR_VAR_1}\n"
	.string "va inscriure el POKéMON en un CONCURS,\l"
	.string "vam aconseguir algunes cites apassionades\l"
	.string "sobre el company de confiança.$"

gTVBravoTrainerText03::
	.string "Preguntat sobre el CONCURS després,\n"
	.string "{STR_VAR_1} va respondre feliçment amb un\l"
	.string "gran somriure, “{STR_VAR_2}!”\p"
	.string "Bé, és clar, el POKéMON de {STR_VAR_1} va\n"
	.string "quedar en el número {STR_VAR_3} al CONCURS.\p"
	.string "Aquesta frase encaixa perfectament amb\n"
	.string "{STR_VAR_1} ara mateix, diria jo!$"

gTVBravoTrainerText04::
	.string "Preguntat sobre el CONCURS després,\n"
	.string "{STR_VAR_1} va respondre amb un toc\l"
	.string "d'amargor, “{STR_VAR_2}.”\p"
	.string "Bé, és clar, el POKéMON de {STR_VAR_1} va\n"
	.string "quedar en el número {STR_VAR_3} al CONCURS.\p"
	.string "La decepció de {STR_VAR_1} es nota\n"
	.string "ben clara, diria jo!$"

gTVBravoTrainerText05::
	.string "No t'agradaria saber què\n"
	.string "imagina {STR_VAR_1} que és {STR_VAR_2}?\p"
	.string "Ja ho crec que sí!\n"
	.string "Així que ho vam preguntar, és clar!\p"
	.string "La resposta és perfectament condensada:\n"
	.string "“{STR_VAR_3}!”\p"
	.string "Això és el que el concepte de {STR_VAR_2}\n"
	.string "representa per a {STR_VAR_1}!$"

gTVBravoTrainerText06::
	.string "L'últim moviment {STR_VAR_2} usat per\n"
	.string "el {STR_VAR_1} és totalment sobre\l"
	.string "“{STR_VAR_3}”!$"

gTVBravoTrainerText07::
	.string "Bravo, {STR_VAR_1}!\n"
	.string "Bravo, {STR_VAR_2}!\p"
	.string "Esperem poder veure com\n"
	.string "{STR_VAR_1} assoleix cotes encara més altes!\p"
	.string "Això és tot el temps que tenim!\n"
	.string "Fins la pròxima, adéu!$"

gTVBravoTrainerText08::
	.string "Presentem el {STR_VAR_1} de l'ENTRENADOR!$"

BattleFrontier_BattleTowerLobby_Text_InterviewRequest::
	.string "Hola! Ets l'ENTRENADOR que acaba de\n"
	.string "tenir un combat, oi?\p"
	.string "Estic recollint entrevistes d'ENTRENADORS\n"
	.string "de tot arreu.\p"
	.string "Puc aconseguir unes paraules teves sobre\n"
	.string "les teves impressions del combat?$"

BattleFrontier_BattleTowerLobby_Text_HowDidBattleTowerTurnOut::
	.string "Ho faràs? De veritat?\n"
	.string "Gràcies!\l"
	.string "Llavors, eh…\p"
	.string "Com han anat les coses a la\n"
	.string "TORRE BATALLA avui?\p"
	.string "Has quedat satisfet amb el combat?\n"
	.string "O estàs desontent?$"

BattleFrontier_BattleTowerLobby_Text_SorryWeDisturbedYou::
	.string "Oh…\n"
	.string "Perdona per molestar-te.\p"
	.string "Si us plau, dóna'ns una entrevista la\n"
	.string "pròxima vegada que visitis la TORRE BATALLA.$"

BattleFrontier_BattleTowerLobby_Text_ObviousYouHadGreatBattle::
	.string "Bé, és clar!\p"
	.string "Aquesta inconfusible mirada de satisfacció\n"
	.string "a la teva cara…\p"
	.string "És obvi que has tingut un gran\n"
	.string "combat.$"

BattleFrontier_BattleTowerLobby_Text_DifficultToMakeBattleTurnOutAsPlanned::
	.string "Oh, ja veig…\p"
	.string "Bé, certament és difícil fer que un\n"
	.string "combat surti exactament com es planeja.$"

BattleFrontier_BattleTowerLobby_Text_DescribeYourBattle::
	.string "Oh, oh, puc fer una pregunta més?\p"
	.string "Si haguessis de descriure les teves\n"
	.string "impressions sobre aquest combat amb\l"
	.string "una frase, quina seria?$"

BattleFrontier_BattleTowerLobby_Text_ThatsGreatLine::
	.string "Oh, això és impressionantment genial!\p"
	.string "Quina frase tan bona!\n"
	.string "Espero que et vagi genial la pròxima.\p"
	.string "Espero veure't de nou!$"

BattleFrontier_BattleTowerLobby_Text_SilentType::
	.string "Oh, ja veig…\p"
	.string "Tot i així, ser del tipus silenciós\n"
	.string "també mola, no?\p"
	.string "Espero que em donis l'oportunitat\n"
	.string "de compartir els teus pensaments de nou!$"

BattleFrontier_BattleTowerLobby_Text_LookingForwardToNextBattle::
	.string "Estaré esperant el teu\n"
	.string "pròxim combat!$"

BravoTrainerBattleTower_Text_Intro::
	.string "Sí!\n"
	.string "És l'hora de BRAVO ENTRENADOR!\p"
	.string "Avui, farem un perfil de {STR_VAR_1},\n"
	.string "que va acceptar el repte de la TORRE BATALLA!\p"
	.string "Per al repte, {STR_VAR_1} va inscriure\n"
	.string "un increïble {STR_VAR_2}.$"

BravoTrainerBattleTower_Text_NewRecord::
	.string "La parella va establir un nou rècord de\n"
	.string "{STR_VAR_2} victòries seguides en competició\l"
	.string "{STR_VAR_1}! Bravo, ENTRENADOR!$"

BravoTrainerBattleTower_Text_Lost::
	.string "El duo finalment va caure davant\n"
	.string "{STR_VAR_1} en el combat número {STR_VAR_2}.\l"
	.string "Bon intent, ENTRENADOR!\p"
	.string "Però, ei, és només mala sort topar amb\n"
	.string "{STR_VAR_1} tan aviat al repte.\p"
	.string "Vam demanar a l'ENTRENADOR impressions\n"
	.string "sobre el combat amb {STR_VAR_1}.$"

BravoTrainerBattleTower_Text_Won::
	.string "El duo ho va guanyar tot derrotant\n"
	.string "completament el {STR_VAR_2} de {STR_VAR_1}.\l"
	.string "Bravo, ENTRENADOR!\p"
	.string "Vèncer fins i tot a {STR_VAR_1}…\n"
	.string "Desafia tota creença! Simplement increïble!\p"
	.string "Vam demanar a l'ENTRENADOR impressions\n"
	.string "sobre el moment de glòria.$"

BravoTrainerBattleTower_Text_LostFinal::
	.string "Després d'una ratxa de victòries, la parella\n"
	.string "finalment va caure davant el {STR_VAR_2} de\l"
	.string "{STR_VAR_1}, el seu obstacle final.\p"
	.string "Bon intent, ENTRENADOR!\p"
	.string "Tot i així, cal reconèixer el mèrit.\n"
	.string "No veus moltes combinacions famoses\l"
	.string "com {STR_VAR_1} i {STR_VAR_2}.\p"
	.string "Vam demanar a l'ENTRENADOR impressions\n"
	.string "sobre lluitar contra la parella de famosos.$"

BravoTrainerBattleTower_Text_Satisfied::
	.string "Això és el que l'ENTRENADOR va dir:\n"
	.string "“Estic satisfet!”\p"
	.string "No és una resposta refrescant?\n"
	.string "Bravo, ENTRENADOR!\p"
	.string "No és totalment genial poder\n"
	.string "lluitar amb plena satisfacció?\p"
	.string "Vaig descobrir exactament com de satisfet\n"
	.string "quan vaig sentir l'ENTRENADOR dir això:$"

BravoTrainerBattleTower_Text_Unsatisfied::
	.string "Això és el que l'ENTRENADOR va dir:\n"
	.string "“No estic satisfet…”\p"
	.string "El nostre ENTRENADOR estava una mica\n"
	.string "deprimit quan va dir això.\p"
	.string "Tot i així, no és fàcil poder lluitar\n"
	.string "amb satisfacció completa, no?\p"
	.string "De tota manera, vaig descobrir com de\n"
	.string "insatisfet estava quan vaig sentir això:$"

BravoTrainerBattleTower_Text_None1::
	.string "Cap$"

BravoTrainerBattleTower_Text_None2::
	.string "Cap$"

BravoTrainerBattleTower_Text_None3::
	.string "Cap$"

BravoTrainerBattleTower_Text_None4::
	.string "Cap$"

BravoTrainerBattleTower_Text_Response::
	.string "“{STR_VAR_1}.”$"

BravoTrainerBattleTower_Text_ResponseSatisfied::
	.string "“{STR_VAR_1}.”\n"
	.string "No és genial?\p"
	.string "Realment expressa l'alegria de {STR_VAR_2},\n"
	.string "diria jo.\p"
	.string "Aquell combat amb {STR_VAR_3} al\n"
	.string "final… Realment era el que diries\l"
	.string "“{STR_VAR_1}”!$"

BravoTrainerBattleTower_Text_ResponseUnsatisfied::
	.string "“{STR_VAR_1}.”\n"
	.string "No és adequat?\p"
	.string "Aquell combat amb {STR_VAR_3} al\n"
	.string "final… No el pots descriure com res\l"
	.string "més que “{STR_VAR_1}”!\p"
	.string "La decepció de {STR_VAR_2} es nota\n"
	.string "ben clara, diria jo!$"

BravoTrainerBattleTower_Text_Outro::
	.string "Bravo, {STR_VAR_1}!\n"
	.string "Bravo, {STR_VAR_2}!\p"
	.string "Esperem poder veure com\n"
	.string "{STR_VAR_1} assoleix cotes encara més altes!\p"
	.string "Això és tot el temps que tenim!\n"
	.string "Fins la pròxima, adéu!$"

SlateportCity_PokemonFanClub_Text_InterviewRequestHasName:
	.string "Uau!\p"
	.string "És evident que prodigues el teu\n"
	.string "amor al teu {STR_VAR_1}.\p"
	.string "D'acord, es diu {STR_VAR_2}.\p"
	.string "Puc demanar-te un favor?\p"
	.string "Sóc reporter de TV, i estic fent\n"
	.string "una enquesta sobre POKéMON.\p"
	.string "Estaries disposat a respondre unes\n"
	.string "preguntes senzilles?$"

SlateportCity_PokemonFanClub_Text_HereGoesQuickAnswers:
	.string "Genial! Gràcies!\p"
	.string "D'acord, comencem.\n"
	.string "Només necessito respostes ràpides, val?$"

SlateportCity_PokemonFanClub_Text_DescribeFeelingsFirstMetMon:
	.string "Quan vas conèixer {STR_VAR_1} per\n"
	.string "primera vegada, què vas sentir?\p"
	.string "Com descriuries els teus sentiments\n"
	.string "en aquell moment?$"

SlateportCity_PokemonFanClub_Text_LikenMonToSomethingYouLike:
	.string "El teu {STR_VAR_1} està ben cuidat.\p"
	.string "Si l'haguessis de comparar amb alguna\n"
	.string "cosa que t'agrada, què seria?$"

SlateportCity_PokemonFanClub_Text_WhatAttractedYouAboutMon:
	.string "Aquesta pregunta també és sobre el teu\n"
	.string "estimat {STR_VAR_1}.\p"
	.string "Què va ser del {STR_VAR_1} el que\n"
	.string "et va atraure?$"

SlateportCity_PokemonFanClub_Text_WhatDoPokemonMeanToYou:
	.string "D'acord, té sentit.\p"
	.string "La següent pregunta pot ser una mica\n"
	.string "difícil.\p"
	.string "Aquí va…\p"
	.string "Què signifiquen els POKéMON per a tu?$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview:
	.string "Ja veig!\p"
	.string "Hmhm…\p"
	.string "D'acord!\n"
	.string "Gràcies per ajudar-me.\p"
	.string "Ha estat divertit i instructiu\n"
	.string "xerrar amb tu.\p"
	.string "És possible que la nostra entrevista\n"
	.string "surti a la TV. Estigues atent!\p"
	.string "D'acord, això és tot.\n"
	.string "Adéu!$"

SlateportCity_PokemonFanClub_Text_HereIfYouGetUrgeToTellMe:
	.string "Oh, d'acord…\p"
	.string "Bé, si tens ganes d'explicar-me\n"
	.string "coses sobre POKéMON, seré aquí!$"

SlateportCity_PokemonFanClub_Text_EnjoyDoingInterviews:
	.string "M'agrada aquesta feina - aprens sobre\n"
	.string "POKéMON fent entrevistes.$"

SlateportCity_PokemonFanClub_Text_InterviewRequest:
	.string "Ei, sembla que estàs molt unit al teu\n"
	.string "{STR_VAR_1}.\p"
	.string "Saps què?\n"
	.string "Sóc reporter de TV.\p"
	.string "Viatjo entrevistant gent\n"
	.string "sobre POKéMON.\p"
	.string "Em pregunto si estaries disposat a\n"
	.string "explicar-me una mica sobre el teu {STR_VAR_1}?$"

SlateportCity_PokemonFanClub_Text_TellMeAnythingAboutYourMon:
	.string "Uau, gràcies!\p"
	.string "D'acord, doncs, explica'm el que\n"
	.string "vulguis sobre el teu {STR_VAR_1}.$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview2:
	.string "Uau…\n"
	.string "Quina història tan interessant.\p"
	.string "Realment estàs molt unit a {STR_VAR_1},\n"
	.string "no?\p"
	.string "Tinc la sensació que la teva història\n"
	.string "farà un gran reportatge de TV.\p"
	.string "Prometo que convertiré això en\n"
	.string "un programa entretingut.\l"
	.string "Estigues atent.\p"
	.string "D'acord, això és tot.\n"
	.string "Adéu!$"

gTVFanClubOpinionsText00::
	.string "SOM EL CLUB DE FANS POKéMON!\p"
	.string "Estem en antena!\p"
	.string "En aquest programa, recollim les vostres\n"
	.string "opinions, i les crido en nom vostre!\l"
	.string "No és un concepte de programa fantàstic?\p"
	.string "Avui, us portem aquest reportatge del\n"
	.string "nostre reporter, que vam enviar al\l"
	.string "CLUB DE FANS POKéMON.\p"
	.string "I bé, qui és el fan POKéMON destacat\n"
	.string "d'avui?\p"
	.string "… … … … … … … …\p"
	.string "{STR_VAR_1}!\p"
	.string "Doncs, sentim què té a dir {STR_VAR_1}\n"
	.string "sobre {STR_VAR_3} el {STR_VAR_2}.\p"
	.string "I jo cridaré aquestes paraules d'amor\n"
	.string "ben fort a la TV!\p"
	.string "Ep-là!\p"
	.string "Cridem!$"

gTVFanClubOpinionsText01::
	.string "Vam preguntar a {STR_VAR_1}, “Quan vas\n"
	.string "veure per primera vegada el teu {STR_VAR_2},\l"
	.string "quin va ser el teu primer pensament?”\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Sí senyor! Quin crit tan potent!\p"
	.string "No et fa recordar aquells\n"
	.string "dies passats?$"

gTVFanClubOpinionsText02::
	.string "Vam preguntar a {STR_VAR_1}, “Si haguessis\n"
	.string "de comparar el teu {STR_VAR_2} amb alguna\l"
	.string "cosa, seria…”\p"
	.string "… … … … … … … …\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Uau, quina idea tan original!\p"
	.string "Es nota la intensitat del\n"
	.string "sentiment que l'ENTRENADOR té per\l"
	.string "{STR_VAR_2}.$"

gTVFanClubOpinionsText03::
	.string "I a veure…\n"
	.string "Què va ser del {STR_VAR_2}\l"
	.string "el que va atraure tant a {STR_VAR_1}?\p"
	.string "… … … … … … … …\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Uau! Quina declaració tan espectacular!\p"
	.string "L'amor de l'ENTRENADOR pel {STR_VAR_2}\n"
	.string "es nota ben clar!$"

gTVFanClubOpinionsText04::
	.string "Hm? Oh, encara hi ha més.\n"
	.string "Mirem-ho!\p"
	.string "A veure…\p"
	.string "Vam preguntar a {STR_VAR_1}, “Què\n"
	.string "signifiquen els POKéMON per a tu?”\p"
	.string "… … … … … …\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Bravo!\p"
	.string "El millor crit que he sentit en tot el dia!\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Et fa venir ganes de cridar-ho ben\n"
	.string "fort una vegada i una altra!\p"
	.string "Ara que hem cridat bé, és hora de\n"
	.string "dir adéu fins la pròxima!\p"
	.string "Doncs, fem un últim crit tots junts!\n"
	.string "Tots a l'hora…\p"
	.string "“{STR_VAR_3}!”$"

gTVFanClubText00::
	.string "SOM EL CLUB DE FANS POKéMON!\p"
	.string "Estem en antena!\p"
	.string "Avui, comencem amb el\n"
	.string "RACÓ DE L'ENQUESTA POKéMON.\p"
	.string "De totes les històries teixides per POKéMON\n"
	.string "i ENTRENADORS, quin nou drama sorprenent\l"
	.string "captarà la nostra atenció avui?\p"
	.string "A veure…\p"
	.string "Aquesta!\p"
	.string "Començarem amb aquesta carta!\p"
	.string "És una carta de {STR_VAR_1} sobre un\n"
	.string "estimat {STR_VAR_2}.\p"
	.string "Vegem com de passionalment pot\n"
	.string "expressar l'amor pel {STR_VAR_2}!\l"
	.string "Hmhm…$"

gTVFanClubText01::
	.string "Uau!\n"
	.string "Quina carta tan increïble!$"

gTVFanClubText02::
	.string "M'ha encantat, així que aquí la teniu de nou!$"

gTVFanClubText03::
	.string "Una gran carta val la pena llegir-la\n"
	.string "una vegada i una altra!$"

gTVFanClubText04::
	.string "La part “{STR_VAR_3},” realment\n"
	.string "accentua l'impacte emocional!\p"
	.string "És una gran carta que té\n"
	.string "profunditat de cor!$"

gTVFanClubText05::
	.string "Especialment la part “{STR_VAR_3}”!\p"
	.string "M'encanta com s'utilitza “{STR_VAR_3}”!$"

gTVFanClubText06::
	.string "Per cert, i no és important,\n"
	.string "però “{STR_VAR_3}” és una gran frase.\p"
	.string "He estat utilitzant “{STR_VAR_3}” molt\n"
	.string "en converses últimament.$"

gTVFanClubText07::
	.string "Si hagués de puntuar aquesta carta,\n"
	.string "li donaria {STR_VAR_3} punts.\p"
	.string "La pròxima vegada, espero una carta\n"
	.string "encara millor, {STR_VAR_1}!\p"
	.string "Ai, mira quina hora és!\n"
	.string "És hora de dir adéu fins la pròxima!$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequest:
	.string "Oh?\n"
	.string "Potser t'agraden els POKéMON?\p"
	.string "Estic treballant per a la cadena de TV.\p"
	.string "Estic recollint històries sobre POKéMON i\n"
	.string "ENTRENADORS que han passat recentment.\p"
	.string "Si no et fa res, podries explicar-me\n"
	.string "alguna cosa sobre tu?$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequestShort:
	.string "Estic recollint històries sobre POKéMON i\n"
	.string "ENTRENADORS que han passat recentment.\p"
	.string "Si no et fa res, podries explicar-me\n"
	.string "alguna cosa sobre tu?$"

SlateportCity_OceanicMuseum_1F_Text_TellMeExperienceInvolvingPokemon:
	.string "Oh, ho faràs?\n"
	.string "Gràcies!\p"
	.string "Doncs, si us plau, explica'm qualsevol cosa\n"
	.string "interessant que hagis viscut recentment\l"
	.string "amb POKéMON.$"

SlateportCity_OceanicMuseum_1F_Text_LetMeKnowIfYouHaveStory:
	.string "Oh, ja veig…\p"
	.string "Bé, si tens alguna història interessant\n"
	.string "per explicar, si us plau digues-m'ho.$"

SlateportCity_OceanicMuseum_1F_Text_ThatsAllForInterview:
	.string "Oh, quina història tan edificant!\p"
	.string "M'asseguraré que la teva història\n"
	.string "surti a la televisió.\p"
	.string "Hauria de sortir en algun moment, crec,\n"
	.string "així que estigues atent.$"

SlateportCity_OceanicMuseum_1F_Text_BetterWriteUpStory:
	.string "Hmmm…\n"
	.string "Tinc una bona història per a un programa.\p"
	.string "Millor que l'escrigui de pressa!$"

gTVRecentHappeningsText00::
	.string "Hola, és l'hora de SUCCESSOS RECENTS.\p"
	.string "Per als ENTRENADORS POKéMON, cada dia\n"
	.string "és un conte de fades.\p"
	.string "El que volem fer és presentar-vos\n"
	.string "alguns d'aquests contes POKéMON.\p"
	.string "Avui, us portem la història\n"
	.string "de l'ENTRENADOR {STR_VAR_1}.\p"
	.string "Què ha viscut {STR_VAR_1} recentment?\n"
	.string "Descobrim-ho.\p"
	.string "A veure…$"

gTVRecentHappeningsText01::
	.string "No ha estat instructiu?\p"
	.string "La història et dóna una idea clara del que\n"
	.string "{STR_VAR_1} ha viscut recentment.\l"
	.string "És com si hi haguéssim estat de testimonis!$"

gTVRecentHappeningsText02::
	.string "“{STR_VAR_3}.” Això\n"
	.string "accentua el conte i li dóna profunditat.$"

gTVRecentHappeningsText03::
	.string "“{STR_VAR_3}.”\n"
	.string "Això dóna al conte un sentit de lloc.\l"
	.string "Ens permet imaginar l'escenari del conte.$"

gTVRecentHappeningsText04::
	.string "La secció “{STR_VAR_3}”\n"
	.string "del conte és molt expressiva.$"

gTVRecentHappeningsText05::
	.string "{STR_VAR_1} ha explicat un conte meravellós\n"
	.string "sobre POKéMON.\p"
	.string "I ara el conte de {STR_VAR_1} està\n"
	.string "gravat en la teva ànima també.\p"
	.string "Això és tot per avui.\n"
	.string "Si us plau, sintonitzeu la pròxima.$"

gTVMassOutbreakText00::
	.string "Salutacions!\n"
	.string "És l'hora de NOTÍCIES POKéMON.\p"
	.string "Acabem de rebre notícies d'un succés\n"
	.string "molt estrany.\p"
	.string "Hi ha hagut informes d'una invasió\n"
	.string "massiva de {STR_VAR_2} a les rodalies\l"
	.string "de {STR_VAR_1}.\p"
	.string "{STR_VAR_2}, com probablement ja saps,\n"
	.string "és conegut com un POKéMON rar\l"
	.string "i difícil de trobar.\p"
	.string "Sembla una oportunitat rara per\n"
	.string "veure la misteriosa invasió de\l"
	.string "{STR_VAR_2} en estat salvatge.\p"
	.string "Aquestes són les notícies a NOTÍCIES POKéMON.$"

gTV3CheersForPokeblocksText00::
	.string "PRESENTADOR: Esperem que estigueu de bon\n"
	.string "humor, “3 HURRES PER {POKEBLOCK}S” és aquí!\p"
	.string "Avui, examinem el {POKEBLOCK} barrejat\n"
	.string "per {STR_VAR_1} i associats.\p"
	.string "Sense cap demora, deixeu-me donar-lo\n"
	.string "al meu POKéMON gourmet GULPIN.\p"
	.string "… … … … … …\n"
	.string "… … … … … …$"

gTV3CheersForPokeblocksText01::
	.string "GULPIN: Gubi! Gubii!\p"
	.string "PRES.: I el veredicte és molt {STR_VAR_1}!\n"
	.string "GULPIN diu que té gust “{STR_VAR_2}!”\p"
	.string "Moltes gràcies, {STR_VAR_3}!$"

gTV3CheersForPokeblocksText02::
	.string "La barreja de {STR_VAR_1}\n"
	.string "deixava alguna cosa a desitjar.\p"
	.string "Si aquest ENTRENADOR barregés millor,\n"
	.string "el {POKEBLOCK} seria molt més gustós.$"

gTV3CheersForPokeblocksText03::
	.string "GULPIN: Gubi! Gubii!\p"
	.string "PRES.: Hmm… És massa {STR_VAR_1}.\n"
	.string "GULPIN diu que té gust “{STR_VAR_2}!”\p"
	.string "Sembla que els errors de {STR_VAR_3}\n"
	.string "han afectat la qualitat de la barreja…$"

gTV3CheersForPokeblocksText04::
	.string "És una llàstima que l'esforç\n"
	.string "de lideratge de {STR_VAR_1} s'hagi perdut.\p"
	.string "Esperem que {STR_VAR_2} ho faci\n"
	.string "millor la pròxima vegada!$"

gTV3CheersForPokeblocksText05::
	.string "No us perdeu el pròxim programa!\n"
	.string "El nostre lema és “3 HURRES PELS {POKEBLOCK}S!”$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer::
	.string "Ei, hola!\p"
	.string "Sóc un gran fan de {STR_VAR_1}.\n"
	.string "Quina és la teva opinió de {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_ThatsWhatYouThink::
	.string "Ja veig, ja veig. Això és el que\n"
	.string "penses de l'ENTRENADOR.$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer::
	.string "Has oblidat completament\n"
	.string "{STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer2::
	.string "Sóc un gran fan de {STR_VAR_1}.\n"
	.string "Quina és la teva opinió de {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_HowStrongRateTrainer::
	.string "Com de fort puntuaries {STR_VAR_1}\n"
	.string "en una escala de cent?$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer2::
	.string "Has oblidat completament\n"
	.string "{STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_YouShouldMeetTrainer::
	.string "Oh, ja veig!\n"
	.string "Hauries de conèixer {STR_VAR_1} algun dia.\l"
	.string "Segur que també et faràs fan!$"

LilycoveCity_PokemonTrainerFanClub_Text_ThankYouIllShareThisInfo::
	.string "Ja veig, ja veig.\p"
	.string "Gràcies!\n"
	.string "Això és molt útil de saber.\p"
	.string "Compartiré aquesta informació amb altres\n"
	.string "fans de {STR_VAR_1} i en parlarem.$"

LilycoveCity_PokemonTrainerFanClub_HopeYouCatchTVSpecial::
	.string "Hi haurà un especial de TV sobre\n"
	.string "{STR_VAR_1} molt aviat.\p"
	.string "Espero que el vegis!$"

gTVTrainerFanClubSpecialText00::
	.string "CLUB DE FANS D'ENTRENADORS\n"
	.string "ESPECIAL {STR_VAR_1}!\p"
	.string "Aquesta és una presentació especial per\n"
	.string "als fans de {STR_VAR_1} a tot HOENN!\p"
	.string "Avui, fem la pregunta: “Què pensa\n"
	.string "la gent de {STR_VAR_1}?”\p"
	.string "Hem fet la pregunta a {STR_VAR_2}\n"
	.string "com a representant dels ENTRENADORS.\p"
	.string "Li hem preguntat: “En una paraula, com\n"
	.string "descriuries {STR_VAR_1}?”\p"
	.string "La resposta: “{STR_VAR_3}.”\p"
	.string "Felicitats a {STR_VAR_2}!\n"
	.string "Quina opinió tan perspicaç!\p"
	.string "“{STR_VAR_3} {STR_VAR_1}.”\n"
	.string "Sona molt bé!\p"
	.string "{STR_VAR_2} també ha puntuat la força\n"
	.string "de {STR_VAR_1} de 0 a 100.$"

gTVTrainerFanClubSpecialText01::
	.string "La puntuació ha estat de {STR_VAR_3} punts!\n"
	.string "Això és una puntuació molt alta!\p"
	.string "{STR_VAR_2} clarament té\n"
	.string "{STR_VAR_1} en molta estima.$"

gTVTrainerFanClubSpecialText02::
	.string "La puntuació ha estat de {STR_VAR_3} punts!\n"
	.string "Això és una puntuació força bona.\p"
	.string "{STR_VAR_2} deu considerar\n"
	.string "{STR_VAR_1} com a rival.$"

gTVTrainerFanClubSpecialText03::
	.string "La puntuació ha estat de {STR_VAR_3} punts!\n"
	.string "Això és una puntuació força baixa.\p"
	.string "{STR_VAR_2} deu considerar\n"
	.string "{STR_VAR_1} un simple company.$"

gTVTrainerFanClubSpecialText04::
	.string "La puntuació ha estat de {STR_VAR_3} punt(s)!\n"
	.string "Això és una puntuació terrible.\p"
	.string "{STR_VAR_2} deu considerar\n"
	.string "{STR_VAR_1} un subordinat.$"

gTVTrainerFanClubSpecialText05::
	.string "Aquí ho teniu, amics!\p"
	.string "Crec que tots hem après alguna cosa\n"
	.string "nova sobre {STR_VAR_1}.\p"
	.string "Per acabar, us deixo amb les\n"
	.string "paraules de {STR_VAR_2}.\p"
	.string "{STR_VAR_3} {STR_VAR_1}!$"

gTVNameRaterText00::
	.string "I ara, és hora de…\n"
	.string "EL PROGRAMA DEL JUTGE DE NOMS.\p"
	.string "Predic la fortuna del teu POKéMON\n"
	.string "a partir del malnom que li has posat.\p"
	.string "Consells és el que tinc per donar, i són\n"
	.string "consells útils els que ofereixo.\p"
	.string "Avui, faré una lectura del\n"
	.string "malnom {STR_VAR_3} del POKéMON\l"
	.string "{STR_VAR_2} de {STR_VAR_1}.\p"
	.string "Hmhm…\p"
	.string "Hmm…\n"
	.string "Aquest malnom és…$"

gTVNameRaterText01::
	.string "Un malnom que suggereix talent en\n"
	.string "moltes formes diferents.\p"
	.string "Animo aquest ENTRENADOR a ser valent\n"
	.string "i afrontar molts reptes.$"

gTVNameRaterText02::
	.string "Un malnom que complementa perfectament\n"
	.string "{STR_VAR_1}, el nom de l'ENTRENADOR.\p"
	.string "Suggereix que forjareu una gran\n"
	.string "associació amb un timing precís.$"

gTVNameRaterText03::
	.string "Un malnom apte per a un POKéMON\n"
	.string "únic i individual!\p"
	.string "Si es cria correctament, la singularitat\n"
	.string "d'aquest POKéMON florixerà enormement!$"

gTVNameRaterText04::
	.string "Un malnom que nodrirà el costat\n"
	.string "afectuós i compassiu del POKéMON.\p"
	.string "Si es cria correctament, aquest POKéMON\n"
	.string "mostrarà una autèntica calidesa!$"

gTVNameRaterText05::
	.string "Un malnom molt fi que suggereix\n"
	.string "grandesa futura.\p"
	.string "Estic intrigat sobre què li depara\n"
	.string "el futur a aquest POKéMON.$"

gTVNameRaterText06::
	.string "Un bon malnom que hauria de fer el\n"
	.string "POKéMON sa i robust!\p"
	.string "Aquest POKéMON hauria de mantenir-se\n"
	.string "en forma durant molt, molt de temps.$"

gTVNameRaterText07::
	.string "Un bon malnom que hauria de fer el\n"
	.string "POKéMON molt actiu!\p"
	.string "Crec que aquest POKéMON serà un\n"
	.string "gran lluitador en les batalles.$"

gTVNameRaterText08::
	.string "Un malnom atractiu que hauria de fer\n"
	.string "el POKéMON molt encantador!\p"
	.string "No dubto que aquest POKéMON serà\n"
	.string "molt encisador als CONCURSOS POKéMON.$"

gTVNameRaterText09::
	.string "El malnom {STR_VAR_1} s'arrelà a\n"
	.string "la lletra “{STR_VAR_3}.”\p"
	.string "Aquesta lletra és recolzada per la primera\n"
	.string "lletra “{STR_VAR_2},” que li dóna una sòlida\l"
	.string "presència com a malnom.$"

gTVNameRaterText10::
	.string "El malnom {STR_VAR_1} és molt\n"
	.string "ben format d'una manera agradable.\p"
	.string "La presència de les lletres “{STR_VAR_2}” i\n"
	.string "“{STR_VAR_3}”--és realment excel·lent!$"

gTVNameRaterText11::
	.string "El malnom {STR_VAR_1}--té una sensació\n"
	.string "sublim i fluida.\p"
	.string "El flux des de la lletra inicial “{STR_VAR_2}” a\n"
	.string "“{STR_VAR_3}” és especialment meravellós.$"

gTVNameRaterText12::
	.string "Examinem altres exemples de\n"
	.string "bons malnoms, oi?$"

gTVNameRaterText13::
	.string "Proveu aquest exemple. Agafeu una part\n"
	.string "del nom d'ENTRENADOR {STR_VAR_1}, i acabeu\l"
	.string "amb l'excel·lent malnom {STR_VAR_2}{STR_VAR_3}.$"

gTVNameRaterText14::
	.string "El malnom {STR_VAR_2}{STR_VAR_3} també funcionaria\n"
	.string "força bé.$"

gTVNameRaterText15::
	.string "El nom de l'espècie POKéMON\n"
	.string "{STR_VAR_2} es podria usar com a base\l"
	.string "per crear el malnom {STR_VAR_1}{STR_VAR_3}.$"

gTVNameRaterText16::
	.string "{STR_VAR_1}{STR_VAR_3} també seria un malnom\n"
	.string "efectiu.$"

gTVNameRaterText17::
	.string "El que sempre s'hauria d'evitar és usar\n"
	.string "el nom d'una altra espècie de POKéMON.\p"
	.string "Per exemple, eviteu agafar el nom de\n"
	.string "{STR_VAR_2} per fer el malnom {STR_VAR_1}{STR_VAR_3}.\l"
	.string "Això és inacceptable.$"

gTVNameRaterText18::
	.string "He de dir que {STR_VAR_1} és un\n"
	.string "malnom força bo.\p"
	.string "Espero que l'ENTRENADOR continuï\n"
	.string "tractant {STR_VAR_1} amb amor.\p"
	.string "Això és tot pel programa d'avui.\n"
	.string "Que ens tornem a veure.$"

gTVPokemonAnglerText00::
	.string "PESCADOR DE {STR_VAR_2}\p"
	.string "PRESENTADOR: Hola! Avui, rebrem consells\n"
	.string "sobre pescar {STR_VAR_2}.\p"
	.string "GURU, quin consell ens pots donar per\n"
	.string "atrapar {STR_VAR_2}?\p"
	.string "GURU: Hm? Atrapar {STR_VAR_2}?\n"
	.string "Bé, deixa'm dir-te, sigues pacient i\l"
	.string "espera. Això és l'essencial.\p"
	.string "Veus {STR_VAR_1} allà?\n"
	.string "Aquell ENTRENADOR és un bon exemple.\p"
	.string "Aquell ENTRENADOR ja ha deixat escapar\n"
	.string "{STR_VAR_3} POKéMON.\p"
	.string "Però {STR_VAR_1} espera. Sense rendir-se.\n"
	.string "Aquesta és la llei per atrapar {STR_VAR_2}.\p"
	.string "PRESENTADOR: Ja veig…\p"
	.string "Oh! {STR_VAR_1} finalment ha atrapat un\n"
	.string "esquiu {STR_VAR_2}!\p"
	.string "L'ENTRENADOR sembla a punt de plorar\n"
	.string "de pura alegria!\p"
	.string "Veient aquella cara d'alegria, a mi també\n"
	.string "em ve de gust anar a pescar!\p"
	.string "Espectadors, per què no aprofiteu per\n"
	.string "provar de pescar {STR_VAR_2}?\p"
	.string "Fins a la propera emissió, adéu i\n"
	.string "bona pesca a tots!$"

gTVPokemonAnglerText01::
	.string "PESCADOR DE {STR_VAR_2}\p"
	.string "PRESENTADOR: Hola! Avui, rebrem consells\n"
	.string "sobre pescar {STR_VAR_2}.\p"
	.string "GURU, quin consell ens pots donar per\n"
	.string "atrapar {STR_VAR_2}?\p"
	.string "GURU: Hm? Atrapar {STR_VAR_2}?\n"
	.string "Bé, deixa'm dir-te, usa la teva CANYA\l"
	.string "amb vigor!\p"
	.string "Veus {STR_VAR_1} allà?\n"
	.string "Veus com maneja la CANYA?\p"
	.string "Aquell ENTRENADOR ja n'ha atrapat\n"
	.string "{STR_VAR_3} seguits.\p"
	.string "PRESENTADOR: És increïble!\n"
	.string "Sembla una tempesta…\p"
	.string "Veient una tècnica d'aquest calibre,\n"
	.string "a mi també em ve de gust anar a pescar.\p"
	.string "Espectadors, per què no aprofiteu per\n"
	.string "provar de pescar {STR_VAR_2}?\p"
	.string "Fins a la propera emissió, adéu i\n"
	.string "bona pesca a tots!$"

gTVPokemonTodayFailedText00::
	.string "Hola!\p"
	.string "És l'hora de POKéMON AVUI!\p"
	.string "GERMANA: Hola! Esteu tots contents\n"
	.string "i animats avui?\p"
	.string "Avui, veurem el POKéMON {STR_VAR_2}\n"
	.string "de {STR_VAR_1}!\p"
	.string "GERMÀ: Sí! Això és el que farem!$"

gTVPokemonTodayFailedText01::
	.string "Oh!\n"
	.string "Parlant de {STR_VAR_1}…\p"
	.string "GERMANA, vaig veure l'ENTRENADOR amb\n"
	.string "els meus propis ulls!\p"
	.string "GERMANA: Oh, què vas veure?\p"
	.string "GERMÀ: Bé, vaig haver de fer un viatge a\n"
	.string "{STR_VAR_2}.\p"
	.string "Llavors em vaig trobar amb\n"
	.string "{STR_VAR_1}, que intentava atrapar el\l"
	.string "POKéMON {STR_VAR_3}, però…$"

gTVPokemonTodayFailedText02::
	.string "El POKéMON va aconseguir escapar-se!\p"
	.string "Va acabar malgastant tantes\n"
	.string "POKé BALLS: {STR_VAR_2}!\p"
	.string "Havíeu de veure l'expressió de\n"
	.string "frustració de {STR_VAR_1} quan\l"
	.string "el POKéMON va fugir!$"

gTVPokemonTodayFailedText03::
	.string "Però {STR_VAR_1} la va espifiar i va fer\n"
	.string "que el POKéMON es desmaiés!\p"
	.string "Va acabar malgastant tantes\n"
	.string "POKé BALLS: {STR_VAR_2}!\p"
	.string "Havíeu de veure l'expressió de\n"
	.string "sorpresa de {STR_VAR_1} quan\l"
	.string "el POKéMON es va desmaiar!$"

gTVPokemonTodayFailedText04::
	.string "GERMANA: Ei, aquí!\n"
	.string "Això no és amable!\p"
	.string "No t'hauries de riure de les\n"
	.string "desgràcies dels altres!\p"
	.string "Oh, pobre {STR_VAR_1}.\n"
	.string "Quina llàstima!\p"
	.string "GERMÀ: És veritat!\n"
	.string "Perdona per riure.$"

gTVPokemonTodayFailedText05::
	.string "GERMANA: Bufufu…\p"
	.string "GERMÀ: Ei!\n"
	.string "Tu també t'has rigut!\p"
	.string "GERMANA: Què?!\p"
	.string "No m'he rigut!\n"
	.string "De veritat que no!\p"
	.string "Oh, pobre {STR_VAR_1}.\n"
	.string "Quina llàstima!\p"
	.string "GERMÀ: …$"

gTVPokemonTodayFailedText06::
	.string "GERMANA: Prou ximpleries!\n"
	.string "Mirem el POKéMON d'avui…\p"
	.string "Eh?\n"
	.string "Ja s'ha acabat el temps?\p"
	.string "Oh!\n"
	.string "No hem pogut mostrar cap POKéMON avui!\p"
	.string "GERMÀ: Ens veiem la pròxima vegada!\p"
	.string "GERMANA: Ei, no acabis el programa\n"
	.string "sense mi!$"

gTVPokemonTodaySuccessfulText00::
	.string "Hola!\p"
	.string "És l'hora de POKéMON AVUI!\p"
	.string "GERMANA: Hola! Esteu tots contents\n"
	.string "i animats avui?\p"
	.string "Avui, veurem el POKéMON {STR_VAR_2}\n"
	.string "de {STR_VAR_1}!\p"
	.string "GERMÀ: Sí! Això és el que farem!$"

gTVPokemonTodaySuccessfulText01::
	.string "GERMANA: {STR_VAR_1} li va posar el malnom\n"
	.string "{STR_VAR_3} al {STR_VAR_2}!\p"
	.string "Sembla que {STR_VAR_3} rep\n"
	.string "molta cura i amor!$"

gTVPokemonTodaySuccessfulText02::
	.string "GERMÀ: L'ENTRENADOR va haver de llençar\n"
	.string "tantes POKé BALLS per atrapar-lo: {STR_VAR_3}!\p"
	.string "Finalment va fer servir una sola {STR_VAR_2}\n"
	.string "per atrapar-lo!$"

gTVPokemonTodaySuccessfulText03::
	.string "GERMANA: Si va ser tan fàcil d'atrapar,\n"
	.string "devia ser el destí que va unir\l"
	.string "{STR_VAR_1} i el {STR_VAR_2}!$"

gTVPokemonTodaySuccessfulText04::
	.string "GERMANA: Uau! Que bé!\p"
	.string "Però ja saps el que diuen, un POKéMON\n"
	.string "que costa molt d'atrapar\l"
	.string "es guanya l'amor del seu ENTRENADOR!$"

gTVPokemonTodaySuccessfulText05::
	.string "GERMANA: El {STR_VAR_2} de {STR_VAR_1} és un\n"
	.string "POKéMON memorable perquè va caler una\l"
	.string "valuosa MASTER BALL per atrapar-lo!\p"
	.string "GERMÀ: Uau! Això és mega-genial!\p"
	.string "GERMANA: {STR_VAR_1} devia voler molt\n"
	.string "aquell {STR_VAR_2}, segur!$"

gTVPokemonTodaySuccessfulText06::
	.string "GERMÀ: I després posar-li el malnom\n"
	.string "{STR_VAR_3} a aquell {STR_VAR_2}…\p"
	.string "Realment et fas una bona idea del\n"
	.string "sentit d'ENTRENADOR de {STR_VAR_1}.\p"
	.string "GERMANA: Estic totalment d'acord!$"

gTVPokemonTodaySuccessfulText07::
	.string "Si fos jo, li posaria aquell malnom\n"
	.string "a alguna cosa com aquest {STR_VAR_3}!\p"
	.string "GERMÀ: Uau! Això podria ser l'inici\n"
	.string "d'alguna cosa nova!$"

gTVPokemonTodaySuccessfulText08::
	.string "{STR_VAR_2} el {STR_VAR_1}?\n"
	.string "No sona perfecte?\p"
	.string "Les lletres i tot--sonen\n"
	.string "perfectes per al POKéMON\l"
	.string "{STR_VAR_1}!\p"
	.string "GERMÀ: Sí, és veritat!$"

gTVPokemonTodaySuccessfulText09::
	.string "Pel que sé, cap ENTRENADOR ha posat\n"
	.string "mai el malnom {STR_VAR_2} al seu\l"
	.string "{STR_VAR_1}!\p"
	.string "GERMÀ: Això només demostra el bon\n"
	.string "gust que té l'ENTRENADOR per triar\l"
	.string "malnoms!$"

gTVPokemonTodaySuccessfulText10::
	.string "La pròxima vegada que atrapi un POKéMON,\n"
	.string "li hauria de posar el nom {STR_VAR_2}.\p"
	.string "GERMÀ: Eh? Jo també!\n"
	.string "Jo també faré servir el malnom {STR_VAR_2}!$"

gTVPokemonTodaySuccessfulText11::
	.string "GERMANA: Oh, no!\n"
	.string "Mira l'hora!\p"
	.string "Bé, amics, això és tot per avui.\n"
	.string "Ens veiem la pròxima vegada!\p"
	.string "GERMÀ: Recordeu, podria ser el vostre\n"
	.string "POKéMON el protagonista la pròxima!$"

SmartShopper_Text_Intro::
	.string "Hola!\p"
	.string "És l'hora del COMPRADOR INTEL·LIGENT D'AVUI.\p"
	.string "ENTREVISTADOR: Com esteu, espectadors?\p"
	.string "Avui estem visitant una botiga\n"
	.string "a {STR_VAR_2}.\p"
	.string "Mirem quins han estat els productes\n"
	.string "més venuts recentment.$"

SmartShopper_Text_ClerkNormal::
	.string "Entrevistem el dependent per saber\n"
	.string "què hi ha.\p"
	.string "Hola, com va el negoci?\p"
	.string "DEPENDENT: Oh, ens va excel·lent.\p"
	.string "Recentment, {STR_VAR_2} s'ha estat\n"
	.string "venent especialment bé.\p"
	.string "De fet, l'altre dia un ENTRENADOR\n"
	.string "anomenat {STR_VAR_1} en va comprar {STR_VAR_3}.$"

SmartShopper_Text_RandomComment1::
	.string "ENTREVISTADOR: L'ENTRENADOR va comprar\n"
	.string "{STR_VAR_3} {STR_VAR_2}S? Quina compra!\p"
	.string "Si em permeteu dir-ho, {STR_VAR_1} devia\n"
	.string "estar fent provisions per un llarg viatge\l"
	.string "a llocs llunyans.\p"
	.string "Per viatjar, els {STR_VAR_2}S són tan\n"
	.string "importants!$"

SmartShopper_Text_RandomComment2::
	.string "ENTREVISTADOR: Parlant de l'objecte\n"
	.string "{STR_VAR_2}, jo acabo de comprar-ne {STR_VAR_3}\l"
	.string "recentment.\p"
	.string "Al cap i a la fi, {STR_VAR_2} és genial!$"

SmartShopper_Text_RandomComment3::
	.string "ENTREVISTADOR: {STR_VAR_2}?!\n"
	.string "Però {STR_VAR_3}?!\p"
	.string "No pensava que hi hagués ningú\n"
	.string "que en comprés tants.\p"
	.string "Déu meu, jo només em puc permetre\n"
	.string "un o dos a la vegada…$"

SmartShopper_Text_RandomComment4::
	.string "ENTREVISTADOR: Una vegada, vaig comprar\n"
	.string "una pila de l'objecte {STR_VAR_2}.\p"
	.string "Però van resultar ser massa.\n"
	.string "Al final me'n vaig penedir…\p"
	.string "Des de llavors, només compro estrictament\n"
	.string "el que necessito absolutament…\p"
	.string "Ups!\p"
	.string "No té sentit parlar de mi!$"

SmartShopper_Text_SecondItem::
	.string "DEPENDENT: {STR_VAR_1} també va comprar\n"
	.string "{STR_VAR_2} a l'engròs, emportant-se'n {STR_VAR_3}.\p"
	.string "ENTREVISTADOR: Oh, això és intel·ligent.\n"
	.string "{STR_VAR_2} també és un objecte molt bo.$"

SmartShopper_Text_ThirdItem::
	.string "DEPENDENT: I, l'ENTRENADOR també va comprar\n"
	.string "{STR_VAR_3} de l'objecte {STR_VAR_2}.$"

SmartShopper_Text_DuringSale::
	.string "DEPENDENT: A més, era durant unes grans\n"
	.string "rebaixes. Això és comprar intel·ligent.$"

SmartShopper_Text_OutroNormal::
	.string "ENTREVISTADOR: Hmm… {STR_VAR_1} sembla\n"
	.string "tot un caçador de gangues astut!\p"
	.string "En total, les compres de {STR_VAR_1} sumen…\p"
	.string "¥{STR_VAR_2}?!\n"
	.string "Quina suma increïble!\p"
	.string "Ups! Se'ns ha acabat el temps!\n"
	.string "Ens veiem a la pròxima emissió!$"

SmartShopper_Text_IsVIP::
	.string "DEPENDENT: {STR_VAR_1} és un client VIP,\n"
	.string "sens dubte.$"

SmartShopper_Text_ClerkMax::
	.string "Entrevistem el dependent per saber\n"
	.string "què hi ha.\p"
	.string "Hola, com va el negoci?\p"
	.string "DEPENDENT: Oh, ens va increïblement\n"
	.string "bé. És gairebé aclaparador.\p"
	.string "Recentment, un ENTRENADOR anomenat {STR_VAR_1}\n"
	.string "va comprar l'objecte {STR_VAR_2} a l'engròs.\p"
	.string "L'ENTRENADOR gairebé va buidar tot el\n"
	.string "nostre estoc de {STR_VAR_2}S.\p"
	.string "Mai hauria somiat que cap client\n"
	.string "necessités tants {STR_VAR_2}S.\l"
	.string "És inaudit!\p"
	.string "ENTREVISTADOR: Llavors serien uns 100\n"
	.string "o 200 venuts?\p"
	.string "DEPENDENT: Oh, no, molts més!\p"
	.string "ENTREVISTADOR: Oh, Déu meu!\n"
	.string "{STR_VAR_1} deu ser un comprador especial!\p"
	.string "DEPENDENT: {STR_VAR_1} és un client VIP,\n"
	.string "sens dubte.$"

SmartShopper_Text_OutroMax::
	.string "ENTREVISTADOR: Hmm…\n"
	.string "Això és increïble.\p"
	.string "Però per què l'ENTRENADOR necessitaria\n"
	.string "comprar-ne tants?\p"
	.string "… …\p"
	.string "El misteri s'aprofundeix, però això és tot\n"
	.string "el temps que tenim avui.\l"
	.string "Ens veiem a la pròxima emissió!\p"
	.string "Tot i així, {STR_VAR_1} és certament un enigma…$"

gTVWorldOfMastersText00::
	.string "EL MÓN DELS MESTRES\p"
	.string "Hola, espectadors.\p"
	.string "Potser coneixeu un ENTRENADOR\n"
	.string "anomenat {STR_VAR_1}.\p"
	.string "{STR_VAR_1} és famós com a mestre\n"
	.string "en atrapar POKéMON.\p"
	.string "La recerca de POKéMON de {STR_VAR_1} depèn\n"
	.string "completament d'una cerca acurada a peu.\p"
	.string "En un dia memorable, l'ENTRENADOR\n"
	.string "va caminar uns {STR_VAR_2} passos.\p"
	.string "El total de POKéMON atrapats\n"
	.string "aquell dia va arribar a un impressionant {STR_VAR_3}!$"

gTVWorldOfMastersText01::
	.string "Aquesta gesta remarcable deu haver estat\n"
	.string "possible gràcies a la confiança entre\l"
	.string "l'ENTRENADOR i {STR_VAR_1}.$"

gTVWorldOfMastersText02::
	.string "El mestre va atrapar l'últim\n"
	.string "{STR_VAR_3} del dia prop de {STR_VAR_2}.\p"
	.string "Aquell POKéMON aparentment gaudeix\n"
	.string "d'un estatus especial com a rècord.\p"
	.string "S'anima als ENTRENADORS hàbils\n"
	.string "a desafiar aquest gran rècord.\p"
	.string "Això és tot per avui.\n"
	.string "Sintonitzeu la pròxima vegada.$"

gTVTodaysRivalTrainerText00::
	.string "L'ENTRENADOR RIVAL D'AVUI!\p"
	.string "Hola, companys ENTRENADORS POKéMON!\n"
	.string "Com estem tots avui?\p"
	.string "Avui, com cada dia,\n"
	.string "examinarem un dels nostres rivals!$"

gTVTodaysRivalTrainerText07::
	.string "L'ENTRENADOR rival d'avui és {STR_VAR_1},\n"
	.string "que és al voltant de {STR_VAR_3} ara.\p"
	.string "{STR_VAR_1} ha registrat fins ara\n"
	.string "{STR_VAR_2} POKéMON a la POKéDEX.$"

gTVTodaysRivalTrainerText08::
	.string "L'ENTRENADOR rival d'avui és {STR_VAR_1},\n"
	.string "que és a una BASE SECRETA ara.\p"
	.string "{STR_VAR_1} ha registrat fins ara\n"
	.string "{STR_VAR_2} POKéMON a la POKéDEX.$"

gTVTodaysRivalTrainerText09::
	.string "L'ENTRENADOR rival d'avui és {STR_VAR_1}.\p"
	.string "Fins ara, {STR_VAR_1} ha registrat\n"
	.string "{STR_VAR_2} POKéMON a la POKéDEX.$"

gTVTodaysRivalTrainerText10::
	.string "L'ENTRENADOR rival d'avui és {STR_VAR_1},\n"
	.string "que és a un ferri ara.\p"
	.string "{STR_VAR_1} ha registrat fins ara\n"
	.string "{STR_VAR_2} POKéMON a la POKéDEX.$"

	.string "$"

gTVTodaysRivalTrainerText01::
	.string "I quantes MEDALLES té el nostre rival?\n"
	.string "El número és {STR_VAR_1}!$"

gTVTodaysRivalTrainerText02::
	.string "Però el nostre rival no ha obtingut\n"
	.string "cap MEDALLA encara!$"

gTVTodaysRivalTrainerText03::
	.string "El nostre rival no ha obtingut cap\n"
	.string "Símbol de la BATALLA FRONTERA encara.$"

gTVTodaysRivalTrainerText04::
	.string "Mirem quants Símbols de la BATALLA\n"
	.string "FRONTERA té el nostre rival.\p"
	.string "Símbols d'Or: {STR_VAR_1}!\n"
	.string "Símbols de Plata: {STR_VAR_2}!$"

gTVTodaysRivalTrainerText05::
	.string "El nostre rival ha col·leccionat {STR_VAR_1}\n"
	.string "Punt(s) de Batalla a la BATALLA FRONTERA.$"

gTVTodaysRivalTrainerText06::
	.string "I tu, com et compares amb\n"
	.string "{STR_VAR_1}?\p"
	.string "L'aventura continua!\p"
	.string "Companys ENTRENADORS!\p"
	.string "Continuem endavant\n"
	.string "i per davant dels nostres rivals!$"

TrendWatcher_Text_Intro::
	.string "XARXA DE TENDÈNCIES DE PORTENY!\p"
	.string "PRES.: Què hi ha?\n"
	.string "Us portarem les últimes novetats sobre\l"
	.string "el que mola a PORTENY.\p"
	.string "El nostre convidat d'avui és aquest home\n"
	.string "gran que és famós per ser l'autoritat\l"
	.string "en tot el que passa a PORTENY.\p"
	.string "Home gran: Encantat de ser aquí.\p"
	.string "PRES.: Anem al gra.\p"
	.string "Què ens pots dir sobre el que fa\n"
	.string "vibrar la bona gent de PORTENY?\p"
	.string "Home gran: {STR_VAR_1} {STR_VAR_2}.\p"
	.string "PRES.: {STR_VAR_1} {STR_VAR_2},\n"
	.string "dius?\p"
	.string "Home gran: No.\p"
	.string "{STR_VAR_1} {STR_VAR_2} mai\n"
	.string "es va fer popular.\p"
	.string "Vols que t'ho expliqui?\p"
	.string "PRES.: Eh, no. El que volem saber és\n"
	.string "què està de moda ara mateix…$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTaughtMePhrase::
	.string "Home gran: {STR_VAR_1} {STR_VAR_2}\n"
	.string "és el que {STR_VAR_3} de POBLE ARRELFERMA\l"
	.string "em va ensenyar com a tendència…$"

TrendWatcher_Text_FemaleTaughtMePhrase::
	.string "Home gran: {STR_VAR_1} {STR_VAR_2}\n"
	.string "és el que {STR_VAR_3} de POBLE ARRELFERMA\l"
	.string "em va ensenyar com a tendència…$"

TrendWatcher_Text_PhraseWasHopeless::
	.string "Però va ser totalment inútil.\p"
	.string "Festival de {STR_VAR_1} {STR_VAR_2}!\p"
	.string "Concurs de {STR_VAR_1} {STR_VAR_2}!\p"
	.string "Vaig intentar ensenyar-ho a tothom\n"
	.string "com millor vaig poder, però…\p"
	.string "Potser la part de {STR_VAR_1}\n"
	.string "no era l'adequada…\p"
	.string "PRES.: Eh, perdona, company, necessito\n"
	.string "saber què està de moda ara…$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTellMeBigger::
	.string "Home gran: {STR_VAR_3}!\n"
	.string "Si us plau, digues-me alguna cosa més gran\l"
	.string "que això de {STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_FemaleTellMeBigger::
	.string "Home gran: {STR_VAR_3}!\n"
	.string "Si us plau, digues-me alguna cosa més gran\l"
	.string "que això de {STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_Outro::
	.string "PRES.: …Eh… Doncs, aquí ho teniu,\n"
	.string "tots els moderns d'aquí fora!\p"
	.string "{STR_VAR_1} {STR_VAR_2}…eh…\n"
	.string "No es va posar de moda a PORTENY!\p"
	.string "S'ha acabat el temps. Fins la pròxima!\p"
	.string "Home gran: {STR_VAR_1} {STR_VAR_2}!$"

gTVHoennTreasureInvestigatorsText00::
	.string "INVESTIGADORS DE TRESORS DE HOENN!\p"
	.string "Hola, colla!\n"
	.string "Heu trobat algun objecte secret últimament?\p"
	.string "Com sempre, examinarem informes de\n"
	.string "testimonis de secrets d'arreu!\p"
	.string "Comencem amb una carta.\n"
	.string "Diu: “{STR_VAR_1} descobert!”$"

gTVHoennTreasureInvestigatorsText01::
	.string "Uau, és millor que comprovem aquesta\n"
	.string "carta! Deixeu-me llegir-la.\p"
	.string "…Benvolguts INVESTIGADORS,\n"
	.string "espero que estigueu bé.\p"
	.string "Recentment vaig veure {STR_VAR_2} per\n"
	.string "algun lloc prop de {STR_VAR_3}.\p"
	.string "L'ENTRENADOR va trobar l'objecte\n"
	.string "{STR_VAR_1}. Em va fer enveja.\p"
	.string "…Bé, ben fet, {STR_VAR_2}!\p"
	.string "Espectadors, que això us motivi a\n"
	.string "encendre els vostres BUSCAOBJETES i buscar!\p"
	.string "Estaré esperant notícies emocionants\n"
	.string "de tots vosaltres!$"

gTVHoennTreasureInvestigatorsText02::
	.string "Uau, és millor que comprovem aquesta\n"
	.string "carta! Deixeu-me llegir-la.\p"
	.string "…Benvolguts INVESTIGADORS,\n"
	.string "espero que estigueu bé.\p"
	.string "Recentment vaig veure {STR_VAR_2} a un ferri.\p"
	.string "L'ENTRENADOR va trobar l'objecte\n"
	.string "{STR_VAR_1}. Em va fer enveja.\p"
	.string "…Bé, ben fet, {STR_VAR_2}!\p"
	.string "Espectadors, que això us motivi a\n"
	.string "encendre els vostres BUSCAOBJETES i buscar!\p"
	.string "Estaré esperant notícies emocionants\n"
	.string "de tots vosaltres!$"

gTVFindThatGamerText00::
	.string "TROBA AQUELL JUGADOR!\p"
	.string "Hola, jugadors!\n"
	.string "Com gira el vostre {STR_VAR_2}?\p"
	.string "Com sempre, posarem el focus en\n"
	.string "un ENTRENADOR rar que ha visitat\l"
	.string "el RACÓ DE JOCS!\p"
	.string "Avui, el nostre jugador núm. 1 és…\n"
	.string "{STR_VAR_1}!$"

gTVFindThatGamerText01::
	.string "{STR_VAR_1} va jugar al joc de {STR_VAR_2}\n"
	.string "i va guanyar {STR_VAR_3} MONEDES.\p"
	.string "“Quan {STR_VAR_1} ve, hem d'assegurar-nos\n"
	.string "que tenim prou MONEDES.”\p"
	.string "Això és el que murmuren els empleats del\n"
	.string "RACÓ DE JOCS quan juga el nostre jugador!\p"
	.string "Espectadors, és millor vigilar les MONEDES\n"
	.string "com {STR_VAR_1} si visiteu el RACÓ\l"
	.string "DE JOCS i jugueu al joc de {STR_VAR_2}.\p"
	.string "Això és en directe des del RACÓ DE JOCS--\n"
	.string "on pots sentir l'emoció!\p"
	.string "Això és tot per avui!$"

gTVFindThatGamerText02::
	.string "{STR_VAR_1} va jugar al joc de {STR_VAR_2}\n"
	.string "i va perdre {STR_VAR_3} MONEDES.\p"
	.string "“Quan {STR_VAR_1} ve, les nostres vendes\n"
	.string "de MONEDES semblen augmentar.”\p"
	.string "Això és el que diuen els empleats del\n"
	.string "RACÓ DE JOCS quan juga el nostre jugador!$"

gTVFindThatGamerText03::
	.string "Espectadors, és millor vigilar les MONEDES\n"
	.string "com {STR_VAR_1} si visiteu el RACÓ\l"
	.string "DE JOCS i jugueu al joc de {STR_VAR_2}.\p"
	.string "Això és en directe des del RACÓ DE JOCS--\n"
	.string "on pots sentir l'emoció!\p"
	.string "Això és tot per avui!$"

gTVBreakingNewsText00::
	.string "NOTÍCIES D'ÚLTIMA HORA!$"

gTVBreakingNewsText01::
	.string "{STR_VAR_2} rar capturat per\n"
	.string "{STR_VAR_1}!\p"
	.string "Som en directe des de les rodalies\n"
	.string "de {STR_VAR_3}!\p"
	.string "{STR_VAR_1} va capturar amb èxit\n"
	.string "un rar {STR_VAR_2} fa poc aquí!$"

gTVBreakingNewsText02::
	.string "Quan {STR_VAR_1} es va trobar el rar\n"
	.string "{STR_VAR_2}, l'ENTRENADOR va treure\l"
	.string "el POKéMON {STR_VAR_3}.$"

gTVBreakingNewsText03::
	.string "A la batalla, el nombre de POKé\n"
	.string "BALLS llençades per l'ENTRENADOR va ser {STR_VAR_1}.\p"
	.string "Finalment, el POKéMON rar va ser\n"
	.string "capturat amb la {STR_VAR_2} usada al final.$"

gTVBreakingNewsText04::
	.string "En aquell instant, {STR_VAR_2}\n"
	.string "va ressonar amb els crits d'alegria\l"
	.string "triomfant de {STR_VAR_1}.\p"
	.string "He de dir que tinc una mica d'enveja de\n"
	.string "{STR_VAR_1}. A mi també m'agradaria cridar.\p"
	.string "…Això acaba la connexió en directe\n"
	.string "des de l'escena feliç!$"

gTVBreakingNewsText05::
	.string "{STR_VAR_1} no aconsegueix capturar un rar\n"
	.string "{STR_VAR_2}!\p"
	.string "Som en directe des de les rodalies\n"
	.string "de {STR_VAR_3}!\p"
	.string "Va ser aquí on {STR_VAR_1} va fallar\n"
	.string "en capturar un rar {STR_VAR_2}!$"

gTVBreakingNewsText06::
	.string "Quan {STR_VAR_1} es va trobar el rar\n"
	.string "{STR_VAR_2}, l'ENTRENADOR va treure\l"
	.string "el POKéMON {STR_VAR_3}.$"

gTVBreakingNewsText07::
	.string "L'ENTRENADOR va fer que {STR_VAR_2}\n"
	.string "usés el moviment {STR_VAR_1}.\p"
	.string "Sense voler, l'ENTRENADOR\n"
	.string "va fer desmaiar el POKéMON rar…$"

gTVBreakingNewsText12::
	.string "No obstant, {STR_VAR_1} es va espantar\n"
	.string "en veure el rar {STR_VAR_2}.\p"
	.string "En la confusió, l'ENTRENADOR va ordenar\n"
	.string "a {STR_VAR_3} atacar.\p"
	.string "Sense voler, l'ENTRENADOR\n"
	.string "va fer desmaiar el POKéMON rar.$"

gTVBreakingNewsText08::
	.string "En aquell instant, {STR_VAR_2}\n"
	.string "va ressonar amb els crits de\l"
	.string "frustració de {STR_VAR_1}…$"

gTVBreakingNewsText09::
	.string "No obstant, {STR_VAR_1} semblava que\n"
	.string "s'havia quedat sense POKé BALLS.\p"
	.string "L'ENTRENADOR va haver d'abandonar\n"
	.string "la batalla amb el rar {STR_VAR_2}.\p"
	.string "En aquell instant, {STR_VAR_3}\n"
	.string "va ressonar amb els crits de\l"
	.string "frustració de {STR_VAR_1}…$"

gTVBreakingNewsText10::
	.string "No obstant, el {STR_VAR_2} va fugir sense\n"
	.string "avisar.\p"
	.string "En aquell instant, {STR_VAR_3}\n"
	.string "va ressonar amb els crits de\l"
	.string "frustració de {STR_VAR_1}…$"

gTVBreakingNewsText11::
	.string "He de dir que compadeixo {STR_VAR_1}.\n"
	.string "A mi també em donen ganes de cridar.\p"
	.string "…Això acaba la connexió en directe\n"
	.string "des de l'escena melancòlica!$"

gTVSecretBaseVisitText00::
	.string "Hola, amics!\n"
	.string "És hora d'una altra\l"
	.string "VISITA A LA BASE SECRETA.\p"
	.string "Avui, visitem la BASE SECRETA\n"
	.string "de {STR_VAR_1}.\p"
	.string "Com ha personalitzat {STR_VAR_1}\n"
	.string "la seva BASE SECRETA?\p"
	.string "Descobrim-ho!\n"
	.string "… … … … … …$"

gTVSecretBaseVisitText01::
	.string "Oh!\n"
	.string "Que meravellós!\p"
	.string "Aquest {STR_VAR_2}…\n"
	.string "No és el que un esperaria\l"
	.string "trobar aquí!$"

gTVSecretBaseVisitText02::
	.string "Oh!\n"
	.string "Que remarcable!\p"
	.string "No hi ha ni un sol moble\n"
	.string "ni articles d'interior!\p"
	.string "Els simples mortals no podrien\n"
	.string "imitar aquesta declaració audaç!\p"
	.string "És simple, però esclata, sí,\n"
	.string "esclata amb salvatgia!\p"
	.string "Em trec el barret, {STR_VAR_1}.\n"
	.string "Només tu ho podries fer!$"

gTVSecretBaseVisitText03::
	.string "Oh! Ja ho veig!\n"
	.string "Amb perfecta claredat, ho veig!\p"
	.string "Que aquest {STR_VAR_2} estigui aquí…\n"
	.string "Envia un missatge efectiu!$"

gTVSecretBaseVisitText04::
	.string "Oh! Ja ho veig!\n"
	.string "Amb perfecta claredat, ho veig!\p"
	.string "Aquest espai es manté deliberadament\n"
	.string "lliure d'articles d'interior!\p"
	.string "Envia un missatge efectiu!$"

gTVSecretBaseVisitText05::
	.string "Uauuu!\p"
	.string "La combinació del {STR_VAR_2}\n"
	.string "amb el {STR_VAR_3}!\p"
	.string "És una combinació de somni si n'hi\n"
	.string "ha cap!$"

gTVSecretBaseVisitText06::
	.string "Uauuu!\p"
	.string "La col·locació d'aquest {STR_VAR_2}\n"
	.string "just aquí…\p"
	.string "Té una presència que omple\n"
	.string "tota la BASE SECRETA!$"

gTVSecretBaseVisitText07::
	.string "Uauuu!\p"
	.string "No hi ha res col·locat aquí.\p"
	.string "Aquest espai buit té un efecte en\n"
	.string "tota la BASE SECRETA.$"

gTVSecretBaseVisitText08::
	.string "Oh!\n"
	.string "Aquí ve {STR_VAR_1}!\l"
	.string "Desafiem l'ENTRENADOR!\p"
	.string "… … … … … …\n"
	.string "… … … … … …$"

gTVSecretBaseVisitText09::
	.string "Sospir…\n"
	.string "Li ho he de reconèixer a {STR_VAR_1}.\p"
	.string "Els POKéMON de l'ENTRENADOR eren\n"
	.string "veritablement dignes del títol de CAMPIÓ.\p"
	.string "Van donar àmplia prova de la\n"
	.string "fortalesa de {STR_VAR_1} com a ENTRENADOR.\p"
	.string "Que el {STR_VAR_2} conegués el moviment\n"
	.string "{STR_VAR_3}…\p"
	.string "Et mostra quin tipus d'ENTRENADOR\n"
	.string "és {STR_VAR_1}.\p"
	.string "Certament, va ser tota una lliçó!$"

gTVSecretBaseVisitText10::
	.string "Ai!\n"
	.string "Li ho he de reconèixer a {STR_VAR_1}.\p"
	.string "Els POKéMON de l'ENTRENADOR eren\n"
	.string "monstruosament forts!\p"
	.string "Van donar àmplia prova de la\n"
	.string "tenacitat de {STR_VAR_1} com a ENTRENADOR.\p"
	.string "Que el {STR_VAR_2} conegués el moviment\n"
	.string "{STR_VAR_3}…\p"
	.string "Et mostra quin tipus d'ENTRENADOR\n"
	.string "és {STR_VAR_1}.\p"
	.string "Certament, va ser tota una lliçó!$"

gTVSecretBaseVisitText11::
	.string "Uauuu!\n"
	.string "Li ho he de reconèixer a {STR_VAR_1}.\p"
	.string "Els POKéMON de l'ENTRENADOR estaven\n"
	.string "clarament criats de manera equilibrada.\p"
	.string "Van donar àmplia prova de la\n"
	.string "reflexió de {STR_VAR_1} com a ENTRENADOR.\p"
	.string "Que el {STR_VAR_2} conegués el moviment\n"
	.string "{STR_VAR_3}…\p"
	.string "Et mostra quin tipus d'ENTRENADOR\n"
	.string "és {STR_VAR_1}.\p"
	.string "Certament, va ser tota una lliçó!$"

gTVSecretBaseVisitText12::
	.string "Bé, bé!\n"
	.string "Li ho he de reconèixer a {STR_VAR_1}.\p"
	.string "Els POKéMON de l'ENTRENADOR mostraven\n"
	.string "gran promesa per al creixement futur.\p"
	.string "Representaven les esperances\n"
	.string "i somnis de {STR_VAR_1}.\p"
	.string "Que el {STR_VAR_2} conegués el moviment\n"
	.string "{STR_VAR_3}…\p"
	.string "Et mostra quin tipus d'ENTRENADOR\n"
	.string "és {STR_VAR_1}.\p"
	.string "Certament, va ser tota una lliçó!$"

gTVSecretBaseVisitText13::
	.string "He de dir, quina BASE SECRETA\n"
	.string "tan superba!\p"
	.string "Espectadors, si teniu l'oportunitat,\n"
	.string "visiteu la BASE SECRETA de {STR_VAR_1}.\p"
	.string "Fins la pròxima, adéu!$"

gTVPokemonLotteryWinnerFlashReportText00::
	.string "És emocionant!\n"
	.string "És dramàtic!\p"
	.string "És l'INFORME RÀPID DEL GUANYADOR\n"
	.string "DE LA LOTERIA POKéMON!\p"
	.string "Hola! Som en directe des del\n"
	.string "RACÓ DE LA LOTERIA POKéMON a la\l"
	.string "planta baixa dels GRANS MAGATZEMS\l"
	.string "DE LLIULLAC!\p"
	.string "Com sempre passa, un altre\n"
	.string "ENTRENADOR afortunat ha aparegut avui!\p"
	.string "El nom d'aquell ENTRENADOR…\n"
	.string "{STR_VAR_1}!\p"
	.string "{STR_VAR_1} ha guanyat el premi {STR_VAR_2}\n"
	.string "i s'ha emportat {STR_VAR_3}!\p"
	.string "{STR_VAR_1}!\n"
	.string "Felicitats!\p"
	.string "Espectadors, no us limiteu a mirar,\n"
	.string "participeu!\p"
	.string "Tots nosaltres als GRANS MAGATZEMS DE\n"
	.string "LLIULLAC esperem la vostra pròxima visita!\p"
	.string "Això ha estat una emissió en directe\n"
	.string "des dels GRANS MAGATZEMS DE LLIULLAC,\l"
	.string "oferint-vos la millor selecció\l"
	.string "de tot HOENN!$"

gTVThePokemonBattleSeminarText00::
	.string "EL SEMINARI DE BATALLES POKéMON!\p"
	.string "Examinem batalles per veure quines\n"
	.string "lliçons podem aprendre dels altres.\p"
	.string "L'estudi de cas d'avui és sobre la\n"
	.string "batalla de {STR_VAR_1}.\p"
	.string "El {STR_VAR_2} de {STR_VAR_1} estava\n"
	.string "lluitant contra un {STR_VAR_3}…$"

gTVThePokemonBattleSeminarText01::
	.string "I va usar el moviment {STR_VAR_3}\n"
	.string "contra el {STR_VAR_2}…\p"
	.string "Hmm… {STR_VAR_1}!\n"
	.string "Això és fer-ho malament!$"

gTVThePokemonBattleSeminarText02::
	.string "A més del moviment fallit,\n"
	.string "el {STR_VAR_1} de l'ENTRENADOR també coneixia$"

gTVThePokemonBattleSeminarText03::
	.string "els moviments {STR_VAR_1}, {STR_VAR_2},\n"
	.string "i {STR_VAR_3}.$"

gTVThePokemonBattleSeminarText04::
	.string "els moviments {STR_VAR_1} i\n"
	.string "{STR_VAR_2}.$"

gTVThePokemonBattleSeminarText05::
	.string "el moviment {STR_VAR_2}.$"

gTVThePokemonBattleSeminarText06::
	.string "Llavors, en aquesta situació, què hauria\n"
	.string "d'haver usat l'ENTRENADOR?\p"
	.string "… … … … … …\n"
	.string "El moviment {STR_VAR_1}!\p"
	.string "El moviment {STR_VAR_1} hauria estat\n"
	.string "absolutament millor que {STR_VAR_2}.\p"
	.string "Espectadors, us animo a aprendre d'aquest\n"
	.string "cas i lluitar amb intel·ligència!\p"
	.string "Fins la pròxima, adéu!$"

gTVTrainerFanClubText00::
	.string "Tots junts ara!\n"
	.string "CLUB DE FANS D'ENTRENADORS!\p"
	.string "PRES.: Com ho porteu?\n"
	.string "Avui, hem reunit els fans de\l"
	.string "l'hiperpopular ENTRENADOR {STR_VAR_1}!\p"
	.string "FANS: Wrooooooaaaaah!\p"
	.string "FANS: {STR_VAR_1}!\p"
	.string "PRES.: Tothom!\n"
	.string "Què us agrada de {STR_VAR_1}?!\p"
	.string "FANS: Ens encanta {STR_VAR_1}!\p"
	.string "PRES.: Què us agrada de\n"
	.string "{STR_VAR_1}?!$"

gTVTrainerFanClubText01::
	.string "FANS: La manera mola de llençar\n"
	.string "POKé BALLS!$"

gTVTrainerFanClubText02::
	.string "FANS: La seva manera adorable de córrer!$"

gTVTrainerFanClubText03::
	.string "FANS: Com l'ENTRENADOR es torna dur\n"
	.string "quan la cosa es posa difícil!$"

gTVTrainerFanClubText04::
	.string "FANS: El coneixement de l'ENTRENADOR\n"
	.string "sobre POKéMON!$"

gTVTrainerFanClubText05::
	.string "FANS: L'amabilitat de l'ENTRENADOR\n"
	.string "amb tots els POKéMON!$"

gTVTrainerFanClubText06::
	.string "FANS: Les tècniques increïbles de\n"
	.string "l'ENTRENADOR amb la BICI!$"

gTVTrainerFanClubText07::
	.string "FANS: L'estil impressionant de\n"
	.string "l'ENTRENADOR comprant objectes!$"

gTVTrainerFanClubText08::
	.string "FANS: La manera encantadora de\n"
	.string "l'ENTRENADOR de posar malnoms als POKéMON!$"

gTVTrainerFanClubText09::
	.string "FANS: L'estil genial de l'ENTRENADOR\n"
	.string "de decorar una BASE SECRETA!$"

gTVTrainerFanClubText10::
	.string "FANS: Les maneres audaces de\n"
	.string "l'ENTRENADOR d'usar MTs!$"

gTVTrainerFanClubText11::
	.string "PRES.: Com acabeu de veure, {STR_VAR_1}\n"
	.string "està de moda! Massa calent per tocar!\p"
	.string "Entre els FANS de {STR_VAR_1}\n"
	.string "hi ha un eslògan especial!\p"
	.string "PRES.: Quan jo dic {STR_VAR_1},\n"
	.string "vosaltres dieu…\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!\p"
	.string "PRES.: Així és, quan algú diu,\n"
	.string "“{STR_VAR_1}”…\p"
	.string "Responeu amb, “{STR_VAR_2}\n"
	.string "{STR_VAR_3}!”\p"
	.string "Això té un so tan únic!\n"
	.string "Ja veig per què la gent es fa FAN\l"
	.string "de {STR_VAR_1}!\p"
	.string "Vinga, tu, davant de la TV, uneix-te!\n"
	.string "Tots junts ara!\p"
	.string "PRES.: Quan jo dic {STR_VAR_1},\n"
	.string "vosaltres dieu…\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!\p"
	.string "PRES.: Gràcies per unir-vos, tots vosaltres\n"
	.string "FANS salvatges de {STR_VAR_1}!\l"
	.string "S'ha acabat el programa! Fins aviat!\p"
	.string "PRES.: Quan jo dic {STR_VAR_1},\n"
	.string "vosaltres dieu…\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!$"

TVSpotTheCuties_Text_Intro::
	.string "TROBA ELS ADORABLES!\n"
	.string "POKéMON AMB LLAÇOS!\p"
	.string "Hola, dolços espectadors!\p"
	.string "Sé que estareu d'acord, però un POKéMON\n"
	.string "amb LLAÇOS és simplement diví!\p"
	.string "Avui, vull compartir amb vosaltres\n"
	.string "un preciós POKéMON que vaig veure mentre\l"
	.string "passejava pel poble.\p"
	.string "El POKéMON bonic d'avui\n"
	.string "és el {STR_VAR_2} de {STR_VAR_1}.$"

TVSpotTheCuties_Text_RibbonsLow::
	.string "El nombre de LLAÇOS que porta\n"
	.string "{STR_VAR_2} és {STR_VAR_3}.\p"
	.string "Diu molt de com estima\n"
	.string "{STR_VAR_1} el POKéMON.$"

TVSpotTheCuties_Text_RibbonsMid::
	.string "{STR_VAR_2} porta uns increïbles\n"
	.string "{STR_VAR_3} LLAÇOS!\p"
	.string "Parla molt del compromís de {STR_VAR_1}\n"
	.string "amb el POKéMON!$"

TVSpotTheCuties_Text_RibbonsHigh::
	.string "{STR_VAR_2} porta uns impressionants\n"
	.string "{STR_VAR_3} LLAÇOS!\p"
	.string "Et mostra la dedicació total de\n"
	.string "{STR_VAR_1} com a col·leccionista!$"

TVSpotTheCuties_Text_RibbonIntro::
	.string "Fem una mirada més de prop als molts\n"
	.string "LLAÇOS que porta {STR_VAR_2}.$"

TVSpotTheCuties_Text_RibbonChampion::
	.string "El LLAÇ DE CAMPIÓ és especialment\n"
	.string "atractiu.\p"
	.string "{STR_VAR_2} el va rebre en entrar\n"
	.string "al SALÓ DE LA FAMA.\p"
	.string "Realment fa ressaltar la valentia\n"
	.string "de {STR_VAR_2}.\p"
	.string "{STR_VAR_2} i el LLAÇ DE CAMPIÓ!\n"
	.string "La combinació és molt efectiva!$"

TVSpotTheCuties_Text_RibbonCool::
	.string "El LLAÇ MOLA és especialment\n"
	.string "atractiu.\p"
	.string "{STR_VAR_2} el va rebre per guanyar\n"
	.string "un CONCURS MOLA.\p"
	.string "Realment fa ressaltar lo mola\n"
	.string "de {STR_VAR_2}.\p"
	.string "{STR_VAR_2} i el LLAÇ MOLA!\n"
	.string "La combinació és molt efectiva!$"

TVSpotTheCuties_Text_RibbonBeauty::
	.string "El LLAÇ DE BELLESA és especialment\n"
	.string "atractiu.\p"
	.string "{STR_VAR_2} el va rebre per guanyar\n"
	.string "un CONCURS DE BELLESA.\p"
	.string "Realment fa ressaltar la bellesa\n"
	.string "de {STR_VAR_2}.\p"
	.string "{STR_VAR_2} i el LLAÇ DE BELLESA!\n"
	.string "La combinació és molt efectiva!$"

TVSpotTheCuties_Text_RibbonCute::
	.string "El LLAÇ MACO és especialment\n"
	.string "atractiu.\p"
	.string "{STR_VAR_2} el va rebre per guanyar\n"
	.string "un CONCURS MACO.\p"
	.string "Realment fa ressaltar la moneria\n"
	.string "de {STR_VAR_2}.\p"
	.string "{STR_VAR_2} i el LLAÇ MACO!\n"
	.string "La combinació és molt efectiva!$"

TVSpotTheCuties_Text_RibbonSmart::
	.string "El LLAÇ LLEST és especialment\n"
	.string "atractiu.\p"
	.string "{STR_VAR_2} el va rebre per guanyar\n"
	.string "un CONCURS LLEST.\p"
	.string "Realment fa ressaltar la intel·ligència\n"
	.string "de {STR_VAR_2}.\p"
	.string "{STR_VAR_2} i el LLAÇ LLEST!\n"
	.string "La combinació és molt efectiva!$"

TVSpotTheCuties_Text_RibbonTough::
	.string "El LLAÇ DUR és especialment\n"
	.string "atractiu.\p"
	.string "{STR_VAR_2} el va rebre per guanyar\n"
	.string "un CONCURS DUR.\p"
	.string "Realment fa ressaltar la duresa\n"
	.string "de {STR_VAR_2}.\p"
	.string "{STR_VAR_2} i el LLAÇ DUR!\n"
	.string "La combinació és molt efectiva!$"

TVSpotTheCuties_Text_RibbonWinning::
	.string "El LLAÇ GUANYADOR és especialment\n"
	.string "atractiu.\p"
	.string "{STR_VAR_2} el va rebre per les seves gestes\n"
	.string "a la TORRE BATALLA.\p"
	.string "Realment fa ressaltar el poder\n"
	.string "de {STR_VAR_2}.\p"
	.string "{STR_VAR_2} i el LLAÇ GUANYADOR!\n"
	.string "La combinació és molt efectiva!$"

TVSpotTheCuties_Text_RibbonVictory::
	.string "El LLAÇ VICTÒRIA és especialment\n"
	.string "atractiu.\p"
	.string "{STR_VAR_2} el va rebre per les seves gestes\n"
	.string "a la TORRE BATALLA.\p"
	.string "Realment fa ressaltar l'increïble\n"
	.string "poder de {STR_VAR_2}.\p"
	.string "{STR_VAR_2} i el LLAÇ VICTÒRIA!\n"
	.string "La combinació és molt efectiva!$"

TVSpotTheCuties_Text_RibbonArtist::
	.string "El LLAÇ D'ARTISTA és especialment\n"
	.string "atractiu.\p"
	.string "{STR_VAR_2} el va rebre per ser\n"
	.string "el model d'un artista.\p"
	.string "Realment fa ressaltar l'encant d'estrella\n"
	.string "de {STR_VAR_2}.\p"
	.string "{STR_VAR_2} i el LLAÇ D'ARTISTA!\n"
	.string "La combinació és molt efectiva!$"

TVSpotTheCuties_Text_RibbonEffort::
	.string "El LLAÇ DE TREBALLADOR és\n"
	.string "especialment atractiu.\p"
	.string "{STR_VAR_2} el va rebre per ser\n"
	.string "un treballador especialment dedicat.\p"
	.string "Realment fa ressaltar la determinació\n"
	.string "de {STR_VAR_2}.\p"
	.string "{STR_VAR_2} i el LLAÇ DE TREBALLADOR!\n"
	.string "La combinació és molt efectiva!$"

TVSpotTheCuties_Text_Outro::
	.string "…Sospir…\p"
	.string "LLAÇOS i POKéMON…\n"
	.string "Van tan bé junts!\p"
	.string "Abans de desmaiar-me,\n"
	.string "us dic adéu a tots!$"

gTVPokemonNewsBattleFrontierText00::
	.string "Salutacions!\n"
	.string "És l'hora de NOTÍCIES POKéMON.\p"
	.string "Tenim notícies encoratjadores de\n"
	.string "la BATALLA FRONTERA.$"

gTVPokemonNewsBattleFrontierText01::
	.string "L'ENTRENADOR {STR_VAR_1} ha establert un nou\n"
	.string "rècord de {STR_VAR_2} victòries seguides al\l"
	.string "desafiament de BATALLA INDIVIDUAL\l"
	.string "de la TORRE BATALLA.\p"
	.string "Felicitats a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText02::
	.string "L'ENTRENADOR {STR_VAR_1} ha establert un nou\n"
	.string "rècord de {STR_VAR_2} victòries seguides al\l"
	.string "desafiament de BATALLA DOBLE\l"
	.string "de la TORRE BATALLA.\p"
	.string "Felicitats a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText03::
	.string "L'ENTRENADOR {STR_VAR_1} ha establert un nou\n"
	.string "rècord de {STR_VAR_2} victòries seguides al\l"
	.string "desafiament de MULTI BATALLA\l"
	.string "de la TORRE BATALLA.\p"
	.string "Felicitats a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText04::
	.string "L'ENTRENADOR {STR_VAR_1} ha establert un nou\n"
	.string "rècord de {STR_VAR_2} victòries seguides al\l"
	.string "desafiament de MULTI BATALLA ENLLAÇ\l"
	.string "de la TORRE BATALLA.\p"
	.string "Felicitats a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText05::
	.string "L'ENTRENADOR {STR_VAR_1} ha establert un nou\n"
	.string "rècord de {STR_VAR_2} campionats seguits\l"
	.string "competint als Tornejos de BATALLA\l"
	.string "INDIVIDUAL del DOM BATALLA.\p"
	.string "Felicitats a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText06::
	.string "L'ENTRENADOR {STR_VAR_1} ha establert un nou\n"
	.string "rècord de {STR_VAR_2} campionats seguits\l"
	.string "competint als Tornejos de BATALLA\l"
	.string "DOBLE del DOM BATALLA.\p"
	.string "Felicitats a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText07::
	.string "L'ENTRENADOR {STR_VAR_1} ha establert un nou\n"
	.string "rècord de {STR_VAR_2} victòries seguides al\l"
	.string "desafiament d'Intercanvi Individual\l"
	.string "de la FÀBRICA BATALLA.\p"
	.string "Felicitats a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText08::
	.string "L'ENTRENADOR {STR_VAR_1} ha establert un nou\n"
	.string "rècord de {STR_VAR_2} victòries seguides al\l"
	.string "desafiament d'Intercanvi Doble\l"
	.string "de la FÀBRICA BATALLA.\p"
	.string "Felicitats a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText09::
	.string "L'ENTRENADOR {STR_VAR_1} ha establert un nou\n"
	.string "rècord de superar {STR_VAR_2} sales\l"
	.string "al desafiament d'Elecció de Batalla\l"
	.string "de la SERP BATALLA.\p"
	.string "Felicitats a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText10::
	.string "L'ENTRENADOR {STR_VAR_1} ha establert un nou\n"
	.string "rècord de {STR_VAR_2} victòries seguides\l"
	.string "competint als Tornejos de KO\l"
	.string "de l'ARENA BATALLA.\p"
	.string "Felicitats a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText11::
	.string "L'ENTRENADOR {STR_VAR_1} ha establert un nou\n"
	.string "rècord de {STR_VAR_2} victòries seguides al\l"
	.string "desafiament de BATALLA INDIVIDUAL\l"
	.string "del PALAU BATALLA.\p"
	.string "Felicitats a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText12::
	.string "L'ENTRENADOR {STR_VAR_1} ha establert un nou\n"
	.string "rècord de {STR_VAR_2} victòries seguides al\l"
	.string "desafiament de BATALLA DOBLE\l"
	.string "del PALAU BATALLA.\p"
	.string "Felicitats a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText13::
	.string "L'ENTRENADOR {STR_VAR_1} ha establert un nou\n"
	.string "rècord de superar {STR_VAR_2} pisos\l"
	.string "al desafiament de Recerca de Batalla\l"
	.string "de la PIRÀMIDE BATALLA.\p"
	.string "Felicitats a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText14::
	.string "I als tres POKéMON, {STR_VAR_1},\n"
	.string "{STR_VAR_2}, i {STR_VAR_3}!\p"
	.string "Felicitats per la vostra\n"
	.string "actuació batent rècords!$"

gTVPokemonNewsBattleFrontierText15::
	.string "I als dos POKéMON, {STR_VAR_1}\n"
	.string "i {STR_VAR_2}!\p"
	.string "Felicitats per la vostra\n"
	.string "actuació batent rècords!$"

gTVPokemonNewsBattleFrontierText16::
	.string "I als quatre POKéMON: {STR_VAR_1}!\p"
	.string "{STR_VAR_2}!\p"
	.string "{STR_VAR_3}!$"

gTVPokemonNewsBattleFrontierText17::
	.string "I {STR_VAR_1}!\p"
	.string "Felicitats per la vostra\n"
	.string "actuació batent rècords!$"

gTVPokemonNewsBattleFrontierText18::
	.string "Esperem més gestes batent rècords\n"
	.string "de {STR_VAR_1} i els lleials\l"
	.string "POKéMON!\p"
	.string "Aquestes són les NOTÍCIES POKéMON!$"

gTVWhatsNo1InHoennTodayText00::
	.string "QUI ÉS EL NÚM. 1 DE HOENN AVUI?\n"
	.string "Sí, és hora d'això un altre cop!\p"
	.string "Hola, espectadors! Esteu donant el\n"
	.string "vostre millor en tot el que feu?\p"
	.string "Mirem l'ENTRENADOR que ho ha fet\n"
	.string "millor avui!\p"
	.string "L'ENTRENADOR núm. 1 d'avui no és altre\n"
	.string "que {STR_VAR_1}!$"

gTVWhatsNo1InHoennTodayText01::
	.string "En un dia, {STR_VAR_1} ha girat les SLOTS\n"
	.string "del RACÓ DE JOCS {STR_VAR_2} vegades.\p"
	.string "Mentre jugava, es va sentir {STR_VAR_1}\n"
	.string "murmurant: “Per a mi, els rodets ni\l"
	.string "es mouen…”\l"
	.string "No és interessant?$"

gTVWhatsNo1InHoennTodayText02::
	.string "En un dia, {STR_VAR_1} ha jugat\n"
	.string "a la RULETA del RACÓ DE\l"
	.string "JOCS {STR_VAR_2} vegades.\p"
	.string "Mentre jugava, {STR_VAR_1} va cridar:\n"
	.string "“Que les boles decideixin!”\p"
	.string "Els ulls de l'ENTRENADOR estaven fixos i\n"
	.string "la cara mostrava concentració.$"

gTVWhatsNo1InHoennTodayText03::
	.string "En un dia, {STR_VAR_1} va lluitar contra\n"
	.string "POKéMON salvatges {STR_VAR_2} vegades!\p"
	.string "Aparentment, els POKéMON de {STR_VAR_1}\n"
	.string "s'han fet incomparablement forts.\p"
	.string "Semblen ansiosos de lluitar a qualsevol\n"
	.string "lloc, en qualsevol moment, i de qualsevol manera!$"

gTVWhatsNo1InHoennTodayText04::
	.string "En només un dia, {STR_VAR_1} ha girat\n"
	.string "la BARREJADORA DE BAIES {STR_VAR_2} vegades!\p"
	.string "Cap al final, fins i tot {STR_VAR_1}\n"
	.string "semblava estar marejat.\p"
	.string "L'ENTRENADOR semblava trontollar\n"
	.string "com un SPINDA!$"

gTVWhatsNo1InHoennTodayText05::
	.string "En només un dia, {STR_VAR_1} ha plantat\n"
	.string "{STR_VAR_2} BAIES!\p"
	.string "Com a resultat, la roba de {STR_VAR_1}\n"
	.string "s'ha embrutat de terra.\p"
	.string "On l'ENTRENADOR ha plantat, incomptables\n"
	.string "flors han florit.\p"
	.string "Es diu que les flors calmen\n"
	.string "les emocions de la gent.$"

gTVWhatsNo1InHoennTodayText06::
	.string "En només un dia, {STR_VAR_1} ha collit\n"
	.string "{STR_VAR_2} BAIES!\p"
	.string "La MOTXILLA de {STR_VAR_1} es va omplir tant\n"
	.string "de BAIES, que l'ENTRENADOR tenia problemes\l"
	.string "per caminar després!$"

gTVWhatsNo1InHoennTodayText07::
	.string "En només un dia, {STR_VAR_1} ha obtingut\n"
	.string "{STR_VAR_2} Punts de Batalla!\p"
	.string "Més tard es va veure {STR_VAR_1} lluitant\n"
	.string "amb l'elecció de canviar els Punts de\l"
	.string "Batalla per un objecte genial o\l"
	.string "una decoració d'interior.\p"
	.string "L'ENTRENADOR suposadament somreia\n"
	.string "mentre considerava les opcions.$"

gTVWhatsNo1InHoennTodayText08::
	.string "Bé, no és increïble!\p"
	.string "{STR_VAR_1}!\n"
	.string "Ets l'ENTRENADOR núm. 1 d'avui!\p"
	.string "Espectadors, inspireu-vos en {STR_VAR_1}!\n"
	.string "Tu també pots ser el núm. 1 cada dia!$"

TVSecretBaseSecrets_Text_Intro::
	.string "SECRETS DE LA BASE SECRETA!\p"
	.string "Què fan els ENTRENADORS en la intimitat\n"
	.string "de les seves BASES SECRETES?\p"
	.string "Avui, investiguem la BASE SECRETA\n"
	.string "de {STR_VAR_1}.\p"
	.string "Oh? Sembla que {STR_VAR_2} ha vingut\n"
	.string "de visita.\p"
	.string "Fem una ullada!\p"
	.string "Què farà {STR_VAR_2}?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext1::
	.string "Què farà {STR_VAR_2} ara?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext2::
	.string "I ara, què farà {STR_VAR_2}?$"

TVSecretBaseSecrets_Text_TookXStepsBeforeLeaving::
	.string "Al final, {STR_VAR_2} va fer {STR_VAR_3} passes\n"
	.string "a la BASE SECRETA de {STR_VAR_1} abans\l"
	.string "de marxar.$"

TVSecretBaseSecrets_Text_BaseFailedToInterestPlayer::
	.string "Hmm…\p"
	.string "Sembla que la BASE SECRETA de {STR_VAR_1}\n"
	.string "no ha interessat {STR_VAR_2}…$"

TVSecretBaseSecrets_Text_PlayerEnjoyedBase::
	.string "{STR_VAR_2} sembla haver gaudit\n"
	.string "molt de la BASE SECRETA de {STR_VAR_1}.$"

TVSecretBaseSecrets_Text_PlayerHugeFanOfBase::
	.string "{STR_VAR_2} sembla haver-se convertit\n"
	.string "en un gran fan de la BASE SECRETA\l"
	.string "de {STR_VAR_1}.$"

TVSecretBaseSecrets_Text_Outro::
	.string "Potser els espectadors voldran visitar\n"
	.string "la BASE SECRETA de {STR_VAR_1} també.\p"
	.string "Sintonitzeu la pròxima vegada quan visitem\n"
	.string "una altra BASE SECRETA! Gràcies per unir-vos!$"

TVSecretBaseSecrets_Text_StoppedMoving1::
	.string "El visitant s'ha aturat!\p"
	.string "El visitant no es mou en absolut!\p"
	.string "La BASE SECRETA de {STR_VAR_1}\n"
	.string "era tan poc impressionant?$"

TVSecretBaseSecrets_Text_StoppedMoving2::
	.string "El visitant s'ha aturat!\p"
	.string "El visitant no es mou en absolut!\p"
	.string "És fatiga?\n"
	.string "El visitant s'ha cansat?$"

TVSecretBaseSecrets_Text_UsedChair::
	.string "El visitant s'ha assegut a una cadira!\n"
	.string "El visitant està assegut!\p"
	.string "Mireu aquella cara de delícia!\p"
	.string "Aquella cadira deu ser molt còmoda\n"
	.string "per obtenir aquella reacció!$"

TVSecretBaseSecrets_Text_UsedBalloon::
	.string "El visitant ha envestit un globus!\p"
	.string "Ha esclatat!\n"
	.string "Mare meva, ha petat!\p"
	.string "El visitant sembla sorprès pel\n"
	.string "soroll sobtat!$"

TVSecretBaseSecrets_Text_UsedTent::
	.string "El visitant ha entrat a una TENDA!\p"
	.string "El visitant corre amunt i avall!\p"
	.string "Oh, el visitant està jugant!\p"
	.string "El visitant sembla sorprès per la\n"
	.string "mida de la TENDA!$"

TVSecretBaseSecrets_Text_UsedPlant::
	.string "El visitant examina\n"
	.string "una planta en test!\p"
	.string "El visitant té un gust\n"
	.string "sorprenentment madur!$"

TVSecretBaseSecrets_Text_UsedGoldShield::
	.string "El visitant examina\n"
	.string "un ESCUT D'OR!\p"
	.string "Els ulls del visitant semblen\n"
	.string "brillar de meravella!$"

TVSecretBaseSecrets_Text_UsedSilverShield::
	.string "El visitant examina\n"
	.string "un ESCUT DE PLATA!\p"
	.string "El visitant sembla tenir els ulls oberts!$"

TVSecretBaseSecrets_Text_UsedGlassOrnament::
	.string "El visitant examina\n"
	.string "un ORNAMENT DE VIDRE!\p"
	.string "Oh, no!\p"
	.string "El visitant l'està tocant!\p"
	.string "S'està omplint\n"
	.string "d'empremtes…$"

TVSecretBaseSecrets_Text_UsedTV::
	.string "El visitant mira la televisió!\p"
	.string "Sembla que tenim un gran fan de la TV!$"

TVSecretBaseSecrets_Text_UsedMudBall::
	.string "El visitant ha trepitjat una BOLA DE FANG!\p"
	.string "El visitant sembla encantat!$"

TVSecretBaseSecrets_Text_UsedBag::
	.string "…Oh?\p"
	.string "El visitant agafa la seva pròpia\n"
	.string "BOSSA i remena dins!\p"
	.string "El visitant ha tret\n"
	.string "un {STR_VAR_2}!\p"
	.string "Mireu el visitant somriure mentre\n"
	.string "aguanta el {STR_VAR_2}!\p"
	.string "És com un anunci de TV!$"

TVSecretBaseSecrets_Text_UsedCushion::
	.string "El visitant agafa un coixí i…$"

TVSecretBaseSecrets_Text_HitCushion::
	.string "…comença a colpejar-lo!\p"
	.string "El visitant està molt estressat?$"

TVSecretBaseSecrets_Text_HuggedCushion::
	.string "…l'abraça fort!\p"
	.string "Potser el visitant està content\n"
	.string "per alguna cosa?$"

TVSecretBaseSecrets_Text_BattledWon::
	.string "El visitant xerra amb\n"
	.string "{STR_VAR_1}!\p"
	.string "Sembla que tindran\n"
	.string "un combat!\p"
	.string "I…\p"
	.string "És el visitant!\n"
	.string "El visitant ha guanyat a fora!\p"
	.string "El visitant està fent\n"
	.string "un ball de victòria!$"

TVSecretBaseSecrets_Text_BattledLost::
	.string "El visitant xerra amb\n"
	.string "{STR_VAR_1}!\p"
	.string "Sembla que tindran\n"
	.string "un combat!\p"
	.string "I…\p"
	.string "És {STR_VAR_1}!\n"
	.string "El visitant ha perdut!\p"
	.string "El visitant sembla abatut!$"

TVSecretBaseSecrets_Text_DeclinedBattle::
	.string "El visitant xerra amb\n"
	.string "{STR_VAR_1}!\p"
	.string "Sembla que tindran\n"
	.string "un combat!\p"
	.string "I…\p"
	.string "No, el visitant ha refusat!\p"
	.string "No hi haurà combat al final!\p"
	.string "El visitant no ha trobat {STR_VAR_1}\n"
	.string "prou atractiu?$"

TVSecretBaseSecrets_Text_UsedPoster::
	.string "El visitant mira fixament\n"
	.string "un pòster!\p"
	.string "Li agrada el pòster al visitant?\p"
	.string "…Però… Hi ha alguna cosa inquietant\n"
	.string "en la mirada del visitant.$"

TVSecretBaseSecrets_Text_UsedNoteMat::
	.string "El visitant ha trepitjat una CATIFA MUSICAL!\p"
	.string "…Hmm…\n"
	.string "El visitant ha compost una melodia graciosa!$"

TVSecretBaseSecrets_Text_BattledDraw::
	.string "El visitant xerra amb\n"
	.string "{STR_VAR_1}!\p"
	.string "Sembla que tindran\n"
	.string "un combat!\p"
	.string "I…\p"
	.string "És un empat!\n"
	.string "No s'ha resolt res!\p"
	.string "Els dos ENTRENADORS semblen molt\n"
	.string "decebuts!$"

TVSecretBaseSecrets_Text_UsedSpinMat::
	.string "El visitant ha trepitjat\n"
	.string "una CATIFA GIRATÒRIA!\p"
	.string "Sembla que el visitant està marejat!\p"
	.string "El visitant trontolla!\n"
	.string "Compte!$"

TVSecretBaseSecrets_Text_UsedSandOrnament::
	.string "El visitant agafa\n"
	.string "un ORNAMENT DE SORRA!\p"
	.string "Oh!\p"
	.string "S'ha ensorrat!\n"
	.string "S'ha desfet!\p"
	.string "El visitant sembla avergonyit\n"
	.string "i culpable!$"

TVSecretBaseSecrets_Text_UsedDesk::
	.string "El visitant frega un escriptori\n"
	.string "amb el dit!\p"
	.string "Pel que sembla, el visitant no tolera\n"
	.string "la pols!\p"
	.string "El visitant és sorprenentment exigent\n"
	.string "amb la neteja!$"

TVSecretBaseSecrets_Text_UsedBrick::
	.string "El visitant mira fixament un MAÓ!\p"
	.string "Potser el visitant pensa en\n"
	.string "l'objecte sobre el MAÓ.$"

TVSecretBaseSecrets_Text_UsedSolidBoard::
	.string "El visitant camina per sobre\n"
	.string "el TAULER SÒLID.\p"
	.string "El visitant no para de mirar avall.\p"
	.string "El visitant sembla sorprenentment\n"
	.string "tímid i cautelós!$"

TVSecretBaseSecrets_Text_UsedFence::
	.string "El visitant mira atentament\n"
	.string "una TANCA!\p"
	.string "Li ha vingut al cap una nova idea\n"
	.string "per a una trampa?$"

TVSecretBaseSecrets_Text_UsedGlitterMat::
	.string "El visitant ha trepitjat\n"
	.string "una CATIFA BRILLANT!\p"
	.string "El visitant està fent diverses\n"
	.string "poses!\p"
	.string "El visitant sembla que fantasieja\n"
	.string "amb ser un ídol!$"

TVSecretBaseSecrets_Text_UsedTire::
	.string "El visitant mira fixament\n"
	.string "un PNEUMÀTIC!\p"
	.string "Potser el visitant pensa en\n"
	.string "quin tipus de cotxe l'utilitzaria?$"

TVSecretBaseSecrets_Text_UsedStand::
	.string "El visitant ha pujat a una TARIMA!\p"
	.string "El visitant mira la BASE de\n"
	.string "{STR_VAR_1} des de dalt!\p"
	.string "I…\p"
	.string "Fa un crit!\n"
	.string "El visitant està cridant!$"

TVSecretBaseSecrets_Text_BrokeDoor::
	.string "El visitant ha envestit de cap\n"
	.string "una PORTA TRENCABLE!\p"
	.string "El visitant riu a carcallades!$"

TVSecretBaseSecrets_Text_UsedDoll::
	.string "El visitant parla amb una NINA!\p"
	.string "…És una mica esgarrifós…$"

TVSecretBaseSecrets_Text_UsedSlide::
	.string "El visitant puja l'escala\n"
	.string "d'un TOBOGAN!\p"
	.string "I…\p"
	.string "El visitant ha baixat!\p"
	.string "Sembla que el visitant s'ho passa\n"
	.string "d'allò més bé!$"

TVSecretBaseSecrets_Text_UsedSlideButDidntGoDown::
	.string "El visitant puja l'escala\n"
	.string "d'un TOBOGAN!\p"
	.string "I…\p"
	.string "El visitant ha baixat per\n"
	.string "l'escala!\p"
	.string "El visitant s'ha acollonit de cop?$"

TVSecretBaseSecrets_Text_UsedJumpMat::
	.string "El visitant ha trepitjat\n"
	.string "una CATIFA DE SALT!\p"
	.string "El visitant ha saltat un cop!\p"
	.string "Ha saltat dues vegades!\p"
	.string "I un aterratge perfecte!\p"
	.string "El visitant aplaudeix!\n"
	.string "Quina actuació en solitari!$"

gTVSafariFanClubText00::
	.string "CLUB DE FANS DEL SAFARI!\p"
	.string "REPORTER: Molt bé, companys!\n"
	.string "Llençant SAFARI BALLS, oi?\p"
	.string "Aquí som a la ZONA SAFARI\n"
	.string "plena de POKéMON increïbles!\p"
	.string "Parlem amb aquest bon home\n"
	.string "que és el GUIA DEL SAFARI!\p"
	.string "Molt bé, amic, com van els\n"
	.string "ENTRENADORS visitants?$"

gTVSafariFanClubText01::
	.string "GUIA: Tothom sembla estar\n"
	.string "donant-ho tot.\p"
	.string "{STR_VAR_1} ho fa especialment bé.\p"
	.string "De fet, abans, {STR_VAR_1} va capturar\n"
	.string "{STR_VAR_2} POKéMON.$"

gTVSafariFanClubText02::
	.string "L'ENTRENADOR és hàbil amb els {POKEBLOCK}S.\n"
	.string "En va usar {STR_VAR_2} aquella vegada.$"

gTVSafariFanClubText03::
	.string "L'ENTRENADOR no va usar ni un\n"
	.string "{POKEBLOCK}! Ni un de sol!\p"
	.string "Això és un expert de debò.$"

gTVSafariFanClubText04::
	.string "REPORTER: Ah sí?\p"
	.string "Sembla que el nostre amic {STR_VAR_1}\n"
	.string "és un mestre del SAFARI!\p"
	.string "GUIA: Espero que l'ENTRENADOR torni\n"
	.string "i ens mostri aquesta gran tècnica.$"

gTVSafariFanClubText05::
	.string "GUIA: Ningú sembla fer-ho\n"
	.string "gaire bé.\p"
	.string "{STR_VAR_1} ho va fer especialment malament.\p"
	.string "De fet, abans, l'ENTRENADOR només\n"
	.string "va aconseguir capturar {STR_VAR_2} POKéMON.$"

gTVSafariFanClubText06::
	.string "GUIA: Ningú sembla fer-ho\n"
	.string "gaire bé.\p"
	.string "{STR_VAR_1} ho va fer especialment malament.\p"
	.string "De fet, abans, l'ENTRENADOR no va\n"
	.string "capturar cap POKéMON. Ni un de sol!$"

gTVSafariFanClubText07::
	.string "L'ENTRENADOR sí que usa {POKEBLOCK}S.\n"
	.string "En va usar {STR_VAR_2} aquella vegada.\p"
	.string "Però m'agradaria que l'ENTRENADOR\n"
	.string "millori una mica.$"

gTVSafariFanClubText08::
	.string "Crec que l'ENTRENADOR tindria més sort\n"
	.string "usant {POKEBLOCK}S, que no va usar\l"
	.string "gens aquella vegada.$"

gTVSafariFanClubText09::
	.string "REPORTER: Ah sí?\p"
	.string "Sembla que el nostre amic {STR_VAR_1}\n"
	.string "necessita més experiència al SAFARI.\p"
	.string "GUIA: Espero que l'ENTRENADOR visiti\n"
	.string "moltes vegades per agafar-hi la mà.$"

gTVSafariFanClubText10::
	.string "REPORTER: Ben dit!\n"
	.string "Enfrontar-se als reptes és important!\p"
	.string "Espectadors, veniu al SAFARI\n"
	.string "i afronteu el repte vosaltres mateixos!\p"
	.string "Fins la propera!$"

ContestLiveUpdates_Text_Intro::
	.string "“CONCURS POKéMON EN DIRECTE!”\p"
	.string "PRESENTADOR: Gràcies per ser aquí!\p"
	.string "Som en directe des del lloc del\n"
	.string "{STR_VAR_1} que acaba de finalitzar.\p"
	.string "La sala encara està plena de\n"
	.string "públic que no vol marxar.\p"
	.string "Espectador: {STR_VAR_2}!\p"
	.string "Espectador: {STR_VAR_3}!\p"
	.string "PRESENTADOR: Com acabeu de sentir,\n"
	.string "el CONCURS l'ha guanyat el POKéMON\l"
	.string "{STR_VAR_2} de {STR_VAR_3}.\p"
	.string "Espectador: {STR_VAR_2}!\n"
	.string "Ets el millor!\p"
	.string "Espectador: {STR_VAR_3}!\n"
	.string "Molt bé!\p"
	.string "PRESENTADOR: Escoltem què diuen els fans\n"
	.string "sobre aquest CONCURS.$"

ContestLiveUpdates_Text_WonBothRounds::
	.string "Espectador: {STR_VAR_2} ha estat el millor\n"
	.string "tant en el judici primari com en el secundari!\p"
	.string "Aquell {STR_VAR_2} seguirà guanyant!$"

ContestLiveUpdates_Text_BetterRound2::
	.string "Espectador: {STR_VAR_2} no ho va fer\n"
	.string "gaire bé en el judici primari, però\l"
	.string "va arrasar en el secundari!\p"
	.string "Ha estat una remuntada miraculosa\n"
	.string "per aquell {STR_VAR_2}. Hurra!$"

ContestLiveUpdates_Text_EqualRounds::
	.string "Espectador: {STR_VAR_2} es va mantenir\n"
	.string "consistent tant en el judici primari\l"
	.string "com en el secundari.\p"
	.string "{STR_VAR_3} i {STR_VAR_2},\n"
	.string "no són cap parella normal!$"

ContestLiveUpdates_Text_BetterRound1::
	.string "Espectador: En termes de ser {STR_VAR_1},\n"
	.string "aquell {STR_VAR_2} va ser excepcional.\p"
	.string "Espero que faci millors exhibicions\n"
	.string "la propera vegada, però.$"

ContestLiveUpdates_Text_GotNervous::
	.string "Espectador: Quan {STR_VAR_2} es va posar\n"
	.string "nerviós, no vaig poder evitar\l"
	.string "cridar-li paraules d'ànim.\p"
	.string "Vull dir-li a aquell\n"
	.string "{STR_VAR_2}, “Felicitats!”$"

ContestLiveUpdates_Text_StartledFoes::
	.string "Espectador: L'exhibició d'aquell {STR_VAR_2}\n"
	.string "em va sorprendre fins i tot a mi!\p"
	.string "{STR_VAR_2}, eres increïble!$"

ContestLiveUpdates_Text_UsedCombo::
	.string "Espectador: L'exhibició combinada\n"
	.string "d'aquell {STR_VAR_2} va ser impressionant!\p"
	.string "M'ha deixat tremolant!$"

ContestLiveUpdates_Text_ExcitingAppeal::
	.string "Espectador: L'exhibició del {STR_VAR_2}\n"
	.string "guanyador m'ha fet bategar el cor!$"

ContestLiveUpdates_Text_WasCool::
	.string "{STR_VAR_2}!\n"
	.string "Eres genial!$"

ContestLiveUpdates_Text_WasBeautiful::
	.string "{STR_VAR_2}!\n"
	.string "Eres preciós!$"

ContestLiveUpdates_Text_WasCute::
	.string "{STR_VAR_2}!\n"
	.string "Eres molt maco!$"

ContestLiveUpdates_Text_WasSmart::
	.string "{STR_VAR_2}!\n"
	.string "Eres molt llest!$"

ContestLiveUpdates_Text_WasTough::
	.string "{STR_VAR_2}!\n"
	.string "Eres molt dur!$"

ContestLiveUpdates_Text_VeryExcitingAppeal::
	.string "Espectador: L'exhibició del {STR_VAR_2}\n"
	.string "guanyador encara em fa bategar el cor!$"

ContestLiveUpdates_Text_VeryCool::
	.string "{STR_VAR_2}!\n"
	.string "Ets l'última paraula en genialitat!$"

ContestLiveUpdates_Text_VeryBeautiful::
	.string "{STR_VAR_2}!\n"
	.string "Ets el més preciós!$"

ContestLiveUpdates_Text_VeryCute::
	.string "{STR_VAR_2}!\n"
	.string "Ets simplement el més maco!$"

ContestLiveUpdates_Text_VerySmart::
	.string "{STR_VAR_2}!\n"
	.string "Ets el més llest entre els llests!$"

ContestLiveUpdates_Text_VeryTough::
	.string "{STR_VAR_2}!\n"
	.string "Ets el més dur entre els durs!$"

ContestLiveUpdates_Text_TookBreak::
	.string "Espectador: Fins i tot quan {STR_VAR_2}\n"
	.string "feia una pausa de les exhibicions,\l"
	.string "no podia apartar-ne la vista.\p"
	.string "Estic captivat per aquell {STR_VAR_2}.$"

ContestLiveUpdates_Text_GotStartled::
	.string "Espectador: Quan {STR_VAR_2} es va\n"
	.string "espantar per l'exhibició d'un altre POKéMON,\l"
	.string "gairebé em vaig posar a plorar.\p"
	.string "{STR_VAR_2}, eres resistent!\n"
	.string "Molt bé!$"

ContestLiveUpdates_Text_MoveWonderful::
	.string "Espectador: Oh…\n"
	.string "El {STR_VAR_3} d'aquell {STR_VAR_2}!\l"
	.string "El {STR_VAR_3} de {STR_VAR_2}!\l"
	.string "El {STR_VAR_3} de {STR_VAR_2}!\l"
	.string "Com pot ser tan meravellós?$"

ContestLiveUpdates_Text_TalkAboutAnotherMon::
	.string "PRESENTADOR: Bé, aquí ho teniu. Aquest lloc\n"
	.string "està ple de fans de {STR_VAR_1}!\p"
	.string "També hauria de mencionar que un altre\n"
	.string "POKéMON, el {STR_VAR_3} de {STR_VAR_2}, \l"
	.string "em va cridar l'atenció.\p"
	.string "El {STR_VAR_3} de {STR_VAR_2}…$"

ContestLiveUpdates_Text_FailedToAppeal::
	.string "No va aconseguir fer ni una exhibició durant\n"
	.string "el judici secundari pels nervis.\p"
	.string "La propera vegada, m'agradaria veure\n"
	.string "aquest {STR_VAR_1} fer almenys una exhibició.$"

ContestLiveUpdates_Text_LastInBothRounds::
	.string "Va quedar l'últim tant en el judici\n"
	.string "primari com en el secundari.\p"
	.string "Espero que {STR_VAR_1} reentreneu aquest\n"
	.string "{STR_VAR_2} i esborreu la vergonya\l"
	.string "d'aquest indiscutible últim lloc.$"

ContestLiveUpdates_Text_NotExcitingEnough::
	.string "No va aprofitar l'emoció del públic\n"
	.string "per fer una exhibició apropiada.\p"
	.string "Esperem que {STR_VAR_1} aprengui a captar\n"
	.string "el públic i portar la seva emoció\l"
	.string "al màxim la propera vegada.$"

ContestLiveUpdates_Text_LostAfterWinningRound1::
	.string "Tot i acabar primer en el judici primari,\n"
	.string "les seves exhibicions en el secundari\l"
	.string "no van funcionar.\p"
	.string "Va patir una humiliant derrota\n"
	.string "de remuntada.\p"
	.string "Segur que {STR_VAR_1} estudia com fer\n"
	.string "exhibicions més efectives ara.$"

ContestLiveUpdates_Text_NeverExciting::
	.string "El públic mai es va emocionar amb les\n"
	.string "seves exhibicions durant el judici secundari.\p"
	.string "Esperem que deixi de preocupar-se pels\n"
	.string "altres POKéMON i aprengui a dirigir\l"
	.string "les exhibicions més al públic.$"

ContestLiveUpdates_Text_LostBySmallMargin::
	.string "Va perdre contra el {STR_VAR_2} de\n"
	.string "{STR_VAR_1} per un marge petit.\p"
	.string "Deu ser descoratjador estar tan a prop\n"
	.string "de la victòria i fracassar.\p"
	.string "No em sorprendria si {STR_VAR_3}\n"
	.string "estigués plorant per aquest resultat.$"

ContestLiveUpdates_Text_RepeatedAppeals::
	.string "Va decebre el JUTGE repetint\n"
	.string "les mateixes exhibicions.\p"
	.string "És un error imperdonable en qualsevol\n"
	.string "CONCURS, i el POKéMON ho va pagar.\p"
	.string "{STR_VAR_1} hauria de sentir-se culpable\n"
	.string "per aquesta trista actuació.$"

ContestLiveUpdates_Text_ValiantEffortButLost::
	.string "{STR_VAR_1} va fer un esforç valent,\n"
	.string "però…\p"
	.string "Tot va ser en va, acabant l'últim.\p"
	.string "{STR_VAR_1} hauria d'aprendre d'aquesta derrota\n"
	.string "i utilitzar el coneixement per millorar.$"

ContestLiveUpdates_Text_Outro::
	.string "M'agradaria acabar el programa amb el\n"
	.string "nostre comiat habitual als guanyadors.\p"
	.string "Aquesta vegada, és {STR_VAR_1} i\n"
	.string "el {STR_VAR_2}!\p"
	.string "PRESENTADOR: Tothom preparat?\n"
	.string "Tots junts!\p"
	.string "Públic: {STR_VAR_1}! {STR_VAR_2}!\n"
	.string "Felicitats!\l"
	.string "Sou els guanyadors del CONCURS!$"

gTVPokemonBattleUpdateText00::
	.string "“ACTUALITZACIÓ DE COMBAT POKéMON!”\p"
	.string "Us portem els resultats dels combats\n"
	.string "POKéMON a mesura que arriben!$"

gTVPokemonBattleUpdateText01::
	.string "Els ENTRENADORS {STR_VAR_1} i\n"
	.string "{STR_VAR_2} s'han enfrontat en\l"
	.string "un COMBAT {STR_VAR_3}.\p"
	.string "Aquest combat ha acabat amb victòria\n"
	.string "per a {STR_VAR_1}!$"

gTVPokemonBattleUpdateText02::
	.string "En el combat, el {STR_VAR_2} de\n"
	.string "{STR_VAR_1} va ser una força formidable\l"
	.string "usant {STR_VAR_3}!$"

gTVPokemonBattleUpdateText03::
	.string "El {STR_VAR_2} de {STR_VAR_1} va tenir una\n"
	.string "actuació feble que va fer mal.$"

gTVPokemonBattleUpdateText04::
	.string "Felicitats per la victòria,\n"
	.string "{STR_VAR_1}!\p"
	.string "I per al derrotat {STR_VAR_2},\n"
	.string "esperem un millor resultat la propera!\p"
	.string "Això conclou aquest episodi de\n"
	.string "“ACTUALITZACIÓ DE COMBAT POKéMON!”$"

gTVPokemonBattleUpdateText05::
	.string "Els equips dels ENTRENADORS {STR_VAR_1} i\n"
	.string "{STR_VAR_2} s'han trobat en un MULTI COMBAT.\p"
	.string "Aquest combat ha acabat amb victòria\n"
	.string "per a l'equip de {STR_VAR_1}.$"

gTVPokemonBattleUpdateText06::
	.string "En el combat, el {STR_VAR_2} de l'equip\n"
	.string "de {STR_VAR_1} va ser una força formidable\l"
	.string "usant {STR_VAR_3}.$"

gTVPokemonBattleUpdateText07::
	.string "L'actuació feble del {STR_VAR_3} de\n"
	.string "l'equip de {STR_VAR_2} va fer mal.\p"
	.string "Felicitats per la victòria del vostre\n"
	.string "equip, {STR_VAR_1}!\p"
	.string "Pel que fa a l'equip derrotat de {STR_VAR_2},\n"
	.string "esperem un millor resultat la propera!\p"
	.string "Això conclou aquest episodi de\n"
	.string "“ACTUALITZACIÓ DE COMBAT POKéMON!”$"

GabbyAndTy_Text_GabbyPreFirstBattle:
	.string "GABBY: Oh! Acabem de veure un ENTRENADOR\n"
	.string "de pinta forta aquí de tots els llocs!\p"
	.string "D'acord, càmera!\n"
	.string "Fem aquesta entrevista.$"

GabbyAndTy_Text_GabbyIntro:
	.string "GABBY: Oh! Ets {PLAYER}! Hola!\n"
	.string "Ens recordes de l'última vegada?\p"
	.string "Ens pots mostrar com de fort t'has\n"
	.string "tornat? D'acord, entrevista!$"

GabbyAndTy_Text_GabbyDefeatFirstTime:
	.string "GABBY: Els meus ulls no mentien!\n"
	.string "He descobert un ENTRENADOR increïble!$"

GabbyAndTy_Text_WhoAreYouInterview:
	.string "GABBY: Increïble! Increïble!\n"
	.string "Qui ets?!\p"
	.string "Sabia que havíem trobat alguna cosa\n"
	.string "salvatge quan et vam veure!\p"
	.string "Oh, deixa'm explicar. Viatgem per tot\n"
	.string "arreu entrevistant tota mena\l"
	.string "d'ENTRENADORS.\p"
	.string "Llavors, ens donaries una mica del teu\n"
	.string "temps per una entrevista?$"

GabbyAndTy_Text_QuoteFromLastInterview:
	.string "GABBY: “{STR_VAR_1}!”\p"
	.string "Te'n recordes? Aquesta és la cita que\n"
	.string "ens vas donar com a clau del combat.\p"
	.string "Mai oblido coses així!$"

GabbyAndTy_Text_YouStompedUsInterviewAgain:
	.string "L'última vegada que vam combatre, ens vas\n"
	.string "esclafar abans que poguéssim reaccionar…\p"
	.string "De totes maneres, què en penses?\n"
	.string "Vols ser entrevistat de nou?$"

GabbyAndTy_Text_YouThrewABallAtUsInterviewAgain:
	.string "L'última vegada que vam combatre, no ens\n"
	.string "vas llençar una POKé BALL?\p"
	.string "Estàvem en xoc! Ho vam dir a tothom,\n"
	.string "absolutament a tothom!\p"
	.string "De totes maneres, què en penses?\n"
	.string "Vols ser entrevistat de nou?$"

GabbyAndTy_Text_CleverItemSkillsInterviewAgain:
	.string "L'última vegada que vam combatre, les teves\n"
	.string "habilitats amb objectes ens van derrotar.\p"
	.string "De totes maneres, què en penses?\n"
	.string "Vols ser entrevistat de nou?$"

GabbyAndTy_Text_WeLookedRespectableInterviewAgain:
	.string "L'última vegada que vam combatre, vam\n"
	.string "aconseguir fer bona cara.\p"
	.string "De totes maneres, què en penses?\n"
	.string "Vols ser entrevistat de nou?$"

GabbyAndTy_Text_InterviewAgain:
	.string "De totes maneres, què en penses?\n"
	.string "Vols ser entrevistat de nou?$"

GabbyAndTy_Text_DescribeYourFeelings:
	.string "Sí que vols?\n"
	.string "Gràcies!\p"
	.string "D'acord, necessito que descriguis els teus\n"
	.string "sentiments sobre el combat, però ha\l"
	.string "de ser curt i concís. Endavant!$"

GabbyAndTy_Text_PerfectWellBeSeeingYou:
	.string "GABBY: Mmm, sí!\n"
	.string "Aquesta és la frase perfecta!\p"
	.string "Tinc la sensació que això farà\n"
	.string "un gran programa de TV.\p"
	.string "Hi ha la possibilitat que ho emetin\n"
	.string "per TV, així que busca'ns!\p"
	.string "D'acord!\n"
	.string "Ens veurem!$"

GabbyAndTy_Text_DontGiveUpKeepingEyeOut:
	.string "GABBY: Oh…\p"
	.string "D'acord, però no et rendeixis!\n"
	.string "Seguirem buscant-te!$"

GabbyAndTy_Text_KeepingAnEyeOutForYou:
	.string "GABBY: Seguirem buscant-te!$"

GabbyAndTy_Text_GabbyNotEnoughMons:
	.string "GABBY: Hi ha algun ENTRENADOR fort\n"
	.string "per aquí amb molts POKéMON?$"

GabbyAndTy_Text_GiveUsAnInterviewThisTime:
	.string "GABBY: Uau, ets algú especial!\p"
	.string "T'has tornat molt més fort--molt--\n"
	.string "des de l'últim combat.\p"
	.string "Teníem raó sobre tu quan et vam\n"
	.string "detectar com un ENTRENADOR prometedor.\p"
	.string "Llavors, què en penses?\n"
	.string "Estàs disposat a donar-nos una entrevista\l"
	.string "aquesta vegada?$"

GabbyAndTy_Text_GabbyDefeat:
	.string "GABBY: Ha estat un combat intens!\n"
	.string "Ho has gravat tot amb la càmera?$"

GabbyAndTy_Text_TyPreFirstBattle:
	.string "TY: Ep, mira aquí! Un ENTRENADOR de\n"
	.string "pinta forta aquí, de tots els llocs!\l"
	.string "La càmera grava!$"

GabbyAndTy_Text_TyIntro:
	.string "TY: Ep, mira aquí!\n"
	.string "Te'n recordo!\p"
	.string "Gravaré tot aquest combat amb\n"
	.string "aquesta càmera!$"

GabbyAndTy_Text_TyPostBattle:
	.string "TY: Ets un natural!\n"
	.string "He gravat un material de primera!$"

GabbyAndTy_Text_TyNotEnoughMons:
	.string "TY: Només tens un POKéMON\n"
	.string "i prou?\p"
	.string "Si tinguessis més POKéMON, faria un\n"
	.string "millor material, però…$"

GabbyAndTy_Text_TyDefeatFirstTime:
	.string "TY: Sí, hem detectat un ENTRENADOR prometedor.\n"
	.string "Això és una gran exclusiva per nosaltres!$"

GabbyAndTy_Text_TyDefeat:
	.string "TY: Sí, ho tinc tot.\n"
	.string "Tot el combat és a la càmera.$"

gTVInSearchOfTrainersText00::
	.string "A LA RECERCA D'ENTRENADORS…\p"
	.string "GABBY: Hola! Avui visito una zona\n"
	.string "prop de {STR_VAR_1}.\p"
	.string "Intentem detectar nous talents\n"
	.string "prometedors en el camp.\p"
	.string "Avui, hem enfocat la càmera en\n"
	.string "l'ENTRENADOR {PLAYER}.\p"
	.string "Hi ha alguna cosa en aquest ENTRENADOR\n"
	.string "que ens ha despertat l'interès.$"

gTVInSearchOfTrainersText01::
	.string "Hem combatut amb {PLAYER} abans, i podem\n"
	.string "confirmar que l'ENTRENADOR ha millorat\l"
	.string "molt des de llavors.\p"
	.string "Sabia que havíem trobat algú especial\n"
	.string "quan vam veure aquest ENTRENADOR!$"

gTVInSearchOfTrainersText02::
	.string "La millor manera de determinar com de\n"
	.string "fort és un ENTRENADOR…\p"
	.string "Bé, la manera més ràpida és combatre.\n"
	.string "I així vam començar la investigació!\p"
	.string "… …\p"
	.string "Així és com vam acabar en combat\n"
	.string "amb {PLAYER}.\p"
	.string "En una actuació dominant, ens van\n"
	.string "aixafar, enrotllar i llençar de banda!\p"
	.string "{PLAYER} és implacablement fort…\p"
	.string "Aquí teniu les nostres impressions després\n"
	.string "de combatre amb l'ENTRENADOR destacat.$"

gTVInSearchOfTrainersText03::
	.string "La combinació de {STR_VAR_1} i\n"
	.string "{STR_VAR_3} va ser divina!\p"
	.string "Veure'ls--{STR_VAR_1} i\n"
	.string "{STR_VAR_3}--donant-se suport\l"
	.string "altruistament en ple combat…\p"
	.string "Va ser un espectacle meravellós!\p"
	.string "{STR_VAR_2} va ser el moviment que l'ENTRENADOR\n"
	.string "va usar per últim al combat.\p"
	.string "El moviment {STR_VAR_2} és el signe d'amistat\n"
	.string "entre {STR_VAR_1} i {STR_VAR_3}!$"

gTVInSearchOfTrainersText04::
	.string "…Vaig perdre la confiança en mi mateixa\n"
	.string "com a resultat del nostre encontre.\p"
	.string "Ens van derrotar abans que poguéssim\n"
	.string "llançar un sol atac.\l"
	.string "Ohhh… Snif…\p"
	.string "Tot i això, els combats de {PLAYER}\n"
	.string "valen la pena de veure.\p"
	.string "Recomano als ENTRENADORS segurs\n"
	.string "que desafiïn {PLAYER}.$"

gTVInSearchOfTrainersText05::
	.string "Només hi ha una cosa a dir.\n"
	.string "No us atreviu a llençar una POKé BALL durant\l"
	.string "un combat d'ENTRENADORS!\p"
	.string "{PLAYER} és certament fort, però no té\n"
	.string "ni idea de les regles bàsiques.\p"
	.string "A la nostra audiència, tinc una petició.\p"
	.string "Si veieu {PLAYER}, si us plau advertiu\n"
	.string "l'ENTRENADOR!$"

gTVInSearchOfTrainersText06::
	.string "{PLAYER} és hàbil llegint les accions\n"
	.string "de l'oponent.\p"
	.string "El moment d'ús dels objectes va ser\n"
	.string "remarcablement efectiu!$"

gTVInSearchOfTrainersText07::
	.string "Sincerament, pensava que potser\n"
	.string "jo també era força bona.\p"
	.string "Tot i que vam acabar perdent, vam tenir\n"
	.string "un combat molt disputat.\p"
	.string "Però si lluites contra mi,\n"
	.string "encara et queda camí, {PLAYER}!$"

gTVInSearchOfTrainersText08::
	.string "Després del combat, vam demanar a {PLAYER}\n"
	.string "un resum succint.\p"
	.string "L'ENTRENADOR va respondre, “{STR_VAR_1}.”\p"
	.string "Els POKéMON de {PLAYER}, {STR_VAR_2} i\n"
	.string "{STR_VAR_3}…\l"
	.string "I “{STR_VAR_1}”…\p"
	.string "Mmm! Això és profund! Hi ha un significat\n"
	.string "profund darrere d'aquesta cita!\p"
	.string "No és sorprenent--un bon ENTRENADOR té\n"
	.string "bones coses a dir.\p"
	.string "Això és tot per avui!\n"
	.string "Ens veiem a la propera emissió!$"

ContestLadyShow_Text_Intro::
	.string "“CONCURS POKéMON EN DIRECTE!”\p"
	.string "PRESENTADOR: Perdoneu la interrupció\n"
	.string "del programa, i gràcies per ser aquí!\p"
	.string "Us portem això en directe des del\n"
	.string "lloc d'un {STR_VAR_1} que acaba\l"
	.string "de finalitzar!\p"
	.string "Espectadors: ?!!!!\p"
	.string "PRESENTADOR: Oh! Sembla que els participants\n"
	.string "del CONCURS vénen cap aquí!\p"
	.string "Intentaré fer una entrevista improvisada\n"
	.string "per a vosaltres a casa!\p"
	.string "Espectadors: ?!!!!\n"
	.string "?!!!!$"

ContestLadyShow_Text_Won::
	.string "PRESENTADOR: Perdona!\n"
	.string "Gràcies per ser aquí a la TV en directe!\p"
	.string "Puc felicitar-te per la victòria?\p"
	.string "Quin ha estat el factor clau en la\n"
	.string "impressionant victòria d'avui?\p"
	.string "BELLA: Hem donat el màxim avui,\n"
	.string "el meu {STR_VAR_2} i jo!\p"
	.string "Però estic segura que no ho hauríem\n"
	.string "aconseguit sense tota l'ajuda que\l"
	.string "hem rebut abans del CONCURS!\p"
	.string "PRESENTADOR: Tens algú especial amb qui\n"
	.string "voldries compartir la teva alegria?\l"
	.string "Digueu-ho en directe!\p"
	.string "BELLA: Ei, allà fora!\p"
	.string "{STR_VAR_3}! Estàs mirant?\n"
	.string "Ho hem aconseguit!\l"
	.string "Gràcies!$"

ContestLadyShow_Text_Lost::
	.string "PRESENTADOR: Perdona!\n"
	.string "Gràcies per ser aquí a la TV en directe!\p"
	.string "Deus estar decebuda pel resultat.\n"
	.string "Tens algun comentari?\p"
	.string "BELLA: És descoratjador…\n"
	.string "El meu {STR_VAR_2} i jo, ho hem donat tot…\p"
	.string "Però sento que he decebut a tothom\n"
	.string "que ens ha donat suport.\p"
	.string "PRESENTADOR: Em sap greu dir-ho, però la\n"
	.string "coloració del POKéMON és una mica pobra.\p"
	.string "BELLA: {STR_VAR_3}, ho sento molt…\n"
	.string "Ho faré millor la propera vegada, ho juro…\l"
	.string "…Snif… Buaaaaa!\p"
	.string "Espectadors: Ho heu vist?\n"
	.string "Pobra noia!\p"
	.string "PRESENTADOR: Uh… Oh-oh…\p"
	.string "Uh… Això és tot per avui!\n"
	.string "Gràcies per sintonitzar-nos!$"

ContestLadyShow_Text_LostBadly::
	.string "PRESENTADOR: Perdona!\n"
	.string "Gràcies per ser aquí a la TV en directe!\p"
	.string "Com ha anat la teva participació al CONCURS?\p"
	.string "BELLA: Res ha anat bé…\n"
	.string "Per alguna raó, el meu {STR_VAR_2}\l"
	.string "no ha atret cap popularitat.\p"
	.string "PRESENTADOR: Em sap greu dir-ho, però la\n"
	.string "coloració del POKéMON és una mica pobra.\p"
	.string "BELLA: … … … … … …\n"
	.string "…Snif… Buaaaaa!\p"
	.string "Espectadors: Ho heu vist?\n"
	.string "Pobra noia!\p"
	.string "PRESENTADOR: Uh… Oh-oh…\p"
	.string "Uh… Això és tot per avui!\n"
	.string "Gràcies per sintonitzar-nos!$"
