VerdanturfTown_House_MapScripts::
	.byte 0

VerdanturfTown_House_EventScript_Woman1::
	msgbox VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague, MSGBOX_NPC
	end

VerdanturfTown_House_EventScript_Woman2::
	msgbox VerdanturfTown_House_Text_DefeatEliteFourInARow, MSGBOX_NPC
	end

VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague:
	.string "Lluny, a les profunditats de\n"
	.string "CALA PERENNE, hi ha la LLIGA POKéMON.\p"
	.string "Els ENTRENADORS que s'hi reuneixen\n"
	.string "estan tots increïblement preparats.$"

VerdanturfTown_House_Text_DefeatEliteFourInARow:
	.string "A la LLIGA POKéMON, crec que les regles\n"
	.string "diuen que has de lluitar contra\l"
	.string "l'ELIT QUATRE tots seguits.\p"
	.string "Si perds contra qualsevol d'ells, has\n"
	.string "de començar el desafiament de nou\l"
	.string "des del primer.$"

