MauvilleCity_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, MauvilleCity_OnTransition
	.byte 0

MauvilleCity_OnTransition:
	setflag FLAG_VISITED_MAUVILLE_CITY
	clearflag FLAG_FORCE_MIRAGE_TOWER_VISIBLE
	clearflag FLAG_HIDE_SLATEPORT_MUSEUM_POPULATION
	setflag FLAG_SYS_TV_START
	clearflag FLAG_MAUVILLE_GYM_BARRIERS_STATE
	setvar VAR_MAUVILLE_GYM_STATE, 0
	call_if_set FLAG_GOT_TM_THUNDERBOLT_FROM_WATTSON, MauvilleCity_EventScript_MoveWattsonBackToGym
	end

MauvilleCity_EventScript_MoveWattsonBackToGym::
	clearflag FLAG_HIDE_MAUVILLE_GYM_WATTSON
	setflag FLAG_HIDE_MAUVILLE_CITY_WATTSON
	setflag FLAG_WATTSON_REMATCH_AVAILABLE
	return

MauvilleCity_EventScript_Boy::
	msgbox MauvilleCity_Text_NurseHurtMonBackToHealth, MSGBOX_NPC
	end

MauvilleCity_EventScript_Maniac::
	msgbox MauvilleCity_Text_AllSortsOfPeopleComeThrough, MSGBOX_NPC
	end

MauvilleCity_EventScript_Woman::
	msgbox MauvilleCity_Text_RydelVeryGenerous, MSGBOX_NPC
	end

MauvilleCity_EventScript_RichBoy::
	msgbox MauvilleCity_Text_PokemonCanJumpYouOnBike, MSGBOX_NPC
	end

MauvilleCity_EventScript_CitySign::
	msgbox MauvilleCity_Text_CitySign, MSGBOX_SIGN
	end

MauvilleCity_EventScript_GymSign::
	msgbox MauvilleCity_Text_GymSign, MSGBOX_SIGN
	end

MauvilleCity_EventScript_BikeShopSign::
	msgbox MauvilleCity_Text_BikeShopSign, MSGBOX_SIGN
	end

MauvilleCity_EventScript_GameCornerSign::
	msgbox MauvilleCity_Text_GameCornerSign, MSGBOX_SIGN
	end

MauvilleCity_EventScript_SchoolKidM::
	lock
	faceplayer
	goto_if_set FLAG_TV_EXPLAINED, MauvilleCity_EventScript_TVExplained
	msgbox MauvilleCity_Text_ExplainTV, MSGBOX_DEFAULT
	setflag FLAG_TV_EXPLAINED
	release
	end

MauvilleCity_EventScript_TVExplained::
	msgbox MauvilleCity_Text_BeenCheckingOutTV, MSGBOX_DEFAULT
	release
	end

MauvilleCity_EventScript_WallysUncle::
	lock
	faceplayer
	goto_if_set FLAG_DECLINED_WALLY_BATTLE_MAUVILLE, MauvilleCity_EventScript_UncleAskPlayerToBattleWally
	msgbox MauvilleCity_Text_UncleHesTooPeppy, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_MAUVILLE_WALLYS_UNCLE, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

MauvilleCity_EventScript_UncleAskPlayerToBattleWally::
	msgbox MauvilleCity_Text_UncleCanYouBattleWally, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_MAUVILLE_WALLYS_UNCLE, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

MauvilleCity_EventScript_Wally::
	lockall
	goto_if_set FLAG_DECLINED_WALLY_BATTLE_MAUVILLE, MauvilleCity_EventScript_WallyRequestBattleAgain
	applymovement LOCALID_MAUVILLE_WALLY, Common_Movement_WalkInPlaceFasterRight
	waitmovement 0
	msgbox MauvilleCity_Text_WallyWantToChallengeGym, MSGBOX_DEFAULT
	msgbox MauvilleCity_Text_UncleYourePushingIt, MSGBOX_DEFAULT
	msgbox MauvilleCity_Text_WallyWeCanBeatAnyone, MSGBOX_DEFAULT
	applymovement LOCALID_MAUVILLE_WALLY, Common_Movement_FacePlayer
	waitmovement 0
	playse SE_PIN
	applymovement LOCALID_MAUVILLE_WALLY, Common_Movement_ExclamationMark
	waitmovement 0
	applymovement LOCALID_MAUVILLE_WALLY, Common_Movement_Delay48
	waitmovement 0
	msgbox MauvilleCity_Text_WallyWillYouBattleMe, MSGBOX_YESNO
	goto MauvilleCity_EventScript_BattleWallyPrompt
	end

MauvilleCity_EventScript_BattleWallyPrompt::
	call_if_eq VAR_RESULT, YES, MauvilleCity_EventScript_BattleWally
	goto_if_eq VAR_RESULT, NO, MauvilleCity_EventScript_DeclineWallyBattle
	closemessage
	switch VAR_FACING
	case DIR_NORTH, MauvilleCity_EventScript_WallyAndUncleExitNorth
	case DIR_EAST, MauvilleCity_EventScript_WallyAndUncleExitEast
	end

MauvilleCity_EventScript_WallyAndUncleExitNorth::
	applymovement LOCALID_PLAYER, MauvilleCity_Movement_PlayerWatchWallyExitNorth1
	applymovement LOCALID_MAUVILLE_WALLY, MauvilleCity_Movement_WallyExitNorth1
	applymovement LOCALID_MAUVILLE_WALLYS_UNCLE, MauvilleCity_Movement_WallysUncleExitNorth1
	waitmovement 0
	applymovement LOCALID_MAUVILLE_WALLY, Common_Movement_WalkInPlaceFasterRight
	waitmovement 0
	delay 30
	applymovement LOCALID_PLAYER, MauvilleCity_Movement_PlayerFaceUncleNorth
	applymovement LOCALID_MAUVILLE_WALLYS_UNCLE, MauvilleCity_Movement_WallysUncleApproachPlayerNorth
	waitmovement 0
	msgbox MauvilleCity_Text_UncleVisitUsSometime, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_PLAYER, MauvilleCity_Movement_PlayerWatchWallyExitNorth2
	applymovement LOCALID_MAUVILLE_WALLYS_UNCLE, MauvilleCity_Movement_WallysUncleExitNorth2
	applymovement LOCALID_MAUVILLE_WALLY, MauvilleCity_Movement_WallyExitNorth2
	waitmovement 0
	goto MauvilleCity_EventScript_DefeatedWally
	end

MauvilleCity_EventScript_WallyAndUncleExitEast::
	applymovement LOCALID_PLAYER, MauvilleCity_Movement_PlayerWatchWallyExitEast1
	applymovement LOCALID_MAUVILLE_WALLY, MauvilleCity_Movement_WallyExitEast1
	applymovement LOCALID_MAUVILLE_WALLYS_UNCLE, MauvilleCity_Movement_WallysUncleExitEast1
	waitmovement 0
	applymovement LOCALID_MAUVILLE_WALLY, Common_Movement_WalkInPlaceFasterRight
	waitmovement 0
	delay 30
	applymovement LOCALID_MAUVILLE_WALLYS_UNCLE, MauvilleCity_Movement_WallysUncleApproachPlayerEast
	waitmovement 0
	msgbox MauvilleCity_Text_UncleVisitUsSometime, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_PLAYER, MauvilleCity_Movement_PlayerWatchWallyExitEast2
	applymovement LOCALID_MAUVILLE_WALLYS_UNCLE, MauvilleCity_Movement_WallysUncleExitEast2
	applymovement LOCALID_MAUVILLE_WALLY, MauvilleCity_Movement_WallyExitEast2
	waitmovement 0
	goto MauvilleCity_EventScript_DefeatedWally
	end

MauvilleCity_EventScript_DefeatedWally::
	removeobject LOCALID_MAUVILLE_WALLY
	removeobject LOCALID_MAUVILLE_WALLYS_UNCLE
	clearflag FLAG_HIDE_VERDANTURF_TOWN_WANDAS_HOUSE_WALLY
	clearflag FLAG_HIDE_VERDANTURF_TOWN_WANDAS_HOUSE_WALLYS_UNCLE
	setflag FLAG_DEFEATED_WALLY_MAUVILLE
	setvar VAR_WALLY_CALL_STEP_COUNTER, 0
	setflag FLAG_ENABLE_FIRST_WALLY_POKENAV_CALL
	call_if_eq VAR_FACING, DIR_NORTH, MauvilleCity_EventScript_ScottApproachPlayerNorth
	call_if_eq VAR_FACING, DIR_EAST, MauvilleCity_EventScript_ScottApproachPlayerEast
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterDown
	waitmovement 0
	msgbox MauvilleCity_Text_ScottYouDidntHoldBack, MSGBOX_DEFAULT
	closemessage
	addvar VAR_SCOTT_STATE, 1
	call_if_eq VAR_FACING, DIR_NORTH, MauvilleCity_EventScript_ScottExitNorth
	call_if_eq VAR_FACING, DIR_EAST, MauvilleCity_EventScript_ScottExitEast
	removeobject LOCALID_MAUVILLE_SCOTT
	releaseall
	end

MauvilleCity_EventScript_ScottApproachPlayerNorth::
	addobject LOCALID_MAUVILLE_SCOTT
	applymovement LOCALID_MAUVILLE_SCOTT, MauvilleCity_Movement_ScottApproachPlayerNorth
	waitmovement 0
	return

MauvilleCity_EventScript_ScottApproachPlayerEast::
	setobjectxyperm LOCALID_MAUVILLE_SCOTT, 12, 13
	addobject LOCALID_MAUVILLE_SCOTT
	applymovement LOCALID_MAUVILLE_SCOTT, MauvilleCity_Movement_ScottApproachPlayerEast
	waitmovement 0
	return

MauvilleCity_EventScript_ScottExitNorth::
	applymovement LOCALID_PLAYER, MauvilleCity_Movement_PlayerWatchScottExitNorth
	applymovement LOCALID_MAUVILLE_SCOTT, MauvilleCity_Movement_ScottExitNorth
	waitmovement 0
	return

MauvilleCity_EventScript_ScottExitEast::
	applymovement LOCALID_PLAYER, MauvilleCity_Movement_PlayerWatchScottExitEast
	applymovement LOCALID_MAUVILLE_SCOTT, MauvilleCity_Movement_ScottExitEast
	waitmovement 0
	return

MauvilleCity_EventScript_BattleWally::
	msgbox MauvilleCity_Text_WallyHereICome, MSGBOX_DEFAULT
	trainerbattle_no_intro TRAINER_WALLY_MAUVILLE, MauvilleCity_Text_WallyDefeat
	applymovement LOCALID_MAUVILLE_WALLY, Common_Movement_WalkInPlaceFasterRight
	waitmovement 0
	msgbox MauvilleCity_Text_WallyIllGoBackToVerdanturf, MSGBOX_DEFAULT
	applymovement LOCALID_MAUVILLE_WALLY, Common_Movement_FacePlayer
	waitmovement 0
	msgbox MauvilleCity_Text_ThankYouNotEnoughToBattle, MSGBOX_DEFAULT
	applymovement LOCALID_MAUVILLE_WALLY, Common_Movement_WalkInPlaceFasterRight
	waitmovement 0
	msgbox MauvilleCity_Text_UncleNoNeedToBeDown, MSGBOX_DEFAULT
	return

MauvilleCity_EventScript_DeclineWallyBattle::
	setflag FLAG_DECLINED_WALLY_BATTLE_MAUVILLE
	msgbox MauvilleCity_Text_WallyMyUncleWontKnowImStrong, MSGBOX_DEFAULT
	release
	end

MauvilleCity_EventScript_WallyRequestBattleAgain::
	applymovement LOCALID_MAUVILLE_WALLY, Common_Movement_FacePlayer
	waitmovement 0
	msgbox MauvilleCity_Text_WallyPleaseBattleMe, MSGBOX_YESNO
	goto MauvilleCity_EventScript_BattleWallyPrompt
	end

MauvilleCity_Movement_WallyExitNorth1:
	walk_left
	walk_left
	walk_down
	walk_down
	walk_left
	step_end

MauvilleCity_Movement_WallyExitEast1:
	walk_down
	walk_down
	walk_left
	walk_left
	walk_left
	step_end

MauvilleCity_Movement_WallyExitNorth2:
	delay_16
	delay_16
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	delay_8
	step_end

MauvilleCity_Movement_WallyExitEast2:
	delay_16
	delay_16
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	delay_8
	step_end

MauvilleCity_Movement_PlayerWatchWallyExitNorth2:
	delay_16
	delay_8
	walk_in_place_faster_left
	step_end

MauvilleCity_Movement_PlayerWatchWallyExitEast2:
	delay_16
	delay_16
	delay_16
	walk_in_place_faster_left
	step_end

MauvilleCity_Movement_PlayerWatchScottExitNorth:
	delay_16
	walk_in_place_faster_left
	step_end

MauvilleCity_Movement_PlayerWatchScottExitEast:
	delay_16
	delay_16
	walk_in_place_faster_left
	step_end

MauvilleCity_Movement_PlayerWatchWallyExitEast1:
	delay_16
	walk_in_place_faster_down
	step_end

MauvilleCity_Movement_PlayerWatchWallyExitNorth1:
	delay_16
	walk_in_place_faster_left
	step_end

MauvilleCity_Movement_WallysUncleExitNorth1:
	walk_left
	walk_left
	walk_left
	walk_down
	walk_down
	step_end

MauvilleCity_Movement_WallysUncleExitEast1:
	walk_left
	walk_down
	walk_down
	walk_left
	walk_left
	step_end

MauvilleCity_Movement_PlayerFaceUncleNorth:
	delay_16
	delay_8
	delay_4
	walk_in_place_faster_down
	step_end

MauvilleCity_Movement_WallysUncleApproachPlayerNorth:
	walk_right
	walk_right
	walk_in_place_faster_up
	step_end

MauvilleCity_Movement_WallysUncleApproachPlayerEast:
	walk_right
	walk_up
	step_end

MauvilleCity_Movement_WallysUncleExitNorth2:
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	step_end

MauvilleCity_Movement_WallysUncleExitEast2:
	walk_down
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	step_end

MauvilleCity_Movement_ScottApproachPlayerNorth:
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_left
	walk_left
	walk_left
	walk_left
	walk_in_place_faster_up
	step_end

MauvilleCity_Movement_ScottApproachPlayerEast:
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_up
	step_end

MauvilleCity_Movement_ScottExitNorth:
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	step_end

MauvilleCity_Movement_ScottExitEast:
	walk_down
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	step_end

MauvilleCity_EventScript_Wattson::
	lock
	faceplayer
	goto_if_set FLAG_GOT_TM_THUNDERBOLT_FROM_WATTSON, MauvilleCity_EventScript_ReceivedThunderbolt
	goto_if_eq VAR_NEW_MAUVILLE_STATE, 2, MauvilleCity_EventScript_CompletedNewMauville
	goto_if_set FLAG_GOT_BASEMENT_KEY_FROM_WATTSON, MauvilleCity_EventScript_BegunNewMauville
	msgbox MauvilleCity_Text_WattsonNeedFavorTakeKey, MSGBOX_DEFAULT
	giveitem ITEM_BASEMENT_KEY
	setflag FLAG_GOT_BASEMENT_KEY_FROM_WATTSON
	msgbox MauvilleCity_Text_WattsonWontBeChallenge, MSGBOX_DEFAULT
	release
	end

MauvilleCity_EventScript_BegunNewMauville::
	msgbox MauvilleCity_Text_WattsonWontBeChallenge, MSGBOX_DEFAULT
	release
	end

MauvilleCity_EventScript_CompletedNewMauville::
	msgbox MauvilleCity_Text_WattsonThanksTakeTM, MSGBOX_DEFAULT
	giveitem ITEM_TM_THUNDERBOLT
	goto_if_eq VAR_RESULT, FALSE, Common_EventScript_ShowBagIsFull
	setflag FLAG_GOT_TM_THUNDERBOLT_FROM_WATTSON
	msgbox MauvilleCity_Text_WattsonYoungTakeCharge, MSGBOX_DEFAULT
	release
	end

MauvilleCity_EventScript_ReceivedThunderbolt::
	msgbox MauvilleCity_Text_WattsonYoungTakeCharge, MSGBOX_DEFAULT
	release
	end

MauvilleCity_EventScript_RegisterWallyCall::
	lockall
	pokenavcall MauvilleCity_Text_WallyPokenavCall
	waitmessage
	delay 30
	playfanfare MUS_REGISTER_MATCH_CALL
	msgbox MauvilleCity_Text_RegisteredWally, MSGBOX_DEFAULT
	waitfanfare
	closemessage
	delay 30
	setflag FLAG_ENABLE_WALLY_MATCH_CALL
	clearflag FLAG_ENABLE_FIRST_WALLY_POKENAV_CALL
	releaseall
	end

MauvilleCity_Text_UncleHesTooPeppy:
	.string "ONCLE: És gràcies als POKéMON que\n"
	.string "aquest noi té més energia, suposo…\l"
	.string "Però s'ha tornat massa energètic…$"

MauvilleCity_Text_WallyWantToChallengeGym:
	.string "BLASI: Ai, ONCLE, si us plau?\p"
	.string "Vull desafiar aquest GIMNÀS i veure\n"
	.string "com de fort m'he tornat.\p"
	.string "Si us plau? Puc, si us plau?$"

MauvilleCity_Text_UncleYourePushingIt:
	.string "ONCLE: Para un moment, BLASI.\p"
	.string "Des que vas començar a viure amb POKéMON,\n"
	.string "t'has tornat força més fort.\p"
	.string "Però no creus que t'esforces massa\n"
	.string "per desafiar un GIMNÀS de sobte?$"

MauvilleCity_Text_WallyWeCanBeatAnyone:
	.string "BLASI: No m'esforço massa.\p"
	.string "Si uneixo forces amb RALTS,\n"
	.string "podem guanyar a qualsevol!$"

MauvilleCity_Text_WallyWillYouBattleMe:
	.string "BLASI: Oh! Hola, {PLAYER}!\p"
	.string "M'he tornat molt més fort des que\n"
	.string "ens vam conèixer.\p"
	.string "{PLAYER}, vull que tu i el meu ONCLE\n"
	.string "ho entengueu.\p"
	.string "{PLAYER}, si us plau, vols tenir\n"
	.string "una batalla amb mi?$"

MauvilleCity_Text_WallyMyUncleWontKnowImStrong:
	.string "BLASI: Oh… Si no lluites amb mi,\n"
	.string "{PLAYER}, el meu ONCLE no sabrà que\l"
	.string "m'he tornat molt fort.$"

MauvilleCity_Text_UncleCanYouBattleWally:
	.string "ONCLE: {PLAYER}{KUN}, oi?\n"
	.string "De part del BLASI, puc demanar-te que\l"
	.string "lluitisamb ell només aquest cop?\p"
	.string "No crec que escolti cap raó\n"
	.string "en l'estat en què es troba ara.$"

MauvilleCity_Text_WallyPleaseBattleMe:
	.string "BLASI: {PLAYER}, si us plau!\n"
	.string "Lluita amb mi, si us plau.$"

MauvilleCity_Text_WallyHereICome:
	.string "BLASI: {PLAYER}, gràcies.\p"
	.string "D'acord… Aquí vaig!$"

MauvilleCity_Text_WallyDefeat:
	.string "BLASI: … … … … … … …\p"
	.string "… … … … … … … …\p"
	.string "He perdut…$"

MauvilleCity_Text_WallyIllGoBackToVerdanturf:
	.string "BLASI: ONCLE…\n"
	.string "Tornaré a VERDEGAL…$"

MauvilleCity_Text_ThankYouNotEnoughToBattle:
	.string "{PLAYER}, gràcies.\n"
	.string "Ser ENTRENADOR és dur, oi?\p"
	.string "No n'hi ha prou amb tenir POKéMON\n"
	.string "i fer-los lluitar. No és això el\l"
	.string "que significa ser un ENTRENADOR de debò.$"

MauvilleCity_Text_UncleNoNeedToBeDown:
	.string "ONCLE: BLASI, no cal que et desanimis\n"
	.string "tant.\p"
	.string "Què t'impedeix tornar-te cada cop\n"
	.string "més fort?\p"
	.string "Vine, anem a casa.\n"
	.string "Tothom t'està esperant.$"

MauvilleCity_Text_UncleVisitUsSometime:
	.string "ONCLE: {PLAYER}{KUN}, acabo d'adonar-me\n"
	.string "que tu deus ser l'ENTRENADOR que va\l"
	.string "tenir cura del BLASI quan va\l"
	.string "atrapar el seu POKéMON.\p"
	.string "Per què no ens visites a VERDEGAL\n"
	.string "algun dia?\l"
	.string "Estic segur que el BLASI ho gaudirà.$"


MauvilleCity_Text_WallyPokenavCall:
	.string "… … … … … …\n"
	.string "… … … … … Bip!\p"
	.string "BLASI: Oh, hola, {PLAYER}!\p"
	.string "Només volia dir-te que\n"
	.string "el meu oncle m'ha comprat un POKéNAV!\p"
	.string "Ara puc contactar amb tu\n"
	.string "quan vulgui, {PLAYER}!\p"
	.string "… … … … … …\n"
	.string "… … … … … Clic!$"

MauvilleCity_Text_RegisteredWally:
	.string "Has registrat el BLASI\n"
	.string "al POKéNAV.$"

MauvilleCity_Text_ScottYouDidntHoldBack:
	.string "SCOTT: Hehe…\n"
	.string "Estava mirant aquest combat!\p"
	.string "Ets amic d'aquell noi BLASI,\n"
	.string "no?\p"
	.string "Però no t'has contingut gens\n"
	.string "i l'has guanyat de manera impressionant.\p"
	.string "Sí! Això és el que és una veritable\n"
	.string "batalla POKéMON!\p"
	.string "Admiro ENTRENADORS com tu!\p"
	.string "… … … … … …\n"
	.string "T'estaré animant!$"

MauvilleCity_Text_WattsonNeedFavorTakeKey:
	.string "TESLA: Oh, {PLAYER}{KUN}!\n"
	.string "Sembla que tens molta energia!\l"
	.string "Això és bo, wahahahaha!\p"
	.string "Molt bé! Ho he decidit!\n"
	.string "Necessito un favor, {PLAYER}{KUN}!\p"
	.string "CIUTAT MALVALONA té un sector\n"
	.string "subterrani anomenat NOVA MALVALONA.\p"
	.string "{PLAYER}{KUN}, m'agradaria que hi anessis\n"
	.string "i apaguessis el GENERADOR.\p"
	.string "El GENERADOR ha estat funcionant una\n"
	.string "mica malament. S'està tornant perillós.\p"
	.string "Aquí tens, aquesta és la CLAU per\n"
	.string "entrar a NOVA MALVALONA.$"

MauvilleCity_Text_WattsonWontBeChallenge:
	.string "TESLA: No et preocupis.\n"
	.string "No serà cap repte per a tu.\p"
	.string "L'entrada a NOVA MALVALONA és just\n"
	.string "a poca distància fent SURF des de la RUTA 110.\p"
	.string "Doncs ja està, confio en tu!\n"
	.string "Wahahahaha!$"

MauvilleCity_Text_WattsonThanksTakeTM:
	.string "TESLA: Wahahahaha!\p"
	.string "Ja ho sabia, {PLAYER}{KUN}! Sabia que\n"
	.string "havia fet bé demanant-t'ho!\p"
	.string "Això és el meu agraïment--un MT que\n"
	.string "conté LLAMPEC!\p"
	.string "Vinga, te l'has guanyat!$"

MauvilleCity_Text_WattsonYoungTakeCharge:
	.string "TESLA: Wahahahaha!\p"
	.string "Em fa molt feliç veure els joves\n"
	.string "donar un pas endavant i prendre les regnes!$"

MauvilleCity_Text_NurseHurtMonBackToHealth:
	.string "Saps, està bé tenir batalles\n"
	.string "POKéMON i tot això…\p"
	.string "Però si el teu POKéMON es fa mal,\n"
	.string "has de curar-lo fins que estigui bé.$"

MauvilleCity_Text_AllSortsOfPeopleComeThrough:
	.string "Els camins d'aquesta ciutat s'estenen\n"
	.string "cap al nord i al sud, i a l'est i l'oest.\p"
	.string "Per això, rebem tot tipus de\n"
	.string "gent que passa per aquí.$"

MauvilleCity_Text_RydelVeryGenerous:
	.string "Has anat a les BICIS RADEL?\p"
	.string "El RADEL, el propietari, és un home\n"
	.string "molt generós.$"

MauvilleCity_Text_PokemonCanJumpYouOnBike:
	.string "Encara que vagis en BICI,\n"
	.string "els POKéMON salvatges et poden atacar.$"

MauvilleCity_Text_CitySign:
	.string "CIUTAT MALVALONA\n"
	.string "“La ciutat brillant i divertida!”$"

MauvilleCity_Text_GymSign:
	.string "GIMNÀS POKéMON DE CIUTAT MALVALONA\n"
	.string "LÍDER: TESLA\l"
	.string "“L'home alegrement electrificant!”$"

MauvilleCity_Text_BikeShopSign:
	.string "“Pedala per la grava i agita\n"
	.string "la teva ànima!”\l"
	.string "BICIS RADEL$"

MauvilleCity_Text_GameCornerSign:
	.string "“El lloc de joc per a tothom!”\n"
	.string "SALA DE JOCS DE MALVALONA$"

MauvilleCity_Text_ExplainTV:
	.string "Hola, mires la TV de tant en tant?\p"
	.string "Han afegit un munt de programes\n"
	.string "nous i xulos recentment.\p"
	.string "La TV és genial. He vist amics meus\n"
	.string "a la TV de sobte.\p"
	.string "I, a vegades, fins i tot et posen a la TV\n"
	.string "sense dir-t'ho.\p"
	.string "M'agradaria sortir a la TV algun dia.\p"
	.string "Per això crec que hauries de mirar\n"
	.string "les TVs sempre que puguis.$"

MauvilleCity_Text_BeenCheckingOutTV:
	.string "Hola, has estat mirant les TVs?$"
