SootopolisCity_House7_MapScripts::
	.byte 0

SootopolisCity_House7_EventScript_OldMan::
	msgbox SootopolisCity_House7_Text_CityFromEruptedVolcano, MSGBOX_NPC
	end

SootopolisCity_House7_EventScript_PokefanF::
	msgbox SootopolisCity_House7_Text_CaveMadeToKeepSomething, MSGBOX_NPC
	end

SootopolisCity_House7_Text_CityFromEruptedVolcano:
	.string "Un volcà submarí va erupcionar i\n"
	.string "va emergir de les profunditats.\p"
	.string "El seu cràter va sorgir del mar i\n"
	.string "es va omplir d'aigua de pluja.\p"
	.string "Així és com va néixer CIUTAT\n"
	.string "ARBORÈTUM.$"

SootopolisCity_House7_Text_CaveMadeToKeepSomething:
	.string "La cova que connecta ARBORÈTUM amb\n"
	.string "el món exterior…\p"
	.string "Sembla com si la cova fos feta per\n"
	.string "evitar que alguna cosa sortís.\p"
	.string "O m'ho estic imaginant?$"

