PetalburgCity_House2_MapScripts::
	.byte 0

PetalburgCity_House2_EventScript_Woman::
	msgbox PetalburgCity_House2_Text_NormanBecameGymLeader, MSGBOX_NPC
	end

PetalburgCity_House2_EventScript_SchoolKid::
	msgbox PetalburgCity_House2_Text_BattledNormanOnce, MSGBOX_NPC
	end

PetalburgCity_House2_Text_NormanBecameGymLeader:
	.string "En NORMAN s'ha convertit en el nou\n"
	.string "LÍDER DE GIMNÀS de la nostra ciutat.\p"
	.string "Crec que va fer venir la seva família\n"
	.string "d'algun lloc molt llunyà.$"

PetalburgCity_House2_Text_BattledNormanOnce:
	.string "Vaig lluitar amb en NORMAN un cop, però, uf,\n"
	.string "era massa fort.\p"
	.string "Com ho diria?\p"
	.string "Només tinc la sensació que ell\n"
	.string "viu pels POKéMON.$"

