OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman::
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
	.string "Quan comença un combat POKéMON, el que\n"
	.string "està a l'esquerra de la llista surt primer.\p"
	.string "Així que, quan tinguis més POKéMON al\n"
	.string "teu equip, prova de canviar l'ordre\l"
	.string "dels teus POKéMON.\p"
	.string "Et podria donar un avantatge.$"

