PetalburgCity_House1_MapScripts::
	.byte 0

PetalburgCity_House1_EventScript_Man::
	msgbox PetalburgCity_House1_Text_TravelingIsWonderful, MSGBOX_NPC
	end

PetalburgCity_House1_EventScript_Woman::
	msgbox PetalburgCity_House1_Text_GoOnAdventure, MSGBOX_NPC
	end

PetalburgCity_House1_Text_TravelingIsWonderful:
	.string "Viatjar és meravellós!\p"
	.string "Quan era jove, vaig recórrer els mars\n"
	.string "i les muntanyes!$"

PetalburgCity_House1_Text_GoOnAdventure:
	.string "Ai…\p"
	.string "M'agradaria poder anar d'aventura\n"
	.string "amb uns POKéMON…\p"
	.string "Arrossegar-me per l'herba humida…\n"
	.string "Escalar muntanyes rocoses i abruptes…\p"
	.string "Creuar els mars embravits…\n"
	.string "Vagar per coves fosques…\p"
	.string "I, de vegades, fins i tot tenir una mica\n"
	.string "de nostàlgia de casa…\p"
	.string "Ha de ser fabulós viatjar!$"

