FortreeCity_House3_MapScripts::
	.byte 0

FortreeCity_House3_EventScript_Maniac::
	msgbox FortreeCity_House3_Text_MetStevenHadAmazingPokemon, MSGBOX_NPC
	end

FortreeCity_House3_EventScript_SchoolKidM::
	msgbox FortreeCity_House3_Text_OhYouHavePokedex, MSGBOX_NPC
	end

FortreeCity_House3_Text_MetStevenHadAmazingPokemon:
	.string "Parlant de POKéDEX,\n"
	.string "m'he recordat d'una cosa.\p"
	.string "Vaig conèixer un ENTRENADOR, el SEBI,\n"
	.string "quan buscava pedres rares.\p"
	.string "Caram, tenia uns POKéMON increïbles\n"
	.string "amb ell.\p"
	.string "No només eren rars, estaven\n"
	.string "entrenats fins a extrems terrorífics!\p"
	.string "Podria ser fins i tot més fort que\n"
	.string "la LÍDER DE GIMNÀS d'aquesta ciutat…$"

FortreeCity_House3_Text_OhYouHavePokedex:
	.string "Què és això que tens aquí?\p"
	.string "… … … … … …\p"
	.string "Oh, es diu POKéDEX?\n"
	.string "És realment impressionant!$"

