SlateportCity_SternsShipyard_2F_MapScripts::
	.byte 0

SlateportCity_SternsShipyard_2F_EventScript_Scientist1::
	msgbox SlateportCity_SternsShipyard_2F_Text_ShipDesignMoreLikeBuilding, MSGBOX_NPC
	end

SlateportCity_SternsShipyard_2F_EventScript_Scientist2::
	msgbox SlateportCity_SternsShipyard_2F_Text_FloatsBecauseBuoyancy, MSGBOX_NPC
	end

SlateportCity_SternsShipyard_2F_Text_ShipDesignMoreLikeBuilding:
	.string "Dissenyar un vaixell gran s'assembla\n"
	.string "més a fer un edifici gran que no pas\l"
	.string "a muntar un vehicle de transport.$"

SlateportCity_SternsShipyard_2F_Text_FloatsBecauseBuoyancy:
	.string "No trobes estrany que un vaixell\n"
	.string "fet de ferro pesat suri?\p"
	.string "Sura gràcies a un principi\n"
	.string "anomenat flotabilitat.$"

