SootopolisCity_Gym_B1F_MapScripts::
	.byte 0

SootopolisCity_Gym_B1F_EventScript_Andrea::
	trainerbattle_single TRAINER_ANDREA, SootopolisCity_Gym_B1F_Text_AndreaIntro, SootopolisCity_Gym_B1F_Text_AndreaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_AndreaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Crissy::
	trainerbattle_single TRAINER_CRISSY, SootopolisCity_Gym_B1F_Text_CrissyIntro, SootopolisCity_Gym_B1F_Text_CrissyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_CrissyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Brianna::
	trainerbattle_single TRAINER_BRIANNA, SootopolisCity_Gym_B1F_Text_BriannaIntro, SootopolisCity_Gym_B1F_Text_BriannaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BriannaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Connie::
	trainerbattle_single TRAINER_CONNIE, SootopolisCity_Gym_B1F_Text_ConnieIntro, SootopolisCity_Gym_B1F_Text_ConnieDefeat
	msgbox SootopolisCity_Gym_B1F_Text_ConniePostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Bridget::
	trainerbattle_single TRAINER_BRIDGET, SootopolisCity_Gym_B1F_Text_BridgetIntro, SootopolisCity_Gym_B1F_Text_BridgetDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BridgetPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Olivia::
	trainerbattle_single TRAINER_OLIVIA, SootopolisCity_Gym_B1F_Text_OliviaIntro, SootopolisCity_Gym_B1F_Text_OliviaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_OliviaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Tiffany::
	trainerbattle_single TRAINER_TIFFANY, SootopolisCity_Gym_B1F_Text_TiffanyIntro, SootopolisCity_Gym_B1F_Text_TiffanyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_TiffanyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Bethany::
	trainerbattle_single TRAINER_BETHANY, SootopolisCity_Gym_B1F_Text_BethanyIntro, SootopolisCity_Gym_B1F_Text_BethanyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BethanyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Annika::
	trainerbattle_single TRAINER_ANNIKA, SootopolisCity_Gym_B1F_Text_AnnikaIntro, SootopolisCity_Gym_B1F_Text_AnnikaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_AnnikaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Daphne::
	trainerbattle_single TRAINER_DAPHNE, SootopolisCity_Gym_B1F_Text_DaphneIntro, SootopolisCity_Gym_B1F_Text_DaphneDefeat
	msgbox SootopolisCity_Gym_B1F_Text_DaphnePostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_Text_AndreaIntro:
	.string "Et mostraré les tècniques sublims\n"
	.string "que he après del nostre LÍDER JOAN!$"

SootopolisCity_Gym_B1F_Text_AndreaDefeat:
	.string "Si us plau, perdona'm, JOAN…$"

SootopolisCity_Gym_B1F_Text_AndreaPostBattle:
	.string "Mira què passa si trenques totes\n"
	.string "les rajoles del terra.$"

SootopolisCity_Gym_B1F_Text_CrissyIntro:
	.string "Has arribat fins aquí, però no veuràs\n"
	.string "en JOAN.\p"
	.string "No si perds contra mi!$"

SootopolisCity_Gym_B1F_Text_CrissyDefeat:
	.string "Ets fort!\n"
	.string "El teu aspecte bufó m'ha enganyat!$"

SootopolisCity_Gym_B1F_Text_CrissyPostBattle:
	.string "Potser ets prou bo per evitar ser\n"
	.string "esborrat d'un sol cop per en JOAN.$"

SootopolisCity_Gym_B1F_Text_DaphneIntro:
	.string "Veure en JOAN dirigint\n"
	.string "un combat…\p"
	.string "La mateixa bellesa d'això em va impulsar\n"
	.string "a fer-me ENTRENADORA.$"

SootopolisCity_Gym_B1F_Text_DaphneDefeat:
	.string "Has combatut amb més bellesa de la\n"
	.string "que jo podia reunir…$"

SootopolisCity_Gym_B1F_Text_DaphnePostBattle:
	.string "La gràcia que aportes al combat és\n"
	.string "fabulosa.\p"
	.string "Oh… Tinc tanta sort d'haver descobert\n"
	.string "els POKéMON.$"

SootopolisCity_Gym_B1F_Text_ConnieIntro:
	.string "T'hauria d'ensenyar com de durs poden\n"
	.string "ser els combats.$"

SootopolisCity_Gym_B1F_Text_ConnieDefeat:
	.string "Oh.\n"
	.string "Ets fort.$"

SootopolisCity_Gym_B1F_Text_ConniePostBattle:
	.string "T'explicaré una cosa interessant.\p"
	.string "Si vols arribar a en JOAN, has de\n"
	.string "trepitjar cada rajola del terra un cop.$"

SootopolisCity_Gym_B1F_Text_BridgetIntro:
	.string "El GIMNÀS POKéMON del nivell més alt\n"
	.string "de la regió de HOENN…\p"
	.string "És el GIMNÀS D'ARBORÈTUM.$"

SootopolisCity_Gym_B1F_Text_BridgetDefeat:
	.string "Quin nivell tan alt tens!$"

SootopolisCity_Gym_B1F_Text_BridgetPostBattle:
	.string "En lloc d'estar satisfeta per ser en\n"
	.string "un GIMNÀS fort, m'imagino que entrenar\l"
	.string "en altres llocs et farà més fort.\l"
	.string "Però sobretot, sembla més divertit.$"

SootopolisCity_Gym_B1F_Text_OliviaIntro:
	.string "Entreno els meus POKéMON juntament\n"
	.string "amb en JOAN.\p"
	.string "No pensis que sóc fàcil de vèncer.$"

SootopolisCity_Gym_B1F_Text_OliviaDefeat:
	.string "M'has derrotat…$"

SootopolisCity_Gym_B1F_Text_OliviaPostBattle:
	.string "Crec que tens potencial.\n"
	.string "Per què no et quedes a entrenar amb\l"
	.string "nosaltres?$"

SootopolisCity_Gym_B1F_Text_TiffanyIntro:
	.string "Un lliscament elegant sobre el gel\n"
	.string "sense creuar cap línia…\p"
	.string "Un ENTRENADOR fent aquesta actuació\n"
	.string "seria elegantment bell!$"

SootopolisCity_Gym_B1F_Text_TiffanyDefeat:
	.string "Com dius?!$"

SootopolisCity_Gym_B1F_Text_TiffanyPostBattle:
	.string "Això és molt obvi, però com de fort\n"
	.string "ets com a ENTRENADOR no té res a\l"
	.string "veure amb si ets jove o gran.$"

SootopolisCity_Gym_B1F_Text_BethanyIntro:
	.string "Quan sóc amb els meus POKéMON, el temps\n"
	.string "vola abans que puguis dir “Ui!”$"

SootopolisCity_Gym_B1F_Text_BethanyDefeat:
	.string "Ui!$"

SootopolisCity_Gym_B1F_Text_BethanyPostBattle:
	.string "M'agradaria poder oblidar les causes\n"
	.string "perdudes abans de poder dir “Ui!”$"

SootopolisCity_Gym_B1F_Text_AnnikaIntro:
	.string "Puc combatre amb POKéMON molt rars\n"
	.string "si vols.$"

SootopolisCity_Gym_B1F_Text_AnnikaDefeat:
	.string "Oh, aquí! Has pogut veure bé\n"
	.string "els meus POKéMON?$"

SootopolisCity_Gym_B1F_Text_AnnikaPostBattle:
	.string "Vaig venir a aquest GIMNÀS perquè\n"
	.string "en JOAN va elogiar els meus POKéMON.\p"
	.string "Oh, si hagués conegut en JOAN fa anys,\n"
	.string "quan era més jove…$"

SootopolisCity_Gym_B1F_Text_BriannaIntro:
	.string "Rialleta…\n"
	.string "El teu aspecte seriós és tan encantador.$"

SootopolisCity_Gym_B1F_Text_BriannaDefeat:
	.string "Oh, vaja.\n"
	.string "He anat massa suau amb tu.$"

SootopolisCity_Gym_B1F_Text_BriannaPostBattle:
	.string "No podries ni tocar en JOAN,\n"
	.string "segur. Rialleta…$"

