LilycoveCity_House4_MapScripts::
	.byte 0

LilycoveCity_House4_EventScript_Man1::
	msgbox LilycoveCity_House4_Text_MysteriesAtBottomOfSea, MSGBOX_NPC
	end

LilycoveCity_House4_EventScript_Man2::
	msgbox LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis, MSGBOX_NPC
	end

LilycoveCity_House4_Text_MysteriesAtBottomOfSea:
	.string "Els misteris més grans d'aquest planeta\n"
	.string "són al fons del mar.\p"
	.string "Algú ho va dir, però no sé…$"

LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis:
	.string "Hi ha una fossa submarina profunda\n"
	.string "entre ALGUERSUARI i ARBORÈTUM.\p"
	.string "Això és el que algú em va dir.$"

